"""
Py Kotodama WASM entrypoint for the Shopify clean-room actor.

Clean-room, API-shaped CRUD over a Datomic-backed Kotoba schema.
Generated by 70-tools/deepen_actors.py (ADR 260607 deepening phase).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/shopify.kotoba")
db = DatomicClient.connect()
app = Runtime("shopify-compat")


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"shopify.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    """Read records of an entity from Datomic (optionally by id)."""
    pattern = {"entity": f"shopify.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing)}}
    return None


@app.route("/v1/products", methods=["POST"])
def create_product(request):
    """Create a Product."""
    data = request.json or request.form or {}
    err = _require(data, ['title', 'vendor'])
    if err:
        return err, 400
    rec = {"id": new_id("shopify_pro")}
    rec["title"] = data.get('title')
    rec["vendor"] = data.get('vendor')
    rec["productType"] = data.get('productType')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Product", rec)
    return rec, 201

@app.route("/v1/products", methods=["GET"])
def list_products(request):
    """List Products."""
    items = _query("Product")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/products/<eid>", methods=["GET"])
def get_product(request, eid):
    """Retrieve a Product by id."""
    rows = _query("Product", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/products/<eid>", methods=["POST", "PATCH"])
def update_product(request, eid):
    """Update a Product."""
    rows = _query("Product", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Product", rec)
    return rec, 200

@app.route("/v1/products/<eid>", methods=["DELETE"])
def delete_product(request, eid):
    """Delete a Product."""
    rows = _query("Product", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"shopify.Product", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/variants", methods=["POST"])
def create_variant(request):
    """Create a Variant."""
    data = request.json or request.form or {}
    err = _require(data, ['sku', 'price'])
    if err:
        return err, 400
    rec = {"id": new_id("shopify_var")}
    rec["productId"] = data.get('productId')
    rec["sku"] = data.get('sku')
    rec["price"] = float(data.get('price') or 0)
    rec["inventoryQuantity"] = int(data.get('inventoryQuantity') or 0)
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Variant", rec)
    return rec, 201

@app.route("/v1/variants", methods=["GET"])
def list_variants(request):
    """List Variants."""
    items = _query("Variant")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/variants/<eid>", methods=["GET"])
def get_variant(request, eid):
    """Retrieve a Variant by id."""
    rows = _query("Variant", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/variants/<eid>", methods=["POST", "PATCH"])
def update_variant(request, eid):
    """Update a Variant."""
    rows = _query("Variant", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Variant", rec)
    return rec, 200

@app.route("/v1/variants/<eid>", methods=["DELETE"])
def delete_variant(request, eid):
    """Delete a Variant."""
    rows = _query("Variant", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"shopify.Variant", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/orders", methods=["POST"])
def create_order(request):
    """Create a Order."""
    data = request.json or request.form or {}
    err = _require(data, ['number', 'totalPrice'])
    if err:
        return err, 400
    rec = {"id": new_id("shopify_ord")}
    rec["customerId"] = data.get('customerId')
    rec["number"] = data.get('number')
    rec["totalPrice"] = float(data.get('totalPrice') or 0)
    rec["currency"] = data.get('currency')
    rec["financialStatus"] = data.get('financialStatus')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Order", rec)
    return rec, 201

@app.route("/v1/orders", methods=["GET"])
def list_orders(request):
    """List Orders."""
    items = _query("Order")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/orders/<eid>", methods=["GET"])
def get_order(request, eid):
    """Retrieve a Order by id."""
    rows = _query("Order", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/orders/<eid>", methods=["POST", "PATCH"])
def update_order(request, eid):
    """Update a Order."""
    rows = _query("Order", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Order", rec)
    return rec, 200

@app.route("/v1/orders/<eid>", methods=["DELETE"])
def delete_order(request, eid):
    """Delete a Order."""
    rows = _query("Order", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"shopify.Order", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/customers", methods=["POST"])
def create_customer(request):
    """Create a Customer."""
    data = request.json or request.form or {}
    err = _require(data, ['email', 'firstName'])
    if err:
        return err, 400
    rec = {"id": new_id("shopify_cus")}
    rec["email"] = data.get('email')
    rec["firstName"] = data.get('firstName')
    rec["lastName"] = data.get('lastName')
    rec["ordersCount"] = int(data.get('ordersCount') or 0)
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Customer", rec)
    return rec, 201

@app.route("/v1/customers", methods=["GET"])
def list_customers(request):
    """List Customers."""
    items = _query("Customer")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/customers/<eid>", methods=["GET"])
def get_customer(request, eid):
    """Retrieve a Customer by id."""
    rows = _query("Customer", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/customers/<eid>", methods=["POST", "PATCH"])
def update_customer(request, eid):
    """Update a Customer."""
    rows = _query("Customer", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Customer", rec)
    return rec, 200

@app.route("/v1/customers/<eid>", methods=["DELETE"])
def delete_customer(request, eid):
    """Delete a Customer."""
    rows = _query("Customer", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"shopify.Customer", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/collections", methods=["POST"])
def create_collection(request):
    """Create a Collection."""
    data = request.json or request.form or {}
    err = _require(data, ['title', 'handle'])
    if err:
        return err, 400
    rec = {"id": new_id("shopify_col")}
    rec["title"] = data.get('title')
    rec["handle"] = data.get('handle')
    rec["published"] = bool(data.get('published'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Collection", rec)
    return rec, 201

@app.route("/v1/collections", methods=["GET"])
def list_collections(request):
    """List Collections."""
    items = _query("Collection")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/collections/<eid>", methods=["GET"])
def get_collection(request, eid):
    """Retrieve a Collection by id."""
    rows = _query("Collection", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/collections/<eid>", methods=["POST", "PATCH"])
def update_collection(request, eid):
    """Update a Collection."""
    rows = _query("Collection", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Collection", rec)
    return rec, 200

@app.route("/v1/collections/<eid>", methods=["DELETE"])
def delete_collection(request, eid):
    """Delete a Collection."""
    rows = _query("Collection", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"shopify.Collection", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/fulfillments", methods=["POST"])
def create_fulfillment(request):
    """Create a Fulfillment."""
    data = request.json or request.form or {}
    err = _require(data, ['status', 'trackingNumber'])
    if err:
        return err, 400
    rec = {"id": new_id("shopify_ful")}
    rec["orderId"] = data.get('orderId')
    rec["status"] = data.get('status')
    rec["trackingNumber"] = data.get('trackingNumber')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Fulfillment", rec)
    return rec, 201

@app.route("/v1/fulfillments", methods=["GET"])
def list_fulfillments(request):
    """List Fulfillments."""
    items = _query("Fulfillment")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/fulfillments/<eid>", methods=["GET"])
def get_fulfillment(request, eid):
    """Retrieve a Fulfillment by id."""
    rows = _query("Fulfillment", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/fulfillments/<eid>", methods=["POST", "PATCH"])
def update_fulfillment(request, eid):
    """Update a Fulfillment."""
    rows = _query("Fulfillment", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Fulfillment", rec)
    return rec, 200

@app.route("/v1/fulfillments/<eid>", methods=["DELETE"])
def delete_fulfillment(request, eid):
    """Delete a Fulfillment."""
    rows = _query("Fulfillment", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"shopify.Fulfillment", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/discountcodes", methods=["POST"])
def create_discount_code(request):
    """Create a DiscountCode."""
    data = request.json or request.form or {}
    err = _require(data, ['code', 'valueType'])
    if err:
        return err, 400
    rec = {"id": new_id("shopify_dis")}
    rec["code"] = data.get('code')
    rec["valueType"] = data.get('valueType')
    rec["value"] = float(data.get('value') or 0)
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("DiscountCode", rec)
    return rec, 201

@app.route("/v1/discountcodes", methods=["GET"])
def list_discount_codes(request):
    """List DiscountCodes."""
    items = _query("DiscountCode")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/discountcodes/<eid>", methods=["GET"])
def get_discount_code(request, eid):
    """Retrieve a DiscountCode by id."""
    rows = _query("DiscountCode", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/discountcodes/<eid>", methods=["POST", "PATCH"])
def update_discount_code(request, eid):
    """Update a DiscountCode."""
    rows = _query("DiscountCode", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("DiscountCode", rec)
    return rec, 200

@app.route("/v1/discountcodes/<eid>", methods=["DELETE"])
def delete_discount_code(request, eid):
    """Delete a DiscountCode."""
    rows = _query("DiscountCode", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"shopify.DiscountCode", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "shopify-compat", "entities": ['Product', 'Variant', 'Order', 'Customer', 'Collection', 'Fulfillment', 'DiscountCode']}, 200


if __name__ == "__main__":
    app.start()
