"""
Py Kotodama WASM entrypoint for the Sonarqube clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/sonarqube.kotoba")
db = DatomicClient.connect()
app = Runtime("sonarqube-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"sonarqube.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"sonarqube.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/issues", methods=["POST"])
def create_issue(request):
    """Create a Issue."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['key', 'severity', 'status', 'type', 'resolution', 'component', 'line', 'message'])
    if err:
        return err, 400
    err = _require(data, ['key', 'severity'])
    if err:
        return err, 400
    if data.get('severity') and data['severity'] not in ['BLOCKER', 'CRITICAL', 'MAJOR', 'MINOR', 'INFO']:
        return {"error": {"message": "invalid severity; allowed: " + ", ".join(['BLOCKER', 'CRITICAL', 'MAJOR', 'MINOR', 'INFO']), "type": "invalid_request_error"}}, 400
    if data.get('type') and data['type'] not in ['BUG', 'VULNERABILITY', 'CODE_SMELL']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['BUG', 'VULNERABILITY', 'CODE_SMELL']), "type": "invalid_request_error"}}, 400
    if data.get('resolution') and data['resolution'] not in ['FIXED', 'REMOVED', 'FALSE_POSITIVE', 'WONTFIX']:
        return {"error": {"message": "invalid resolution; allowed: " + ", ".join(['FIXED', 'REMOVED', 'FALSE_POSITIVE', 'WONTFIX']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("sonarqub_iss")}
    rec["key"] = data.get('key')
    rec["severity"] = data.get('severity')
    rec["status"] = data.get('status')
    rec["type"] = data.get('type')
    rec["resolution"] = data.get('resolution')
    rec["component"] = data.get('component')
    rec["line"] = _as_int(data.get('line'))
    rec["message"] = data.get('message')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Issue", rec)
    return rec, 201

@app.route("/v1/issues", methods=["GET"])
def list_issues(request):
    """List Issues with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Issue")
    rows = _apply_filters(rows, params, ['key', 'severity', 'status', 'type', 'resolution', 'component', 'line', 'message'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/issues/<eid>", methods=["GET"])
def get_issue(request, eid):
    """Retrieve a Issue by id (supports ?expand=)."""
    rows = _query("Issue", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/issues/<eid>", methods=["POST", "PATCH"])
def update_issue(request, eid):
    """Update a Issue."""
    rows = _query("Issue", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['key', 'severity', 'status', 'type', 'resolution', 'component', 'line', 'message'])
    if err:
        return err, 400
    if data.get('severity') and data['severity'] not in ['BLOCKER', 'CRITICAL', 'MAJOR', 'MINOR', 'INFO']:
        return {"error": {"message": "invalid severity; allowed: " + ", ".join(['BLOCKER', 'CRITICAL', 'MAJOR', 'MINOR', 'INFO']), "type": "invalid_request_error"}}, 400
    if data.get('type') and data['type'] not in ['BUG', 'VULNERABILITY', 'CODE_SMELL']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['BUG', 'VULNERABILITY', 'CODE_SMELL']), "type": "invalid_request_error"}}, 400
    if data.get('resolution') and data['resolution'] not in ['FIXED', 'REMOVED', 'FALSE_POSITIVE', 'WONTFIX']:
        return {"error": {"message": "invalid resolution; allowed: " + ", ".join(['FIXED', 'REMOVED', 'FALSE_POSITIVE', 'WONTFIX']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Issue", rec)
    return rec, 200

@app.route("/v1/issues/<eid>", methods=["DELETE"])
def delete_issue(request, eid):
    """Delete a Issue."""
    rows = _query("Issue", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"sonarqube.Issue", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/hotspots", methods=["POST"])
def create_hotspot(request):
    """Create a Hotspot."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['key', 'status', 'message', 'component'])
    if err:
        return err, 400
    err = _require(data, ['key', 'status'])
    if err:
        return err, 400
    if data.get('status') and data['status'] not in ['TO_REVIEW', 'FIXED', 'SAFE']:
        return {"error": {"message": "invalid status; allowed: " + ", ".join(['TO_REVIEW', 'FIXED', 'SAFE']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("sonarqub_hot")}
    rec["key"] = data.get('key')
    rec["status"] = data.get('status')
    rec["message"] = data.get('message')
    rec["component"] = data.get('component')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Hotspot", rec)
    return rec, 201

@app.route("/v1/hotspots", methods=["GET"])
def list_hotspots(request):
    """List Hotspots with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Hotspot")
    rows = _apply_filters(rows, params, ['key', 'status', 'message', 'component'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/hotspots/<eid>", methods=["GET"])
def get_hotspot(request, eid):
    """Retrieve a Hotspot by id (supports ?expand=)."""
    rows = _query("Hotspot", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/hotspots/<eid>", methods=["POST", "PATCH"])
def update_hotspot(request, eid):
    """Update a Hotspot."""
    rows = _query("Hotspot", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['key', 'status', 'message', 'component'])
    if err:
        return err, 400
    if data.get('status') and data['status'] not in ['TO_REVIEW', 'FIXED', 'SAFE']:
        return {"error": {"message": "invalid status; allowed: " + ", ".join(['TO_REVIEW', 'FIXED', 'SAFE']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Hotspot", rec)
    return rec, 200

@app.route("/v1/hotspots/<eid>", methods=["DELETE"])
def delete_hotspot(request, eid):
    """Delete a Hotspot."""
    rows = _query("Hotspot", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"sonarqube.Hotspot", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/qualitygates", methods=["POST"])
def create_quality_gate(request):
    """Create a QualityGate."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['status', 'ignoredConditions'])
    if err:
        return err, 400
    err = _require(data, ['status', 'ignoredConditions'])
    if err:
        return err, 400
    rec = {"id": new_id("sonarqub_qua")}
    rec["status"] = data.get('status')
    rec["ignoredConditions"] = _as_bool(data.get('ignoredConditions'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("QualityGate", rec)
    return rec, 201

@app.route("/v1/qualitygates", methods=["GET"])
def list_quality_gates(request):
    """List QualityGates with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("QualityGate")
    rows = _apply_filters(rows, params, ['status', 'ignoredConditions'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/qualitygates/<eid>", methods=["GET"])
def get_quality_gate(request, eid):
    """Retrieve a QualityGate by id (supports ?expand=)."""
    rows = _query("QualityGate", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/qualitygates/<eid>", methods=["POST", "PATCH"])
def update_quality_gate(request, eid):
    """Update a QualityGate."""
    rows = _query("QualityGate", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['status', 'ignoredConditions'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("QualityGate", rec)
    return rec, 200

@app.route("/v1/qualitygates/<eid>", methods=["DELETE"])
def delete_quality_gate(request, eid):
    """Delete a QualityGate."""
    rows = _query("QualityGate", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"sonarqube.QualityGate", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/conditions", methods=["POST"])
def create_condition(request):
    """Create a Condition."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['status', 'metricKey', 'comparator', 'errorThreshold', 'actualValue'])
    if err:
        return err, 400
    err = _require(data, ['status', 'metricKey'])
    if err:
        return err, 400
    if data.get('status') and data['status'] not in ['OK', 'ERROR']:
        return {"error": {"message": "invalid status; allowed: " + ", ".join(['OK', 'ERROR']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("sonarqub_con")}
    rec["status"] = data.get('status')
    rec["metricKey"] = data.get('metricKey')
    rec["comparator"] = data.get('comparator')
    rec["errorThreshold"] = data.get('errorThreshold')
    rec["actualValue"] = data.get('actualValue')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Condition", rec)
    return rec, 201

@app.route("/v1/conditions", methods=["GET"])
def list_conditions(request):
    """List Conditions with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Condition")
    rows = _apply_filters(rows, params, ['status', 'metricKey', 'comparator', 'errorThreshold', 'actualValue'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/conditions/<eid>", methods=["GET"])
def get_condition(request, eid):
    """Retrieve a Condition by id (supports ?expand=)."""
    rows = _query("Condition", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/conditions/<eid>", methods=["POST", "PATCH"])
def update_condition(request, eid):
    """Update a Condition."""
    rows = _query("Condition", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['status', 'metricKey', 'comparator', 'errorThreshold', 'actualValue'])
    if err:
        return err, 400
    if data.get('status') and data['status'] not in ['OK', 'ERROR']:
        return {"error": {"message": "invalid status; allowed: " + ", ".join(['OK', 'ERROR']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Condition", rec)
    return rec, 200

@app.route("/v1/conditions/<eid>", methods=["DELETE"])
def delete_condition(request, eid):
    """Delete a Condition."""
    rows = _query("Condition", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"sonarqube.Condition", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/measures", methods=["POST"])
def create_measure(request):
    """Create a Measure."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['metric', 'value', 'bestValue'])
    if err:
        return err, 400
    err = _require(data, ['metric', 'value'])
    if err:
        return err, 400
    rec = {"id": new_id("sonarqub_mea")}
    rec["metric"] = data.get('metric')
    rec["value"] = data.get('value')
    rec["bestValue"] = _as_bool(data.get('bestValue'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Measure", rec)
    return rec, 201

@app.route("/v1/measures", methods=["GET"])
def list_measures(request):
    """List Measures with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Measure")
    rows = _apply_filters(rows, params, ['metric', 'value', 'bestValue'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/measures/<eid>", methods=["GET"])
def get_measure(request, eid):
    """Retrieve a Measure by id (supports ?expand=)."""
    rows = _query("Measure", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/measures/<eid>", methods=["POST", "PATCH"])
def update_measure(request, eid):
    """Update a Measure."""
    rows = _query("Measure", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['metric', 'value', 'bestValue'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Measure", rec)
    return rec, 200

@app.route("/v1/measures/<eid>", methods=["DELETE"])
def delete_measure(request, eid):
    """Delete a Measure."""
    rows = _query("Measure", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"sonarqube.Measure", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "sonarqube-compat", "tier": "L4",
            "entities": ['Issue', 'Hotspot', 'QualityGate', 'Condition', 'Measure']}, 200


if __name__ == "__main__":
    app.start()
