"""
Py Kotodama WASM entrypoint for the Canva clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/canva.kotoba")
db = DatomicClient.connect()
app = Runtime("canva-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"canva.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"canva.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/designs", methods=["POST"])
def create_design(request):
    """Create a Design."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'title', 'pageCount', 'createdAt', 'updatedAt'])
    if err:
        return err, 400
    err = _require(data, ['id', 'title'])
    if err:
        return err, 400
    rec = {"id": new_id("canva_des")}
    rec["id"] = data.get('id')
    rec["title"] = data.get('title')
    rec["pageCount"] = _as_int(data.get('pageCount'))
    rec["createdAt"] = _as_int(data.get('createdAt'))
    rec["updatedAt"] = _as_int(data.get('updatedAt'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Design", rec)
    return rec, 201

@app.route("/v1/designs", methods=["GET"])
def list_designs(request):
    """List Designs with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Design")
    rows = _apply_filters(rows, params, ['id', 'title', 'pageCount', 'createdAt', 'updatedAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/designs/<eid>", methods=["GET"])
def get_design(request, eid):
    """Retrieve a Design by id (supports ?expand=)."""
    rows = _query("Design", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/designs/<eid>", methods=["POST", "PATCH"])
def update_design(request, eid):
    """Update a Design."""
    rows = _query("Design", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'title', 'pageCount', 'createdAt', 'updatedAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Design", rec)
    return rec, 200

@app.route("/v1/designs/<eid>", methods=["DELETE"])
def delete_design(request, eid):
    """Delete a Design."""
    rows = _query("Design", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"canva.Design", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/assets", methods=["POST"])
def create_asset(request):
    """Create a Asset."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'name', 'type', 'createdAt', 'updatedAt'])
    if err:
        return err, 400
    err = _require(data, ['id', 'name'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['image', 'video']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['image', 'video']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("canva_ass")}
    rec["id"] = data.get('id')
    rec["name"] = data.get('name')
    rec["type"] = data.get('type')
    rec["createdAt"] = _as_int(data.get('createdAt'))
    rec["updatedAt"] = _as_int(data.get('updatedAt'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Asset", rec)
    return rec, 201

@app.route("/v1/assets", methods=["GET"])
def list_assets(request):
    """List Assets with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Asset")
    rows = _apply_filters(rows, params, ['id', 'name', 'type', 'createdAt', 'updatedAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/assets/<eid>", methods=["GET"])
def get_asset(request, eid):
    """Retrieve a Asset by id (supports ?expand=)."""
    rows = _query("Asset", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/assets/<eid>", methods=["POST", "PATCH"])
def update_asset(request, eid):
    """Update a Asset."""
    rows = _query("Asset", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'name', 'type', 'createdAt', 'updatedAt'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['image', 'video']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['image', 'video']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Asset", rec)
    return rec, 200

@app.route("/v1/assets/<eid>", methods=["DELETE"])
def delete_asset(request, eid):
    """Delete a Asset."""
    rows = _query("Asset", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"canva.Asset", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/folders", methods=["POST"])
def create_folder(request):
    """Create a Folder."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'name', 'createdAt', 'updatedAt'])
    if err:
        return err, 400
    err = _require(data, ['id', 'name'])
    if err:
        return err, 400
    rec = {"id": new_id("canva_fol")}
    rec["id"] = data.get('id')
    rec["name"] = data.get('name')
    rec["createdAt"] = _as_int(data.get('createdAt'))
    rec["updatedAt"] = _as_int(data.get('updatedAt'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Folder", rec)
    return rec, 201

@app.route("/v1/folders", methods=["GET"])
def list_folders(request):
    """List Folders with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Folder")
    rows = _apply_filters(rows, params, ['id', 'name', 'createdAt', 'updatedAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/folders/<eid>", methods=["GET"])
def get_folder(request, eid):
    """Retrieve a Folder by id (supports ?expand=)."""
    rows = _query("Folder", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/folders/<eid>", methods=["POST", "PATCH"])
def update_folder(request, eid):
    """Update a Folder."""
    rows = _query("Folder", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'name', 'createdAt', 'updatedAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Folder", rec)
    return rec, 200

@app.route("/v1/folders/<eid>", methods=["DELETE"])
def delete_folder(request, eid):
    """Delete a Folder."""
    rows = _query("Folder", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"canva.Folder", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/brandtemplates", methods=["POST"])
def create_brand_template(request):
    """Create a BrandTemplate."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'title', 'viewUrl', 'createdAt', 'updatedAt'])
    if err:
        return err, 400
    err = _require(data, ['id', 'title'])
    if err:
        return err, 400
    rec = {"id": new_id("canva_bra")}
    rec["id"] = data.get('id')
    rec["title"] = data.get('title')
    rec["viewUrl"] = data.get('viewUrl')
    rec["createdAt"] = _as_int(data.get('createdAt'))
    rec["updatedAt"] = _as_int(data.get('updatedAt'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("BrandTemplate", rec)
    return rec, 201

@app.route("/v1/brandtemplates", methods=["GET"])
def list_brand_templates(request):
    """List BrandTemplates with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("BrandTemplate")
    rows = _apply_filters(rows, params, ['id', 'title', 'viewUrl', 'createdAt', 'updatedAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/brandtemplates/<eid>", methods=["GET"])
def get_brand_template(request, eid):
    """Retrieve a BrandTemplate by id (supports ?expand=)."""
    rows = _query("BrandTemplate", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/brandtemplates/<eid>", methods=["POST", "PATCH"])
def update_brand_template(request, eid):
    """Update a BrandTemplate."""
    rows = _query("BrandTemplate", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'title', 'viewUrl', 'createdAt', 'updatedAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("BrandTemplate", rec)
    return rec, 200

@app.route("/v1/brandtemplates/<eid>", methods=["DELETE"])
def delete_brand_template(request, eid):
    """Delete a BrandTemplate."""
    rows = _query("BrandTemplate", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"canva.BrandTemplate", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/exportjobs", methods=["POST"])
def create_export_job(request):
    """Create a ExportJob."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'status', 'format'])
    if err:
        return err, 400
    err = _require(data, ['id', 'status'])
    if err:
        return err, 400
    if data.get('status') and data['status'] not in ['in_progress', 'success', 'failed']:
        return {"error": {"message": "invalid status; allowed: " + ", ".join(['in_progress', 'success', 'failed']), "type": "invalid_request_error"}}, 400
    if data.get('format') and data['format'] not in ['pdf', 'jpg', 'png', 'gif', 'pptx', 'mp4', 'svg', 'html_bundle', 'html_standalone']:
        return {"error": {"message": "invalid format; allowed: " + ", ".join(['pdf', 'jpg', 'png', 'gif', 'pptx', 'mp4', 'svg', 'html_bundle', 'html_standalone']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("canva_exp")}
    rec["id"] = data.get('id')
    rec["status"] = data.get('status')
    rec["format"] = data.get('format')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("ExportJob", rec)
    return rec, 201

@app.route("/v1/exportjobs", methods=["GET"])
def list_export_jobs(request):
    """List ExportJobs with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("ExportJob")
    rows = _apply_filters(rows, params, ['id', 'status', 'format'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/exportjobs/<eid>", methods=["GET"])
def get_export_job(request, eid):
    """Retrieve a ExportJob by id (supports ?expand=)."""
    rows = _query("ExportJob", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/exportjobs/<eid>", methods=["POST", "PATCH"])
def update_export_job(request, eid):
    """Update a ExportJob."""
    rows = _query("ExportJob", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'status', 'format'])
    if err:
        return err, 400
    if data.get('status') and data['status'] not in ['in_progress', 'success', 'failed']:
        return {"error": {"message": "invalid status; allowed: " + ", ".join(['in_progress', 'success', 'failed']), "type": "invalid_request_error"}}, 400
    if data.get('format') and data['format'] not in ['pdf', 'jpg', 'png', 'gif', 'pptx', 'mp4', 'svg', 'html_bundle', 'html_standalone']:
        return {"error": {"message": "invalid format; allowed: " + ", ".join(['pdf', 'jpg', 'png', 'gif', 'pptx', 'mp4', 'svg', 'html_bundle', 'html_standalone']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("ExportJob", rec)
    return rec, 200

@app.route("/v1/exportjobs/<eid>", methods=["DELETE"])
def delete_export_job(request, eid):
    """Delete a ExportJob."""
    rows = _query("ExportJob", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"canva.ExportJob", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/users", methods=["POST"])
def create_user(request):
    """Create a User."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'displayName'])
    if err:
        return err, 400
    err = _require(data, ['id', 'displayName'])
    if err:
        return err, 400
    rec = {"id": new_id("canva_use")}
    rec["id"] = data.get('id')
    rec["displayName"] = data.get('displayName')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("User", rec)
    return rec, 201

@app.route("/v1/users", methods=["GET"])
def list_users(request):
    """List Users with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("User")
    rows = _apply_filters(rows, params, ['id', 'displayName'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/users/<eid>", methods=["GET"])
def get_user(request, eid):
    """Retrieve a User by id (supports ?expand=)."""
    rows = _query("User", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/users/<eid>", methods=["POST", "PATCH"])
def update_user(request, eid):
    """Update a User."""
    rows = _query("User", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'displayName'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("User", rec)
    return rec, 200

@app.route("/v1/users/<eid>", methods=["DELETE"])
def delete_user(request, eid):
    """Delete a User."""
    rows = _query("User", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"canva.User", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "canva-compat", "tier": "L4",
            "entities": ['Design', 'Asset', 'Folder', 'BrandTemplate', 'ExportJob', 'User']}, 200


if __name__ == "__main__":
    app.start()
