"""
Py Kotodama WASM entrypoint for the Orcid clean-room actor.

Clean-room, API-shaped CRUD over a Datomic-backed Kotoba schema.
Generated by 70-tools/deepen_actors.py (ADR 260607 deepening phase).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/orcid.kotoba")
db = DatomicClient.connect()
app = Runtime("orcid-compat")


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"orcid.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    """Read records of an entity from Datomic (optionally by id)."""
    pattern = {"entity": f"orcid.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing)}}
    return None


@app.route("/v1/works", methods=["POST"])
def create_work(request):
    """Create a Work."""
    data = request.json or request.form or {}
    err = _require(data, ['doi', 'title'])
    if err:
        return err, 400
    rec = {"id": new_id("orcid_wor")}
    rec["doi"] = data.get('doi')
    rec["title"] = data.get('title')
    rec["type"] = data.get('type')
    rec["publishedAt"] = data.get('publishedAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Work", rec)
    return rec, 201

@app.route("/v1/works", methods=["GET"])
def list_works(request):
    """List Works."""
    items = _query("Work")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/works/<eid>", methods=["GET"])
def get_work(request, eid):
    """Retrieve a Work by id."""
    rows = _query("Work", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/works/<eid>", methods=["POST", "PATCH"])
def update_work(request, eid):
    """Update a Work."""
    rows = _query("Work", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Work", rec)
    return rec, 200

@app.route("/v1/works/<eid>", methods=["DELETE"])
def delete_work(request, eid):
    """Delete a Work."""
    rows = _query("Work", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"orcid.Work", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/authors", methods=["POST"])
def create_author(request):
    """Create a Author."""
    data = request.json or request.form or {}
    err = _require(data, ['orcid', 'givenName'])
    if err:
        return err, 400
    rec = {"id": new_id("orcid_aut")}
    rec["orcid"] = data.get('orcid')
    rec["givenName"] = data.get('givenName')
    rec["familyName"] = data.get('familyName')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Author", rec)
    return rec, 201

@app.route("/v1/authors", methods=["GET"])
def list_authors(request):
    """List Authors."""
    items = _query("Author")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/authors/<eid>", methods=["GET"])
def get_author(request, eid):
    """Retrieve a Author by id."""
    rows = _query("Author", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/authors/<eid>", methods=["POST", "PATCH"])
def update_author(request, eid):
    """Update a Author."""
    rows = _query("Author", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Author", rec)
    return rec, 200

@app.route("/v1/authors/<eid>", methods=["DELETE"])
def delete_author(request, eid):
    """Delete a Author."""
    rows = _query("Author", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"orcid.Author", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/citations", methods=["POST"])
def create_citation(request):
    """Create a Citation."""
    data = request.json or request.form or {}
    err = _require(data, ['citedDoi'])
    if err:
        return err, 400
    rec = {"id": new_id("orcid_cit")}
    rec["workId"] = data.get('workId')
    rec["citedDoi"] = data.get('citedDoi')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Citation", rec)
    return rec, 201

@app.route("/v1/citations", methods=["GET"])
def list_citations(request):
    """List Citations."""
    items = _query("Citation")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/citations/<eid>", methods=["GET"])
def get_citation(request, eid):
    """Retrieve a Citation by id."""
    rows = _query("Citation", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/citations/<eid>", methods=["POST", "PATCH"])
def update_citation(request, eid):
    """Update a Citation."""
    rows = _query("Citation", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Citation", rec)
    return rec, 200

@app.route("/v1/citations/<eid>", methods=["DELETE"])
def delete_citation(request, eid):
    """Delete a Citation."""
    rows = _query("Citation", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"orcid.Citation", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/standards", methods=["POST"])
def create_standard(request):
    """Create a Standard."""
    data = request.json or request.form or {}
    err = _require(data, ['designation', 'title'])
    if err:
        return err, 400
    rec = {"id": new_id("orcid_sta")}
    rec["designation"] = data.get('designation')
    rec["title"] = data.get('title')
    rec["organization"] = data.get('organization')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Standard", rec)
    return rec, 201

@app.route("/v1/standards", methods=["GET"])
def list_standards(request):
    """List Standards."""
    items = _query("Standard")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/standards/<eid>", methods=["GET"])
def get_standard(request, eid):
    """Retrieve a Standard by id."""
    rows = _query("Standard", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/standards/<eid>", methods=["POST", "PATCH"])
def update_standard(request, eid):
    """Update a Standard."""
    rows = _query("Standard", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Standard", rec)
    return rec, 200

@app.route("/v1/standards/<eid>", methods=["DELETE"])
def delete_standard(request, eid):
    """Delete a Standard."""
    rows = _query("Standard", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"orcid.Standard", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/records", methods=["POST"])
def create_record(request):
    """Create a Record."""
    data = request.json or request.form or {}
    err = _require(data, ['accession', 'database'])
    if err:
        return err, 400
    rec = {"id": new_id("orcid_rec")}
    rec["accession"] = data.get('accession')
    rec["database"] = data.get('database')
    rec["title"] = data.get('title')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Record", rec)
    return rec, 201

@app.route("/v1/records", methods=["GET"])
def list_records(request):
    """List Records."""
    items = _query("Record")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/records/<eid>", methods=["GET"])
def get_record(request, eid):
    """Retrieve a Record by id."""
    rows = _query("Record", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/records/<eid>", methods=["POST", "PATCH"])
def update_record(request, eid):
    """Update a Record."""
    rows = _query("Record", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Record", rec)
    return rec, 200

@app.route("/v1/records/<eid>", methods=["DELETE"])
def delete_record(request, eid):
    """Delete a Record."""
    rows = _query("Record", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"orcid.Record", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/subjects", methods=["POST"])
def create_subject(request):
    """Create a Subject."""
    data = request.json or request.form or {}
    err = _require(data, ['term', 'scheme'])
    if err:
        return err, 400
    rec = {"id": new_id("orcid_sub")}
    rec["workId"] = data.get('workId')
    rec["term"] = data.get('term')
    rec["scheme"] = data.get('scheme')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Subject", rec)
    return rec, 201

@app.route("/v1/subjects", methods=["GET"])
def list_subjects(request):
    """List Subjects."""
    items = _query("Subject")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/subjects/<eid>", methods=["GET"])
def get_subject(request, eid):
    """Retrieve a Subject by id."""
    rows = _query("Subject", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/subjects/<eid>", methods=["POST", "PATCH"])
def update_subject(request, eid):
    """Update a Subject."""
    rows = _query("Subject", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Subject", rec)
    return rec, 200

@app.route("/v1/subjects/<eid>", methods=["DELETE"])
def delete_subject(request, eid):
    """Delete a Subject."""
    rows = _query("Subject", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"orcid.Subject", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "orcid-compat", "entities": ['Work', 'Author', 'Citation', 'Standard', 'Record', 'Subject']}, 200


if __name__ == "__main__":
    app.start()
