"""
Py Kotodama WASM entrypoint for the Relativity clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/relativity.kotoba")
db = DatomicClient.connect()
app = Runtime("relativity-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"relativity.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"relativity.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/records", methods=["POST"])
def create_record(request):
    """Create a Record."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'type', 'ownerId', 'status'])
    if err:
        return err, 400
    err = _require(data, ['name', 'type'])
    if err:
        return err, 400
    rec = {"id": new_id("relativi_rec")}
    rec["name"] = data.get('name')
    rec["type"] = data.get('type')
    rec["ownerId"] = data.get('ownerId')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Record", rec)
    return rec, 201

@app.route("/v1/records", methods=["GET"])
def list_records(request):
    """List Records with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Record")
    rows = _apply_filters(rows, params, ['name', 'type', 'ownerId', 'status'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/records/<eid>", methods=["GET"])
def get_record(request, eid):
    """Retrieve a Record by id (supports ?expand=)."""
    rows = _query("Record", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/records/<eid>", methods=["POST", "PATCH"])
def update_record(request, eid):
    """Update a Record."""
    rows = _query("Record", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'type', 'ownerId', 'status'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Record", rec)
    return rec, 200

@app.route("/v1/records/<eid>", methods=["DELETE"])
def delete_record(request, eid):
    """Delete a Record."""
    rows = _query("Record", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"relativity.Record", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/matters", methods=["POST"])
def create_matter(request):
    """Create a Matter."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['clientId', 'title', 'status', 'openedAt'])
    if err:
        return err, 400
    err = _require(data, ['title', 'status'])
    if err:
        return err, 400
    rec = {"id": new_id("relativi_mat")}
    rec["clientId"] = data.get('clientId')
    rec["title"] = data.get('title')
    rec["status"] = data.get('status')
    rec["openedAt"] = data.get('openedAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Matter", rec)
    return rec, 201

@app.route("/v1/matters", methods=["GET"])
def list_matters(request):
    """List Matters with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Matter")
    rows = _apply_filters(rows, params, ['clientId', 'title', 'status', 'openedAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/matters/<eid>", methods=["GET"])
def get_matter(request, eid):
    """Retrieve a Matter by id (supports ?expand=)."""
    rows = _query("Matter", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/matters/<eid>", methods=["POST", "PATCH"])
def update_matter(request, eid):
    """Update a Matter."""
    rows = _query("Matter", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['clientId', 'title', 'status', 'openedAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Matter", rec)
    return rec, 200

@app.route("/v1/matters/<eid>", methods=["DELETE"])
def delete_matter(request, eid):
    """Delete a Matter."""
    rows = _query("Matter", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"relativity.Matter", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/contracts", methods=["POST"])
def create_contract(request):
    """Create a Contract."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['counterparty', 'value', 'status', 'signedAt'])
    if err:
        return err, 400
    err = _require(data, ['counterparty', 'value'])
    if err:
        return err, 400
    rec = {"id": new_id("relativi_con")}
    rec["counterparty"] = data.get('counterparty')
    rec["value"] = _as_float(data.get('value'))
    rec["status"] = data.get('status')
    rec["signedAt"] = data.get('signedAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Contract", rec)
    return rec, 201

@app.route("/v1/contracts", methods=["GET"])
def list_contracts(request):
    """List Contracts with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Contract")
    rows = _apply_filters(rows, params, ['counterparty', 'value', 'status', 'signedAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/contracts/<eid>", methods=["GET"])
def get_contract(request, eid):
    """Retrieve a Contract by id (supports ?expand=)."""
    rows = _query("Contract", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/contracts/<eid>", methods=["POST", "PATCH"])
def update_contract(request, eid):
    """Update a Contract."""
    rows = _query("Contract", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['counterparty', 'value', 'status', 'signedAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Contract", rec)
    return rec, 200

@app.route("/v1/contracts/<eid>", methods=["DELETE"])
def delete_contract(request, eid):
    """Delete a Contract."""
    rows = _query("Contract", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"relativity.Contract", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/courses", methods=["POST"])
def create_course(request):
    """Create a Course."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['title', 'term', 'enrollment'])
    if err:
        return err, 400
    err = _require(data, ['title', 'term'])
    if err:
        return err, 400
    rec = {"id": new_id("relativi_cou")}
    rec["title"] = data.get('title')
    rec["term"] = data.get('term')
    rec["enrollment"] = _as_int(data.get('enrollment'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Course", rec)
    return rec, 201

@app.route("/v1/courses", methods=["GET"])
def list_courses(request):
    """List Courses with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Course")
    rows = _apply_filters(rows, params, ['title', 'term', 'enrollment'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/courses/<eid>", methods=["GET"])
def get_course(request, eid):
    """Retrieve a Course by id (supports ?expand=)."""
    rows = _query("Course", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/courses/<eid>", methods=["POST", "PATCH"])
def update_course(request, eid):
    """Update a Course."""
    rows = _query("Course", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['title', 'term', 'enrollment'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Course", rec)
    return rec, 200

@app.route("/v1/courses/<eid>", methods=["DELETE"])
def delete_course(request, eid):
    """Delete a Course."""
    rows = _query("Course", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"relativity.Course", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/properties", methods=["POST"])
def create_property(request):
    """Create a Property."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['address', 'units', 'value'])
    if err:
        return err, 400
    err = _require(data, ['address', 'units'])
    if err:
        return err, 400
    rec = {"id": new_id("relativi_pro")}
    rec["address"] = data.get('address')
    rec["units"] = _as_int(data.get('units'))
    rec["value"] = _as_float(data.get('value'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Property", rec)
    return rec, 201

@app.route("/v1/properties", methods=["GET"])
def list_properties(request):
    """List Properties with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Property")
    rows = _apply_filters(rows, params, ['address', 'units', 'value'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/properties/<eid>", methods=["GET"])
def get_property(request, eid):
    """Retrieve a Property by id (supports ?expand=)."""
    rows = _query("Property", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/properties/<eid>", methods=["POST", "PATCH"])
def update_property(request, eid):
    """Update a Property."""
    rows = _query("Property", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['address', 'units', 'value'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Property", rec)
    return rec, 200

@app.route("/v1/properties/<eid>", methods=["DELETE"])
def delete_property(request, eid):
    """Delete a Property."""
    rows = _query("Property", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"relativity.Property", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/documents", methods=["POST"])
def create_document(request):
    """Create a Document."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['recordId', 'name', 'contentRef'])
    if err:
        return err, 400
    err = _require(data, ['name'])
    if err:
        return err, 400
    rec = {"id": new_id("relativi_doc")}
    rec["recordId"] = data.get('recordId')
    rec["name"] = data.get('name')
    rec["contentRef"] = data.get('contentRef')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Document", rec)
    return rec, 201

@app.route("/v1/documents", methods=["GET"])
def list_documents(request):
    """List Documents with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Document")
    rows = _apply_filters(rows, params, ['recordId', 'name', 'contentRef'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/documents/<eid>", methods=["GET"])
def get_document(request, eid):
    """Retrieve a Document by id (supports ?expand=)."""
    rows = _query("Document", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'recordId': 'Record'})
    return rec, 200

@app.route("/v1/documents/<eid>", methods=["POST", "PATCH"])
def update_document(request, eid):
    """Update a Document."""
    rows = _query("Document", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['recordId', 'name', 'contentRef'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Document", rec)
    return rec, 200

@app.route("/v1/documents/<eid>", methods=["DELETE"])
def delete_document(request, eid):
    """Delete a Document."""
    rows = _query("Document", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"relativity.Document", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "relativity-compat", "tier": "L4",
            "entities": ['Record', 'Matter', 'Contract', 'Course', 'Property', 'Document']}, 200


if __name__ == "__main__":
    app.start()
