apiVersion: v1
kind: Service
metadata:
  name: atproto-pds
  namespace: atproto
  labels:
    app: atproto-pds
    adr: "2605111300"
spec:
  type: ClusterIP
  selector:
    app: atproto-pds
  ports:
    - name: http
      port: 8787
      targetPort: 8787
      protocol: TCP
