apiVersion: v1
kind: Service
metadata:
  name: zeebe-murakumo-gateway
  namespace: mitama-udf
  labels:
    app.kubernetes.io/name: zeebe
    app.kubernetes.io/component: broker
    app.kubernetes.io/part-of: yoro.etzhayyim.com
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "tcp"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges:
    # Murakumo LAN egress, verified 2026-04-26.
    - 219.104.136.140/32
  selector:
    app.kubernetes.io/name: zeebe
  ports:
    - name: gateway
      port: 26500
      targetPort: 26500
      protocol: TCP
    - name: metrics
      port: 9600
      targetPort: 9600
      protocol: TCP
