// Auto-generated by etzhayyim wit-gen host-sdk — DO NOT EDIT.
// Source: packages/contract/wit/deps/magatama-*/package.wit

// magatama:bsky/richtext — byte-slice
export interface ByteSlice {
  byteStart: bigint;
  byteEnd: bigint;
}

// magatama:bsky/richtext — mention
export interface Mention {
  did: string;
}

// magatama:bsky/richtext — link
export interface Link {
  uri: string;
}

// magatama:bsky/richtext — tag
export interface Tag {
  tag: string;
}

// magatama:bsky/richtext — color-annotation
export interface ColorAnnotation {
  color: string;
}

// magatama:bsky/richtext — heading-annotation
export interface HeadingAnnotation {
  level: number;
}

// magatama:bsky/richtext — code-block-annotation
export interface CodeBlockAnnotation {
  language?: string;
}

// magatama:bsky/richtext — callout-annotation
export interface CalloutAnnotation {
  icon?: string;
  color?: string;
}

// magatama:bsky/richtext — list-annotation
export interface ListAnnotation {
  indent: number;
}

// magatama:bsky/richtext — todo-annotation
export interface TodoAnnotation {
  checked: boolean;
  indent: number;
}

// magatama:bsky/richtext — table-cell-annotation
export interface TableCellAnnotation {
  row: number;
  col: number;
  header?: boolean;
}

// magatama:bsky/richtext — math-annotation
export interface MathAnnotation {
  block: boolean;
}

