"""
Py Kotodama WASM entrypoint for the Salesforce clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/salesforce.kotoba")
db = DatomicClient.connect()
app = Runtime("salesforce-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"salesforce.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"salesforce.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/accounts", methods=["POST"])
def create_account(request):
    """Create a Account."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'industry', 'annualRevenue', 'ownerId', 'website'])
    if err:
        return err, 400
    err = _require(data, ['name', 'industry'])
    if err:
        return err, 400
    rec = {"id": new_id("salesfor_acc")}
    rec["name"] = data.get('name')
    rec["industry"] = data.get('industry')
    rec["annualRevenue"] = _as_float(data.get('annualRevenue'))
    rec["ownerId"] = data.get('ownerId')
    rec["website"] = data.get('website')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Account", rec)
    return rec, 201

@app.route("/v1/accounts", methods=["GET"])
def list_accounts(request):
    """List Accounts with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Account")
    rows = _apply_filters(rows, params, ['name', 'industry', 'annualRevenue', 'ownerId', 'website'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/accounts/<eid>", methods=["GET"])
def get_account(request, eid):
    """Retrieve a Account by id (supports ?expand=)."""
    rows = _query("Account", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/accounts/<eid>", methods=["POST", "PATCH"])
def update_account(request, eid):
    """Update a Account."""
    rows = _query("Account", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'industry', 'annualRevenue', 'ownerId', 'website'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Account", rec)
    return rec, 200

@app.route("/v1/accounts/<eid>", methods=["DELETE"])
def delete_account(request, eid):
    """Delete a Account."""
    rows = _query("Account", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"salesforce.Account", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/contacts", methods=["POST"])
def create_contact(request):
    """Create a Contact."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['accountId', 'firstName', 'lastName', 'email', 'title'])
    if err:
        return err, 400
    err = _require(data, ['firstName', 'lastName'])
    if err:
        return err, 400
    rec = {"id": new_id("salesfor_con")}
    rec["accountId"] = data.get('accountId')
    rec["firstName"] = data.get('firstName')
    rec["lastName"] = data.get('lastName')
    rec["email"] = data.get('email')
    rec["title"] = data.get('title')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Contact", rec)
    return rec, 201

@app.route("/v1/contacts", methods=["GET"])
def list_contacts(request):
    """List Contacts with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Contact")
    rows = _apply_filters(rows, params, ['accountId', 'firstName', 'lastName', 'email', 'title'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/contacts/<eid>", methods=["GET"])
def get_contact(request, eid):
    """Retrieve a Contact by id (supports ?expand=)."""
    rows = _query("Contact", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'accountId': 'Account'})
    return rec, 200

@app.route("/v1/contacts/<eid>", methods=["POST", "PATCH"])
def update_contact(request, eid):
    """Update a Contact."""
    rows = _query("Contact", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['accountId', 'firstName', 'lastName', 'email', 'title'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Contact", rec)
    return rec, 200

@app.route("/v1/contacts/<eid>", methods=["DELETE"])
def delete_contact(request, eid):
    """Delete a Contact."""
    rows = _query("Contact", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"salesforce.Contact", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/leads", methods=["POST"])
def create_lead(request):
    """Create a Lead."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['company', 'firstName', 'lastName', 'status', 'leadSource'])
    if err:
        return err, 400
    err = _require(data, ['company', 'firstName'])
    if err:
        return err, 400
    rec = {"id": new_id("salesfor_lea")}
    rec["company"] = data.get('company')
    rec["firstName"] = data.get('firstName')
    rec["lastName"] = data.get('lastName')
    rec["status"] = data.get('status')
    rec["leadSource"] = data.get('leadSource')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Lead", rec)
    return rec, 201

@app.route("/v1/leads", methods=["GET"])
def list_leads(request):
    """List Leads with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Lead")
    rows = _apply_filters(rows, params, ['company', 'firstName', 'lastName', 'status', 'leadSource'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/leads/<eid>", methods=["GET"])
def get_lead(request, eid):
    """Retrieve a Lead by id (supports ?expand=)."""
    rows = _query("Lead", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/leads/<eid>", methods=["POST", "PATCH"])
def update_lead(request, eid):
    """Update a Lead."""
    rows = _query("Lead", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['company', 'firstName', 'lastName', 'status', 'leadSource'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Lead", rec)
    return rec, 200

@app.route("/v1/leads/<eid>", methods=["DELETE"])
def delete_lead(request, eid):
    """Delete a Lead."""
    rows = _query("Lead", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"salesforce.Lead", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/opportunities", methods=["POST"])
def create_opportunity(request):
    """Create a Opportunity."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['accountId', 'name', 'stageName', 'amount', 'closeDate'])
    if err:
        return err, 400
    err = _require(data, ['name', 'stageName'])
    if err:
        return err, 400
    rec = {"id": new_id("salesfor_opp")}
    rec["accountId"] = data.get('accountId')
    rec["name"] = data.get('name')
    rec["stageName"] = data.get('stageName')
    rec["amount"] = _as_float(data.get('amount'))
    rec["closeDate"] = data.get('closeDate')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Opportunity", rec)
    return rec, 201

@app.route("/v1/opportunities", methods=["GET"])
def list_opportunities(request):
    """List Opportunities with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Opportunity")
    rows = _apply_filters(rows, params, ['accountId', 'name', 'stageName', 'amount', 'closeDate'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/opportunities/<eid>", methods=["GET"])
def get_opportunity(request, eid):
    """Retrieve a Opportunity by id (supports ?expand=)."""
    rows = _query("Opportunity", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'accountId': 'Account'})
    return rec, 200

@app.route("/v1/opportunities/<eid>", methods=["POST", "PATCH"])
def update_opportunity(request, eid):
    """Update a Opportunity."""
    rows = _query("Opportunity", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['accountId', 'name', 'stageName', 'amount', 'closeDate'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Opportunity", rec)
    return rec, 200

@app.route("/v1/opportunities/<eid>", methods=["DELETE"])
def delete_opportunity(request, eid):
    """Delete a Opportunity."""
    rows = _query("Opportunity", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"salesforce.Opportunity", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/cases", methods=["POST"])
def create_case(request):
    """Create a Case."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['accountId', 'subject', 'status', 'priority', 'origin'])
    if err:
        return err, 400
    err = _require(data, ['subject', 'status'])
    if err:
        return err, 400
    rec = {"id": new_id("salesfor_cas")}
    rec["accountId"] = data.get('accountId')
    rec["subject"] = data.get('subject')
    rec["status"] = data.get('status')
    rec["priority"] = data.get('priority')
    rec["origin"] = data.get('origin')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Case", rec)
    return rec, 201

@app.route("/v1/cases", methods=["GET"])
def list_cases(request):
    """List Cases with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Case")
    rows = _apply_filters(rows, params, ['accountId', 'subject', 'status', 'priority', 'origin'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/cases/<eid>", methods=["GET"])
def get_case(request, eid):
    """Retrieve a Case by id (supports ?expand=)."""
    rows = _query("Case", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'accountId': 'Account'})
    return rec, 200

@app.route("/v1/cases/<eid>", methods=["POST", "PATCH"])
def update_case(request, eid):
    """Update a Case."""
    rows = _query("Case", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['accountId', 'subject', 'status', 'priority', 'origin'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Case", rec)
    return rec, 200

@app.route("/v1/cases/<eid>", methods=["DELETE"])
def delete_case(request, eid):
    """Delete a Case."""
    rows = _query("Case", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"salesforce.Case", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/campaigns", methods=["POST"])
def create_campaign(request):
    """Create a Campaign."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'type', 'status', 'budgetedCost'])
    if err:
        return err, 400
    err = _require(data, ['name', 'type'])
    if err:
        return err, 400
    rec = {"id": new_id("salesfor_cam")}
    rec["name"] = data.get('name')
    rec["type"] = data.get('type')
    rec["status"] = data.get('status')
    rec["budgetedCost"] = _as_float(data.get('budgetedCost'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Campaign", rec)
    return rec, 201

@app.route("/v1/campaigns", methods=["GET"])
def list_campaigns(request):
    """List Campaigns with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Campaign")
    rows = _apply_filters(rows, params, ['name', 'type', 'status', 'budgetedCost'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/campaigns/<eid>", methods=["GET"])
def get_campaign(request, eid):
    """Retrieve a Campaign by id (supports ?expand=)."""
    rows = _query("Campaign", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/campaigns/<eid>", methods=["POST", "PATCH"])
def update_campaign(request, eid):
    """Update a Campaign."""
    rows = _query("Campaign", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'type', 'status', 'budgetedCost'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Campaign", rec)
    return rec, 200

@app.route("/v1/campaigns/<eid>", methods=["DELETE"])
def delete_campaign(request, eid):
    """Delete a Campaign."""
    rows = _query("Campaign", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"salesforce.Campaign", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/tasks", methods=["POST"])
def create_task(request):
    """Create a Task."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['whoId', 'subject', 'status', 'activityDate'])
    if err:
        return err, 400
    err = _require(data, ['subject', 'status'])
    if err:
        return err, 400
    rec = {"id": new_id("salesfor_tas")}
    rec["whoId"] = data.get('whoId')
    rec["subject"] = data.get('subject')
    rec["status"] = data.get('status')
    rec["activityDate"] = data.get('activityDate')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Task", rec)
    return rec, 201

@app.route("/v1/tasks", methods=["GET"])
def list_tasks(request):
    """List Tasks with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Task")
    rows = _apply_filters(rows, params, ['whoId', 'subject', 'status', 'activityDate'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/tasks/<eid>", methods=["GET"])
def get_task(request, eid):
    """Retrieve a Task by id (supports ?expand=)."""
    rows = _query("Task", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/tasks/<eid>", methods=["POST", "PATCH"])
def update_task(request, eid):
    """Update a Task."""
    rows = _query("Task", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['whoId', 'subject', 'status', 'activityDate'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Task", rec)
    return rec, 200

@app.route("/v1/tasks/<eid>", methods=["DELETE"])
def delete_task(request, eid):
    """Delete a Task."""
    rows = _query("Task", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"salesforce.Task", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "salesforce-compat", "tier": "L4",
            "entities": ['Account', 'Contact', 'Lead', 'Opportunity', 'Case', 'Campaign', 'Task']}, 200


if __name__ == "__main__":
    app.start()
