"""
Py Kotodama WASM entrypoint for the Imf clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/imf.kotoba")
db = DatomicClient.connect()
app = Runtime("imf-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"imf.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"imf.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/dataqueries", methods=["POST"])
def create_data_query(request):
    """Create a DataQuery."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['flowRef', 'key', 'startPeriod', 'endPeriod', 'updatedAfter', 'firstNObservations', 'lastNObservations', 'detail', 'includeHistory'])
    if err:
        return err, 400
    err = _require(data, ['key', 'startPeriod'])
    if err:
        return err, 400
    if data.get('detail') and data['detail'] not in ['full', 'dataonly', 'serieskeysonly', 'nodata']:
        return {"error": {"message": "invalid detail; allowed: " + ", ".join(['full', 'dataonly', 'serieskeysonly', 'nodata']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("imf_dat")}
    rec["flowRef"] = data.get('flowRef')
    rec["key"] = data.get('key')
    rec["startPeriod"] = data.get('startPeriod')
    rec["endPeriod"] = data.get('endPeriod')
    rec["updatedAfter"] = data.get('updatedAfter')
    rec["firstNObservations"] = _as_int(data.get('firstNObservations'))
    rec["lastNObservations"] = _as_int(data.get('lastNObservations'))
    rec["detail"] = data.get('detail')
    rec["includeHistory"] = _as_bool(data.get('includeHistory'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("DataQuery", rec)
    return rec, 201

@app.route("/v1/dataqueries", methods=["GET"])
def list_data_queries(request):
    """List DataQueries with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("DataQuery")
    rows = _apply_filters(rows, params, ['flowRef', 'key', 'startPeriod', 'endPeriod', 'updatedAfter', 'firstNObservations', 'lastNObservations', 'detail', 'includeHistory'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/dataqueries/<eid>", methods=["GET"])
def get_data_query(request, eid):
    """Retrieve a DataQuery by id (supports ?expand=)."""
    rows = _query("DataQuery", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/dataqueries/<eid>", methods=["POST", "PATCH"])
def update_data_query(request, eid):
    """Update a DataQuery."""
    rows = _query("DataQuery", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['flowRef', 'key', 'startPeriod', 'endPeriod', 'updatedAfter', 'firstNObservations', 'lastNObservations', 'detail', 'includeHistory'])
    if err:
        return err, 400
    if data.get('detail') and data['detail'] not in ['full', 'dataonly', 'serieskeysonly', 'nodata']:
        return {"error": {"message": "invalid detail; allowed: " + ", ".join(['full', 'dataonly', 'serieskeysonly', 'nodata']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("DataQuery", rec)
    return rec, 200

@app.route("/v1/dataqueries/<eid>", methods=["DELETE"])
def delete_data_query(request, eid):
    """Delete a DataQuery."""
    rows = _query("DataQuery", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"imf.DataQuery", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/dataflows", methods=["POST"])
def create_dataflow(request):
    """Create a Dataflow."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['agencyID', 'version', 'name'])
    if err:
        return err, 400
    err = _require(data, ['agencyID', 'version'])
    if err:
        return err, 400
    rec = {"id": new_id("imf_dat")}
    rec["agencyID"] = data.get('agencyID')
    rec["version"] = data.get('version')
    rec["name"] = data.get('name')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Dataflow", rec)
    return rec, 201

@app.route("/v1/dataflows", methods=["GET"])
def list_dataflows(request):
    """List Dataflows with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Dataflow")
    rows = _apply_filters(rows, params, ['agencyID', 'version', 'name'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/dataflows/<eid>", methods=["GET"])
def get_dataflow(request, eid):
    """Retrieve a Dataflow by id (supports ?expand=)."""
    rows = _query("Dataflow", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/dataflows/<eid>", methods=["POST", "PATCH"])
def update_dataflow(request, eid):
    """Update a Dataflow."""
    rows = _query("Dataflow", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['agencyID', 'version', 'name'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Dataflow", rec)
    return rec, 200

@app.route("/v1/dataflows/<eid>", methods=["DELETE"])
def delete_dataflow(request, eid):
    """Delete a Dataflow."""
    rows = _query("Dataflow", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"imf.Dataflow", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/serieses", methods=["POST"])
def create_series(request):
    """Create a Series."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['seriesKey', 'frequency', 'lastUpdated'])
    if err:
        return err, 400
    err = _require(data, ['seriesKey', 'frequency'])
    if err:
        return err, 400
    rec = {"id": new_id("imf_ser")}
    rec["seriesKey"] = data.get('seriesKey')
    rec["frequency"] = data.get('frequency')
    rec["lastUpdated"] = data.get('lastUpdated')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Series", rec)
    return rec, 201

@app.route("/v1/serieses", methods=["GET"])
def list_serieses(request):
    """List Serieses with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Series")
    rows = _apply_filters(rows, params, ['seriesKey', 'frequency', 'lastUpdated'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/serieses/<eid>", methods=["GET"])
def get_series(request, eid):
    """Retrieve a Series by id (supports ?expand=)."""
    rows = _query("Series", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/serieses/<eid>", methods=["POST", "PATCH"])
def update_series(request, eid):
    """Update a Series."""
    rows = _query("Series", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['seriesKey', 'frequency', 'lastUpdated'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Series", rec)
    return rec, 200

@app.route("/v1/serieses/<eid>", methods=["DELETE"])
def delete_series(request, eid):
    """Delete a Series."""
    rows = _query("Series", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"imf.Series", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "imf-compat", "tier": "L4",
            "entities": ['DataQuery', 'Dataflow', 'Series']}, 200


if __name__ == "__main__":
    app.start()
