"""
Py Kotodama WASM entrypoint for the Pagerduty clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/pagerduty.kotoba")
db = DatomicClient.connect()
app = Runtime("pagerduty-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"pagerduty.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"pagerduty.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/services", methods=["POST"])
def create_service(request):
    """Create a Service."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'environment', 'language'])
    if err:
        return err, 400
    err = _require(data, ['name', 'environment'])
    if err:
        return err, 400
    rec = {"id": new_id("pagerdut_ser")}
    rec["name"] = data.get('name')
    rec["environment"] = data.get('environment')
    rec["language"] = data.get('language')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Service", rec)
    return rec, 201

@app.route("/v1/services", methods=["GET"])
def list_services(request):
    """List Services with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Service")
    rows = _apply_filters(rows, params, ['name', 'environment', 'language'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/services/<eid>", methods=["GET"])
def get_service(request, eid):
    """Retrieve a Service by id (supports ?expand=)."""
    rows = _query("Service", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/services/<eid>", methods=["POST", "PATCH"])
def update_service(request, eid):
    """Update a Service."""
    rows = _query("Service", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'environment', 'language'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Service", rec)
    return rec, 200

@app.route("/v1/services/<eid>", methods=["DELETE"])
def delete_service(request, eid):
    """Delete a Service."""
    rows = _query("Service", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"pagerduty.Service", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/errors", methods=["POST"])
def create_error(request):
    """Create a Error."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['serviceId', 'message', 'culprit', 'count'])
    if err:
        return err, 400
    err = _require(data, ['message', 'culprit'])
    if err:
        return err, 400
    rec = {"id": new_id("pagerdut_err")}
    rec["serviceId"] = data.get('serviceId')
    rec["message"] = data.get('message')
    rec["culprit"] = data.get('culprit')
    rec["count"] = _as_int(data.get('count'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Error", rec)
    return rec, 201

@app.route("/v1/errors", methods=["GET"])
def list_errors(request):
    """List Errors with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Error")
    rows = _apply_filters(rows, params, ['serviceId', 'message', 'culprit', 'count'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/errors/<eid>", methods=["GET"])
def get_error(request, eid):
    """Retrieve a Error by id (supports ?expand=)."""
    rows = _query("Error", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'serviceId': 'Service'})
    return rec, 200

@app.route("/v1/errors/<eid>", methods=["POST", "PATCH"])
def update_error(request, eid):
    """Update a Error."""
    rows = _query("Error", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['serviceId', 'message', 'culprit', 'count'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Error", rec)
    return rec, 200

@app.route("/v1/errors/<eid>", methods=["DELETE"])
def delete_error(request, eid):
    """Delete a Error."""
    rows = _query("Error", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"pagerduty.Error", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/traces", methods=["POST"])
def create_trace(request):
    """Create a Trace."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['serviceId', 'operation', 'durationMs', 'status'])
    if err:
        return err, 400
    err = _require(data, ['operation', 'durationMs'])
    if err:
        return err, 400
    rec = {"id": new_id("pagerdut_tra")}
    rec["serviceId"] = data.get('serviceId')
    rec["operation"] = data.get('operation')
    rec["durationMs"] = _as_int(data.get('durationMs'))
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Trace", rec)
    return rec, 201

@app.route("/v1/traces", methods=["GET"])
def list_traces(request):
    """List Traces with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Trace")
    rows = _apply_filters(rows, params, ['serviceId', 'operation', 'durationMs', 'status'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/traces/<eid>", methods=["GET"])
def get_trace(request, eid):
    """Retrieve a Trace by id (supports ?expand=)."""
    rows = _query("Trace", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'serviceId': 'Service'})
    return rec, 200

@app.route("/v1/traces/<eid>", methods=["POST", "PATCH"])
def update_trace(request, eid):
    """Update a Trace."""
    rows = _query("Trace", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['serviceId', 'operation', 'durationMs', 'status'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Trace", rec)
    return rec, 200

@app.route("/v1/traces/<eid>", methods=["DELETE"])
def delete_trace(request, eid):
    """Delete a Trace."""
    rows = _query("Trace", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"pagerduty.Trace", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/metrics", methods=["POST"])
def create_metric(request):
    """Create a Metric."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['serviceId', 'name', 'value', 'unit'])
    if err:
        return err, 400
    err = _require(data, ['name', 'value'])
    if err:
        return err, 400
    rec = {"id": new_id("pagerdut_met")}
    rec["serviceId"] = data.get('serviceId')
    rec["name"] = data.get('name')
    rec["value"] = _as_float(data.get('value'))
    rec["unit"] = data.get('unit')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Metric", rec)
    return rec, 201

@app.route("/v1/metrics", methods=["GET"])
def list_metrics(request):
    """List Metrics with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Metric")
    rows = _apply_filters(rows, params, ['serviceId', 'name', 'value', 'unit'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/metrics/<eid>", methods=["GET"])
def get_metric(request, eid):
    """Retrieve a Metric by id (supports ?expand=)."""
    rows = _query("Metric", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'serviceId': 'Service'})
    return rec, 200

@app.route("/v1/metrics/<eid>", methods=["POST", "PATCH"])
def update_metric(request, eid):
    """Update a Metric."""
    rows = _query("Metric", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['serviceId', 'name', 'value', 'unit'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Metric", rec)
    return rec, 200

@app.route("/v1/metrics/<eid>", methods=["DELETE"])
def delete_metric(request, eid):
    """Delete a Metric."""
    rows = _query("Metric", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"pagerduty.Metric", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/alerts", methods=["POST"])
def create_alert(request):
    """Create a Alert."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['serviceId', 'condition', 'severity', 'active'])
    if err:
        return err, 400
    err = _require(data, ['condition', 'severity'])
    if err:
        return err, 400
    rec = {"id": new_id("pagerdut_ale")}
    rec["serviceId"] = data.get('serviceId')
    rec["condition"] = data.get('condition')
    rec["severity"] = data.get('severity')
    rec["active"] = _as_bool(data.get('active'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Alert", rec)
    return rec, 201

@app.route("/v1/alerts", methods=["GET"])
def list_alerts(request):
    """List Alerts with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Alert")
    rows = _apply_filters(rows, params, ['serviceId', 'condition', 'severity', 'active'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/alerts/<eid>", methods=["GET"])
def get_alert(request, eid):
    """Retrieve a Alert by id (supports ?expand=)."""
    rows = _query("Alert", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'serviceId': 'Service'})
    return rec, 200

@app.route("/v1/alerts/<eid>", methods=["POST", "PATCH"])
def update_alert(request, eid):
    """Update a Alert."""
    rows = _query("Alert", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['serviceId', 'condition', 'severity', 'active'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Alert", rec)
    return rec, 200

@app.route("/v1/alerts/<eid>", methods=["DELETE"])
def delete_alert(request, eid):
    """Delete a Alert."""
    rows = _query("Alert", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"pagerduty.Alert", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/incidents", methods=["POST"])
def create_incident(request):
    """Create a Incident."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['title', 'status', 'severity', 'startedAt'])
    if err:
        return err, 400
    err = _require(data, ['title', 'status'])
    if err:
        return err, 400
    rec = {"id": new_id("pagerdut_inc")}
    rec["title"] = data.get('title')
    rec["status"] = data.get('status')
    rec["severity"] = data.get('severity')
    rec["startedAt"] = data.get('startedAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Incident", rec)
    return rec, 201

@app.route("/v1/incidents", methods=["GET"])
def list_incidents(request):
    """List Incidents with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Incident")
    rows = _apply_filters(rows, params, ['title', 'status', 'severity', 'startedAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/incidents/<eid>", methods=["GET"])
def get_incident(request, eid):
    """Retrieve a Incident by id (supports ?expand=)."""
    rows = _query("Incident", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/incidents/<eid>", methods=["POST", "PATCH"])
def update_incident(request, eid):
    """Update a Incident."""
    rows = _query("Incident", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['title', 'status', 'severity', 'startedAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Incident", rec)
    return rec, 200

@app.route("/v1/incidents/<eid>", methods=["DELETE"])
def delete_incident(request, eid):
    """Delete a Incident."""
    rows = _query("Incident", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"pagerduty.Incident", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "pagerduty-compat", "tier": "L4",
            "entities": ['Service', 'Error', 'Trace', 'Metric', 'Alert', 'Incident']}, 200


if __name__ == "__main__":
    app.start()
