"""
Py Kotodama WASM entrypoint for the Canvaslms clean-room actor.

Clean-room, API-shaped CRUD over a Datomic-backed Kotoba schema.
Generated by 70-tools/deepen_actors.py (ADR 260607 deepening phase).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/canvaslms.kotoba")
db = DatomicClient.connect()
app = Runtime("canvaslms-compat")


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"canvaslms.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    """Read records of an entity from Datomic (optionally by id)."""
    pattern = {"entity": f"canvaslms.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing)}}
    return None


@app.route("/v1/records", methods=["POST"])
def create_record(request):
    """Create a Record."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'type'])
    if err:
        return err, 400
    rec = {"id": new_id("canvaslm_rec")}
    rec["name"] = data.get('name')
    rec["type"] = data.get('type')
    rec["ownerId"] = data.get('ownerId')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Record", rec)
    return rec, 201

@app.route("/v1/records", methods=["GET"])
def list_records(request):
    """List Records."""
    items = _query("Record")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/records/<eid>", methods=["GET"])
def get_record(request, eid):
    """Retrieve a Record by id."""
    rows = _query("Record", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/records/<eid>", methods=["POST", "PATCH"])
def update_record(request, eid):
    """Update a Record."""
    rows = _query("Record", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Record", rec)
    return rec, 200

@app.route("/v1/records/<eid>", methods=["DELETE"])
def delete_record(request, eid):
    """Delete a Record."""
    rows = _query("Record", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"canvaslms.Record", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/matters", methods=["POST"])
def create_matter(request):
    """Create a Matter."""
    data = request.json or request.form or {}
    err = _require(data, ['title', 'status'])
    if err:
        return err, 400
    rec = {"id": new_id("canvaslm_mat")}
    rec["clientId"] = data.get('clientId')
    rec["title"] = data.get('title')
    rec["status"] = data.get('status')
    rec["openedAt"] = data.get('openedAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Matter", rec)
    return rec, 201

@app.route("/v1/matters", methods=["GET"])
def list_matters(request):
    """List Matters."""
    items = _query("Matter")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/matters/<eid>", methods=["GET"])
def get_matter(request, eid):
    """Retrieve a Matter by id."""
    rows = _query("Matter", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/matters/<eid>", methods=["POST", "PATCH"])
def update_matter(request, eid):
    """Update a Matter."""
    rows = _query("Matter", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Matter", rec)
    return rec, 200

@app.route("/v1/matters/<eid>", methods=["DELETE"])
def delete_matter(request, eid):
    """Delete a Matter."""
    rows = _query("Matter", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"canvaslms.Matter", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/contracts", methods=["POST"])
def create_contract(request):
    """Create a Contract."""
    data = request.json or request.form or {}
    err = _require(data, ['counterparty', 'value'])
    if err:
        return err, 400
    rec = {"id": new_id("canvaslm_con")}
    rec["counterparty"] = data.get('counterparty')
    rec["value"] = float(data.get('value') or 0)
    rec["status"] = data.get('status')
    rec["signedAt"] = data.get('signedAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Contract", rec)
    return rec, 201

@app.route("/v1/contracts", methods=["GET"])
def list_contracts(request):
    """List Contracts."""
    items = _query("Contract")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/contracts/<eid>", methods=["GET"])
def get_contract(request, eid):
    """Retrieve a Contract by id."""
    rows = _query("Contract", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/contracts/<eid>", methods=["POST", "PATCH"])
def update_contract(request, eid):
    """Update a Contract."""
    rows = _query("Contract", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Contract", rec)
    return rec, 200

@app.route("/v1/contracts/<eid>", methods=["DELETE"])
def delete_contract(request, eid):
    """Delete a Contract."""
    rows = _query("Contract", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"canvaslms.Contract", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/courses", methods=["POST"])
def create_course(request):
    """Create a Course."""
    data = request.json or request.form or {}
    err = _require(data, ['title', 'term'])
    if err:
        return err, 400
    rec = {"id": new_id("canvaslm_cou")}
    rec["title"] = data.get('title')
    rec["term"] = data.get('term')
    rec["enrollment"] = int(data.get('enrollment') or 0)
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Course", rec)
    return rec, 201

@app.route("/v1/courses", methods=["GET"])
def list_courses(request):
    """List Courses."""
    items = _query("Course")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/courses/<eid>", methods=["GET"])
def get_course(request, eid):
    """Retrieve a Course by id."""
    rows = _query("Course", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/courses/<eid>", methods=["POST", "PATCH"])
def update_course(request, eid):
    """Update a Course."""
    rows = _query("Course", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Course", rec)
    return rec, 200

@app.route("/v1/courses/<eid>", methods=["DELETE"])
def delete_course(request, eid):
    """Delete a Course."""
    rows = _query("Course", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"canvaslms.Course", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/properties", methods=["POST"])
def create_property(request):
    """Create a Property."""
    data = request.json or request.form or {}
    err = _require(data, ['address', 'units'])
    if err:
        return err, 400
    rec = {"id": new_id("canvaslm_pro")}
    rec["address"] = data.get('address')
    rec["units"] = int(data.get('units') or 0)
    rec["value"] = float(data.get('value') or 0)
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Property", rec)
    return rec, 201

@app.route("/v1/properties", methods=["GET"])
def list_properties(request):
    """List Properties."""
    items = _query("Property")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/properties/<eid>", methods=["GET"])
def get_property(request, eid):
    """Retrieve a Property by id."""
    rows = _query("Property", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/properties/<eid>", methods=["POST", "PATCH"])
def update_property(request, eid):
    """Update a Property."""
    rows = _query("Property", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Property", rec)
    return rec, 200

@app.route("/v1/properties/<eid>", methods=["DELETE"])
def delete_property(request, eid):
    """Delete a Property."""
    rows = _query("Property", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"canvaslms.Property", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/documents", methods=["POST"])
def create_document(request):
    """Create a Document."""
    data = request.json or request.form or {}
    err = _require(data, ['name'])
    if err:
        return err, 400
    rec = {"id": new_id("canvaslm_doc")}
    rec["recordId"] = data.get('recordId')
    rec["name"] = data.get('name')
    rec["contentRef"] = data.get('contentRef')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Document", rec)
    return rec, 201

@app.route("/v1/documents", methods=["GET"])
def list_documents(request):
    """List Documents."""
    items = _query("Document")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/documents/<eid>", methods=["GET"])
def get_document(request, eid):
    """Retrieve a Document by id."""
    rows = _query("Document", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/documents/<eid>", methods=["POST", "PATCH"])
def update_document(request, eid):
    """Update a Document."""
    rows = _query("Document", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Document", rec)
    return rec, 200

@app.route("/v1/documents/<eid>", methods=["DELETE"])
def delete_document(request, eid):
    """Delete a Document."""
    rows = _query("Document", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"canvaslms.Document", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "canvaslms-compat", "entities": ['Record', 'Matter', 'Contract', 'Course', 'Property', 'Document']}, 200


if __name__ == "__main__":
    app.start()
