"""
Py Kotodama WASM entrypoint for the Coinbase clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/coinbase.kotoba")
db = DatomicClient.connect()
app = Runtime("coinbase-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"coinbase.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"coinbase.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/orders", methods=["POST"])
def create_order(request):
    """Create a Order."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['orderId', 'productId', 'side', 'status', 'clientOrderId', 'orderType'])
    if err:
        return err, 400
    err = _require(data, ['side', 'status'])
    if err:
        return err, 400
    if data.get('side') and data['side'] not in ['BUY', 'SELL']:
        return {"error": {"message": "invalid side; allowed: " + ", ".join(['BUY', 'SELL']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("coinbase_ord")}
    rec["orderId"] = data.get('orderId')
    rec["productId"] = data.get('productId')
    rec["side"] = data.get('side')
    rec["status"] = data.get('status')
    rec["clientOrderId"] = data.get('clientOrderId')
    rec["orderType"] = data.get('orderType')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Order", rec)
    return rec, 201

@app.route("/v1/orders", methods=["GET"])
def list_orders(request):
    """List Orders with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Order")
    rows = _apply_filters(rows, params, ['orderId', 'productId', 'side', 'status', 'clientOrderId', 'orderType'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/orders/<eid>", methods=["GET"])
def get_order(request, eid):
    """Retrieve a Order by id (supports ?expand=)."""
    rows = _query("Order", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'orderId': 'Order', 'productId': 'Product'})
    return rec, 200

@app.route("/v1/orders/<eid>", methods=["POST", "PATCH"])
def update_order(request, eid):
    """Update a Order."""
    rows = _query("Order", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['orderId', 'productId', 'side', 'status', 'clientOrderId', 'orderType'])
    if err:
        return err, 400
    if data.get('side') and data['side'] not in ['BUY', 'SELL']:
        return {"error": {"message": "invalid side; allowed: " + ", ".join(['BUY', 'SELL']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Order", rec)
    return rec, 200

@app.route("/v1/orders/<eid>", methods=["DELETE"])
def delete_order(request, eid):
    """Delete a Order."""
    rows = _query("Order", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"coinbase.Order", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/fills", methods=["POST"])
def create_fill(request):
    """Create a Fill."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['entryId', 'tradeId', 'orderId', 'price', 'size', 'productId', 'side'])
    if err:
        return err, 400
    err = _require(data, ['price', 'size'])
    if err:
        return err, 400
    if data.get('side') and data['side'] not in ['BUY', 'SELL']:
        return {"error": {"message": "invalid side; allowed: " + ", ".join(['BUY', 'SELL']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("coinbase_fil")}
    rec["entryId"] = data.get('entryId')
    rec["tradeId"] = data.get('tradeId')
    rec["orderId"] = data.get('orderId')
    rec["price"] = data.get('price')
    rec["size"] = data.get('size')
    rec["productId"] = data.get('productId')
    rec["side"] = data.get('side')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Fill", rec)
    return rec, 201

@app.route("/v1/fills", methods=["GET"])
def list_fills(request):
    """List Fills with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Fill")
    rows = _apply_filters(rows, params, ['entryId', 'tradeId', 'orderId', 'price', 'size', 'productId', 'side'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/fills/<eid>", methods=["GET"])
def get_fill(request, eid):
    """Retrieve a Fill by id (supports ?expand=)."""
    rows = _query("Fill", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'orderId': 'Order', 'productId': 'Product'})
    return rec, 200

@app.route("/v1/fills/<eid>", methods=["POST", "PATCH"])
def update_fill(request, eid):
    """Update a Fill."""
    rows = _query("Fill", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['entryId', 'tradeId', 'orderId', 'price', 'size', 'productId', 'side'])
    if err:
        return err, 400
    if data.get('side') and data['side'] not in ['BUY', 'SELL']:
        return {"error": {"message": "invalid side; allowed: " + ", ".join(['BUY', 'SELL']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Fill", rec)
    return rec, 200

@app.route("/v1/fills/<eid>", methods=["DELETE"])
def delete_fill(request, eid):
    """Delete a Fill."""
    rows = _query("Fill", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"coinbase.Fill", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/accounts", methods=["POST"])
def create_account(request):
    """Create a Account."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['uuid', 'name', 'currency', 'default', 'active', 'type'])
    if err:
        return err, 400
    err = _require(data, ['uuid', 'name'])
    if err:
        return err, 400
    rec = {"id": new_id("coinbase_acc")}
    rec["uuid"] = data.get('uuid')
    rec["name"] = data.get('name')
    rec["currency"] = data.get('currency')
    rec["default"] = _as_bool(data.get('default'))
    rec["active"] = _as_bool(data.get('active'))
    rec["type"] = data.get('type')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Account", rec)
    return rec, 201

@app.route("/v1/accounts", methods=["GET"])
def list_accounts(request):
    """List Accounts with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Account")
    rows = _apply_filters(rows, params, ['uuid', 'name', 'currency', 'default', 'active', 'type'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/accounts/<eid>", methods=["GET"])
def get_account(request, eid):
    """Retrieve a Account by id (supports ?expand=)."""
    rows = _query("Account", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/accounts/<eid>", methods=["POST", "PATCH"])
def update_account(request, eid):
    """Update a Account."""
    rows = _query("Account", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['uuid', 'name', 'currency', 'default', 'active', 'type'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Account", rec)
    return rec, 200

@app.route("/v1/accounts/<eid>", methods=["DELETE"])
def delete_account(request, eid):
    """Delete a Account."""
    rows = _query("Account", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"coinbase.Account", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/products", methods=["POST"])
def create_product(request):
    """Create a Product."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['productId', 'price', 'volume24h', 'productType', 'status'])
    if err:
        return err, 400
    err = _require(data, ['price', 'volume24h'])
    if err:
        return err, 400
    rec = {"id": new_id("coinbase_pro")}
    rec["productId"] = data.get('productId')
    rec["price"] = data.get('price')
    rec["volume24h"] = data.get('volume24h')
    rec["productType"] = data.get('productType')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Product", rec)
    return rec, 201

@app.route("/v1/products", methods=["GET"])
def list_products(request):
    """List Products with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Product")
    rows = _apply_filters(rows, params, ['productId', 'price', 'volume24h', 'productType', 'status'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/products/<eid>", methods=["GET"])
def get_product(request, eid):
    """Retrieve a Product by id (supports ?expand=)."""
    rows = _query("Product", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'productId': 'Product'})
    return rec, 200

@app.route("/v1/products/<eid>", methods=["POST", "PATCH"])
def update_product(request, eid):
    """Update a Product."""
    rows = _query("Product", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['productId', 'price', 'volume24h', 'productType', 'status'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Product", rec)
    return rec, 200

@app.route("/v1/products/<eid>", methods=["DELETE"])
def delete_product(request, eid):
    """Delete a Product."""
    rows = _query("Product", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"coinbase.Product", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/portfolios", methods=["POST"])
def create_portfolio(request):
    """Create a Portfolio."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['uuid', 'name', 'type'])
    if err:
        return err, 400
    err = _require(data, ['uuid', 'name'])
    if err:
        return err, 400
    rec = {"id": new_id("coinbase_por")}
    rec["uuid"] = data.get('uuid')
    rec["name"] = data.get('name')
    rec["type"] = data.get('type')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Portfolio", rec)
    return rec, 201

@app.route("/v1/portfolios", methods=["GET"])
def list_portfolios(request):
    """List Portfolios with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Portfolio")
    rows = _apply_filters(rows, params, ['uuid', 'name', 'type'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/portfolios/<eid>", methods=["GET"])
def get_portfolio(request, eid):
    """Retrieve a Portfolio by id (supports ?expand=)."""
    rows = _query("Portfolio", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/portfolios/<eid>", methods=["POST", "PATCH"])
def update_portfolio(request, eid):
    """Update a Portfolio."""
    rows = _query("Portfolio", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['uuid', 'name', 'type'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Portfolio", rec)
    return rec, 200

@app.route("/v1/portfolios/<eid>", methods=["DELETE"])
def delete_portfolio(request, eid):
    """Delete a Portfolio."""
    rows = _query("Portfolio", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"coinbase.Portfolio", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/portfoliopositions", methods=["POST"])
def create_portfolio_position(request):
    """Create a PortfolioPosition."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['asset', 'totalBalanceFiat', 'totalBalanceCrypto', 'allocation'])
    if err:
        return err, 400
    err = _require(data, ['asset', 'totalBalanceFiat'])
    if err:
        return err, 400
    rec = {"id": new_id("coinbase_por")}
    rec["asset"] = data.get('asset')
    rec["totalBalanceFiat"] = _as_float(data.get('totalBalanceFiat'))
    rec["totalBalanceCrypto"] = _as_float(data.get('totalBalanceCrypto'))
    rec["allocation"] = _as_float(data.get('allocation'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("PortfolioPosition", rec)
    return rec, 201

@app.route("/v1/portfoliopositions", methods=["GET"])
def list_portfolio_positions(request):
    """List PortfolioPositions with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("PortfolioPosition")
    rows = _apply_filters(rows, params, ['asset', 'totalBalanceFiat', 'totalBalanceCrypto', 'allocation'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/portfoliopositions/<eid>", methods=["GET"])
def get_portfolio_position(request, eid):
    """Retrieve a PortfolioPosition by id (supports ?expand=)."""
    rows = _query("PortfolioPosition", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/portfoliopositions/<eid>", methods=["POST", "PATCH"])
def update_portfolio_position(request, eid):
    """Update a PortfolioPosition."""
    rows = _query("PortfolioPosition", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['asset', 'totalBalanceFiat', 'totalBalanceCrypto', 'allocation'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("PortfolioPosition", rec)
    return rec, 200

@app.route("/v1/portfoliopositions/<eid>", methods=["DELETE"])
def delete_portfolio_position(request, eid):
    """Delete a PortfolioPosition."""
    rows = _query("PortfolioPosition", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"coinbase.PortfolioPosition", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "coinbase-compat", "tier": "L4",
            "entities": ['Order', 'Fill', 'Account', 'Product', 'Portfolio', 'PortfolioPosition']}, 200


if __name__ == "__main__":
    app.start()
