"""
Py Kotodama WASM entrypoint for the Trello clean-room actor.

Clean-room, API-shaped CRUD over a Datomic-backed Kotoba schema.
Generated by 70-tools/deepen_actors.py (ADR 260607 deepening phase).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/trello.kotoba")
db = DatomicClient.connect()
app = Runtime("trello-compat")


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"trello.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    """Read records of an entity from Datomic (optionally by id)."""
    pattern = {"entity": f"trello.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing)}}
    return None


@app.route("/v1/boards", methods=["POST"])
def create_board(request):
    """Create a Board."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'desc'])
    if err:
        return err, 400
    rec = {"id": new_id("trello_boa")}
    rec["name"] = data.get('name')
    rec["desc"] = data.get('desc')
    rec["closed"] = bool(data.get('closed'))
    rec["pinned"] = bool(data.get('pinned'))
    rec["starred"] = bool(data.get('starred'))
    rec["url"] = data.get('url')
    rec["shortUrl"] = data.get('shortUrl')
    rec["shortLink"] = data.get('shortLink')
    rec["subscribed"] = bool(data.get('subscribed'))
    rec["dateLastActivity"] = data.get('dateLastActivity')
    rec["creationMethod"] = data.get('creationMethod')
    rec["enterpriseOwned"] = bool(data.get('enterpriseOwned'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Board", rec)
    return rec, 201

@app.route("/v1/boards", methods=["GET"])
def list_boards(request):
    """List Boards."""
    items = _query("Board")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/boards/<eid>", methods=["GET"])
def get_board(request, eid):
    """Retrieve a Board by id."""
    rows = _query("Board", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/boards/<eid>", methods=["POST", "PATCH"])
def update_board(request, eid):
    """Update a Board."""
    rows = _query("Board", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Board", rec)
    return rec, 200

@app.route("/v1/boards/<eid>", methods=["DELETE"])
def delete_board(request, eid):
    """Delete a Board."""
    rows = _query("Board", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"trello.Board", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/lists", methods=["POST"])
def create_list(request):
    """Create a List."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'closed'])
    if err:
        return err, 400
    rec = {"id": new_id("trello_lis")}
    rec["name"] = data.get('name')
    rec["closed"] = bool(data.get('closed'))
    rec["pos"] = float(data.get('pos') or 0)
    rec["softLimit"] = data.get('softLimit')
    rec["idBoard"] = data.get('idBoard')
    rec["subscribed"] = bool(data.get('subscribed'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("List", rec)
    return rec, 201

@app.route("/v1/lists", methods=["GET"])
def list_lists(request):
    """List Lists."""
    items = _query("List")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/lists/<eid>", methods=["GET"])
def get_list(request, eid):
    """Retrieve a List by id."""
    rows = _query("List", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/lists/<eid>", methods=["POST", "PATCH"])
def update_list(request, eid):
    """Update a List."""
    rows = _query("List", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("List", rec)
    return rec, 200

@app.route("/v1/lists/<eid>", methods=["DELETE"])
def delete_list(request, eid):
    """Delete a List."""
    rows = _query("List", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"trello.List", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/cards", methods=["POST"])
def create_card(request):
    """Create a Card."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'desc'])
    if err:
        return err, 400
    rec = {"id": new_id("trello_car")}
    rec["name"] = data.get('name')
    rec["desc"] = data.get('desc')
    rec["closed"] = bool(data.get('closed'))
    rec["cardRole"] = data.get('cardRole')
    rec["due"] = data.get('due')
    rec["dueReminder"] = data.get('dueReminder')
    rec["idBoard"] = data.get('idBoard')
    rec["idList"] = data.get('idList')
    rec["idShort"] = int(data.get('idShort') or 0)
    rec["pos"] = float(data.get('pos') or 0)
    rec["shortLink"] = data.get('shortLink')
    rec["url"] = data.get('url')
    rec["subscribed"] = bool(data.get('subscribed'))
    rec["dateLastActivity"] = data.get('dateLastActivity')
    rec["locationName"] = data.get('locationName')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Card", rec)
    return rec, 201

@app.route("/v1/cards", methods=["GET"])
def list_cards(request):
    """List Cards."""
    items = _query("Card")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/cards/<eid>", methods=["GET"])
def get_card(request, eid):
    """Retrieve a Card by id."""
    rows = _query("Card", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/cards/<eid>", methods=["POST", "PATCH"])
def update_card(request, eid):
    """Update a Card."""
    rows = _query("Card", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Card", rec)
    return rec, 200

@app.route("/v1/cards/<eid>", methods=["DELETE"])
def delete_card(request, eid):
    """Delete a Card."""
    rows = _query("Card", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"trello.Card", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/members", methods=["POST"])
def create_member(request):
    """Create a Member."""
    data = request.json or request.form or {}
    err = _require(data, ['fullName', 'username'])
    if err:
        return err, 400
    rec = {"id": new_id("trello_mem")}
    rec["fullName"] = data.get('fullName')
    rec["username"] = data.get('username')
    rec["initials"] = data.get('initials')
    rec["bio"] = data.get('bio')
    rec["confirmed"] = bool(data.get('confirmed'))
    rec["memberType"] = data.get('memberType')
    rec["email"] = data.get('email')
    rec["avatarUrl"] = data.get('avatarUrl')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Member", rec)
    return rec, 201

@app.route("/v1/members", methods=["GET"])
def list_members(request):
    """List Members."""
    items = _query("Member")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/members/<eid>", methods=["GET"])
def get_member(request, eid):
    """Retrieve a Member by id."""
    rows = _query("Member", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/members/<eid>", methods=["POST", "PATCH"])
def update_member(request, eid):
    """Update a Member."""
    rows = _query("Member", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Member", rec)
    return rec, 200

@app.route("/v1/members/<eid>", methods=["DELETE"])
def delete_member(request, eid):
    """Delete a Member."""
    rows = _query("Member", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"trello.Member", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/labels", methods=["POST"])
def create_label(request):
    """Create a Label."""
    data = request.json or request.form or {}
    err = _require(data, ['idBoard', 'name'])
    if err:
        return err, 400
    rec = {"id": new_id("trello_lab")}
    rec["idBoard"] = data.get('idBoard')
    rec["name"] = data.get('name')
    rec["color"] = data.get('color')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Label", rec)
    return rec, 201

@app.route("/v1/labels", methods=["GET"])
def list_labels(request):
    """List Labels."""
    items = _query("Label")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/labels/<eid>", methods=["GET"])
def get_label(request, eid):
    """Retrieve a Label by id."""
    rows = _query("Label", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/labels/<eid>", methods=["POST", "PATCH"])
def update_label(request, eid):
    """Update a Label."""
    rows = _query("Label", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Label", rec)
    return rec, 200

@app.route("/v1/labels/<eid>", methods=["DELETE"])
def delete_label(request, eid):
    """Delete a Label."""
    rows = _query("Label", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"trello.Label", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/organizations", methods=["POST"])
def create_organization(request):
    """Create a Organization."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'displayName'])
    if err:
        return err, 400
    rec = {"id": new_id("trello_org")}
    rec["name"] = data.get('name')
    rec["displayName"] = data.get('displayName')
    rec["url"] = data.get('url')
    rec["offering"] = data.get('offering')
    rec["dateLastActivity"] = data.get('dateLastActivity')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Organization", rec)
    return rec, 201

@app.route("/v1/organizations", methods=["GET"])
def list_organizations(request):
    """List Organizations."""
    items = _query("Organization")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/organizations/<eid>", methods=["GET"])
def get_organization(request, eid):
    """Retrieve a Organization by id."""
    rows = _query("Organization", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/organizations/<eid>", methods=["POST", "PATCH"])
def update_organization(request, eid):
    """Update a Organization."""
    rows = _query("Organization", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Organization", rec)
    return rec, 200

@app.route("/v1/organizations/<eid>", methods=["DELETE"])
def delete_organization(request, eid):
    """Delete a Organization."""
    rows = _query("Organization", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"trello.Organization", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "trello-compat", "entities": ['Board', 'List', 'Card', 'Member', 'Label', 'Organization']}, 200


if __name__ == "__main__":
    app.start()
