"""
Py Kotodama WASM entrypoint for the Airbyte clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/airbyte.kotoba")
db = DatomicClient.connect()
app = Runtime("airbyte-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"airbyte.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"airbyte.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/airbytemessages", methods=["POST"])
def create_airbyte_message(request):
    """Create a AirbyteMessage."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type'])
    if err:
        return err, 400
    err = _require(data, ['type'])
    if err:
        return err, 400
    rec = {"id": new_id("airbyte_air")}
    rec["type"] = data.get('type')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("AirbyteMessage", rec)
    return rec, 201

@app.route("/v1/airbytemessages", methods=["GET"])
def list_airbyte_messages(request):
    """List AirbyteMessages with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("AirbyteMessage")
    rows = _apply_filters(rows, params, ['type'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/airbytemessages/<eid>", methods=["GET"])
def get_airbyte_message(request, eid):
    """Retrieve a AirbyteMessage by id (supports ?expand=)."""
    rows = _query("AirbyteMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/airbytemessages/<eid>", methods=["POST", "PATCH"])
def update_airbyte_message(request, eid):
    """Update a AirbyteMessage."""
    rows = _query("AirbyteMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("AirbyteMessage", rec)
    return rec, 200

@app.route("/v1/airbytemessages/<eid>", methods=["DELETE"])
def delete_airbyte_message(request, eid):
    """Delete a AirbyteMessage."""
    rows = _query("AirbyteMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"airbyte.AirbyteMessage", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/airbyterecordmessages", methods=["POST"])
def create_airbyte_record_message(request):
    """Create a AirbyteRecordMessage."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['stream', 'namespace', 'emittedAt'])
    if err:
        return err, 400
    err = _require(data, ['stream', 'namespace'])
    if err:
        return err, 400
    rec = {"id": new_id("airbyte_air")}
    rec["stream"] = data.get('stream')
    rec["namespace"] = data.get('namespace')
    rec["emittedAt"] = _as_int(data.get('emittedAt'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("AirbyteRecordMessage", rec)
    return rec, 201

@app.route("/v1/airbyterecordmessages", methods=["GET"])
def list_airbyte_record_messages(request):
    """List AirbyteRecordMessages with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("AirbyteRecordMessage")
    rows = _apply_filters(rows, params, ['stream', 'namespace', 'emittedAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/airbyterecordmessages/<eid>", methods=["GET"])
def get_airbyte_record_message(request, eid):
    """Retrieve a AirbyteRecordMessage by id (supports ?expand=)."""
    rows = _query("AirbyteRecordMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/airbyterecordmessages/<eid>", methods=["POST", "PATCH"])
def update_airbyte_record_message(request, eid):
    """Update a AirbyteRecordMessage."""
    rows = _query("AirbyteRecordMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['stream', 'namespace', 'emittedAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("AirbyteRecordMessage", rec)
    return rec, 200

@app.route("/v1/airbyterecordmessages/<eid>", methods=["DELETE"])
def delete_airbyte_record_message(request, eid):
    """Delete a AirbyteRecordMessage."""
    rows = _query("AirbyteRecordMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"airbyte.AirbyteRecordMessage", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/airbytelogmessages", methods=["POST"])
def create_airbyte_log_message(request):
    """Create a AirbyteLogMessage."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['level', 'message', 'stackTrace'])
    if err:
        return err, 400
    err = _require(data, ['level', 'message'])
    if err:
        return err, 400
    if data.get('level') and data['level'] not in ['FATAL', 'ERROR', 'WARN', 'INFO', 'DEBUG', 'TRACE']:
        return {"error": {"message": "invalid level; allowed: " + ", ".join(['FATAL', 'ERROR', 'WARN', 'INFO', 'DEBUG', 'TRACE']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("airbyte_air")}
    rec["level"] = data.get('level')
    rec["message"] = data.get('message')
    rec["stackTrace"] = data.get('stackTrace')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("AirbyteLogMessage", rec)
    return rec, 201

@app.route("/v1/airbytelogmessages", methods=["GET"])
def list_airbyte_log_messages(request):
    """List AirbyteLogMessages with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("AirbyteLogMessage")
    rows = _apply_filters(rows, params, ['level', 'message', 'stackTrace'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/airbytelogmessages/<eid>", methods=["GET"])
def get_airbyte_log_message(request, eid):
    """Retrieve a AirbyteLogMessage by id (supports ?expand=)."""
    rows = _query("AirbyteLogMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/airbytelogmessages/<eid>", methods=["POST", "PATCH"])
def update_airbyte_log_message(request, eid):
    """Update a AirbyteLogMessage."""
    rows = _query("AirbyteLogMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['level', 'message', 'stackTrace'])
    if err:
        return err, 400
    if data.get('level') and data['level'] not in ['FATAL', 'ERROR', 'WARN', 'INFO', 'DEBUG', 'TRACE']:
        return {"error": {"message": "invalid level; allowed: " + ", ".join(['FATAL', 'ERROR', 'WARN', 'INFO', 'DEBUG', 'TRACE']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("AirbyteLogMessage", rec)
    return rec, 200

@app.route("/v1/airbytelogmessages/<eid>", methods=["DELETE"])
def delete_airbyte_log_message(request, eid):
    """Delete a AirbyteLogMessage."""
    rows = _query("AirbyteLogMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"airbyte.AirbyteLogMessage", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/airbyteconnectionstatuses", methods=["POST"])
def create_airbyte_connection_status(request):
    """Create a AirbyteConnectionStatus."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['status', 'message'])
    if err:
        return err, 400
    err = _require(data, ['status', 'message'])
    if err:
        return err, 400
    if data.get('status') and data['status'] not in ['SUCCEEDED', 'FAILED']:
        return {"error": {"message": "invalid status; allowed: " + ", ".join(['SUCCEEDED', 'FAILED']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("airbyte_air")}
    rec["status"] = data.get('status')
    rec["message"] = data.get('message')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("AirbyteConnectionStatus", rec)
    return rec, 201

@app.route("/v1/airbyteconnectionstatuses", methods=["GET"])
def list_airbyte_connection_statuses(request):
    """List AirbyteConnectionStatuses with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("AirbyteConnectionStatus")
    rows = _apply_filters(rows, params, ['status', 'message'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/airbyteconnectionstatuses/<eid>", methods=["GET"])
def get_airbyte_connection_status(request, eid):
    """Retrieve a AirbyteConnectionStatus by id (supports ?expand=)."""
    rows = _query("AirbyteConnectionStatus", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/airbyteconnectionstatuses/<eid>", methods=["POST", "PATCH"])
def update_airbyte_connection_status(request, eid):
    """Update a AirbyteConnectionStatus."""
    rows = _query("AirbyteConnectionStatus", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['status', 'message'])
    if err:
        return err, 400
    if data.get('status') and data['status'] not in ['SUCCEEDED', 'FAILED']:
        return {"error": {"message": "invalid status; allowed: " + ", ".join(['SUCCEEDED', 'FAILED']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("AirbyteConnectionStatus", rec)
    return rec, 200

@app.route("/v1/airbyteconnectionstatuses/<eid>", methods=["DELETE"])
def delete_airbyte_connection_status(request, eid):
    """Delete a AirbyteConnectionStatus."""
    rows = _query("AirbyteConnectionStatus", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"airbyte.AirbyteConnectionStatus", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/airbytestatemessages", methods=["POST"])
def create_airbyte_state_message(request):
    """Create a AirbyteStateMessage."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type'])
    if err:
        return err, 400
    err = _require(data, ['type'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['GLOBAL', 'STREAM', 'LEGACY']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['GLOBAL', 'STREAM', 'LEGACY']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("airbyte_air")}
    rec["type"] = data.get('type')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("AirbyteStateMessage", rec)
    return rec, 201

@app.route("/v1/airbytestatemessages", methods=["GET"])
def list_airbyte_state_messages(request):
    """List AirbyteStateMessages with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("AirbyteStateMessage")
    rows = _apply_filters(rows, params, ['type'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/airbytestatemessages/<eid>", methods=["GET"])
def get_airbyte_state_message(request, eid):
    """Retrieve a AirbyteStateMessage by id (supports ?expand=)."""
    rows = _query("AirbyteStateMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/airbytestatemessages/<eid>", methods=["POST", "PATCH"])
def update_airbyte_state_message(request, eid):
    """Update a AirbyteStateMessage."""
    rows = _query("AirbyteStateMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['GLOBAL', 'STREAM', 'LEGACY']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['GLOBAL', 'STREAM', 'LEGACY']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("AirbyteStateMessage", rec)
    return rec, 200

@app.route("/v1/airbytestatemessages/<eid>", methods=["DELETE"])
def delete_airbyte_state_message(request, eid):
    """Delete a AirbyteStateMessage."""
    rows = _query("AirbyteStateMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"airbyte.AirbyteStateMessage", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/airbytestreamstatustracemessages", methods=["POST"])
def create_airbyte_stream_status_trace_message(request):
    """Create a AirbyteStreamStatusTraceMessage."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['status'])
    if err:
        return err, 400
    err = _require(data, ['status'])
    if err:
        return err, 400
    if data.get('status') and data['status'] not in ['STARTED', 'RUNNING', 'COMPLETE', 'INCOMPLETE']:
        return {"error": {"message": "invalid status; allowed: " + ", ".join(['STARTED', 'RUNNING', 'COMPLETE', 'INCOMPLETE']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("airbyte_air")}
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("AirbyteStreamStatusTraceMessage", rec)
    return rec, 201

@app.route("/v1/airbytestreamstatustracemessages", methods=["GET"])
def list_airbyte_stream_status_trace_messages(request):
    """List AirbyteStreamStatusTraceMessages with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("AirbyteStreamStatusTraceMessage")
    rows = _apply_filters(rows, params, ['status'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/airbytestreamstatustracemessages/<eid>", methods=["GET"])
def get_airbyte_stream_status_trace_message(request, eid):
    """Retrieve a AirbyteStreamStatusTraceMessage by id (supports ?expand=)."""
    rows = _query("AirbyteStreamStatusTraceMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/airbytestreamstatustracemessages/<eid>", methods=["POST", "PATCH"])
def update_airbyte_stream_status_trace_message(request, eid):
    """Update a AirbyteStreamStatusTraceMessage."""
    rows = _query("AirbyteStreamStatusTraceMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['status'])
    if err:
        return err, 400
    if data.get('status') and data['status'] not in ['STARTED', 'RUNNING', 'COMPLETE', 'INCOMPLETE']:
        return {"error": {"message": "invalid status; allowed: " + ", ".join(['STARTED', 'RUNNING', 'COMPLETE', 'INCOMPLETE']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("AirbyteStreamStatusTraceMessage", rec)
    return rec, 200

@app.route("/v1/airbytestreamstatustracemessages/<eid>", methods=["DELETE"])
def delete_airbyte_stream_status_trace_message(request, eid):
    """Delete a AirbyteStreamStatusTraceMessage."""
    rows = _query("AirbyteStreamStatusTraceMessage", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"airbyte.AirbyteStreamStatusTraceMessage", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/configuredairbytestreams", methods=["POST"])
def create_configured_airbyte_stream(request):
    """Create a ConfiguredAirbyteStream."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['syncMode', 'destinationSyncMode', 'cursorField', 'primaryKey'])
    if err:
        return err, 400
    err = _require(data, ['syncMode', 'destinationSyncMode'])
    if err:
        return err, 400
    if data.get('syncMode') and data['syncMode'] not in ['full_refresh', 'incremental']:
        return {"error": {"message": "invalid syncMode; allowed: " + ", ".join(['full_refresh', 'incremental']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("airbyte_con")}
    rec["syncMode"] = data.get('syncMode')
    rec["destinationSyncMode"] = data.get('destinationSyncMode')
    rec["cursorField"] = data.get('cursorField')
    rec["primaryKey"] = data.get('primaryKey')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("ConfiguredAirbyteStream", rec)
    return rec, 201

@app.route("/v1/configuredairbytestreams", methods=["GET"])
def list_configured_airbyte_streams(request):
    """List ConfiguredAirbyteStreams with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("ConfiguredAirbyteStream")
    rows = _apply_filters(rows, params, ['syncMode', 'destinationSyncMode', 'cursorField', 'primaryKey'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/configuredairbytestreams/<eid>", methods=["GET"])
def get_configured_airbyte_stream(request, eid):
    """Retrieve a ConfiguredAirbyteStream by id (supports ?expand=)."""
    rows = _query("ConfiguredAirbyteStream", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/configuredairbytestreams/<eid>", methods=["POST", "PATCH"])
def update_configured_airbyte_stream(request, eid):
    """Update a ConfiguredAirbyteStream."""
    rows = _query("ConfiguredAirbyteStream", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['syncMode', 'destinationSyncMode', 'cursorField', 'primaryKey'])
    if err:
        return err, 400
    if data.get('syncMode') and data['syncMode'] not in ['full_refresh', 'incremental']:
        return {"error": {"message": "invalid syncMode; allowed: " + ", ".join(['full_refresh', 'incremental']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("ConfiguredAirbyteStream", rec)
    return rec, 200

@app.route("/v1/configuredairbytestreams/<eid>", methods=["DELETE"])
def delete_configured_airbyte_stream(request, eid):
    """Delete a ConfiguredAirbyteStream."""
    rows = _query("ConfiguredAirbyteStream", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"airbyte.ConfiguredAirbyteStream", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "airbyte-compat", "tier": "L4",
            "entities": ['AirbyteMessage', 'AirbyteRecordMessage', 'AirbyteLogMessage', 'AirbyteConnectionStatus', 'AirbyteStateMessage', 'AirbyteStreamStatusTraceMessage', 'ConfiguredAirbyteStream']}, 200


if __name__ == "__main__":
    app.start()
