CREATE TABLE IF NOT EXISTS vertex_occupation_bls (
      vertex_id         VARCHAR PRIMARY KEY,
      rkey              VARCHAR,
      repo              VARCHAR,
      label             VARCHAR,
      source            VARCHAR,
      source_license    VARCHAR,
      source_homepage   VARCHAR,
      soc_code          VARCHAR,
      isco_code         VARCHAR,
      occ_title         VARCHAR,
      occ_group         VARCHAR,
      reference_year    VARCHAR,
      tot_emp           DOUBLE PRECISION,
      emp_prse          DOUBLE PRECISION,
      h_mean            DOUBLE PRECISION,
      a_mean            DOUBLE PRECISION,
      h_pct10           DOUBLE PRECISION,
      h_pct25           DOUBLE PRECISION,
      h_pct50           DOUBLE PRECISION,
      h_pct75           DOUBLE PRECISION,
      h_pct90           DOUBLE PRECISION,
      a_pct10           DOUBLE PRECISION,
      a_pct25           DOUBLE PRECISION,
      a_pct50           DOUBLE PRECISION,
      a_pct75           DOUBLE PRECISION,
      a_pct90           DOUBLE PRECISION,
      ingested_at       VARCHAR
    );
