CREATE TABLE IF NOT EXISTS vertex_flight_offer_watch (
      vertex_id          VARCHAR PRIMARY KEY,
      origin_iata        VARCHAR,
      destination_iata   VARCHAR,
      outbound_date      VARCHAR,
      return_date        VARCHAR,
      currency           VARCHAR,
      threshold_pct      DOUBLE PRECISION,
      cadence_minutes    BIGINT,
      provider_hint      VARCHAR,
      max_offers         BIGINT,
      notify_did         VARCHAR,
      status             VARCHAR,
      last_polled_at     VARCHAR,
      next_due_at        VARCHAR,
      created_at         VARCHAR,
      sensitivity_ord    BIGINT,
      org_id             VARCHAR,
      user_id            VARCHAR,
      actor_id           VARCHAR
    );
