"""
Py Kotodama WASM entrypoint for the Gs1_epcis clean-room actor.

Clean-room, API-shaped CRUD over a Datomic-backed Kotoba schema.
Generated by 70-tools/deepen_actors.py (ADR 260607 deepening phase).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/gs1_epcis.kotoba")
db = DatomicClient.connect()
app = Runtime("gs1_epcis-compat")


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"gs1_epcis.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    """Read records of an entity from Datomic (optionally by id)."""
    pattern = {"entity": f"gs1_epcis.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing)}}
    return None


@app.route("/v1/tradeitems", methods=["POST"])
def create_trade_item(request):
    """Create a TradeItem."""
    data = request.json or request.form or {}
    err = _require(data, ['gtin', 'description'])
    if err:
        return err, 400
    rec = {"id": new_id("gs1epcis_tra")}
    rec["gtin"] = data.get('gtin')
    rec["description"] = data.get('description')
    rec["brand"] = data.get('brand')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("TradeItem", rec)
    return rec, 201

@app.route("/v1/tradeitems", methods=["GET"])
def list_trade_items(request):
    """List TradeItems."""
    items = _query("TradeItem")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/tradeitems/<eid>", methods=["GET"])
def get_trade_item(request, eid):
    """Retrieve a TradeItem by id."""
    rows = _query("TradeItem", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/tradeitems/<eid>", methods=["POST", "PATCH"])
def update_trade_item(request, eid):
    """Update a TradeItem."""
    rows = _query("TradeItem", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("TradeItem", rec)
    return rec, 200

@app.route("/v1/tradeitems/<eid>", methods=["DELETE"])
def delete_trade_item(request, eid):
    """Delete a TradeItem."""
    rows = _query("TradeItem", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"gs1_epcis.TradeItem", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/events", methods=["POST"])
def create_event(request):
    """Create a Event."""
    data = request.json or request.form or {}
    err = _require(data, ['bizStep', 'disposition'])
    if err:
        return err, 400
    rec = {"id": new_id("gs1epcis_eve")}
    rec["itemId"] = data.get('itemId')
    rec["bizStep"] = data.get('bizStep')
    rec["disposition"] = data.get('disposition')
    rec["recordedAt"] = data.get('recordedAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Event", rec)
    return rec, 201

@app.route("/v1/events", methods=["GET"])
def list_events(request):
    """List Events."""
    items = _query("Event")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/events/<eid>", methods=["GET"])
def get_event(request, eid):
    """Retrieve a Event by id."""
    rows = _query("Event", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/events/<eid>", methods=["POST", "PATCH"])
def update_event(request, eid):
    """Update a Event."""
    rows = _query("Event", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Event", rec)
    return rec, 200

@app.route("/v1/events/<eid>", methods=["DELETE"])
def delete_event(request, eid):
    """Delete a Event."""
    rows = _query("Event", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"gs1_epcis.Event", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/documents", methods=["POST"])
def create_document(request):
    """Create a Document."""
    data = request.json or request.form or {}
    err = _require(data, ['type', 'status'])
    if err:
        return err, 400
    rec = {"id": new_id("gs1epcis_doc")}
    rec["type"] = data.get('type')
    rec["senderId"] = data.get('senderId')
    rec["receiverId"] = data.get('receiverId')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Document", rec)
    return rec, 201

@app.route("/v1/documents", methods=["GET"])
def list_documents(request):
    """List Documents."""
    items = _query("Document")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/documents/<eid>", methods=["GET"])
def get_document(request, eid):
    """Retrieve a Document by id."""
    rows = _query("Document", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/documents/<eid>", methods=["POST", "PATCH"])
def update_document(request, eid):
    """Update a Document."""
    rows = _query("Document", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Document", rec)
    return rec, 200

@app.route("/v1/documents/<eid>", methods=["DELETE"])
def delete_document(request, eid):
    """Delete a Document."""
    rows = _query("Document", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"gs1_epcis.Document", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/containers", methods=["POST"])
def create_container(request):
    """Create a Container."""
    data = request.json or request.form or {}
    err = _require(data, ['bicCode', 'type'])
    if err:
        return err, 400
    rec = {"id": new_id("gs1epcis_con")}
    rec["bicCode"] = data.get('bicCode')
    rec["type"] = data.get('type')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Container", rec)
    return rec, 201

@app.route("/v1/containers", methods=["GET"])
def list_containers(request):
    """List Containers."""
    items = _query("Container")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/containers/<eid>", methods=["GET"])
def get_container(request, eid):
    """Retrieve a Container by id."""
    rows = _query("Container", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/containers/<eid>", methods=["POST", "PATCH"])
def update_container(request, eid):
    """Update a Container."""
    rows = _query("Container", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Container", rec)
    return rec, 200

@app.route("/v1/containers/<eid>", methods=["DELETE"])
def delete_container(request, eid):
    """Delete a Container."""
    rows = _query("Container", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"gs1_epcis.Container", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/parties", methods=["POST"])
def create_party(request):
    """Create a Party."""
    data = request.json or request.form or {}
    err = _require(data, ['gln', 'name'])
    if err:
        return err, 400
    rec = {"id": new_id("gs1epcis_par")}
    rec["gln"] = data.get('gln')
    rec["name"] = data.get('name')
    rec["role"] = data.get('role')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Party", rec)
    return rec, 201

@app.route("/v1/parties", methods=["GET"])
def list_parties(request):
    """List Parties."""
    items = _query("Party")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/parties/<eid>", methods=["GET"])
def get_party(request, eid):
    """Retrieve a Party by id."""
    rows = _query("Party", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/parties/<eid>", methods=["POST", "PATCH"])
def update_party(request, eid):
    """Update a Party."""
    rows = _query("Party", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Party", rec)
    return rec, 200

@app.route("/v1/parties/<eid>", methods=["DELETE"])
def delete_party(request, eid):
    """Delete a Party."""
    rows = _query("Party", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"gs1_epcis.Party", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/shipments", methods=["POST"])
def create_shipment(request):
    """Create a Shipment."""
    data = request.json or request.form or {}
    err = _require(data, ['origin', 'destination'])
    if err:
        return err, 400
    rec = {"id": new_id("gs1epcis_shi")}
    rec["documentId"] = data.get('documentId')
    rec["origin"] = data.get('origin')
    rec["destination"] = data.get('destination')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Shipment", rec)
    return rec, 201

@app.route("/v1/shipments", methods=["GET"])
def list_shipments(request):
    """List Shipments."""
    items = _query("Shipment")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/shipments/<eid>", methods=["GET"])
def get_shipment(request, eid):
    """Retrieve a Shipment by id."""
    rows = _query("Shipment", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/shipments/<eid>", methods=["POST", "PATCH"])
def update_shipment(request, eid):
    """Update a Shipment."""
    rows = _query("Shipment", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Shipment", rec)
    return rec, 200

@app.route("/v1/shipments/<eid>", methods=["DELETE"])
def delete_shipment(request, eid):
    """Delete a Shipment."""
    rows = _query("Shipment", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"gs1_epcis.Shipment", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "gs1_epcis-compat", "entities": ['TradeItem', 'Event', 'Document', 'Container', 'Party', 'Shipment']}, 200


if __name__ == "__main__":
    app.start()
