apiVersion: v1
kind: Secret
metadata:
  name: medical-coverage-ingester-secrets
  namespace: risingwave
type: Opaque
stringData:
  RW_DSN: host=risingwave.risingwave.svc.cluster.local port=4566 dbname=dev user=root
  NCBI_API_KEY: ""
  FACILITY_CSV_URL: ""
  FACILITY_SOURCE_LABEL: ""
