// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 etzhayyim Japan株式会社 / etzhayyim. All rights reserved.
// Licensed under the Apache License, Version 2.0 — see LICENSE at repo root.

// Defence cluster handlers — generated by gen-defence-cfworker.mjs.
// Source: 70-tools/scripts/contract/defence-catalog.tsv
// Catalog wave 1-5 (105 NSIDs). This file holds the 1 handler owned by open-banking.
//
// Wire into app.ts with:
//   import { defenceRoutes } from "./defence-handlers";
//   const handler = defenceRoutes[nsid]; if (handler) return handler(env, body);
//
// All handlers write a single row to vertex_open_defence_event via Hyperdrive,
// then return { ok: true, vertexId, severity } as JSON. PDS routing should
// prefer this Worker over the legacy BPMN binding (see migration doc).
import { createKyselyDb } from "@etzhayyim/kotodama-host-sdk";

export interface DefenceEnv {
  HYPERDRIVE: { connectionString: string };
  PRIMARY_DID?: string;
  APP_HANDLE?: string;
}

function nanoid(len = 12): string {
  const a = "abcdefghijklmnopqrstuvwxyz0123456789";
  const b = crypto.getRandomValues(new Uint8Array(len));
  let o = ""; for (let i = 0; i < len; i++) o += a[b[i] % a.length]; return o;
}

async function insertDefenceEvent(env: DefenceEnv, params: {
  vertexId: string; project: string; nsid: string; bpmnProcessId: string;
  subjectVid: string | null; actionClass: string; severity: string; callerDid: string;
}) {
  const now = new Date().toISOString();
  const db = createKyselyDb(env.HYPERDRIVE) as any;
  await db
    .insertInto("vertex_open_defence_event")
    .values({
      vertex_id: params.vertexId,
      owner_did: params.callerDid,
      bpmn_process_id: params.bpmnProcessId,
      nsid: params.nsid,
      project: params.project,
      subject_vid: params.subjectVid,
      action_class: params.actionClass,
      severity: params.severity,
      detected_at: now,
      created_at: now,
      sensitivity_ord: 1,
      org_id: params.callerDid,
      user_id: params.callerDid,
      actor_id: `open-defence.${params.project}`,
    })
    .onConflict((oc: any) => oc.doNothing())
    .execute();
}

// com.etzhayyim.apps.openBanking.flagSuspiciousTransaction — 疑わしい取引 STR
export async function handle_flagSuspiciousTransaction(env: DefenceEnv, body: any): Promise<Response> {
  const callerDid = body?.callerDid ?? env.PRIMARY_DID ?? "did:web:anon";
  const subjectVid = body?.accountVid ?? null;
  const vertexId = body?.vertexId ?? `at://${callerDid}/com.etzhayyim.apps.openBanking.flagSuspiciousTransaction/${nanoid(12)}`;
  try {
    await insertDefenceEvent(env, {
      vertexId,
      project: "open-banking",
      nsid: "com.etzhayyim.apps.openBanking.flagSuspiciousTransaction",
      bpmnProcessId: "open_banking_flag_suspicious_transaction",
      subjectVid,
      actionClass: "openBanking.transaction.flagSuspicious",
      severity: "high",
      callerDid,
    });
    return new Response(JSON.stringify({ ok: true, vertexId, severity: "high" }), {
      status: 200, headers: { "content-type": "application/json" },
    });
  } catch (e: any) {
    return new Response(JSON.stringify({ ok: false, error: String(e?.message ?? e) }), {
      status: 500, headers: { "content-type": "application/json" },
    });
  }
}

export const defenceRoutes: Record<string, (env: DefenceEnv, body: any) => Promise<Response>> = {
  "com.etzhayyim.apps.openBanking.flagSuspiciousTransaction": handle_flagSuspiciousTransaction,
};
