"""
Py Kotodama WASM entrypoint for the Everlaw clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/everlaw.kotoba")
db = DatomicClient.connect()
app = Runtime("everlaw-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"everlaw.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"everlaw.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/datasubjects", methods=["POST"])
def create_data_subject(request):
    """Create a DataSubject."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['email', 'jurisdiction', 'status'])
    if err:
        return err, 400
    err = _require(data, ['email', 'jurisdiction'])
    if err:
        return err, 400
    rec = {"id": new_id("everlaw_dat")}
    rec["email"] = data.get('email')
    rec["jurisdiction"] = data.get('jurisdiction')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("DataSubject", rec)
    return rec, 201

@app.route("/v1/datasubjects", methods=["GET"])
def list_data_subjects(request):
    """List DataSubjects with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("DataSubject")
    rows = _apply_filters(rows, params, ['email', 'jurisdiction', 'status'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/datasubjects/<eid>", methods=["GET"])
def get_data_subject(request, eid):
    """Retrieve a DataSubject by id (supports ?expand=)."""
    rows = _query("DataSubject", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/datasubjects/<eid>", methods=["POST", "PATCH"])
def update_data_subject(request, eid):
    """Update a DataSubject."""
    rows = _query("DataSubject", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['email', 'jurisdiction', 'status'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("DataSubject", rec)
    return rec, 200

@app.route("/v1/datasubjects/<eid>", methods=["DELETE"])
def delete_data_subject(request, eid):
    """Delete a DataSubject."""
    rows = _query("DataSubject", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"everlaw.DataSubject", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/consentrecords", methods=["POST"])
def create_consent_record(request):
    """Create a ConsentRecord."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['subjectId', 'purpose', 'granted', 'recordedAt'])
    if err:
        return err, 400
    err = _require(data, ['purpose', 'granted'])
    if err:
        return err, 400
    rec = {"id": new_id("everlaw_con")}
    rec["subjectId"] = data.get('subjectId')
    rec["purpose"] = data.get('purpose')
    rec["granted"] = _as_bool(data.get('granted'))
    rec["recordedAt"] = data.get('recordedAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("ConsentRecord", rec)
    return rec, 201

@app.route("/v1/consentrecords", methods=["GET"])
def list_consent_records(request):
    """List ConsentRecords with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("ConsentRecord")
    rows = _apply_filters(rows, params, ['subjectId', 'purpose', 'granted', 'recordedAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/consentrecords/<eid>", methods=["GET"])
def get_consent_record(request, eid):
    """Retrieve a ConsentRecord by id (supports ?expand=)."""
    rows = _query("ConsentRecord", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/consentrecords/<eid>", methods=["POST", "PATCH"])
def update_consent_record(request, eid):
    """Update a ConsentRecord."""
    rows = _query("ConsentRecord", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['subjectId', 'purpose', 'granted', 'recordedAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("ConsentRecord", rec)
    return rec, 200

@app.route("/v1/consentrecords/<eid>", methods=["DELETE"])
def delete_consent_record(request, eid):
    """Delete a ConsentRecord."""
    rows = _query("ConsentRecord", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"everlaw.ConsentRecord", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/requests", methods=["POST"])
def create_request(request):
    """Create a Request."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['subjectId', 'type', 'status', 'dueAt'])
    if err:
        return err, 400
    err = _require(data, ['type', 'status'])
    if err:
        return err, 400
    rec = {"id": new_id("everlaw_req")}
    rec["subjectId"] = data.get('subjectId')
    rec["type"] = data.get('type')
    rec["status"] = data.get('status')
    rec["dueAt"] = data.get('dueAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Request", rec)
    return rec, 201

@app.route("/v1/requests", methods=["GET"])
def list_requests(request):
    """List Requests with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Request")
    rows = _apply_filters(rows, params, ['subjectId', 'type', 'status', 'dueAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/requests/<eid>", methods=["GET"])
def get_request(request, eid):
    """Retrieve a Request by id (supports ?expand=)."""
    rows = _query("Request", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/requests/<eid>", methods=["POST", "PATCH"])
def update_request(request, eid):
    """Update a Request."""
    rows = _query("Request", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['subjectId', 'type', 'status', 'dueAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Request", rec)
    return rec, 200

@app.route("/v1/requests/<eid>", methods=["DELETE"])
def delete_request(request, eid):
    """Delete a Request."""
    rows = _query("Request", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"everlaw.Request", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/controls", methods=["POST"])
def create_control(request):
    """Create a Control."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['framework', 'name', 'status'])
    if err:
        return err, 400
    err = _require(data, ['framework', 'name'])
    if err:
        return err, 400
    rec = {"id": new_id("everlaw_con")}
    rec["framework"] = data.get('framework')
    rec["name"] = data.get('name')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Control", rec)
    return rec, 201

@app.route("/v1/controls", methods=["GET"])
def list_controls(request):
    """List Controls with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Control")
    rows = _apply_filters(rows, params, ['framework', 'name', 'status'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/controls/<eid>", methods=["GET"])
def get_control(request, eid):
    """Retrieve a Control by id (supports ?expand=)."""
    rows = _query("Control", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/controls/<eid>", methods=["POST", "PATCH"])
def update_control(request, eid):
    """Update a Control."""
    rows = _query("Control", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['framework', 'name', 'status'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Control", rec)
    return rec, 200

@app.route("/v1/controls/<eid>", methods=["DELETE"])
def delete_control(request, eid):
    """Delete a Control."""
    rows = _query("Control", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"everlaw.Control", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/evidences", methods=["POST"])
def create_evidence(request):
    """Create a Evidence."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['controlId', 'name', 'contentRef'])
    if err:
        return err, 400
    err = _require(data, ['name'])
    if err:
        return err, 400
    rec = {"id": new_id("everlaw_evi")}
    rec["controlId"] = data.get('controlId')
    rec["name"] = data.get('name')
    rec["contentRef"] = data.get('contentRef')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Evidence", rec)
    return rec, 201

@app.route("/v1/evidences", methods=["GET"])
def list_evidences(request):
    """List Evidences with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Evidence")
    rows = _apply_filters(rows, params, ['controlId', 'name', 'contentRef'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/evidences/<eid>", methods=["GET"])
def get_evidence(request, eid):
    """Retrieve a Evidence by id (supports ?expand=)."""
    rows = _query("Evidence", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'controlId': 'Control'})
    return rec, 200

@app.route("/v1/evidences/<eid>", methods=["POST", "PATCH"])
def update_evidence(request, eid):
    """Update a Evidence."""
    rows = _query("Evidence", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['controlId', 'name', 'contentRef'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Evidence", rec)
    return rec, 200

@app.route("/v1/evidences/<eid>", methods=["DELETE"])
def delete_evidence(request, eid):
    """Delete a Evidence."""
    rows = _query("Evidence", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"everlaw.Evidence", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/assessments", methods=["POST"])
def create_assessment(request):
    """Create a Assessment."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'riskLevel', 'completedAt'])
    if err:
        return err, 400
    err = _require(data, ['name', 'riskLevel'])
    if err:
        return err, 400
    rec = {"id": new_id("everlaw_ass")}
    rec["name"] = data.get('name')
    rec["riskLevel"] = data.get('riskLevel')
    rec["completedAt"] = data.get('completedAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Assessment", rec)
    return rec, 201

@app.route("/v1/assessments", methods=["GET"])
def list_assessments(request):
    """List Assessments with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Assessment")
    rows = _apply_filters(rows, params, ['name', 'riskLevel', 'completedAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/assessments/<eid>", methods=["GET"])
def get_assessment(request, eid):
    """Retrieve a Assessment by id (supports ?expand=)."""
    rows = _query("Assessment", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/assessments/<eid>", methods=["POST", "PATCH"])
def update_assessment(request, eid):
    """Update a Assessment."""
    rows = _query("Assessment", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'riskLevel', 'completedAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Assessment", rec)
    return rec, 200

@app.route("/v1/assessments/<eid>", methods=["DELETE"])
def delete_assessment(request, eid):
    """Delete a Assessment."""
    rows = _query("Assessment", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"everlaw.Assessment", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "everlaw-compat", "tier": "L4",
            "entities": ['DataSubject', 'ConsentRecord', 'Request', 'Control', 'Evidence', 'Assessment']}, 200


if __name__ == "__main__":
    app.start()
