"""
Py Kotodama WASM entrypoint for the Segment clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/segment.kotoba")
db = DatomicClient.connect()
app = Runtime("segment-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"segment.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"segment.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/trackevents", methods=["POST"])
def create_track_event(request):
    """Create a TrackEvent."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type', 'event', 'userId', 'anonymousId', 'messageId', 'timestamp'])
    if err:
        return err, 400
    err = _require(data, ['type', 'event'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['track', 'identify', 'page', 'screen', 'group', 'alias']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['track', 'identify', 'page', 'screen', 'group', 'alias']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("segment_tra")}
    rec["type"] = data.get('type')
    rec["event"] = data.get('event')
    rec["userId"] = data.get('userId')
    rec["anonymousId"] = data.get('anonymousId')
    rec["messageId"] = data.get('messageId')
    rec["timestamp"] = data.get('timestamp')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("TrackEvent", rec)
    return rec, 201

@app.route("/v1/trackevents", methods=["GET"])
def list_track_events(request):
    """List TrackEvents with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("TrackEvent")
    rows = _apply_filters(rows, params, ['type', 'event', 'userId', 'anonymousId', 'messageId', 'timestamp'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/trackevents/<eid>", methods=["GET"])
def get_track_event(request, eid):
    """Retrieve a TrackEvent by id (supports ?expand=)."""
    rows = _query("TrackEvent", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/trackevents/<eid>", methods=["POST", "PATCH"])
def update_track_event(request, eid):
    """Update a TrackEvent."""
    rows = _query("TrackEvent", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type', 'event', 'userId', 'anonymousId', 'messageId', 'timestamp'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['track', 'identify', 'page', 'screen', 'group', 'alias']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['track', 'identify', 'page', 'screen', 'group', 'alias']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("TrackEvent", rec)
    return rec, 200

@app.route("/v1/trackevents/<eid>", methods=["DELETE"])
def delete_track_event(request, eid):
    """Delete a TrackEvent."""
    rows = _query("TrackEvent", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"segment.TrackEvent", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/identifyevents", methods=["POST"])
def create_identify_event(request):
    """Create a IdentifyEvent."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type', 'userId', 'anonymousId', 'messageId', 'timestamp'])
    if err:
        return err, 400
    err = _require(data, ['type', 'timestamp'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['track', 'identify', 'page', 'screen', 'group', 'alias']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['track', 'identify', 'page', 'screen', 'group', 'alias']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("segment_ide")}
    rec["type"] = data.get('type')
    rec["userId"] = data.get('userId')
    rec["anonymousId"] = data.get('anonymousId')
    rec["messageId"] = data.get('messageId')
    rec["timestamp"] = data.get('timestamp')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("IdentifyEvent", rec)
    return rec, 201

@app.route("/v1/identifyevents", methods=["GET"])
def list_identify_events(request):
    """List IdentifyEvents with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("IdentifyEvent")
    rows = _apply_filters(rows, params, ['type', 'userId', 'anonymousId', 'messageId', 'timestamp'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/identifyevents/<eid>", methods=["GET"])
def get_identify_event(request, eid):
    """Retrieve a IdentifyEvent by id (supports ?expand=)."""
    rows = _query("IdentifyEvent", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/identifyevents/<eid>", methods=["POST", "PATCH"])
def update_identify_event(request, eid):
    """Update a IdentifyEvent."""
    rows = _query("IdentifyEvent", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type', 'userId', 'anonymousId', 'messageId', 'timestamp'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['track', 'identify', 'page', 'screen', 'group', 'alias']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['track', 'identify', 'page', 'screen', 'group', 'alias']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("IdentifyEvent", rec)
    return rec, 200

@app.route("/v1/identifyevents/<eid>", methods=["DELETE"])
def delete_identify_event(request, eid):
    """Delete a IdentifyEvent."""
    rows = _query("IdentifyEvent", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"segment.IdentifyEvent", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/pageevents", methods=["POST"])
def create_page_event(request):
    """Create a PageEvent."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type', 'userId', 'anonymousId', 'category', 'name', 'messageId', 'timestamp'])
    if err:
        return err, 400
    err = _require(data, ['type', 'category'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['track', 'identify', 'page', 'screen', 'group', 'alias']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['track', 'identify', 'page', 'screen', 'group', 'alias']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("segment_pag")}
    rec["type"] = data.get('type')
    rec["userId"] = data.get('userId')
    rec["anonymousId"] = data.get('anonymousId')
    rec["category"] = data.get('category')
    rec["name"] = data.get('name')
    rec["messageId"] = data.get('messageId')
    rec["timestamp"] = data.get('timestamp')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("PageEvent", rec)
    return rec, 201

@app.route("/v1/pageevents", methods=["GET"])
def list_page_events(request):
    """List PageEvents with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("PageEvent")
    rows = _apply_filters(rows, params, ['type', 'userId', 'anonymousId', 'category', 'name', 'messageId', 'timestamp'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/pageevents/<eid>", methods=["GET"])
def get_page_event(request, eid):
    """Retrieve a PageEvent by id (supports ?expand=)."""
    rows = _query("PageEvent", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/pageevents/<eid>", methods=["POST", "PATCH"])
def update_page_event(request, eid):
    """Update a PageEvent."""
    rows = _query("PageEvent", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type', 'userId', 'anonymousId', 'category', 'name', 'messageId', 'timestamp'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['track', 'identify', 'page', 'screen', 'group', 'alias']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['track', 'identify', 'page', 'screen', 'group', 'alias']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("PageEvent", rec)
    return rec, 200

@app.route("/v1/pageevents/<eid>", methods=["DELETE"])
def delete_page_event(request, eid):
    """Delete a PageEvent."""
    rows = _query("PageEvent", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"segment.PageEvent", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/groupevents", methods=["POST"])
def create_group_event(request):
    """Create a GroupEvent."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type', 'userId', 'anonymousId', 'groupId', 'messageId', 'timestamp'])
    if err:
        return err, 400
    err = _require(data, ['type', 'timestamp'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['track', 'identify', 'page', 'screen', 'group', 'alias']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['track', 'identify', 'page', 'screen', 'group', 'alias']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("segment_gro")}
    rec["type"] = data.get('type')
    rec["userId"] = data.get('userId')
    rec["anonymousId"] = data.get('anonymousId')
    rec["groupId"] = data.get('groupId')
    rec["messageId"] = data.get('messageId')
    rec["timestamp"] = data.get('timestamp')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("GroupEvent", rec)
    return rec, 201

@app.route("/v1/groupevents", methods=["GET"])
def list_group_events(request):
    """List GroupEvents with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("GroupEvent")
    rows = _apply_filters(rows, params, ['type', 'userId', 'anonymousId', 'groupId', 'messageId', 'timestamp'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/groupevents/<eid>", methods=["GET"])
def get_group_event(request, eid):
    """Retrieve a GroupEvent by id (supports ?expand=)."""
    rows = _query("GroupEvent", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/groupevents/<eid>", methods=["POST", "PATCH"])
def update_group_event(request, eid):
    """Update a GroupEvent."""
    rows = _query("GroupEvent", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type', 'userId', 'anonymousId', 'groupId', 'messageId', 'timestamp'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['track', 'identify', 'page', 'screen', 'group', 'alias']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['track', 'identify', 'page', 'screen', 'group', 'alias']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("GroupEvent", rec)
    return rec, 200

@app.route("/v1/groupevents/<eid>", methods=["DELETE"])
def delete_group_event(request, eid):
    """Delete a GroupEvent."""
    rows = _query("GroupEvent", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"segment.GroupEvent", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/sources", methods=["POST"])
def create_source(request):
    """Create a Source."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'slug', 'enabled', 'workspaceId'])
    if err:
        return err, 400
    err = _require(data, ['name', 'slug'])
    if err:
        return err, 400
    rec = {"id": new_id("segment_sou")}
    rec["name"] = data.get('name')
    rec["slug"] = data.get('slug')
    rec["enabled"] = _as_bool(data.get('enabled'))
    rec["workspaceId"] = data.get('workspaceId')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Source", rec)
    return rec, 201

@app.route("/v1/sources", methods=["GET"])
def list_sources(request):
    """List Sources with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Source")
    rows = _apply_filters(rows, params, ['name', 'slug', 'enabled', 'workspaceId'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/sources/<eid>", methods=["GET"])
def get_source(request, eid):
    """Retrieve a Source by id (supports ?expand=)."""
    rows = _query("Source", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/sources/<eid>", methods=["POST", "PATCH"])
def update_source(request, eid):
    """Update a Source."""
    rows = _query("Source", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'slug', 'enabled', 'workspaceId'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Source", rec)
    return rec, 200

@app.route("/v1/sources/<eid>", methods=["DELETE"])
def delete_source(request, eid):
    """Delete a Source."""
    rows = _query("Source", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"segment.Source", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/destinations", methods=["POST"])
def create_destination(request):
    """Create a Destination."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'enabled', 'sourceId', 'workspaceId'])
    if err:
        return err, 400
    err = _require(data, ['name', 'enabled'])
    if err:
        return err, 400
    rec = {"id": new_id("segment_des")}
    rec["name"] = data.get('name')
    rec["enabled"] = _as_bool(data.get('enabled'))
    rec["sourceId"] = data.get('sourceId')
    rec["workspaceId"] = data.get('workspaceId')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Destination", rec)
    return rec, 201

@app.route("/v1/destinations", methods=["GET"])
def list_destinations(request):
    """List Destinations with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Destination")
    rows = _apply_filters(rows, params, ['name', 'enabled', 'sourceId', 'workspaceId'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/destinations/<eid>", methods=["GET"])
def get_destination(request, eid):
    """Retrieve a Destination by id (supports ?expand=)."""
    rows = _query("Destination", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'sourceId': 'Source'})
    return rec, 200

@app.route("/v1/destinations/<eid>", methods=["POST", "PATCH"])
def update_destination(request, eid):
    """Update a Destination."""
    rows = _query("Destination", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'enabled', 'sourceId', 'workspaceId'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Destination", rec)
    return rec, 200

@app.route("/v1/destinations/<eid>", methods=["DELETE"])
def delete_destination(request, eid):
    """Delete a Destination."""
    rows = _query("Destination", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"segment.Destination", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "segment-compat", "tier": "L4",
            "entities": ['TrackEvent', 'IdentifyEvent', 'PageEvent', 'GroupEvent', 'Source', 'Destination']}, 200


if __name__ == "__main__":
    app.start()
