"""Bulk topology migration for 51 builtin assistants (P3, ADR-2605080600).

Auto-generated by /tmp/extract_topology.py + /tmp/gen_topology_migrations.py.
Each row replaces the prior py_factory row (PK upsert on assistant_id) and
inserts per-node binding rows (kind=py_primitive). Watcher detects the
updated_at diff and re-compiles each assistant on next poll.
"""

from __future__ import annotations

from pathlib import Path

from alembic import op

from graph_schema.db import execute_sql_text


revision = "r_20260509150000_topology_bulk_51"
down_revision = "r_20260509140000_topology_saikin_cycle"
branch_labels = None
depends_on = None

ROOT = Path(__file__).resolve().parents[2]


def _read(name: str) -> str:
    return (ROOT / "sql_migrations" / name).read_text(encoding="utf-8")


def upgrade() -> None:
    execute_sql_text(op.get_bind(), _read("20260509150000_topology_bulk_51.up.sql"))


def downgrade() -> None:
    execute_sql_text(op.get_bind(), _read("20260509150000_topology_bulk_51.down.sql"))
