# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


@dataclass
class Quad:
    graph: str
    subject: str
    predicate: str
    object_cbor: bytes


def assert_quad(q: Quad) -> None:
    """
    Raises: `componentize_py_types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
def retract_quad(q: Quad) -> None:
    """
    Raises: `componentize_py_types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
def query(datalog_src: str) -> List[Quad]:
    """
    Raises: `componentize_py_types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
def get_objects(graph: str, subject: str, predicate: str) -> List[bytes]:
    raise NotImplementedError
def get_head(graph_name: str) -> Optional[str]:
    raise NotImplementedError
def evaluate_rules(rules_cbor: bytes) -> List[Quad]:
    """
    Raises: `componentize_py_types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
