name = "ai-gftd-project-itonami"
compatibility_date = "2024-03-20"
pages_build_output_dir = "build"

[env.production]
name = "ai-gftd-project-itonami"

[[env.production.custom_domains]]
pattern = "itonami.gftd.ai"
custom_certificate_id = "default"

[env.preview]
name = "ai-gftd-project-itonami-staging"

[[env.preview.custom_domains]]
pattern = "staging.itonami.gftd.ai"
custom_certificate_id = "default"
