import { Kysely, sql } from 'kysely';

/**
 * World coverage live read model (migrated 2026-04-14).
 *
 * **SSoT migration** — this replaces `50-infra/linode/risingwave-iceberg/sql/
 * 04-world-coverage-live-mv.sql` which has been archived. All world-coverage
 * DDL now lives in this Kysely migration per graph-schema CLAUDE.md rule
 * "All database schema definitions live in this directory".
 *
 * Drives `etzhayyim coverage world` — replaces the CLI's manual
 * `CountProfilesByRepoGrouped()` aggregation (world_coverage.go:2605) with
 * a single MV read.
 *
 * Schema:
 *   1. dim_world_domain              — 405 world domains (domain, app_host, world_total, unit, sector)
 *   2. dim_app_host_alias            — 183 aliases (nanoid / g0v* → canonical host)
 *   3. mv_world_did_per_host         — DID count per canonical host (vertex_profile, alias-resolved)
 *   4. mv_world_record_per_host      — Record count per canonical host (vertex_repo_record)
 *   5. mv_world_vertex_per_host      — Typed-table vertex count per canonical host
 *   6. mv_world_coverage_live        — Final: GREATEST(did, record, vertex) per domain
 *
 * CHANGE vs. 04-world-coverage-live-mv.sql:
 *   - `collected = GREATEST(did, record, vertex)` instead of `did + record + vertex`.
 *     The old sum triple-counted the same entity (one legal_entity row produces
 *     one vertex row + one repo_record commit + one profile DID), inflating
 *     legal_entity to 3.14M vs. the real 3.04M vertex count and blowing
 *     `sovereign` to 2959 vs. world_total=195.
 */
export async function up(db: Kysely<unknown>): Promise<void> {
  // ── 1. dim_world_domain ──────────────────────────────────────────────
  await sql`CREATE TABLE IF NOT EXISTS dim_world_domain (
    domain      VARCHAR NOT NULL PRIMARY KEY,
    app_host    VARCHAR NOT NULL,
    world_total BIGINT  NOT NULL,
    unit        VARCHAR NOT NULL DEFAULT '',
    sector      VARCHAR NOT NULL DEFAULT ''
  )`.execute(db);

  await sql`DELETE FROM dim_world_domain`.execute(db);

  await sql`INSERT INTO dim_world_domain (domain, app_host, world_total, unit, sector) VALUES
    ('abuse_contact', 'malak', 500000, 'abuse contacts', 'security'),
    ('adult_age_verification', 'shinshi', 100000000, 'age verification records', 'adult'),
    ('adult_content', 'shinshi', 500000000, 'adult content items', 'adult'),
    ('adult_performer', 'shinshi', 5000000, 'adult performers', 'adult'),
    ('adult_platform', 'shinshi', 50000, 'adult platforms', 'adult'),
    ('adult_studio', 'shinshi', 50000, 'adult studios', 'adult'),
    ('aircraft', 'aircraft', 450000, 'registered aircraft', 'transport'),
    ('android_app', 'software', 3500000, 'Android apps', 'software'),
    ('anima', 'anima', 8700000, 'known species', 'science'),
    ('anteisei_shiken', 'seiyaku', 5000000, 'stability studies', 'pharma'),
    ('api_endpoint', 'api', 1000000000, 'public API endpoints', 'software'),
    ('api_schema', 'api', 1000000000, 'API schemas', 'software'),
    ('app_review', 'software', 10000000000, 'app reviews', 'software'),
    ('apparel', 'apparel', 100000000, 'apparel SKUs', 'commerce'),
    ('apparel_rfid', 'serial', 20000000000, 'RFID-tagged apparel/yr', 'serial'),
    ('apt_group', 'malak', 300, 'APT groups', 'security'),
    ('art', 'art', 70000000, 'artworks', 'content'),
    ('asn', 'malak', 100000, 'ASNs', 'security'),
    ('autorace', 'autorace', 5, 'autorace venues', 'gambling'),
    ('baibai_keiyaku', 'keiyaku', 5000000000, 'purchase/sale contracts/yr', 'contract'),
    ('bank', 'bank', 25000, 'banks (global)', 'finance'),
    ('bank_account', 'bank', 10000000000, 'bank accounts', 'finance'),
    ('bankruptcy', 'bankruptcy', 5000000, 'insolvency proceedings/yr', 'law'),
    ('battery_passport', 'serial', 15000000000, 'batteries/yr', 'serial'),
    ('bgp_route', 'malak', 1000000, 'BGP routes', 'security'),
    ('blockchain', 'blockchain', 1000, 'active chains', 'blockchain'),
    ('blockchain_address', 'blockchain', 1300000000, 'blockchain addresses', 'blockchain'),
    ('blockchain_transaction', 'blockchain', 3500000000, 'blockchain transactions', 'blockchain'),
    ('bom', 'seizo', 500000000, 'bill of materials', 'manufacturing'),
    ('botnet_c2', 'malak', 100000, 'botnet C2 servers', 'security'),
    ('boueki_kinyu', 'boueki', 50000000, 'trade finance instruments/yr', 'finance'),
    ('browser_extension', 'software', 500000, 'browser extensions', 'software'),
    ('building_bouka', 'bim', 30000000000, 'fire safety devices', 'building'),
    ('building_densen', 'bim', 225000000000, 'electrical wiring', 'building'),
    ('building_haikan', 'bim', 300000000000, 'plumbing elements', 'building'),
    ('building_kouzoutai', 'bim', 150000000000, 'structural members', 'building'),
    ('building_kuuchou', 'bim', 25000000000, 'HVAC elements', 'building'),
    ('building_setsubi', 'bim', 15000000000, 'building equipment', 'building'),
    ('building_shoumei', 'bim', 150000000000, 'fixtures', 'building'),
    ('building_tsushin', 'bim', 100000000000, 'communication cabling', 'building'),
    ('bulletproof_host', 'malak', 500, 'bulletproof hosts', 'security'),
    ('bus', 'bus', 3000000, 'buses (global)', 'transport'),
    ('bus_stop', 'bus', 5000000, 'bus stops (global)', 'transport'),
    ('car_dealer', 'kuruma', 500000, 'car dealerships', 'transport'),
    ('car_maker', 'kuruma', 5000, 'automotive OEMs', 'transport'),
    ('carbon_credit', 'carbon', 500000000, 'carbon credits', 'energy'),
    ('cas', 'cas', 210000000, 'CAS substances', 'science'),
    ('casino', 'casino', 6500, 'casinos (global)', 'gambling'),
    ('cast_mapping', 'character', 50000000, 'cast mappings', 'fiction'),
    ('celler', 'celler', 8400000000, 'mobile subscriptions', 'telecom'),
    ('chain_of_custody', 'hanrei', 1000000000, 'custody records', 'law'),
    ('character', 'character', 500000000, 'fictional characters', 'fiction'),
    ('character_anime', 'character', 500000, 'anime characters', 'fiction'),
    ('character_book', 'character', 500000000, 'book characters', 'fiction'),
    ('character_game', 'character', 9000000, 'game characters', 'fiction'),
    ('character_manga', 'character', 2000000, 'manga characters', 'fiction'),
    ('character_movie', 'character', 5000000, 'movie characters', 'fiction'),
    ('character_relation', 'character', 1000000000, 'character relationships', 'fiction'),
    ('character_tv', 'character', 3000000, 'TV characters', 'fiction'),
    ('chi_hyoji', 'chizai', 10000, 'geographical indications', 'ip'),
    ('chinshaku_keiyaku', 'keiyaku', 1500000000, 'lease/rental contracts', 'contract'),
    ('chosakuken', 'chizai', 100000000, 'copyrights', 'ip'),
    ('chotatsaku_keiyaku', 'keiyaku', 50000000, 'govt procurement contracts/yr', 'contract'),
    ('chotatsu', 'chotatsu', 200000, 'procurement notices/yr (JP)', 'law'),
    ('chukantai', 'seizo', 5000000000, 'intermediate products/yr', 'manufacturing'),
    ('chuushajou', 'chuushajou', 500000000, 'parking spaces', 'transport'),
    ('cicd_pipeline', 'cicd', 1000000000, 'CI/CD pipelines', 'software'),
    ('cloud_instance', 'cloud', 500000000, 'cloud instances', 'software'),
    ('code_file', 'repo', 100000000000, 'source code files', 'software'),
    ('code_symbol', 'repo', 50000000000, 'function/class definitions', 'software'),
    ('cofog', 'cofog', 6000, 'COFOG functions', 'governance'),
    ('commodities', 'commodities', 5500, 'traded commodities', 'commerce'),
    ('communities', 'communities', 10000, 'intl organizations', 'governance'),
    ('container', 'container', 50000000, 'shipping containers', 'transport'),
    ('container_image', 'container', 500000000, 'container images', 'software'),
    ('cpc', 'cpc', 2738, 'CPC Ver.2.1 products', 'commerce'),
    ('creditcard', 'creditcard', 1200000000, 'credit cards', 'finance'),
    ('crime_org', 'malak', 10000, 'criminal organizations', 'security'),
    ('ct_monitor', 'ct-monitor', 10000000000, 'CT log certificates', 'security'),
    ('customary', 'customary', 1500, 'customary law systems', 'governance'),
    ('cve', 'malak', 250000, 'CVE vulnerabilities', 'security'),
    ('cybercrime_group', 'malak', 5000, 'cybercrime gangs', 'security'),
    ('danyaku', 'serial', 15000000000, 'ammunition rounds/yr', 'serial'),
    ('darkweb_site', 'malak', 100000, 'dark web sites', 'security'),
    ('data_breach', 'malak', 10000, 'data breaches', 'security'),
    ('data_center', 'dc', 10000, 'data centers', 'infra'),
    ('db_schema', 'db', 5000000000, 'database tables', 'software'),
    ('demae', 'demae', 10000000, 'delivery merchants', 'commerce'),
    ('denki', 'denki', 60000, 'power plants', 'energy'),
    ('denshi_buhin', 'denshi-buhin', 1000000000, 'electronic parts', 'manufacturing'),
    ('derivative', 'derivative', 1000000000, 'derivatives contracts', 'finance'),
    ('desktop_software', 'software', 5000000, 'desktop software', 'software'),
    ('dev_account', 'dev', 200000000, 'developer accounts', 'software'),
    ('digital_forensic', 'hanrei', 50000000, 'forensic artifacts', 'law'),
    ('dmf', 'seiyaku', 100000, 'Drug Master Files', 'pharma'),
    ('dns', 'dns', 350000000, 'registered domains', 'infra'),
    ('dns_cert_history', 'dns', 1000000000, 'SSL/TLS certificates', 'infra'),
    ('dns_record', 'malak', 5000000000, 'DNS records', 'security'),
    ('dns_whois_history', 'dns', 350000000, 'domain WHOIS snapshots', 'infra'),
    ('dojo', 'dojo', 10000, 'readiness kata drills', 'welfare'),
    ('douga', 'douga', 1000000000, 'video content', 'content'),
    ('douro_hyouji', 'douro', 1000000000, 'road markings', 'transport'),
    ('douro_hyoushiki', 'douro', 500000000, 'road signs (global)', 'transport'),
    ('drama', 'drama', 100000, 'TV drama titles', 'content'),
    ('drone', 'drone', 2000000, 'registered drones', 'transport'),
    ('e_waste', 'haikibutsu', 50000000000, 'e-waste items/yr', 'waste'),
    ('eigyo_himitsu', 'chizai', 50000000, 'trade secrets', 'ip'),
    ('eigyo_kyoka', 'kyoka', 500000000, 'business licenses', 'governance'),
    ('email', 'gmail', 4500000000, 'email accounts', 'identity'),
    ('energy', 'energy', 5000000, 'energy assets', 'energy'),
    ('energy_consumption', 'energy', 10000000000, 'energy records/yr', 'energy'),
    ('episode', 'episode', 500000000, 'episodes/chapters', 'fiction'),
    ('equipment', 'equipment', 50000000, 'industrial equipment', 'manufacturing'),
    ('escort_listing', 'shinshi', 10000000, 'escort listings', 'adult'),
    ('ethics', 'ethics', 12000, 'professional ethics codes', 'governance'),
    ('eula', 'software', 50000000, 'EULA documents', 'software'),
    ('ev_charger', 'ev', 5000000, 'EV charging stations', 'energy'),
    ('exploit_kit', 'malak', 500, 'exploit kits', 'security'),
    ('exposed_service', 'malak', 500000000, 'exposed services', 'security'),
    ('factory', 'factory', 10000000, 'factories', 'manufacturing'),
    ('farm', 'farm', 570000000, 'farms (global)', 'food'),
    ('festival_global', 'festival', 5000000, 'festivals (global)', 'culture'),
    ('fiction_item', 'character', 50000000, 'fictional items', 'fiction'),
    ('fiction_location', 'character', 50000000, 'fictional places', 'fiction'),
    ('fiction_world', 'character', 10000000, 'fictional universes', 'fiction'),
    ('fleamarket', 'fleamarket', 5000000, 'C2C marketplace listings/day', 'commerce'),
    ('food', 'food', 400000, 'food products', 'food'),
    ('fraud_phone_line', 'malak', 500000, 'fraud phone lines', 'security'),
    ('fudosan_kaisha', 'fudosan', 5000000, 'real estate agencies', 'property'),
    ('fudosan_torihiki', 'fudosan', 100000000, 'property transactions/yr', 'property'),
    ('fuhou_touki', 'haikibutsu', 10000000, 'illegal dumping sites/yr', 'waste'),
    ('gaitou', 'douro', 300000000, 'street lights', 'transport'),
    ('gakko', 'gakko', 1000000, 'schools & universities', 'education'),
    ('gakui', 'gakureki', 500000000, 'academic degrees', 'education'),
    ('gakujutsu_ronbun', 'ronbun', 200000000, 'academic papers', 'education'),
    ('gakusei', 'gakko', 1500000000, 'enrolled students', 'education'),
    ('game_store', 'software', 1000000, 'game titles', 'software'),
    ('gas', 'gas', 25000, 'gas facilities', 'energy'),
    ('gas_station', 'gas-station', 500000, 'gas/fuel stations', 'transport'),
    ('genome', 'genome', 1000000000, 'sequenced genomes', 'science'),
    ('genyaku', 'seiyaku', 10000, 'API manufacturing sources', 'pharma'),
    ('git_commit', 'repo', 10000000000, 'git commits', 'software'),
    ('git_issue', 'repo', 2000000000, 'issues & PRs', 'software'),
    ('git_repo', 'repo', 500000000, 'software repositories', 'software'),
    ('gmp_batch', 'seiyaku', 500000000, 'GMP batch records/yr', 'pharma'),
    ('gomi_route', 'haikibutsu', 5000000, 'waste collection routes', 'waste'),
    ('gomi_shuushuu', 'haikibutsu', 500000000, 'waste collection points', 'waste'),
    ('gov', 'gov', 500000, 'government agencies', 'governance'),
    ('gtin', 'gtin', 1000000000, 'GTIN barcodes', 'commerce'),
    ('guardrail', 'douro', 200000000, 'guardrails & barriers', 'transport'),
    ('haiki_manifest', 'haikibutsu', 5000000000, 'waste manifests/yr', 'waste'),
    ('haisha', 'haikibutsu', 50000000, 'end-of-life vehicles/yr', 'waste'),
    ('hakubutsukan', 'hakubutsukan', 100000, 'museums', 'culture'),
    ('handotai', 'handotai', 100000, 'semiconductor products', 'manufacturing'),
    ('hanrei', 'hanrei', 400000, 'court decisions (JP)', 'law'),
    ('hanrei_global', 'hanrei', 50000000, 'court decisions (global)', 'law'),
    ('hanzai', 'hanzai', 500000000, 'crime reports/yr', 'security'),
    ('hinshitsu_kensa', 'seizo', 100000000000, 'quality inspections/yr', 'manufacturing'),
    ('hinshitsu_shomei', 'seizo', 10000000000, 'certificates of analysis/yr', 'manufacturing'),
    ('hinshu_shushi', 'hinshu', 500000, 'crop varieties', 'food'),
    ('hogoku', 'shizen', 250000, 'protected areas', 'nature'),
    ('hosho_keiyaku', 'keiyaku', 2000000000, 'warranty contracts', 'contract'),
    ('hourei', 'hourei', 10000000, 'statutes & regulations', 'law'),
    ('i18n', 'i18n', 7168, 'living languages', 'culture'),
    ('iap_item', 'software', 500000000, 'IAP items', 'software'),
    ('icd_shikkan', 'iryo', 70000, 'ICD-11 disease codes', 'healthcare'),
    ('imei', 'serial', 20000000000, 'mobile devices (IMEI)', 'serial'),
    ('industry_standard', 'industry-standard', 45000, 'industry standards', 'governance'),
    ('insurance', 'insurance', 12000, 'insurance companies', 'finance'),
    ('insurance_contract', 'insurance', 3000000000, 'insurance policies', 'finance'),
    ('invoice', 'invoice', 500000000000, 'invoices/yr', 'finance'),
    ('ios_app', 'software', 2000000, 'iOS apps', 'software'),
    ('iot', 'iot', 18000000000, 'IoT devices', 'infra'),
    ('ip_scan', 'ipaddress', 4294967296, 'IPv4 scan results', 'infra'),
    ('ipaddress', 'ipaddress', 4294967296, 'IPv4 addresses', 'infra'),
    ('ippan_haikibutsu', 'haikibutsu', 2000000000, 'MSW tons/yr', 'waste'),
    ('ipv6', 'ipaddress', 10000000000, 'IPv6 addresses', 'infra'),
    ('iryo', 'iryo', 5000000000, 'medical records', 'healthcare'),
    ('iryo_seikyu', 'iryo', 10000000000, 'medical claims/yr', 'healthcare'),
    ('iryo_shisetsu', 'iryo', 1000000, 'hospitals & clinics', 'healthcare'),
    ('isbn', 'isbn', 175000000, 'ISBN books', 'content'),
    ('isbn_pd_fulltext', 'isbn', 587000, 'public domain book fulltexts', 'content'),
    ('isco', 'isco', 436, 'ISCO-08 occupations', 'governance'),
    ('isho', 'chizai', 20000000, 'industrial designs', 'ip'),
    ('isic', 'isic', 419, 'ISIC Rev.4 industries', 'governance'),
    ('isin', 'isin', 20000000, 'ISIN securities', 'finance'),
    ('issn', 'issn', 2500000, 'ISSN serials', 'content'),
    ('itaku_keiyaku', 'keiyaku', 1000000000, 'outsourcing contracts', 'contract'),
    ('iyakuhin_serial', 'serial', 30000000000, 'serialized drug packages/yr', 'serial'),
    ('jidosha_buhin', 'jidosha-buhin', 500000000, 'automotive parts', 'manufacturing'),
    ('jiko', 'jiko', 100000000, 'accidents/yr', 'welfare'),
    ('jinushi', 'jinushi', 3500000000, 'land parcels (global)', 'spatial'),
    ('jitsuyo_shinan', 'chizai', 10000000, 'utility models', 'ip'),
    ('joucho', 'joucho', 8100000000, 'persons (joucho scoring)', 'welfare'),
    ('juki_serial', 'serial', 1000000000, 'firearms', 'serial'),
    ('k8s_cluster', 'k8s', 5000000, 'K8s clusters', 'software'),
    ('k8s_pod', 'k8s', 500000000, 'K8s pods', 'software'),
    ('kabushiki_chumon', 'torihiki', 100000000000, 'stock/futures orders/yr', 'finance'),
    ('kachiku', 'kachiku', 30000000000, 'livestock', 'food'),
    ('kagu', 'kagu', 50000000, 'furniture SKUs', 'commerce'),
    ('kaigo', 'kaigo', 250000, 'care facilities (JP)', 'welfare'),
    ('kaigo_global', 'kaigo', 2000000, 'elderly care facilities (global)', 'welfare'),
    ('kaitai_kouji', 'haikibutsu', 5000000, 'demolition projects/yr', 'waste'),
    ('kaku_haikibutsu', 'haikibutsu', 500000, 'nuclear waste containers', 'waste'),
    ('kanagata', 'seizo', 100000000, 'molds/dies/tooling', 'manufacturing'),
    ('kantei', 'hanrei', 10000000, 'expert reports', 'law'),
    ('kasen', 'shizen', 250000, 'rivers & water bodies', 'nature'),
    ('keiba', 'keiba', 25, 'horse racing venues (JP)', 'gambling'),
    ('keiba_global', 'keiba', 500, 'horse racing (global)', 'gambling'),
    ('keirin', 'keirin', 43, 'keirin velodromes', 'gambling'),
    ('kensetsu', 'kensetsu', 10000000, 'construction projects/yr', 'building'),
    ('kenzai', 'kenzai', 5000000, 'construction materials', 'building'),
    ('kessai', 'kessai', 1000000000000, 'payment transactions/yr', 'finance'),
    ('kikai_buhin', 'kikai-buhin', 200000000, 'mechanical parts', 'manufacturing'),
    ('kiken_haikibutsu', 'haikibutsu', 500000000, 'hazardous waste tons/yr', 'waste'),
    ('kisei_todoke', 'kisei', 1000000000, 'regulatory filings/yr', 'law'),
    ('kishou', 'shizen', 100000, 'weather stations', 'nature'),
    ('kokyuhin_serial', 'serial', 500000000, 'luxury goods serial', 'serial'),
    ('konin_keiyaku', 'keiyaku', 2000000000, 'marriage registrations', 'contract'),
    ('kouku_buhin_serial', 'serial', 5000000000, 'aerospace parts', 'serial'),
    ('kousei_kiroku', 'seizo', 5000000000, 'calibration records/yr', 'manufacturing'),
    ('koutei_recipe', 'seizo', 50000000, 'process recipes', 'manufacturing'),
    ('koutei_step', 'seizo', 1000000000000, 'process steps/yr', 'manufacturing'),
    ('koutsuu_ihan', 'koutsuu', 500000000, 'traffic violations/yr', 'transport'),
    ('koyo_keiyaku', 'keiyaku', 3500000000, 'employment contracts', 'contract'),
    ('koza', 'gakko', 50000000, 'courses/curricula', 'education'),
    ('kuruma', 'kuruma', 80000, 'car models', 'transport'),
    ('kyotei', 'kyotei', 24, 'kyotei boat race venues', 'gambling'),
    ('kyouryou', 'douro', 10000000, 'bridges (global)', 'transport'),
    ('leaked_credential', 'malak', 15000000000, 'leaked credentials', 'security'),
    ('lease_doosan', 'keiyaku', 500000000, 'equipment leases', 'contract'),
    ('legal_entity', 'legal-entity', 400000000, 'legal entities', 'identity'),
    ('legal_entity_lei', 'legal-entity', 2700000, 'LEI registrations', 'finance'),
    ('license_keiyaku', 'keiyaku', 500000000, 'license agreements', 'contract'),
    ('life_event', 'life-event', 5000000000, 'life events/yr', 'welfare'),
    ('linux_package', 'software', 200000, 'Linux packages', 'software'),
    ('live_event', 'event', 50000000, 'live events/yr', 'culture'),
    ('loan', 'loan', 500000000, 'active loans', 'finance'),
    ('mac_address', 'mac', 20000000000, 'MAC addresses', 'infra'),
    ('macos_app', 'software', 100000, 'macOS apps', 'software'),
    ('malak', 'malak', 500000, 'cybercrime indicators/yr', 'security'),
    ('malicious_domain', 'malak', 10000000, 'malicious domains', 'security'),
    ('malicious_ip', 'malak', 50000000, 'malicious IPs', 'security'),
    ('malicious_registrar', 'malak', 5000, 'abusive registrars', 'security'),
    ('malware_family', 'malak', 1000000, 'malware families', 'security'),
    ('malware_sample', 'malak', 2000000000, 'malware samples', 'security'),
    ('manga', 'manga', 150000, 'manga titles', 'content'),
    ('maps', 'maps', 200000000, 'addressable locations', 'spatial'),
    ('maps_building', 'maps', 1500000000, 'buildings (global)', 'spatial'),
    ('maps_poi', 'maps', 500000000, 'POIs (global)', 'spatial'),
    ('media_anime', 'media-anime', 25000, 'anime titles', 'content'),
    ('media_gamers', 'media-gamers', 900000, 'game titles', 'content'),
    ('megane', 'serial', 2000000000, 'eyewear/yr', 'serial'),
    ('menkyo', 'menkyo', 1500000000, 'driver licenses', 'identity'),
    ('mine', 'mine', 35000, 'active mines', 'manufacturing'),
    ('minpaku', 'minpaku', 6000000, 'vacation rentals', 'property'),
    ('music', 'music', 200000000, 'music tracks', 'content'),
    ('narou', 'narou', 1000000, 'web novel titles', 'content'),
    ('natural_person', 'natural-person', 8100000000, 'natural persons', 'identity'),
    ('nda', 'keiyaku', 2000000000, 'NDA agreements', 'contract'),
    ('ndc', 'ndc', 350000, 'NDC drug codes', 'pharma'),
    ('nft', 'blockchain', 100000000, 'minted NFTs', 'blockchain'),
    ('nijisousaku', 'nijisousaku', 500000000, 'fan works', 'fiction'),
    ('nimotsu', 'nimotsu', 200000000000, 'parcels/yr', 'commerce'),
    ('nirin', 'nirin', 500000000, 'motorcycles & bicycles', 'transport'),
    ('noukyou', 'nougyou', 5000000, 'agricultural cooperatives', 'food'),
    ('nozei_shinkoku', 'zeimu', 1000000000, 'tax returns/yr', 'governance'),
    ('npo', 'npo', 10000000, 'NPOs & NGOs', 'welfare'),
    ('okaimono', 'okaimono', 30000000, 'e-commerce merchants', 'commerce'),
    ('omatsuri', 'omatsuri', 300000, 'festivals (JP)', 'culture'),
    ('open_proxy', 'malak', 10000000, 'open proxies', 'security'),
    ('oryori', 'oryori', 5000000, 'recipes', 'food'),
    ('oss_license', 'repo', 1000000000, 'OSS license applications', 'software'),
    ('otoshimono', 'otoshimono', 4000000, 'lost items/yr (JP)', 'welfare'),
    ('pachinko', 'pachinko', 7500, 'pachinko stores (JP)', 'gambling'),
    ('package_version', 'sbom', 5000000000, 'package versions', 'software'),
    ('passport', 'passport', 1500000000, 'passports', 'identity'),
    ('paste_leak', 'malak', 50000000, 'paste leaks', 'security'),
    ('patent', 'patent', 200000000, 'patent documents', 'ip'),
    ('pep', 'yabai', 5000000, 'PEPs', 'security'),
    ('pharma', 'pharma', 350000, 'pharmaceutical products', 'pharma'),
    ('phishing_domain', 'malak', 5000000, 'phishing domains', 'security'),
    ('phishing_kit', 'malak', 10000, 'phishing kits', 'security'),
    ('phishing_page', 'malak', 50000000, 'phishing pages/yr', 'security'),
    ('phonenumber', 'phonenumber', 15000000000, 'phone numbers', 'telecom'),
    ('photos', 'photos', 5000000000000, 'photos/yr', 'content'),
    ('port', 'port', 8500, 'major ports (global)', 'transport'),
    ('property', 'property', 3500000000, 'property parcels', 'property'),
    ('public_fund', 'public-fund', 150000, 'public funds', 'governance'),
    ('railway', 'railway', 1370000, 'railway stations (global)', 'transport'),
    ('railway_route', 'railway', 500000, 'railway routes/lines', 'transport'),
    ('railway_vehicle', 'railway', 1000000, 'railway rolling stock', 'transport'),
    ('ransomware_family', 'malak', 5000, 'ransomware families', 'security'),
    ('real_estate', 'real-estate', 350000000, 'real estate listings', 'property'),
    ('receipt', 'receipt', 500000000000, 'receipts/yr', 'finance'),
    ('recycle_flow', 'recycle', 1000000000, 'recycled material tons/yr', 'waste'),
    ('recycle_rate', 'recycle', 200, 'national recycling rates', 'waste'),
    ('recycle_shisetsu', 'recycle', 500000, 'recycling facilities', 'waste'),
    ('religious', 'religious', 4300, 'religious legal systems', 'governance'),
    ('rinshou_shiken', 'iryo', 500000, 'clinical trials', 'healthcare'),
    ('riyo_kiyaku', 'keiyaku', 10000000000, 'ToS/SaaS agreements', 'contract'),
    ('road', 'road', 64000000, 'road km (global)', 'transport'),
    ('robocall_campaign', 'malak', 5000000, 'robocall campaigns', 'security'),
    ('robocall_number', 'malak', 50000000, 'spam phone numbers', 'security'),
    ('robot', 'robot', 4000000, 'industrial robots', 'manufacturing'),
    ('ryoukinjo', 'douro', 500000, 'toll gates', 'transport'),
    ('saas_service', 'software', 30000, 'SaaS services', 'software'),
    ('saiban_shoko', 'hanrei', 500000000, 'court evidence items', 'law'),
    ('saigai', 'saigai', 1000, 'natural disasters/yr', 'welfare'),
    ('sanctions', 'sanctions', 50000, 'sanctioned entities', 'governance'),
    ('sangyo_haikibutsu', 'haikibutsu', 10000000000, 'industrial waste tons/yr', 'waste'),
    ('satellite', 'satellite', 10000, 'active satellites', 'space'),
    ('sbom', 'sbom', 50000000, 'software packages', 'software'),
    ('scam_template', 'malak', 1000000, 'scam templates', 'security'),
    ('securities', 'securities', 3000, 'stock exchanges', 'finance'),
    ('seibi_kiroku', 'seibi', 5000000000, 'maintenance records/yr', 'transport'),
    ('seitaikei', 'shizen', 800, 'ecoregions', 'nature'),
    ('seizo_batch', 'seizo', 10000000000, 'production batches/yr', 'manufacturing'),
    ('seizo_shiji', 'seizo', 50000000000, 'work orders/yr', 'manufacturing'),
    ('senkyo', 'senkyo', 1000, 'elections/yr', 'governance'),
    ('senpaku_kaitai', 'haikibutsu', 1000, 'ship recycling/yr', 'waste'),
    ('setai', 'setai', 2000000000, 'households', 'welfare'),
    ('sex_offender', 'yabai', 1000000, 'sex offenders', 'security'),
    ('sgtin', 'serial', 1000000000000, 'serialized products', 'serial'),
    ('shell_company', 'yabai', 50000000, 'shell companies', 'security'),
    ('shigotoba', 'shigotoba', 400000000, 'business establishments', 'commerce'),
    ('shikaku', 'shikaku', 2000000000, 'certifications', 'education'),
    ('shiken_seiseki', 'gakko', 5000000000, 'exam records/yr', 'education'),
    ('shingou', 'douro', 10000000, 'traffic signals', 'transport'),
    ('shinsa_process', 'shinsa', 2000000000, 'credit assessments/yr', 'finance'),
    ('shinshi', 'shinshi', 10000000, 'sensitive content items', 'content'),
    ('shisan_lifecycle', 'shisan', 50000000000, 'asset lifecycle records', 'manufacturing'),
    ('shohin', 'shohin', 2000000000, 'consumer products', 'commerce'),
    ('shohousen', 'iryo', 5000000000, 'prescriptions/yr', 'healthcare'),
    ('shohyo', 'chizai', 70000000, 'trademarks', 'ip'),
    ('shokubutsu_hinshu', 'chizai', 200000, 'plant varieties', 'ip'),
    ('shokuhin_anzen', 'shokuhin-anzen', 100000000, 'food safety inspections/yr', 'food'),
    ('shokuhin_lot', 'serial', 1000000000000, 'food lots/yr', 'serial'),
    ('shoukyaku', 'haikibutsu', 2000, 'WtE plants', 'waste'),
    ('shujutsu_kiroku', 'iryo', 300000000, 'surgical procedures/yr', 'healthcare'),
    ('shukaku_cycle', 'nougyou', 5000000000, 'harvest cycles/yr', 'food'),
    ('shukyo_shisetsu', 'religious', 5000000, 'religious institutions', 'culture'),
    ('shussei_todoke', 'koseki', 3000000000, 'birth/death certificates', 'governance'),
    ('sns_account', 'sns', 5000000000, 'social media accounts', 'identity'),
    ('society6', 'society6', 195, 'COFOG national systems', 'welfare'),
    ('solar_serial', 'serial', 500000000, 'solar panels', 'serial'),
    ('soshou_stage', 'hanrei', 500000000, 'litigation stages', 'law'),
    ('souden_infra', 'souden', 500000000, 'grid infrastructure', 'energy'),
    ('sovereign', 'states', 195, 'sovereign states', 'governance'),
    ('sozai', 'sozai', 200000, 'material grades', 'manufacturing'),
    ('spam_campaign', 'malak', 50000000, 'spam campaigns', 'security'),
    ('spam_sender', 'malak', 500000000, 'spam senders', 'security'),
    ('sports_club', 'sports', 5000000, 'sports clubs', 'culture'),
    ('sports_shiai', 'sports', 10000000, 'sports matches/yr', 'culture'),
    ('story_arc', 'episode', 100000000, 'story arcs', 'fiction'),
    ('subscription', 'keiyaku', 5000000000, 'subscription contracts', 'contract'),
    ('suido', 'suido', 1400, 'water utilities (JP)', 'energy'),
    ('supply_chain', 'supply-chain', 100000000, 'vendor relationships', 'commerce'),
    ('sw_license_key', 'software', 10000000000, 'license keys', 'software'),
    ('sw_patch', 'software', 5000000, 'security patches', 'software'),
    ('sw_subscription', 'software', 5000000000, 'software subscriptions', 'software'),
    ('sw_vendor', 'software', 500000, 'software vendors', 'software'),
    ('syosetsu', 'syosetsu', 1000000, 'light novel titles', 'content'),
    ('taiyou_nensu', 'shisan', 100000000, 'useful life entries', 'manufacturing'),
    ('tanpakushitsu', 'genome', 200000000, 'protein structures', 'science'),
    ('tatemono_tenken', 'bim', 500000000, 'building inspections/yr', 'property'),
    ('taxi', 'taxi', 15000000, 'taxis & ride-hail', 'transport'),
    ('telecom', 'telecom', 4000, 'telecom operators', 'telecom'),
    ('tentai_asteroid', 'tentai', 1300000, 'asteroids', 'space'),
    ('tentai_comet', 'tentai', 4000, 'comets', 'space'),
    ('tentai_exoplanet', 'tentai', 5700, 'exoplanets', 'space'),
    ('tentai_galaxy', 'tentai', 2000000, 'galaxies', 'space'),
    ('tentai_moon', 'tentai', 300, 'natural satellites', 'space'),
    ('tentai_star', 'tentai', 1800000000, 'catalogued stars', 'space'),
    ('terror_watchlist', 'yabai', 2000000, 'terror watchlist entities', 'security'),
    ('threat_actor', 'malak', 50000, 'threat actors', 'security'),
    ('tire_serial', 'serial', 10000000000, 'tires in service', 'serial'),
    ('tor_node', 'malak', 8000, 'Tor nodes', 'security'),
    ('toshokan', 'toshokan', 400000, 'libraries', 'education'),
    ('tradition', 'tradition', 50000, 'cultural traditions', 'culture'),
    ('treaty', 'treaty', 560, 'multilateral treaties', 'governance'),
    ('trust', 'trust', 8100000000, 'trust-scored DIDs', 'welfare'),
    ('tsukan_shinkoku', 'tsukan', 500000000, 'customs declarations/yr', 'commerce'),
    ('tunnel', 'douro', 100000, 'road & rail tunnels', 'transport'),
    ('uchu_debris', 'uchu', 30000, 'orbital debris', 'space'),
    ('uchu_mission', 'uchu', 200, 'space launches/yr', 'space'),
    ('udi', 'serial', 2000000000, 'medical devices (UDI)', 'serial'),
    ('umetatchi', 'haikibutsu', 500000, 'landfill sites', 'waste'),
    ('unkou_kiroku', 'unkou', 500000000, 'service records/yr', 'transport'),
    ('unspsc', 'unspsc', 70000, 'UNSPSC commodities', 'commerce'),
    ('vehicle', 'vehicle', 1500000000, 'registered vehicles', 'transport'),
    ('vessel', 'vessel', 105000, 'merchant vessels', 'transport'),
    ('visa', 'visa', 200000000, 'visas/yr', 'governance'),
    ('wanted_person', 'yabai', 200000, 'wanted persons', 'security'),
    ('warehouse', 'warehouse', 500000, 'warehouses', 'commerce'),
    ('water', 'water', 300000, 'water utilities', 'energy'),
    ('webpage', 'webpage', 50000000000, 'web pages (indexed)', 'content'),
    ('well_becoming', 'well-becoming', 8100000000, 'persons (well-becoming)', 'welfare'),
    ('whois_record', 'malak', 350000000, 'WHOIS records', 'security'),
    ('windows_app', 'software', 500000, 'Windows apps', 'software'),
    ('witness_statement', 'hanrei', 200000000, 'witness statements', 'law'),
    ('yabai', 'yabai', 5000000, 'risk intelligence records', 'security'),
    ('yakuji_shinsei', 'seiyaku', 500000, 'regulatory submissions', 'pharma'),
    ('yobou_sesshu', 'iryo', 15000000000, 'vaccination records', 'healthcare'),
    ('yugai_jisho', 'seiyaku', 20000000, 'adverse event reports', 'pharma')`.execute(db);

  // ── 2. dim_app_host_alias ───────────────────────────────────────────
  await sql`CREATE TABLE IF NOT EXISTS dim_app_host_alias (
    alias_host     VARCHAR NOT NULL PRIMARY KEY,
    canonical_host VARCHAR NOT NULL
  )`.execute(db);

  await sql`DELETE FROM dim_app_host_alias`.execute(db);

  await sql`INSERT INTO dim_app_host_alias (alias_host, canonical_host) VALUES
    ('a7m8oocs', 'media-gamers'),
    ('business-person', 'legal-entity'),
    ('c0ll3ct1', 'maps'),
    ('d3yqp37e', 'gov'),
    ('g0vafg01', 'states'),
    ('g0vago01', 'states'),
    ('g0vagy01', 'states'),
    ('g0valb01', 'states'),
    ('g0vand01', 'states'),
    ('g0vare01', 'states'),
    ('g0varg01', 'states'),
    ('g0vatg01', 'states'),
    ('g0vaus01', 'states'),
    ('g0vaut01', 'states'),
    ('g0vbel01', 'states'),
    ('g0vbgd01', 'states'),
    ('g0vbgr01', 'states'),
    ('g0vbhr01', 'states'),
    ('g0vbih01', 'states'),
    ('g0vblr01', 'states'),
    ('g0vbol01', 'states'),
    ('g0vbra01', 'states'),
    ('g0vbrb01', 'states'),
    ('g0vbrn01', 'states'),
    ('g0vbwa01', 'states'),
    ('g0vcan01', 'states'),
    ('g0vche01', 'states'),
    ('g0vchl01', 'states'),
    ('g0vchn01', 'states'),
    ('g0vciv01', 'states'),
    ('g0vcmr01', 'states'),
    ('g0vcod01', 'states'),
    ('g0vcol01', 'states'),
    ('g0vcom01', 'states'),
    ('g0vcpv01', 'states'),
    ('g0vcri01', 'states'),
    ('g0vcub01', 'states'),
    ('g0vcyp01', 'states'),
    ('g0vcze01', 'states'),
    ('g0vdeu01', 'states'),
    ('g0vdji01', 'states'),
    ('g0vdma01', 'states'),
    ('g0vdnk01', 'states'),
    ('g0vdom01', 'states'),
    ('g0vdza01', 'states'),
    ('g0vecu01', 'states'),
    ('g0vegy01', 'states'),
    ('g0veri01', 'states'),
    ('g0vesp01', 'states'),
    ('g0vest01', 'states'),
    ('g0veth01', 'states'),
    ('g0vfin01', 'states'),
    ('g0vfji01', 'states'),
    ('g0vfra01', 'states'),
    ('g0vgbr01', 'states'),
    ('g0vgha01', 'states'),
    ('g0vgin01', 'states'),
    ('g0vgmb01', 'states'),
    ('g0vgnb01', 'states'),
    ('g0vgnq01', 'states'),
    ('g0vgrc01', 'states'),
    ('g0vgrd01', 'states'),
    ('g0vgtm01', 'states'),
    ('g0vguy01', 'states'),
    ('g0vhnd01', 'states'),
    ('g0vhrv01', 'states'),
    ('g0vhti01', 'states'),
    ('g0vhun01', 'states'),
    ('g0vidn01', 'states'),
    ('g0vind01', 'states'),
    ('g0virl01', 'states'),
    ('g0virn01', 'states'),
    ('g0virq01', 'states'),
    ('g0visl01', 'states'),
    ('g0vita01', 'states'),
    ('g0vjam01', 'states'),
    ('g0vjor01', 'states'),
    ('g0vjpn01', 'states'),
    ('g0vkaz01', 'states'),
    ('g0vken01', 'states'),
    ('g0vkgz01', 'states'),
    ('g0vkhm01', 'states'),
    ('g0vkir01', 'states'),
    ('g0vkna01', 'states'),
    ('g0vkor01', 'states'),
    ('g0vkwt01', 'states'),
    ('g0vlao01', 'states'),
    ('g0vlbn01', 'states'),
    ('g0vlbr01', 'states'),
    ('g0vlby01', 'states'),
    ('g0vlca01', 'states'),
    ('g0vlka01', 'states'),
    ('g0vlso01', 'states'),
    ('g0vltu01', 'states'),
    ('g0vlux01', 'states'),
    ('g0vlva01', 'states'),
    ('g0vmar01', 'states'),
    ('g0vmco01', 'states'),
    ('g0vmda01', 'states'),
    ('g0vmdg01', 'states'),
    ('g0vmex01', 'states'),
    ('g0vmhl01', 'states'),
    ('g0vmli01', 'states'),
    ('g0vmlt01', 'states'),
    ('g0vmmr01', 'states'),
    ('g0vmne01', 'states'),
    ('g0vmng01', 'states'),
    ('g0vmoz01', 'states'),
    ('g0vmrt01', 'states'),
    ('g0vmus01', 'states'),
    ('g0vmwi01', 'states'),
    ('g0vmys01', 'states'),
    ('g0vner01', 'states'),
    ('g0vnga01', 'states'),
    ('g0vnic01', 'states'),
    ('g0vnld01', 'states'),
    ('g0vnor01', 'states'),
    ('g0vnpl01', 'states'),
    ('g0vnru01', 'states'),
    ('g0vnzl01', 'states'),
    ('g0vomn01', 'states'),
    ('g0vpak01', 'states'),
    ('g0vpan01', 'states'),
    ('g0vper01', 'states'),
    ('g0vphl01', 'states'),
    ('g0vpng01', 'states'),
    ('g0vpol01', 'states'),
    ('g0vprt01', 'states'),
    ('g0vpry01', 'states'),
    ('g0vpse01', 'states'),
    ('g0vqat01', 'states'),
    ('g0vrou01', 'states'),
    ('g0vrus01', 'states'),
    ('g0vrwa01', 'states'),
    ('g0vsau01', 'states'),
    ('g0vsdn01', 'states'),
    ('g0vsen01', 'states'),
    ('g0vsgp01', 'states'),
    ('g0vslb01', 'states'),
    ('g0vsle01', 'states'),
    ('g0vslv01', 'states'),
    ('g0vsom01', 'states'),
    ('g0vsrb01', 'states'),
    ('g0vssd01', 'states'),
    ('g0vstp01', 'states'),
    ('g0vsur01', 'states'),
    ('g0vsvk01', 'states'),
    ('g0vsvn01', 'states'),
    ('g0vswe01', 'states'),
    ('g0vswz01', 'states'),
    ('g0vsyc01', 'states'),
    ('g0vsyr01', 'states'),
    ('g0vtcd01', 'states'),
    ('g0vtgo01', 'states'),
    ('g0vtha01', 'states'),
    ('g0vtjk01', 'states'),
    ('g0vtkm01', 'states'),
    ('g0vtls01', 'states'),
    ('g0vtto01', 'states'),
    ('g0vtun01', 'states'),
    ('g0vtur01', 'states'),
    ('g0vtuv01', 'states'),
    ('g0vtza01', 'states'),
    ('g0vuga01', 'states'),
    ('g0vukr01', 'states'),
    ('g0vury01', 'states'),
    ('g0vusa01', 'states'),
    ('g0vuzb01', 'states'),
    ('g0vvct01', 'states'),
    ('g0vven01', 'states'),
    ('g0vvnm01', 'states'),
    ('g0vvut01', 'states'),
    ('g0vwsm01', 'states'),
    ('g0vyem01', 'states'),
    ('g0vzaf01', 'states'),
    ('g0vzmb01', 'states'),
    ('g0vzwe01', 'states'),
    ('hs54vjd0', 'maps'),
    ('le9k4x2m', 'legal-entity'),
    ('play-google-com', 'software'),
    ('sh1n5h1x', 'character'),
    ('uqpel6i6', 'maps'),
    ('w3bpg001', 'webpage')`.execute(db);

  // ── 3. mv_world_did_per_host ────────────────────────────────────────
  await sql`CREATE MATERIALIZED VIEW IF NOT EXISTS mv_world_did_per_host AS
    SELECT
      COALESCE(a.canonical_host, raw.app_host) AS app_host,
      SUM(raw.did_count) AS did_count
    FROM (
      SELECT
        SPLIT_PART(SPLIT_PART(did, '.etzhayyim.com', 1), 'did:web:', 2) AS app_host,
        COUNT(DISTINCT did) AS did_count
      FROM vertex_profile
      WHERE did IS NOT NULL AND did LIKE 'did:web:%.etzhayyim.com%'
      GROUP BY SPLIT_PART(SPLIT_PART(did, '.etzhayyim.com', 1), 'did:web:', 2)
    ) raw
    LEFT JOIN dim_app_host_alias a ON a.alias_host = raw.app_host
    GROUP BY COALESCE(a.canonical_host, raw.app_host)`.execute(db);

  // ── 4. mv_world_record_per_host ─────────────────────────────────────
  await sql`CREATE MATERIALIZED VIEW IF NOT EXISTS mv_world_record_per_host AS
    SELECT
      COALESCE(a.canonical_host, raw.app_host) AS app_host,
      SUM(raw.record_count) AS record_count
    FROM (
      SELECT
        SPLIT_PART(SPLIT_PART(repo, '.etzhayyim.com', 1), 'did:web:', 2) AS app_host,
        COUNT(*) AS record_count
      FROM vertex_repo_record
      WHERE repo IS NOT NULL AND repo LIKE 'did:web:%.etzhayyim.com%'
      GROUP BY SPLIT_PART(SPLIT_PART(repo, '.etzhayyim.com', 1), 'did:web:', 2)
    ) raw
    LEFT JOIN dim_app_host_alias a ON a.alias_host = raw.app_host
    GROUP BY COALESCE(a.canonical_host, raw.app_host)`.execute(db);

  // ── 5. mv_world_vertex_per_host ─────────────────────────────────────
  await sql`CREATE MATERIALIZED VIEW IF NOT EXISTS mv_world_vertex_per_host AS
    SELECT app_host, SUM(cnt) AS vertex_count FROM (
      SELECT 'legal-entity' AS app_host, COUNT(*) AS cnt FROM vertex_legal_entity
      UNION ALL SELECT 'maps',         COUNT(*) FROM vertex_spatial
      UNION ALL SELECT 'gov',          COUNT(*) FROM vertex_gov_org
      UNION ALL SELECT 'dns',          COUNT(*) FROM vertex_dns_observation
      UNION ALL SELECT 'railway',      COUNT(*) FROM vertex_transport
      UNION ALL SELECT 'blockchain',   COUNT(*) FROM vertex_blockchain_actor
      UNION ALL SELECT 'gtin',         COUNT(*) FROM vertex_gtin_product
      UNION ALL SELECT 'media-gamers', COUNT(*) FROM vertex_game_actor
      UNION ALL SELECT 'media-gamers', COUNT(*) FROM vertex_game_item
      UNION ALL SELECT 'bank',         COUNT(*) FROM vertex_finance
    ) sub
    GROUP BY app_host`.execute(db);

  // ── 6. mv_world_coverage_live (GREATEST, not sum) ───────────────────
  await sql`CREATE MATERIALIZED VIEW IF NOT EXISTS mv_world_coverage_live AS
    SELECT
      d.domain,
      d.app_host,
      d.world_total,
      d.unit,
      d.sector,
      COALESCE(p.did_count, 0)    AS did_count,
      COALESCE(r.record_count, 0) AS record_count,
      COALESCE(v.vertex_count, 0) AS vertex_count,
      GREATEST(
        COALESCE(p.did_count, 0),
        COALESCE(r.record_count, 0),
        COALESCE(v.vertex_count, 0)
      ) AS collected,
      CASE WHEN d.world_total > 0
        THEN GREATEST(
               COALESCE(p.did_count, 0),
               COALESCE(r.record_count, 0),
               COALESCE(v.vertex_count, 0)
             )::DOUBLE PRECISION / d.world_total::DOUBLE PRECISION
        ELSE 0.0
      END AS coverage_rate,
      CASE WHEN d.world_total > 0
        THEN 1.0 - GREATEST(
                     COALESCE(p.did_count, 0),
                     COALESCE(r.record_count, 0),
                     COALESCE(v.vertex_count, 0)
                   )::DOUBLE PRECISION / d.world_total::DOUBLE PRECISION
        ELSE 1.0
      END AS gap_rate,
      GREATEST(
        d.world_total - GREATEST(
          COALESCE(p.did_count, 0),
          COALESCE(r.record_count, 0),
          COALESCE(v.vertex_count, 0)
        ),
        0
      )::BIGINT AS remaining
    FROM dim_world_domain d
    LEFT JOIN mv_world_did_per_host p    ON p.app_host = d.app_host
    LEFT JOIN mv_world_record_per_host r ON r.app_host = d.app_host
    LEFT JOIN mv_world_vertex_per_host v ON v.app_host = d.app_host`.execute(db);
}

export async function down(db: Kysely<unknown>): Promise<void> {
  await sql`DROP MATERIALIZED VIEW IF EXISTS mv_world_coverage_live`.execute(db);
  await sql`DROP MATERIALIZED VIEW IF EXISTS mv_world_vertex_per_host`.execute(db);
  await sql`DROP MATERIALIZED VIEW IF EXISTS mv_world_record_per_host`.execute(db);
  await sql`DROP MATERIALIZED VIEW IF EXISTS mv_world_did_per_host`.execute(db);
  await sql`DROP TABLE IF EXISTS dim_app_host_alias`.execute(db);
  await sql`DROP TABLE IF EXISTS dim_world_domain`.execute(db);
}
