"""Captured from Kysely migration 20260423191000_seed_open_seiyaku_bpmn_actors."""

from __future__ import annotations

from alembic import op

from graph_schema.db import execute_bound_statements


revision = "r_20260423191000_seed_open_seiyaku_bpmn_actors"
down_revision = 'r_20260423190000_vertex_open_seiyaku'
branch_labels = None
depends_on = None

UP = [{'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id,\n'
         '      owner_did,\n'
         '      bpmn_process_id,\n'
         '      version,\n'
         '      xml,\n'
         '      xml_byte_size,\n'
         '      source_path,\n'
         '      status,\n'
         '      created_at,\n'
         '      sensitivity_ord,\n'
         '      org_id,\n'
         '      user_id,\n'
         '      actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1,\n'
         '      $2,\n'
         '      $3,\n'
         '      1,\n'
         '      $4,\n'
         '      CAST($5 AS integer),\n'
         '      $6,\n'
         "      'active',\n"
         '      $7,\n'
         '      1,\n'
         '      $8,\n'
         '      $9,\n'
         "      'sys.bpmn.seed.open-seiyaku'\n"
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $10\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.processDef/open-seiyaku-register-batch-v1',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'seiyaku_register_batch',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_seiyaku_register_batch"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/open-seiyaku"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="seiyaku_register_batch" name="製薬バッチ登録" isExecutable="true">\n'
                 '    <bpmn:startEvent id="Start" name="開始">\n'
                 '      <bpmn:outgoing>Flow_S</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_S" sourceRef="Start" targetRef="Task_Form"/>\n'
                 '\n'
                 '    <bpmn:userTask id="Task_Form" name="バッチ記録入力">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:formDefinition '
                 'formKey="camunda-forms:bpmn:open-seiyaku-batch-form-v1"/>\n'
                 '        <zeebe:assignmentDefinition candidateGroups="plant-operator"/>\n'
                 '        <zeebe:taskSchedule dueDate="=now() + duration(&quot;P7D&quot;)"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_S</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_LoopBack</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_ValidationLoopBack</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_QAReworkLoop</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_F1</bpmn:outgoing>\n'
                 '    </bpmn:userTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_F1" sourceRef="Task_Form" '
                 'targetRef="Task_ValidateSubmission"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ValidateSubmission" name="GMP 必須項目検証">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.rules.evaluate"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;open-seiyaku.batch.register.v1&quot;" '
                 'target="ruleSet"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertexId:             vertexId,\n'
                 '              manufacturerOrgId:    manufacturerOrgId,\n'
                 '              plantOrgId:           plantOrgId,\n'
                 '              productCode:          productCode,\n'
                 '              batchNumber:          batchNumber,\n'
                 '              dosageForm:           string(batchIdentity.dosageForm),\n'
                 '              masterFormulaPayload: string(masterFormulaPayload),\n'
                 '              materialPayload:      string(materialPayload),\n'
                 '              batchRecordPayload:   string(batchRecordPayload),\n'
                 '              qualityPayload:       string(qualityPayload),\n'
                 '              deviationPayload:     string(deviationPayload)\n'
                 '          }" target="facts"/>\n'
                 '          <zeebe:output source="=passed" target="validationPassed"/>\n'
                 '          <zeebe:output source="=findings" target="validationFindings"/>\n'
                 '          <zeebe:output source="=coalesce(riskTier, &quot;standard&quot;)" '
                 'target="batchRiskTier"/>\n'
                 '          <zeebe:output source="=coalesce(exportControlled, false)" '
                 'target="exportControlled"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_F1</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ValidationGate</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ValidationGate" '
                 'sourceRef="Task_ValidateSubmission" targetRef="Gate_ValidationPassed"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gate_ValidationPassed" name="検証 OK?" '
                 'default="Flow_ValidationFailed">\n'
                 '      <bpmn:incoming>Flow_ValidationGate</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ValidationPassed</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_ValidationFailed</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_ValidationPassed" '
                 'sourceRef="Gate_ValidationPassed" targetRef="Task_SaveConfidential">\n'
                 '      <bpmn:conditionExpression '
                 'xsi:type="bpmn:tFormalExpression">=validationPassed = '
                 'true</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_ValidationFailed" '
                 'sourceRef="Gate_ValidationPassed" targetRef="Task_AuditValidationFailed"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditValidationFailed" name="audit validation '
                 'failed">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;did:web:open-seiyaku.etzhayyim.com:manufacturing&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;openSeiyaku.batch.validationFailed&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertexId:           vertexId,\n'
                 '              manufacturerOrgId:  manufacturerOrgId,\n'
                 '              plantOrgId:         plantOrgId,\n'
                 '              productCode:        productCode,\n'
                 '              batchNumber:        batchNumber,\n'
                 '              findings:           validationFindings\n'
                 '          }" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ValidationFailed</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ValidationLoopBack</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ValidationLoopBack" '
                 'sourceRef="Task_AuditValidationFailed" targetRef="Task_Form"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_SaveConfidential" name="confidential payload '
                 '保存">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;vertex_open_seiyaku_batch_confidential&quot;" target="table"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertex_id:              vertexId,\n'
                 '              manufacturer_org_id:    manufacturerOrgId,\n'
                 '              plant_org_id:           plantOrgId,\n'
                 '              master_formula_payload: string(masterFormulaPayload),\n'
                 '              material_payload:       string(materialPayload),\n'
                 '              batch_record_payload:   string(batchRecordPayload),\n'
                 '              quality_payload:        string(qualityPayload),\n'
                 '              deviation_payload:      string(deviationPayload),\n'
                 '              amendment_log:          &quot;[]&quot;,\n'
                 '              retention_until:        string(now() + '
                 'duration(&quot;P3650D&quot;)),\n'
                 '              created_at:             string(now()),\n'
                 '              owner_did:              callerDid,\n'
                 '              sensitivity_ord:        2,\n'
                 '              org_id:                 manufacturerOrgId,\n'
                 '              user_id:                callerDid,\n'
                 '              actor_id:               &quot;sys.bpmn.open-seiyaku&quot;\n'
                 '          }" target="values"/>\n'
                 '          <zeebe:input source="=&quot;ignore&quot;" target="onConflict"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ValidationPassed</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_F2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_F2" sourceRef="Task_SaveConfidential" '
                 'targetRef="Task_SaveMeta"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_SaveMeta" name="Tier 1 メタ保存">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_open_seiyaku_batch&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertex_id:             vertexId,\n'
                 '              manufacturer_org_id:   manufacturerOrgId,\n'
                 '              plant_org_id:          plantOrgId,\n'
                 '              product_code:          productCode,\n'
                 '              batch_number:          batchNumber,\n'
                 '              dosage_form:           string(batchIdentity.dosageForm),\n'
                 '              process_type:          &quot;register&quot;,\n'
                 '              status:                &quot;submitted&quot;,\n'
                 '              batch_hash:            string(batchHash),\n'
                 '              qa_required:           true,\n'
                 '              amendment_count:       0,\n'
                 '              submitted_at:          string(now()),\n'
                 '              created_at:            string(now()),\n'
                 '              owner_did:             callerDid,\n'
                 '              sensitivity_ord:       1,\n'
                 '              org_id:                manufacturerOrgId,\n'
                 '              user_id:               callerDid,\n'
                 '              actor_id:              &quot;sys.bpmn.open-seiyaku&quot;\n'
                 '          }" target="values"/>\n'
                 '          <zeebe:input source="=&quot;ignore&quot;" target="onConflict"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_F2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_F3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_F3" sourceRef="Task_SaveMeta" '
                 'targetRef="Gate_ExportScreenNeeded"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gate_ExportScreenNeeded" name="輸出管理確認要?" '
                 'default="Flow_NoExportScreen">\n'
                 '      <bpmn:incoming>Flow_F3</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ExportScreen</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_NoExportScreen</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_ExportScreen" '
                 'sourceRef="Gate_ExportScreenNeeded" targetRef="Task_ExportControlReview">\n'
                 '      <bpmn:conditionExpression '
                 'xsi:type="bpmn:tFormalExpression">=exportControlled = true or batchRiskTier = '
                 '"restricted"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_NoExportScreen" '
                 'sourceRef="Gate_ExportScreenNeeded" targetRef="Task_QAReview"/>\n'
                 '\n'
                 '    <bpmn:userTask id="Task_ExportControlReview" name="輸出管理レビュー">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:formDefinition '
                 'formKey="camunda-forms:bpmn:open-seiyaku-export-control-v1"/>\n'
                 '        <zeebe:assignmentDefinition candidateGroups="trade-compliance"/>\n'
                 '        <zeebe:taskSchedule dueDate="=now() + duration(&quot;P3D&quot;)"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ExportScreen</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ExportGate</bpmn:outgoing>\n'
                 '    </bpmn:userTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ExportGate" sourceRef="Task_ExportControlReview" '
                 'targetRef="Gate_ExportCleared"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gate_ExportCleared" name="輸出管理 OK?" '
                 'default="Flow_ExportBlocked">\n'
                 '      <bpmn:incoming>Flow_ExportGate</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ExportCleared</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_ExportBlocked</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_ExportCleared" sourceRef="Gate_ExportCleared" '
                 'targetRef="Task_QAReview">\n'
                 '      <bpmn:conditionExpression '
                 'xsi:type="bpmn:tFormalExpression">=exportControlDecision = '
                 '"clear"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_ExportBlocked" sourceRef="Gate_ExportCleared" '
                 'targetRef="Task_MarkRejected"/>\n'
                 '\n'
                 '    <bpmn:userTask id="Task_QAReview" name="QA レビュー">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:formDefinition '
                 'formKey="camunda-forms:bpmn:open-seiyaku-batch-review-v1"/>\n'
                 '        <zeebe:assignmentDefinition candidateGroups="qa-officer"/>\n'
                 '        <zeebe:taskSchedule dueDate="=now() + duration(&quot;P5D&quot;)"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_NoExportScreen</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_ExportCleared</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_F4</bpmn:outgoing>\n'
                 '    </bpmn:userTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_F4" sourceRef="Task_QAReview" '
                 'targetRef="Gate_QAComplete"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gate_QAComplete" name="QA 完了?" '
                 'default="Flow_QARework">\n'
                 '      <bpmn:incoming>Flow_F4</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_QAComplete</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_QARework</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_QAComplete" sourceRef="Gate_QAComplete" '
                 'targetRef="Gate_Approved">\n'
                 '      <bpmn:conditionExpression '
                 'xsi:type="bpmn:tFormalExpression">=coalesce(reviewComplete, true) = '
                 'true</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_QARework" sourceRef="Gate_QAComplete" '
                 'targetRef="Task_AuditQARework"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditQARework" name="audit QA rework">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;did:web:open-seiyaku.etzhayyim.com:manufacturing&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;openSeiyaku.batch.qaRework&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertexId:        vertexId,\n'
                 '              batchNumber:     batchNumber,\n'
                 '              reviewFindings:  reviewFindings\n'
                 '          }" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_QARework</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_QAReworkLoop</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_QAReworkLoop" sourceRef="Task_AuditQARework" '
                 'targetRef="Task_Form"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gate_Approved" name="承認?" default="Flow_Reject">\n'
                 '      <bpmn:incoming>Flow_QAComplete</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Approve</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Reject</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_Approve" sourceRef="Gate_Approved" '
                 'targetRef="Task_MarkReleased">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=verdict = '
                 '"approve"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Reject" sourceRef="Gate_Approved" '
                 'targetRef="Task_MarkRejected"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_MarkReleased" name="released 化">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_open_seiyaku_batch&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertex_id:             vertexId,\n'
                 '              manufacturer_org_id:   manufacturerOrgId,\n'
                 '              plant_org_id:          plantOrgId,\n'
                 '              product_code:          productCode,\n'
                 '              batch_number:          batchNumber,\n'
                 '              dosage_form:           string(batchIdentity.dosageForm),\n'
                 '              process_type:          &quot;register&quot;,\n'
                 '              status:                &quot;released&quot;,\n'
                 '              batch_hash:            string(batchHash),\n'
                 '              qa_required:           true,\n'
                 '              qa_decision:           &quot;approve&quot;,\n'
                 '              released_at:           string(now()),\n'
                 '              approved_at:           string(now()),\n'
                 '              approved_by_did:       string(reviewerDid),\n'
                 '              amendment_count:       0,\n'
                 '              submitted_at:          string(now()),\n'
                 '              created_at:            string(now()),\n'
                 '              owner_did:             callerDid,\n'
                 '              sensitivity_ord:       1,\n'
                 '              org_id:                manufacturerOrgId,\n'
                 '              user_id:               callerDid,\n'
                 '              actor_id:              &quot;sys.bpmn.open-seiyaku&quot;\n'
                 '          }" target="values"/>\n'
                 '          <zeebe:input source="=&quot;replace&quot;" target="onConflict"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Approve</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AuditApproved</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AuditApproved" sourceRef="Task_MarkReleased" '
                 'targetRef="Task_AuditReleased"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditReleased" name="audit released">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;did:web:open-seiyaku.etzhayyim.com:manufacturing&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;openSeiyaku.batch.release&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertexId:           vertexId,\n'
                 '              manufacturerOrgId:  manufacturerOrgId,\n'
                 '              plantOrgId:         plantOrgId,\n'
                 '              productCode:        productCode,\n'
                 '              batchNumber:        batchNumber\n'
                 '          }" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_AuditApproved</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_EndA</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_EndA" sourceRef="Task_AuditReleased" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_MarkRejected" name="差戻し">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_open_seiyaku_batch&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertex_id:             vertexId,\n'
                 '              manufacturer_org_id:   manufacturerOrgId,\n'
                 '              plant_org_id:          plantOrgId,\n'
                 '              product_code:          productCode,\n'
                 '              batch_number:          batchNumber,\n'
                 '              dosage_form:           string(batchIdentity.dosageForm),\n'
                 '              process_type:          &quot;register&quot;,\n'
                 '              status:                &quot;rejected&quot;,\n'
                 '              batch_hash:            string(batchHash),\n'
                 '              qa_required:           true,\n'
                 '              qa_decision:           &quot;reject&quot;,\n'
                 '              amendment_count:       0,\n'
                 '              submitted_at:          string(now()),\n'
                 '              created_at:            string(now()),\n'
                 '              owner_did:             callerDid,\n'
                 '              sensitivity_ord:       1,\n'
                 '              org_id:                manufacturerOrgId,\n'
                 '              user_id:               callerDid,\n'
                 '              actor_id:              &quot;sys.bpmn.open-seiyaku&quot;\n'
                 '          }" target="values"/>\n'
                 '          <zeebe:input source="=&quot;replace&quot;" target="onConflict"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Reject</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_ExportBlocked</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AuditRejected</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AuditRejected" sourceRef="Task_MarkRejected" '
                 'targetRef="Task_AuditRejected"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditRejected" name="audit rejected">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;did:web:open-seiyaku.etzhayyim.com:manufacturing&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;openSeiyaku.batch.reject&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertexId:    vertexId,\n'
                 '              batchNumber: batchNumber\n'
                 '          }" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_AuditRejected</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_LoopBack</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_LoopBack" sourceRef="Task_AuditRejected" '
                 'targetRef="Task_Form"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="完了">\n'
                 '      <bpmn:incoming>Flow_EndA</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 18396,
                 '00-contracts/bpmn/ai/gftd/open-seiyaku/registerBatch.bpmn',
                 '2026-04-23T19:10:00Z',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.processDef/open-seiyaku-register-batch-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id,\n'
         '      owner_did,\n'
         '      bpmn_process_id,\n'
         '      version,\n'
         '      xml,\n'
         '      xml_byte_size,\n'
         '      source_path,\n'
         '      status,\n'
         '      created_at,\n'
         '      sensitivity_ord,\n'
         '      org_id,\n'
         '      user_id,\n'
         '      actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1,\n'
         '      $2,\n'
         '      $3,\n'
         '      1,\n'
         '      $4,\n'
         '      CAST($5 AS integer),\n'
         '      $6,\n'
         "      'active',\n"
         '      $7,\n'
         '      1,\n'
         '      $8,\n'
         '      $9,\n'
         "      'sys.bpmn.seed.open-seiyaku'\n"
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $10\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.processDef/open-seiyaku-amend-batch-v1',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'seiyaku_amend_batch',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_seiyaku_amend_batch"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/open-seiyaku"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="seiyaku_amend_batch" name="製薬バッチ変更" isExecutable="true">\n'
                 '    <bpmn:startEvent id="Start" name="変更開始">\n'
                 '      <bpmn:outgoing>Flow_S</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_S" sourceRef="Start" '
                 'targetRef="Task_AmendForm"/>\n'
                 '\n'
                 '    <bpmn:userTask id="Task_AmendForm" name="変更申請入力">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:formDefinition '
                 'formKey="camunda-forms:bpmn:open-seiyaku-amend-v1"/>\n'
                 '        <zeebe:assignmentDefinition candidateGroups="plant-operator"/>\n'
                 '        <zeebe:taskSchedule dueDate="=now() + duration(&quot;P3D&quot;)"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_S</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_QARejectLoop</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_F1</bpmn:outgoing>\n'
                 '    </bpmn:userTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_F1" sourceRef="Task_AmendForm" '
                 'targetRef="Task_ClassifyAmendment"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ClassifyAmendment" name="変更リスク分類">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.rules.evaluate"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;open-seiyaku.batch.amend.v1&quot;" '
                 'target="ruleSet"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertexId:            vertexId,\n'
                 '              amendmentType:       amendmentType,\n'
                 '              batchNumber:         batchNumber,\n'
                 '              deviationPayload:    string(deviationPayload),\n'
                 '              amendmentPayload:    string(amendmentPayload),\n'
                 '              requiresQaApproval:  requiresQaApproval\n'
                 '          }" target="facts"/>\n'
                 '          <zeebe:output source="=coalesce(riskTier, if requiresQaApproval then '
                 '&quot;major&quot; else &quot;minor&quot;)" target="amendmentRiskTier"/>\n'
                 '          <zeebe:output source="=coalesce(capaRequired, false)" '
                 'target="capaRequired"/>\n'
                 '          <zeebe:output source="=coalesce(approvalRequired, requiresQaApproval)" '
                 'target="effectiveQaApprovalRequired"/>\n'
                 '          <zeebe:output source="=findings" target="amendmentFindings"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_F1</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Classified</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Classified" sourceRef="Task_ClassifyAmendment" '
                 'targetRef="Gate_ApprovalNeeded"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gate_ApprovalNeeded" name="QA 承認要?" '
                 'default="Flow_NoApproval">\n'
                 '      <bpmn:incoming>Flow_Classified</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Approval</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_NoApproval</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_Approval" sourceRef="Gate_ApprovalNeeded" '
                 'targetRef="Task_QAReview">\n'
                 '      <bpmn:conditionExpression '
                 'xsi:type="bpmn:tFormalExpression">=effectiveQaApprovalRequired = '
                 'true</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_NoApproval" sourceRef="Gate_ApprovalNeeded" '
                 'targetRef="Task_AppendAmendment"/>\n'
                 '\n'
                 '    <bpmn:userTask id="Task_QAReview" name="QA 変更レビュー">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:formDefinition '
                 'formKey="camunda-forms:bpmn:open-seiyaku-batch-review-v1"/>\n'
                 '        <zeebe:assignmentDefinition candidateGroups="qa-officer"/>\n'
                 '        <zeebe:taskSchedule dueDate="=now() + duration(&quot;P5D&quot;)"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Approval</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_F2</bpmn:outgoing>\n'
                 '    </bpmn:userTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_F2" sourceRef="Task_QAReview" '
                 'targetRef="Gate_QAApproved"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gate_QAApproved" name="変更承認?" '
                 'default="Flow_QAReject">\n'
                 '      <bpmn:incoming>Flow_F2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_QAApprove</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_QAReject</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_QAApprove" sourceRef="Gate_QAApproved" '
                 'targetRef="Task_AppendAmendment">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=verdict = '
                 '"approve"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_QAReject" sourceRef="Gate_QAApproved" '
                 'targetRef="Task_AuditQAReject"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditQAReject" name="audit amendment rejected">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;did:web:open-seiyaku.etzhayyim.com:manufacturing&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;openSeiyaku.batch.amend.reject&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertexId:          vertexId,\n'
                 '              batchNumber:       batchNumber,\n'
                 '              amendmentType:     amendmentType,\n'
                 '              amendmentRiskTier: amendmentRiskTier,\n'
                 '              findings:          amendmentFindings,\n'
                 '              reviewFindings:    reviewFindings\n'
                 '          }" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_QAReject</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_QARejectLoop</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_QARejectLoop" sourceRef="Task_AuditQAReject" '
                 'targetRef="Task_AmendForm"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AppendAmendment" name="変更ログ append">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;vertex_open_seiyaku_batch_confidential&quot;" target="table"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertex_id:              vertexId,\n'
                 '              manufacturer_org_id:    manufacturerOrgId,\n'
                 '              plant_org_id:           plantOrgId,\n'
                 '              master_formula_payload: string(masterFormulaPayload),\n'
                 '              material_payload:       string(materialPayload),\n'
                 '              batch_record_payload:   string(batchRecordPayload),\n'
                 '              quality_payload:        string(qualityPayload),\n'
                 '              deviation_payload:      string(deviationPayload),\n'
                 '              amendment_log:          string(amendmentPayload),\n'
                 '              retention_until:        string(now() + '
                 'duration(&quot;P3650D&quot;)),\n'
                 '              created_at:             string(now()),\n'
                 '              owner_did:              callerDid,\n'
                 '              sensitivity_ord:        2,\n'
                 '              org_id:                 manufacturerOrgId,\n'
                 '              user_id:                callerDid,\n'
                 '              actor_id:               &quot;sys.bpmn.open-seiyaku&quot;\n'
                 '          }" target="values"/>\n'
                 '          <zeebe:input source="=&quot;replace&quot;" target="onConflict"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_NoApproval</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_QAApprove</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_F3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_F3" sourceRef="Task_AppendAmendment" '
                 'targetRef="Task_UpdateMeta"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_UpdateMeta" name="Tier 1 amendment 反映">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_open_seiyaku_batch&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertex_id:             vertexId,\n'
                 '              manufacturer_org_id:   manufacturerOrgId,\n'
                 '              plant_org_id:          plantOrgId,\n'
                 '              product_code:          productCode,\n'
                 '              batch_number:          batchNumber,\n'
                 '              process_type:          &quot;amend&quot;,\n'
                 '              status:                &quot;amended&quot;,\n'
                 '              batch_hash:            string(batchHash),\n'
                 '              qa_required:           effectiveQaApprovalRequired,\n'
                 '              qa_decision:           if effectiveQaApprovalRequired then '
                 'string(verdict) else &quot;auto&quot;,\n'
                 '              amendment_risk_tier:   amendmentRiskTier,\n'
                 '              capa_required:         capaRequired,\n'
                 '              amendment_count:       1,\n'
                 '              submitted_at:          string(now()),\n'
                 '              created_at:            string(now()),\n'
                 '              owner_did:             callerDid,\n'
                 '              sensitivity_ord:       1,\n'
                 '              org_id:                manufacturerOrgId,\n'
                 '              user_id:               callerDid,\n'
                 '              actor_id:              &quot;sys.bpmn.open-seiyaku&quot;\n'
                 '          }" target="values"/>\n'
                 '          <zeebe:input source="=&quot;replace&quot;" target="onConflict"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_F3</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_F4</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_F4" sourceRef="Task_UpdateMeta" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="audit amendment">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;did:web:open-seiyaku.etzhayyim.com:manufacturing&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;openSeiyaku.batch.amend&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={\n'
                 '              vertexId:       vertexId,\n'
                 '              batchNumber:    batchNumber,\n'
                 '              amendmentType:  amendmentType,\n'
                 '              requiresQa:     effectiveQaApprovalRequired,\n'
                 '              riskTier:       amendmentRiskTier,\n'
                 '              capaRequired:   capaRequired,\n'
                 '              findings:       amendmentFindings\n'
                 '          }" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_F4</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="完了">\n'
                 '      <bpmn:incoming>Flow_End</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 10260,
                 '00-contracts/bpmn/ai/gftd/open-seiyaku/amendBatch.bpmn',
                 '2026-04-23T19:10:00Z',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.processDef/open-seiyaku-amend-batch-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id,\n'
         '      owner_did,\n'
         '      bpmn_process_id,\n'
         '      version,\n'
         '      xml,\n'
         '      xml_byte_size,\n'
         '      source_path,\n'
         '      status,\n'
         '      created_at,\n'
         '      sensitivity_ord,\n'
         '      org_id,\n'
         '      user_id,\n'
         '      actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1,\n'
         '      $2,\n'
         '      $3,\n'
         '      1,\n'
         '      $4,\n'
         '      CAST($5 AS integer),\n'
         '      $6,\n'
         "      'active',\n"
         '      $7,\n'
         '      1,\n'
         '      $8,\n'
         '      $9,\n'
         "      'sys.bpmn.seed.open-seiyaku'\n"
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $10\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.processDef/open-seiyaku-purge-v1',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'seiyaku_purge',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_seiyaku_purge"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/open-seiyaku"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="seiyaku_purge" name="製薬 confidential purge" '
                 'isExecutable="true">\n'
                 '    <bpmn:startEvent id="StartTimer" name="03:30 daily">\n'
                 '      <bpmn:outgoing>Flow_T</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition>\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression">0 30 3 * * '
                 '?</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_T" sourceRef="StartTimer" '
                 'targetRef="Task_FindExpired"/>\n'
                 '\n'
                 '    <bpmn:startEvent id="StartManual" name="manual purge">\n'
                 '      <bpmn:outgoing>Flow_M</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_M" sourceRef="StartManual" '
                 'targetRef="Task_FindExpired"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_FindExpired" name="期限切れ検索">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;vertex_open_seiyaku_batch_confidential&quot;" target="table"/>\n'
                 '          <zeebe:input source="=&quot;retention_until &lt; %s&quot;" '
                 'target="whereExpr"/>\n'
                 '          <zeebe:input source="=[string(now())]" target="whereParams"/>\n'
                 '          <zeebe:input source="=&quot;vertex_id, manufacturer_org_id, '
                 'plant_org_id&quot;" target="columns"/>\n'
                 '          <zeebe:input source="=200" target="limit"/>\n'
                 '          <zeebe:output source="=rows" target="expiredRows"/>\n'
                 '          <zeebe:output source="=rowCount" target="purgedCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_T</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_M</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_F1</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_F1" sourceRef="Task_FindExpired" '
                 'targetRef="Gate_HasRows"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gate_HasRows" name="対象あり?" '
                 'default="Flow_NoRows">\n'
                 '      <bpmn:incoming>Flow_F1</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_HasRows</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_NoRows</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_HasRows" sourceRef="Gate_HasRows" '
                 'targetRef="Task_PurgeBatch">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=purgedCount '
                 '&gt; 0</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_NoRows" sourceRef="Gate_HasRows" '
                 'targetRef="Task_AuditNoOp"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_PurgeBatch" name="confidential payload hard '
                 'delete">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.purgeSeiyakuConfidential"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=expiredRows" target="rows"/>\n'
                 '          <zeebe:output source="=deleted" target="deletedCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_HasRows</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_F2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_F2" sourceRef="Task_PurgeBatch" '
                 'targetRef="Task_AuditPurged"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditPurged" name="audit purged">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;did:web:open-seiyaku.etzhayyim.com:manufacturing&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;openSeiyaku.purge&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={\n'
                 '              purgedCount:  purgedCount,\n'
                 '              deletedCount: deletedCount\n'
                 '          }" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_F2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_EndA</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_EndA" sourceRef="Task_AuditPurged" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditNoOp" name="audit noop">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;did:web:open-seiyaku.etzhayyim.com:manufacturing&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;openSeiyaku.purge.noop&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={ purgedCount: 0 }" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_NoRows</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_EndB</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_EndB" sourceRef="Task_AuditNoOp" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="完了">\n'
                 '      <bpmn:incoming>Flow_EndA</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_EndB</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 4981,
                 '00-contracts/bpmn/ai/gftd/open-seiyaku/purge.bpmn',
                 '2026-04-23T19:10:00Z',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.processDef/open-seiyaku-purge-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id,\n'
         '      owner_did,\n'
         '      nsid,\n'
         '      bpmn_process_id,\n'
         '      bpmn_version,\n'
         '      result_timeout_ms,\n'
         '      status,\n'
         '      created_at,\n'
         '      sensitivity_ord,\n'
         '      org_id,\n'
         '      user_id,\n'
         '      actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1,\n'
         '      $2,\n'
         '      $3,\n'
         '      $4,\n'
         '      1,\n'
         '      CAST($5 AS integer),\n'
         "      'active',\n"
         '      $6,\n'
         '      1,\n'
         '      $7,\n'
         '      $8,\n'
         "      'sys.bpmn.seed.open-seiyaku'\n"
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $9\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.binding/open-seiyaku-startBatchRecord-v1',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'ai.gftd.apps.openSeiyaku.startBatchRecord',
                 'seiyaku_register_batch',
                 0,
                 '2026-04-23T19:10:00Z',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.binding/open-seiyaku-startBatchRecord-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id,\n'
         '      owner_did,\n'
         '      nsid,\n'
         '      bpmn_process_id,\n'
         '      bpmn_version,\n'
         '      result_timeout_ms,\n'
         '      status,\n'
         '      created_at,\n'
         '      sensitivity_ord,\n'
         '      org_id,\n'
         '      user_id,\n'
         '      actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1,\n'
         '      $2,\n'
         '      $3,\n'
         '      $4,\n'
         '      1,\n'
         '      CAST($5 AS integer),\n'
         "      'active',\n"
         '      $6,\n'
         '      1,\n'
         '      $7,\n'
         '      $8,\n'
         "      'sys.bpmn.seed.open-seiyaku'\n"
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $9\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.binding/open-seiyaku-amendBatchRecord-v1',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'ai.gftd.apps.openSeiyaku.amendBatchRecord',
                 'seiyaku_amend_batch',
                 0,
                 '2026-04-23T19:10:00Z',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.binding/open-seiyaku-amendBatchRecord-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id,\n'
         '      owner_did,\n'
         '      nsid,\n'
         '      bpmn_process_id,\n'
         '      bpmn_version,\n'
         '      result_timeout_ms,\n'
         '      status,\n'
         '      created_at,\n'
         '      sensitivity_ord,\n'
         '      org_id,\n'
         '      user_id,\n'
         '      actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1,\n'
         '      $2,\n'
         '      $3,\n'
         '      $4,\n'
         '      1,\n'
         '      CAST($5 AS integer),\n'
         "      'active',\n"
         '      $6,\n'
         '      1,\n'
         '      $7,\n'
         '      $8,\n'
         "      'sys.bpmn.seed.open-seiyaku'\n"
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $9\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.binding/open-seiyaku-purge-v1',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'ai.gftd.apps.openSeiyaku.purge',
                 'seiyaku_purge',
                 120000,
                 '2026-04-23T19:10:00Z',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'did:web:open-seiyaku.etzhayyim.com:manufacturing',
                 'at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.binding/open-seiyaku-purge-v1']}]

DOWN = [{'sql': '\n      DELETE FROM vertex_bpmn_lexicon_binding\n      WHERE vertex_id = $1\n    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.binding/open-seiyaku-startBatchRecord-v1']},
 {'sql': '\n      DELETE FROM vertex_bpmn_lexicon_binding\n      WHERE vertex_id = $1\n    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.binding/open-seiyaku-amendBatchRecord-v1']},
 {'sql': '\n      DELETE FROM vertex_bpmn_lexicon_binding\n      WHERE vertex_id = $1\n    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.binding/open-seiyaku-purge-v1']},
 {'sql': '\n      DELETE FROM vertex_bpmn_process_def\n      WHERE vertex_id = $1\n    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.processDef/open-seiyaku-register-batch-v1']},
 {'sql': '\n      DELETE FROM vertex_bpmn_process_def\n      WHERE vertex_id = $1\n    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.processDef/open-seiyaku-amend-batch-v1']},
 {'sql': '\n      DELETE FROM vertex_bpmn_process_def\n      WHERE vertex_id = $1\n    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/ai.gftd.apps.bpmn.processDef/open-seiyaku-purge-v1']}]


def upgrade() -> None:
    execute_bound_statements(op.get_bind(), UP)


def downgrade() -> None:
    execute_bound_statements(op.get_bind(), DOWN)
