"""Captured from Kysely migration 20260507131200_seed_agent_autonomous_dispatch_bpmn."""

from __future__ import annotations

from alembic import op

from graph_schema.db import execute_bound_statements


revision = "r_20260507131200_seed_agent_autonomous_dispatch_bpmn"
down_revision = 'r_20260507130100_seed_shosha_settle_bpmn'
branch_labels = None
depends_on = None

UP = [{'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def\n'
         '      (vertex_id, owner_did, bpmn_process_id, version, xml, xml_byte_size,\n'
         '       source_path, status, created_at, sensitivity_ord, org_id, user_id,\n'
         '       actor_id, actor_did, org_did)\n'
         '    SELECT\n'
         '      $1, $2, $3, 1,\n'
         "      $4, CAST($5 AS integer), $6, 'active',\n"
         '      $7, 1, $8, $9, $10,\n'
         "      $11, 'anon'\n"
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $12\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/agent-realworld-autonomous-dispatch-v1',
                 'did:web:bpmn.gftd.ai',
                 'agent_realworld_autonomous_dispatch',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Autonomous real-world effect dispatch — active influence path.\n'
                 '\n'
                 '  This process does not wait for per-action human approval. It requires a\n'
                 '  scoped autonomous authority ref, policy ref, payload hash match, and a\n'
                 '  supported channel task plan. Phase A dispatches email only because\n'
                 '  mailer.sendEmail is the channel worker currently present in this repo.\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_agent_realworld_autonomous_dispatch"\n'
                 '    targetNamespace="https://gftd.ai/bpmn/agent"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="agent_realworld_autonomous_dispatch" name="Agent real-world '
                 'autonomous dispatch" isExecutable="true">\n'
                 '    <bpmn:startEvent id="Start" name="effect proposal received">\n'
                 '      <bpmn:outgoing>Flow_Start_Classify</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Start_Classify" sourceRef="Start" '
                 'targetRef="Task_Classify"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Classify" name="Classify effect with autonomous '
                 'authority">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="agent.classifyRealWorldEffect"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=channel" target="channel"/>\n'
                 '          <zeebe:input source="=payload" target="payload"/>\n'
                 '          <zeebe:input source="=actionProposalId" target="actionProposalId"/>\n'
                 '          <zeebe:input source="=agentDid" target="agentDid"/>\n'
                 '          <zeebe:input source="=principalDid" target="principalDid"/>\n'
                 '          <zeebe:input source="=effectClass" target="effectClass"/>\n'
                 '          <zeebe:input source="=targetRef" target="targetRef"/>\n'
                 '          <zeebe:input source="=summary" target="summary"/>\n'
                 '          <zeebe:input source="=approvalRef" target="approvalRef"/>\n'
                 '          <zeebe:input source="=authorityRef" target="authorityRef"/>\n'
                 '          <zeebe:input source="=autonomousAuthorityRef" '
                 'target="autonomousAuthorityRef"/>\n'
                 '          <zeebe:input source="=budgetRef" target="budgetRef"/>\n'
                 '          <zeebe:output source="=realWorldEffect" target="realWorldEffect"/>\n'
                 '          <zeebe:output source="=requiresApproval" target="requiresApproval"/>\n'
                 '          <zeebe:output source="=authorityMode" target="authorityMode"/>\n'
                 '          <zeebe:output source="=blockers" target="effectBlockers"/>\n'
                 '          <zeebe:output source="=externalEffectPenalty" '
                 'target="externalEffectPenalty"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Start_Classify</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Classify_Write</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Classify_Write" sourceRef="Task_Classify" '
                 'targetRef="Task_Write"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Write" name="Record real-world effect">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_agent_realworld_effect&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="={ vertex_id: realWorldEffect.vertex_id, '
                 'action_proposal_id: realWorldEffect.action_proposal_id, agent_did: '
                 'realWorldEffect.agent_did, principal_did: realWorldEffect.principal_did, '
                 'channel: realWorldEffect.channel, effect_class: realWorldEffect.effect_class, '
                 'target_ref_hash: realWorldEffect.target_ref_hash, payload_hash: '
                 'realWorldEffect.payload_hash, summary: realWorldEffect.summary, approval_ref: '
                 'realWorldEffect.approval_ref, authority_ref: realWorldEffect.authority_ref, '
                 'budget_ref: realWorldEffect.budget_ref, dispatch_state: '
                 'realWorldEffect.dispatch_state, dispatch_receipt_ref: '
                 'realWorldEffect.dispatch_receipt_ref, observation_plan_json: '
                 'realWorldEffect.observation_plan_json, created_at: realWorldEffect.created_at, '
                 'updated_at: realWorldEffect.updated_at, sensitivity_ord: 1, actor_id: '
                 '&quot;sys.agent.autonomousDispatch&quot;, owner_did: realWorldEffect.agent_did, '
                 'org_id: realWorldEffect.agent_did, user_id: realWorldEffect.agent_did }" '
                 'target="values"/>\n'
                 '          <zeebe:input source="=&quot;agent_realworld_autonomous_dispatch&quot;" '
                 'target="_bpmnProcessId"/>\n'
                 '          <zeebe:output source="=inserted" target="effectInserted"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Classify_Write</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Write_Plan</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Write_Plan" sourceRef="Task_Write" '
                 'targetRef="Task_Plan"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Plan" name="Plan autonomous channel dispatch">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="agent.planRealWorldDispatch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=realWorldEffect" target="realWorldEffect"/>\n'
                 '          <zeebe:input source="=payload" target="payload"/>\n'
                 '          <zeebe:input source="=autonomousAuthorityRef" '
                 'target="autonomousAuthorityRef"/>\n'
                 '          <zeebe:input source="=policyRef" target="policyRef"/>\n'
                 '          <zeebe:input source="=policy" target="policy"/>\n'
                 '          <zeebe:input source="=budgetRef" target="budgetRef"/>\n'
                 '          <zeebe:input source="=&quot;autonomous&quot;" target="mode"/>\n'
                 '          <zeebe:output source="={ dispatchAllowed: dispatchAllowed, '
                 'dispatchPlanId: dispatchPlanId, blockers: blockers, channel: channel, '
                 'effectClass: effectClass, taskType: taskType, nsid: nsid, channelPayload: '
                 'channelPayload, payloadHash: payloadHash, authorityRef: authorityRef, policyRef: '
                 'policyRef, budgetRef: budgetRef, receiptExpectation: receiptExpectation }" '
                 'target="dispatchPlan"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Write_Plan</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Plan_RecordLedger</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Plan_RecordLedger" sourceRef="Task_Plan" '
                 'targetRef="Task_RecordDispatchLedger"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_RecordDispatchLedger" name="Record dispatch '
                 'ledger">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_agent_dispatch_ledger&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="={ vertex_id: dispatchPlan.dispatchPlanId, '
                 'agent_did: agentDid, dispatch_plan_id: dispatchPlan.dispatchPlanId, '
                 'realworld_effect_id: realWorldEffect.vertex_id, channel: dispatchPlan.channel, '
                 'task_type: dispatchPlan.taskType, payload_hash: dispatchPlan.payloadHash, '
                 'authority_ref: dispatchPlan.authorityRef, policy_ref: dispatchPlan.policyRef, '
                 'dispatch_state: &quot;planned&quot;, created_at: realWorldEffect.updated_at, '
                 'updated_at: realWorldEffect.updated_at, sensitivity_ord: 1, actor_id: '
                 '&quot;sys.agent.dispatchLedger&quot;, owner_did: agentDid, org_id: agentDid, '
                 'user_id: agentDid }" target="values"/>\n'
                 '          <zeebe:input source="=&quot;agent_realworld_autonomous_dispatch&quot;" '
                 'target="_bpmnProcessId"/>\n'
                 '          <zeebe:output source="=inserted" target="dispatchLedgerInserted"/>\n'
                 '          <zeebe:output source="=already_known" target="dispatchAlreadyKnown"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Plan_RecordLedger</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Ledger_Gateway</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Ledger_Gateway" '
                 'sourceRef="Task_RecordDispatchLedger" targetRef="Gateway_Dispatch"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gateway_Dispatch" name="dispatch allowed?" '
                 'default="Flow_Dispatch_Blocked">\n'
                 '      <bpmn:incoming>Flow_Ledger_Gateway</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Dispatch_Email</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Dispatch_Blocked</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_Dispatch_Email" sourceRef="Gateway_Dispatch" '
                 'targetRef="Task_SendEmail">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">=dispatchPlan.dispatchAllowed '
                 'and dispatchPlan.taskType = "mailer.sendEmail" and dispatchLedgerInserted = '
                 '1</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Dispatch_Blocked" sourceRef="Gateway_Dispatch" '
                 'targetRef="Task_AuditBlocked"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_SendEmail" name="Send autonomous email">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="mailer.sendEmail"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=dispatchPlan.channelPayload.to" target="to"/>\n'
                 '          <zeebe:input source="=dispatchPlan.channelPayload.subject" '
                 'target="subject"/>\n'
                 '          <zeebe:input source="=dispatchPlan.channelPayload.text" '
                 'target="text"/>\n'
                 '          <zeebe:input source="=dispatchPlan.channelPayload.html" '
                 'target="html"/>\n'
                 '          <zeebe:input source="=dispatchPlan.channelPayload.fromAddress" '
                 'target="fromAddress"/>\n'
                 '          <zeebe:input source="=dispatchPlan.channelPayload.replyTo" '
                 'target="replyTo"/>\n'
                 '          <zeebe:output source="={ messageId: messageId, provider: provider, '
                 'sentAt: sentAt, error: error, status: status, body: body }" '
                 'target="dispatchResult"/>\n'
                 '          <zeebe:output source="=messageId" target="dispatchReceiptRef"/>\n'
                 '          <zeebe:output source="=error" target="dispatchError"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Dispatch_Email</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Email_BuildReceipt</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Email_BuildReceipt" sourceRef="Task_SendEmail" '
                 'targetRef="Task_BuildReceiptObservation"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_BuildReceiptObservation" name="Build dispatch '
                 'receipt observation">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="agent.buildDispatchReceiptObservation"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=realWorldEffect" target="realWorldEffect"/>\n'
                 '          <zeebe:input source="=dispatchPlan" target="dispatchPlan"/>\n'
                 '          <zeebe:input source="=dispatchResult" target="dispatchResult"/>\n'
                 '          <zeebe:output source="=observation" target="receiptObservation"/>\n'
                 '          <zeebe:output source="=effectPatch" target="effectPatch"/>\n'
                 '          <zeebe:output source="=dispatchState" target="dispatchState"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Email_BuildReceipt</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_BuildReceipt_RecordEffectReceipt</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_BuildReceipt_RecordEffectReceipt" '
                 'sourceRef="Task_BuildReceiptObservation" targetRef="Task_RecordEffectReceipt"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_RecordEffectReceipt" name="Record effect dispatch '
                 'receipt">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="agent.recordDispatchReceipt"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=effectPatch" target="effectPatch"/>\n'
                 '          <zeebe:output source="=updated" target="effectReceiptUpdated"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_BuildReceipt_RecordEffectReceipt</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_RecordEffectReceipt_RecordObservation</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_RecordEffectReceipt_RecordObservation" '
                 'sourceRef="Task_RecordEffectReceipt" '
                 'targetRef="Task_RecordReceiptObservation"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_RecordReceiptObservation" name="Record dispatch '
                 'receipt observation">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_agent_observation&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=receiptObservation" target="values"/>\n'
                 '          <zeebe:input source="=&quot;agent_realworld_autonomous_dispatch&quot;" '
                 'target="_bpmnProcessId"/>\n'
                 '          <zeebe:output source="=inserted" '
                 'target="receiptObservationInserted"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_RecordEffectReceipt_RecordObservation</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_RecordObservation_Audit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_RecordObservation_Audit" '
                 'sourceRef="Task_RecordReceiptObservation" targetRef="Task_AuditSent"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditSent" name="Audit autonomous dispatch">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;agent.realWorldEffect.autonomousDispatched&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;agentDid&quot;: agentDid, '
                 '&quot;channel&quot;: dispatchPlan.channel, &quot;taskType&quot;: '
                 'dispatchPlan.taskType, &quot;dispatchPlanId&quot;: dispatchPlan.dispatchPlanId, '
                 '&quot;authorityRef&quot;: dispatchPlan.authorityRef, &quot;policyRef&quot;: '
                 'dispatchPlan.policyRef, &quot;payloadHash&quot;: dispatchPlan.payloadHash, '
                 '&quot;receiptRef&quot;: dispatchReceiptRef, &quot;dispatchState&quot;: '
                 'dispatchState, &quot;effectReceiptUpdated&quot;: effectReceiptUpdated, '
                 '&quot;observationInserted&quot;: receiptObservationInserted, &quot;error&quot;: '
                 'dispatchError }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_RecordObservation_Audit</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AuditSent_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AuditSent_End" sourceRef="Task_AuditSent" '
                 'targetRef="End_Sent"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditBlocked" name="Audit autonomous dispatch '
                 'blocked">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;agent.realWorldEffect.autonomousBlocked&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;agentDid&quot;: agentDid, '
                 '&quot;channel&quot;: channel, &quot;effectBlockers&quot;: effectBlockers, '
                 '&quot;dispatchBlockers&quot;: dispatchPlan.blockers, &quot;dispatchPlanId&quot;: '
                 'dispatchPlan.dispatchPlanId, &quot;dispatchLedgerInserted&quot;: '
                 'dispatchLedgerInserted, &quot;dispatchAlreadyKnown&quot;: dispatchAlreadyKnown, '
                 '&quot;policyRef&quot;: policyRef }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Dispatch_Blocked</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AuditBlocked_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AuditBlocked_End" sourceRef="Task_AuditBlocked" '
                 'targetRef="End_Blocked"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End_Sent" name="autonomous dispatch sent">\n'
                 '      <bpmn:incoming>Flow_AuditSent_End</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '    <bpmn:endEvent id="End_Blocked" name="autonomous dispatch blocked">\n'
                 '      <bpmn:incoming>Flow_AuditBlocked_End</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 14842,
                 '00-contracts/bpmn/ai/gftd/agent/realWorldAutonomousDispatch.bpmn',
                 '2026-05-07T13:12:00Z',
                 'did:web:bpmn.gftd.ai',
                 'did:web:bpmn.gftd.ai',
                 'sys.bpmn.seed.agent-autonomous-dispatch',
                 'did:web:bpmn.gftd.ai',
                 'at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/agent-realworld-autonomous-dispatch-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding\n'
         '      (vertex_id, owner_did, nsid, bpmn_process_id, bpmn_version,\n'
         '       result_timeout_ms, write_table_allowlist, status, created_at,\n'
         '       sensitivity_ord, org_id, user_id, actor_id, actor_did, org_did)\n'
         '    SELECT\n'
         '      $1, $2, $3, $4, 1,\n'
         "      120000, $5, 'active', $6,\n"
         "      1, $7, $8, $9, $10, 'anon'\n"
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $11\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.lexiconBinding/agent-realworld-autonomous-dispatch-v1',
                 'did:web:bpmn.gftd.ai',
                 'ai.gftd.apps.agent.planRealWorldDispatch',
                 'agent_realworld_autonomous_dispatch',
                 'vertex_agent_realworld_effect,vertex_agent_observation,vertex_agent_dispatch_ledger',
                 '2026-05-07T13:12:00Z',
                 'did:web:bpmn.gftd.ai',
                 'did:web:bpmn.gftd.ai',
                 'sys.bpmn.seed.agent-autonomous-dispatch',
                 'did:web:bpmn.gftd.ai',
                 'at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.lexiconBinding/agent-realworld-autonomous-dispatch-v1']}]

DOWN = [{'sql': '\n    DELETE FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $1\n  ',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.lexiconBinding/agent-realworld-autonomous-dispatch-v1']},
 {'sql': '\n    DELETE FROM vertex_bpmn_process_def WHERE vertex_id = $1\n  ',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/agent-realworld-autonomous-dispatch-v1']}]


def upgrade() -> None:
    execute_bound_statements(op.get_bind(), UP)


def downgrade() -> None:
    execute_bound_statements(op.get_bind(), DOWN)
