"""Captured from Kysely migration 20260428270000_fix_flight_offer_timer_bpmn_start_events."""

from __future__ import annotations

from alembic import op

from graph_schema.db import execute_bound_statements


revision = "r_20260428270000_fix_flight_offer_timer_bpmn_start_events"
down_revision = 'r_20260428270000_add_ipfs_cid_to_gyosei_source'
branch_labels = None
depends_on = None

UP = [{'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — daily cleanup of vertex_flight_offer_source_run.\n'
                 '  Default retention 90d. Also addressable via XRPC '
                 'com.etzhayyim.apps.flightOffer.cleanupRuns\n'
                 '  for ad-hoc / manual purges.\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_flight_offer_cleanup_runs"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/flight-offer"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="flight_offer_cleanup_runs" name="cleanupRuns" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.flightOffer.cleanupRuns", "version": 1, '
                 '"resultTimeoutMs": 300000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 24 hours">\n'
                 '      <bpmn:outgoing>Flow_Health_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT24H">\n'
                 '        <bpmn:timeCycle '
                 'xsi:type="bpmn:tFormalExpression">R/PT24H</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Health_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Health_Timer" sourceRef="Start_Timer" '
                 'targetRef="Task_Health"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Health_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Health"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Health" name="rw health gate">\n'
                 '      <bpmn:extensionElements><zeebe:taskDefinition '
                 'type="rw.health.probe"/></bpmn:extensionElements>\n'
                 '      '
                 '<bpmn:incoming>Flow_Health_Timer</bpmn:incoming><bpmn:incoming>Flow_Health_Manual</bpmn:incoming><bpmn:outgoing>Flow_Cleanup</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Cleanup" sourceRef="Task_Health" '
                 'targetRef="Task_Cleanup"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Cleanup" name="delete old source-run rows">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="flight.offer.cleanupRuns"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=if retentionDays != null then retentionDays else '
                 '90" target="retentionDays"/>\n'
                 '          <zeebe:output source="=deleted" target="deleted"/>\n'
                 '          <zeebe:output source="=cutoffAt" target="cutoffAt"/>\n'
                 '          <zeebe:output source="=retentionDays" target="retentionDaysOut"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      '
                 '<bpmn:incoming>Flow_Cleanup</bpmn:incoming><bpmn:outgoing>Flow_Audit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Audit" sourceRef="Task_Cleanup" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="audit cleanup">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:flight-offer.etzhayyim.com&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;flight.offer.cleanupRuns&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={deleted: deleted, cutoffAt: cutoffAt, '
                 'retentionDays: retentionDaysOut}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      '
                 '<bpmn:incoming>Flow_Audit</bpmn:incoming><bpmn:outgoing>Flow_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent '
                 'id="End"><bpmn:incoming>Flow_End</bpmn:incoming></bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 3520,
                 '00-contracts/bpmn/com/etzhayyim/flight-offer/cleanupRuns.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/flight-offer-cleanup-runs-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_lexicon_binding\n'
         '      SET result_timeout_ms = 300000\n'
         '      WHERE nsid = $1\n'
         '    ',
  'parameters': ['com.etzhayyim.apps.flightOffer.cleanupRuns']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — refreshes vertex_flight_offer_watch entries every 6 hours.\n'
                 '\n'
                 '  flight.offer.pollWatchlist primitive:\n'
                 '    - SELECTs active watch rows where next_due_at <= now\n'
                 '    - per row: _do_search() then _do_check_drop()\n'
                 '    - bumps last_polled_at + next_due_at = now + cadence_minutes\n'
                 '    - returns { watchesRead, offersWritten, alertsFired, errors, dropAlerts[] }\n'
                 '\n'
                 '  AT post fan-out for individual drop alerts is handled by the\n'
                 '  flight_offer_check_price_drop BPMN when invoked directly via XRPC.\n'
                 '  Within this poll, the alert row is written to vertex_flight_offer_alert\n'
                 '  (downstream consumers can subscribe).\n'
                 '\n'
                 '  NSID: com.etzhayyim.apps.flightOffer.pollWatchlist\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/flight-offer-poll-watchlist-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_flight_offer_poll_watchlist"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/flight-offer"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="flight_offer_poll_watchlist" name="pollWatchlist" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.flightOffer.pollWatchlist", "version": 1, '
                 '"resultTimeoutMs": 300000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 6 hours">\n'
                 '      <bpmn:outgoing>Flow_Health_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT6H">\n'
                 '        <bpmn:timeCycle '
                 'xsi:type="bpmn:tFormalExpression">R/PT6H</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Health_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Health_Timer" sourceRef="Start_Timer" '
                 'targetRef="Task_Health"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Health_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Health"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Health" name="rw health gate">\n'
                 '      <bpmn:extensionElements><zeebe:taskDefinition '
                 'type="rw.health.probe"/></bpmn:extensionElements>\n'
                 '      '
                 '<bpmn:incoming>Flow_Health_Timer</bpmn:incoming><bpmn:incoming>Flow_Health_Manual</bpmn:incoming><bpmn:outgoing>Flow_Poll</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Poll" sourceRef="Task_Health" '
                 'targetRef="Task_Poll"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Poll" name="poll watchlist">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="flight.offer.pollWatchlist"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=if limit != null then limit else 50" '
                 'target="limit"/>\n'
                 '          <zeebe:input source="=if force != null then force else false" '
                 'target="force"/>\n'
                 '          <zeebe:output source="=watchesRead" target="watchesRead"/>\n'
                 '          <zeebe:output source="=offersWritten" target="offersWritten"/>\n'
                 '          <zeebe:output source="=alertsFired" target="alertsFired"/>\n'
                 '          <zeebe:output source="=errors" target="errors"/>\n'
                 '          <zeebe:output source="=dropAlerts" target="dropAlerts"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      '
                 '<bpmn:incoming>Flow_Poll</bpmn:incoming><bpmn:outgoing>Flow_Audit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Audit" sourceRef="Task_Poll" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="audit poll">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:flight-offer.etzhayyim.com&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;flight.offer.pollWatchlist&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={watchesRead: watchesRead, offersWritten: '
                 'offersWritten, alertsFired: alertsFired, errors: errors}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      '
                 '<bpmn:incoming>Flow_Audit</bpmn:incoming><bpmn:outgoing>Flow_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent '
                 'id="End"><bpmn:incoming>Flow_End</bpmn:incoming></bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 4304,
                 '00-contracts/bpmn/com/etzhayyim/flight-offer/pollWatchlist.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/flight-offer-poll-watchlist-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_lexicon_binding\n'
         '      SET result_timeout_ms = 300000\n'
         '      WHERE nsid = $1\n'
         '    ',
  'parameters': ['com.etzhayyim.apps.flightOffer.pollWatchlist']}]

DOWN = [{'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET version = 1,\n'
         '          deployed_at = NULL,\n'
         '          deployed_zeebe_key = NULL\n'
         '      WHERE vertex_id = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/flight-offer-cleanup-runs-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_lexicon_binding\n'
         '      SET result_timeout_ms = 10000\n'
         '      WHERE nsid = $1\n'
         '    ',
  'parameters': ['com.etzhayyim.apps.flightOffer.cleanupRuns']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET version = 1,\n'
         '          deployed_at = NULL,\n'
         '          deployed_zeebe_key = NULL\n'
         '      WHERE vertex_id = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/flight-offer-poll-watchlist-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_lexicon_binding\n'
         '      SET result_timeout_ms = 10000\n'
         '      WHERE nsid = $1\n'
         '    ',
  'parameters': ['com.etzhayyim.apps.flightOffer.pollWatchlist']}]


def upgrade() -> None:
    execute_bound_statements(op.get_bind(), UP)


def downgrade() -> None:
    execute_bound_statements(op.get_bind(), DOWN)
