"""Captured from Kysely migration 20260429110000_netintel_bpmn_timer_1min."""

from __future__ import annotations

from alembic import op

from graph_schema.db import execute_bound_statements


revision = "r_20260429110000_netintel_bpmn_timer_1min"
down_revision = 'r_20260429100100_seed_hanrei_bpmn_actors'
branch_labels = None
depends_on = None

UP = [{'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml"            = $1,\n'
         '          "xml_byte_size"  = CAST($2 AS integer),\n'
         '          "version"        = 2,\n'
         '          "source_path"    = $3\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — monthly DNS/RDAP enrichment for shadow-level domains.\n'
                 '  Pulls stale domains from vertex_dns_observation, re-queries RDAP + DoH,\n'
                 '  and writes updated rows.\n'
                 '\n'
                 '  NSID: ai.gftd.apps.ingest.start (timer-triggered)\n'
                 '  Task: netintel.dns.delta\n'
                 '  Cadence: R/PT1M (every 1 minute)\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_netintel_dns_delta"\n'
                 '    targetNamespace="https://gftd.ai/bpmn/ingest/netintel"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="netintel_dns_delta" name="netintel dns delta" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "ai.gftd.apps.ingest.netintelDnsDelta", "version": 1, '
                 '"resultTimeoutMs": 3600000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 1 minute">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_P1M">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/PT1M</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer"  sourceRef="Start_Timer"  '
                 'targetRef="Task_Health"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Health"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Health" name="rw health gate">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="rw.health.probe"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Ingest</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Ingest" sourceRef="Task_Health" '
                 'targetRef="Task_Ingest"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Ingest" name="ingest dns delta">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="netintel.dns.delta"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;shadow&quot;"  target="targetTier"/>\n'
                 '          <zeebe:input source="=200"              target="batchSize"/>\n'
                 '          <zeebe:output source="=domainsRead"     target="recordsRead"/>\n'
                 '          <zeebe:output source="=rowsWritten"     target="recordsWritten"/>\n'
                 '          <zeebe:output source="=runId"           target="runId"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Ingest</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Audit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Audit" sourceRef="Task_Ingest" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="audit dns delta">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:ingest.gftd.ai&quot;"       '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;netintel.dns.delta&quot;"            '
                 'target="action"/>\n'
                 '          <zeebe:input source="={runId: runId, recordsRead: recordsRead, '
                 'recordsWritten: recordsWritten}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Audit</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_MarkCompleted</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_MarkCompleted" sourceRef="Task_Audit" '
                 'targetRef="Task_MarkCompleted"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_MarkCompleted" name="mark run completed">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ingest.run.markCompleted"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=runId"          target="runId"/>\n'
                 '          <zeebe:input source="=&quot;completed&quot;" target="status"/>\n'
                 '          <zeebe:input source="=recordsRead"    target="recordsRead"/>\n'
                 '          <zeebe:input source="=recordsWritten" target="recordsWritten"/>\n'
                 '          <zeebe:input source="=0"              target="recordsSkipped"/>\n'
                 '          <zeebe:input source="=0"              target="errorCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_MarkCompleted</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End" sourceRef="Task_MarkCompleted" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="completed">\n'
                 '      <bpmn:incoming>Flow_End</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 4636,
                 '00-contracts/bpmn/ai/gftd/ingest/netintelDnsDelta.bpmn',
                 'at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/netintel-dns-delta-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml"            = $1,\n'
         '          "xml_byte_size"  = CAST($2 AS integer),\n'
         '          "version"        = 2,\n'
         '          "source_path"    = $3\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — monthly GeoIP enrichment for shadow-level IPs.\n'
                 '  Pulls stale IPs from vertex_ip_address, re-queries GeoIP API,\n'
                 '  and writes updated rows.\n'
                 '\n'
                 '  Task: netintel.ip.enrich\n'
                 '  Cadence: R/PT1M (every 1 minute)\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_netintel_ip_enrich_delta"\n'
                 '    targetNamespace="https://gftd.ai/bpmn/ingest/netintel"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="netintel_ip_enrich_delta" name="netintel ip enrich delta" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "ai.gftd.apps.ingest.netintelIpEnrichDelta", "version": 1, '
                 '"resultTimeoutMs": 3600000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 1 minute">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_P1M">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/PT1M</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer"  sourceRef="Start_Timer"  '
                 'targetRef="Task_Health"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Health"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Health" name="rw health gate">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="rw.health.probe"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Ingest</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Ingest" sourceRef="Task_Health" '
                 'targetRef="Task_Ingest"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Ingest" name="enrich ip addresses">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="netintel.ip.enrich"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;shadow&quot;"  target="targetTier"/>\n'
                 '          <zeebe:input source="=500"              target="batchSize"/>\n'
                 '          <zeebe:output source="=ipsRead"         target="recordsRead"/>\n'
                 '          <zeebe:output source="=rowsWritten"     target="recordsWritten"/>\n'
                 '          <zeebe:output source="=runId"           target="runId"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Ingest</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Audit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Audit" sourceRef="Task_Ingest" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="audit ip enrich">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:ingest.gftd.ai&quot;"    '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;netintel.ip.enrich&quot;"         '
                 'target="action"/>\n'
                 '          <zeebe:input source="={runId: runId, recordsRead: recordsRead, '
                 'recordsWritten: recordsWritten}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Audit</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_MarkCompleted</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_MarkCompleted" sourceRef="Task_Audit" '
                 'targetRef="Task_MarkCompleted"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_MarkCompleted" name="mark run completed">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ingest.run.markCompleted"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=runId"          target="runId"/>\n'
                 '          <zeebe:input source="=&quot;completed&quot;" target="status"/>\n'
                 '          <zeebe:input source="=recordsRead"    target="recordsRead"/>\n'
                 '          <zeebe:input source="=recordsWritten" target="recordsWritten"/>\n'
                 '          <zeebe:input source="=0"              target="recordsSkipped"/>\n'
                 '          <zeebe:input source="=0"              target="errorCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_MarkCompleted</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End" sourceRef="Task_MarkCompleted" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="completed">\n'
                 '      <bpmn:incoming>Flow_End</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 4587,
                 '00-contracts/bpmn/ai/gftd/ingest/ipEnrichDelta.bpmn',
                 'at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/netintel-ip-enrich-delta-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml"            = $1,\n'
         '          "xml_byte_size"  = CAST($2 AS integer),\n'
         '          "version"        = 2,\n'
         '          "source_path"    = $3\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — monthly WHOIS snapshot for shadow-level domains.\n'
                 '  Pulls domains from vertex_dns_observation, queries WHOIS/RDAP,\n'
                 '  and writes to vertex_whois_record.\n'
                 '\n'
                 '  Task: netintel.whois.delta\n'
                 '  Cadence: R/PT1M (every 1 minute)\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_netintel_whois_delta"\n'
                 '    targetNamespace="https://gftd.ai/bpmn/ingest/netintel"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="netintel_whois_delta" name="netintel whois delta" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "ai.gftd.apps.ingest.netintelWhoisDelta", "version": 1, '
                 '"resultTimeoutMs": 3600000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 1 minute">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_P1M">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/PT1M</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer"  sourceRef="Start_Timer"  '
                 'targetRef="Task_Health"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Health"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Health" name="rw health gate">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="rw.health.probe"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Ingest</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Ingest" sourceRef="Task_Health" '
                 'targetRef="Task_Ingest"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Ingest" name="ingest whois records">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="netintel.whois.delta"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;shadow&quot;"  target="targetTier"/>\n'
                 '          <zeebe:input source="=200"              target="batchSize"/>\n'
                 '          <zeebe:output source="=domainsRead"     target="recordsRead"/>\n'
                 '          <zeebe:output source="=rowsWritten"     target="recordsWritten"/>\n'
                 '          <zeebe:output source="=runId"           target="runId"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Ingest</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Audit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Audit" sourceRef="Task_Ingest" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="audit whois delta">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:ingest.gftd.ai&quot;"  '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;netintel.whois.delta&quot;"     '
                 'target="action"/>\n'
                 '          <zeebe:input source="={runId: runId, recordsRead: recordsRead, '
                 'recordsWritten: recordsWritten}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Audit</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_MarkCompleted</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_MarkCompleted" sourceRef="Task_Audit" '
                 'targetRef="Task_MarkCompleted"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_MarkCompleted" name="mark run completed">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ingest.run.markCompleted"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=runId"          target="runId"/>\n'
                 '          <zeebe:input source="=&quot;completed&quot;" target="status"/>\n'
                 '          <zeebe:input source="=recordsRead"    target="recordsRead"/>\n'
                 '          <zeebe:input source="=recordsWritten" target="recordsWritten"/>\n'
                 '          <zeebe:input source="=0"              target="recordsSkipped"/>\n'
                 '          <zeebe:input source="=0"              target="errorCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_MarkCompleted</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End" sourceRef="Task_MarkCompleted" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="completed">\n'
                 '      <bpmn:incoming>Flow_End</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 4588,
                 '00-contracts/bpmn/ai/gftd/ingest/whoisDelta.bpmn',
                 'at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/netintel-whois-delta-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml"            = $1,\n'
         '          "xml_byte_size"  = CAST($2 AS integer),\n'
         '          "version"        = 2,\n'
         '          "source_path"    = $3\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — monthly port scan + banner grab for shadow-level IPs.\n'
                 '  Pulls IPs from vertex_ip_address, uses external proxy for scanning,\n'
                 '  and writes results to vertex_scan_result.\n'
                 '\n'
                 '  Task: netintel.scan.banner\n'
                 '  Cadence: R/PT1M (every 1 minute)\n'
                 '  Security: scanning performed via SCAN_PROXY_URL (not direct socket from '
                 'cluster)\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_netintel_scan_banner_delta"\n'
                 '    targetNamespace="https://gftd.ai/bpmn/ingest/netintel"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="netintel_scan_banner_delta" name="netintel scan banner '
                 'delta" isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "ai.gftd.apps.ingest.netintelScanBannerDelta", "version": 1, '
                 '"resultTimeoutMs": 7200000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 1 minute">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_P1M">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/PT1M</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer"  sourceRef="Start_Timer"  '
                 'targetRef="Task_Health"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Health"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Health" name="rw health gate">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="rw.health.probe"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Ingest</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Ingest" sourceRef="Task_Health" '
                 'targetRef="Task_Ingest"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Ingest" name="port scan and banner grab">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="netintel.scan.banner"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;shadow&quot;"  target="targetTier"/>\n'
                 '          <zeebe:input source="=100"              target="batchSize"/>\n'
                 '          <zeebe:output source="=ipsScanned"      target="recordsRead"/>\n'
                 '          <zeebe:output source="=rowsWritten"     target="recordsWritten"/>\n'
                 '          <zeebe:output source="=runId"           target="runId"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Ingest</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Audit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Audit" sourceRef="Task_Ingest" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="audit scan banner">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:ingest.gftd.ai&quot;"   '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;netintel.scan.banner&quot;"      '
                 'target="action"/>\n'
                 '          <zeebe:input source="={runId: runId, recordsRead: recordsRead, '
                 'recordsWritten: recordsWritten}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Audit</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_MarkCompleted</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_MarkCompleted" sourceRef="Task_Audit" '
                 'targetRef="Task_MarkCompleted"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_MarkCompleted" name="mark run completed">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ingest.run.markCompleted"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=runId"          target="runId"/>\n'
                 '          <zeebe:input source="=&quot;completed&quot;" target="status"/>\n'
                 '          <zeebe:input source="=recordsRead"    target="recordsRead"/>\n'
                 '          <zeebe:input source="=recordsWritten" target="recordsWritten"/>\n'
                 '          <zeebe:input source="=0"              target="recordsSkipped"/>\n'
                 '          <zeebe:input source="=0"              target="errorCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_MarkCompleted</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End" sourceRef="Task_MarkCompleted" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="completed">\n'
                 '      <bpmn:incoming>Flow_End</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 4718,
                 '00-contracts/bpmn/ai/gftd/ingest/scanBannerDelta.bpmn',
                 'at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/netintel-scan-banner-delta-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml"            = $1,\n'
         '          "xml_byte_size"  = CAST($2 AS integer),\n'
         '          "version"        = 2,\n'
         '          "source_path"    = $3\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — monthly TLS/HTTP fingerprinting for shadow-level hosts.\n'
                 '  Pulls domains/IPs from vertex_dns_observation + vertex_ip_address,\n'
                 '  probes TLS handshake + HTTP headers via external proxy, writes to '
                 'vertex_scan_result.\n'
                 '\n'
                 '  Task: netintel.fingerprint.delta\n'
                 '  Cadence: R/PT1M (every 1 minute)\n'
                 '  Security: probing performed via SCAN_PROXY_URL (not direct socket from '
                 'cluster)\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_netintel_fingerprint_delta"\n'
                 '    targetNamespace="https://gftd.ai/bpmn/ingest/netintel"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="netintel_fingerprint_delta" name="netintel fingerprint '
                 'delta" isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "ai.gftd.apps.ingest.netintelFingerprintDelta", "version": 1, '
                 '"resultTimeoutMs": 7200000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 1 minute">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_P1M">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/PT1M</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer"  sourceRef="Start_Timer"  '
                 'targetRef="Task_Health"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Health"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Health" name="rw health gate">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="rw.health.probe"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Ingest</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Ingest" sourceRef="Task_Health" '
                 'targetRef="Task_Ingest"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Ingest" name="tls and http fingerprint">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="netintel.fingerprint.delta"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;shadow&quot;"  target="targetTier"/>\n'
                 '          <zeebe:input source="=100"              target="batchSize"/>\n'
                 '          <zeebe:output source="=hostsProbed"     target="recordsRead"/>\n'
                 '          <zeebe:output source="=rowsWritten"     target="recordsWritten"/>\n'
                 '          <zeebe:output source="=runId"           target="runId"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Ingest</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Audit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Audit" sourceRef="Task_Ingest" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="audit fingerprint delta">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:ingest.gftd.ai&quot;"        '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;netintel.fingerprint.delta&quot;"     '
                 'target="action"/>\n'
                 '          <zeebe:input source="={runId: runId, recordsRead: recordsRead, '
                 'recordsWritten: recordsWritten}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Audit</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_MarkCompleted</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_MarkCompleted" sourceRef="Task_Audit" '
                 'targetRef="Task_MarkCompleted"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_MarkCompleted" name="mark run completed">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ingest.run.markCompleted"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=runId"          target="runId"/>\n'
                 '          <zeebe:input source="=&quot;completed&quot;" target="status"/>\n'
                 '          <zeebe:input source="=recordsRead"    target="recordsRead"/>\n'
                 '          <zeebe:input source="=recordsWritten" target="recordsWritten"/>\n'
                 '          <zeebe:input source="=0"              target="recordsSkipped"/>\n'
                 '          <zeebe:input source="=0"              target="errorCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_MarkCompleted</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End" sourceRef="Task_MarkCompleted" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="completed">\n'
                 '      <bpmn:incoming>Flow_End</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 4790,
                 '00-contracts/bpmn/ai/gftd/ingest/fingerprintDelta.bpmn',
                 'at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/netintel-fingerprint-delta-v1']}]

DOWN = [{'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET version = 1\n'
         '      WHERE vertex_id = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/netintel-dns-delta-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET version = 1\n'
         '      WHERE vertex_id = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/netintel-ip-enrich-delta-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET version = 1\n'
         '      WHERE vertex_id = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/netintel-whois-delta-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET version = 1\n'
         '      WHERE vertex_id = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/netintel-scan-banner-delta-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET version = 1\n'
         '      WHERE vertex_id = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/netintel-fingerprint-delta-v1']}]


def upgrade() -> None:
    execute_bound_statements(op.get_bind(), UP)


def downgrade() -> None:
    execute_bound_statements(op.get_bind(), DOWN)
