"""Captured from Kysely migration 20260427160000_seed_projector_bpmn_actors."""

from __future__ import annotations

from alembic import op

from graph_schema.db import execute_bound_statements


revision = "r_20260427160000_seed_projector_bpmn_actors"
down_revision = 'r_20260427150200_seed_flight_offer_phase6_bpmn'
branch_labels = None
depends_on = None

UP = [{'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id, owner_did, bpmn_process_id, version, xml, xml_byte_size,\n'
         '      source_path, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, 1,\n'
         "      $4, CAST($5 AS integer), $6, 'active',\n"
         '      $7, 1, $8, $9, $10\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $11\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-send-project-message-v1',
                 'did:web:projector.etzhayyim.com',
                 'projector_send_project_message',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  projector.sendProjectMessage — root router for /projects chat.\n'
                 '\n'
                 '  Single entry point for the yoro `/projects/{convoId}` UI. CF Worker\n'
                 '  (atproto.etzhayyim.com) receives the XRPC `com.etzhayyim.projector.sendProjectMessage`,\n'
                 '  publishes the message + variables to Zeebe, and returns 202 Accepted.\n'
                 '  Reply is delivered async via SSE / poll.\n'
                 '\n'
                 '  XOR gateway routes by leading slash command to a dedicated sub-process:\n'
                 '    /image     → projector.imageGen        (Murakumo WAI-REAL, deferred to Phase '
                 '3)\n'
                 '    /think     → projector.deepReason      (qwq-32b, deferred to Phase 3)\n'
                 '    /explore   → projector.treeOfThoughts  (Phase 2, ToT)\n'
                 '    /consistent→ projector.selfConsistency (Phase 2, SC)\n'
                 '    /reflect   → projector.reflexionWrite  (writes episodic memory only)\n'
                 '    default    → projector.agentLoop       (Phase 1, LangGraph ReAct + CoT + '
                 'Reflexion)\n'
                 '\n'
                 '  NSID:      com.etzhayyim.apps.projector.sendProjectMessage\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-send-project-message-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_projector_send_project_message"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/projector"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="projector_send_project_message" name="projector '
                 'sendProjectMessage" isExecutable="true">\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.projector.sendProjectMessage", "version": 1, '
                 '"resultTimeoutMs": 60000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start" name="message in">\n'
                 '      <bpmn:outgoing>Flow_ToParse</bpmn:outgoing>\n'
                 '      <bpmn:messageEventDefinition id="Msg_Send" '
                 'messageRef="Message_sendProjectMessage"/>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToParse" sourceRef="Start" '
                 'targetRef="Task_ParseCommand"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ParseCommand" name="parse leading slash '
                 'command">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="projector.command.parse"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=text" target="text"/>\n'
                 '          <zeebe:output source="=command" target="command"/>\n'
                 '          <zeebe:output source="=argText" target="argText"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ToParse</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ToRouter</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToRouter" sourceRef="Task_ParseCommand" '
                 'targetRef="Gateway_Command"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gateway_Command" name="route by command" '
                 'default="Flow_Default">\n'
                 '      <bpmn:incoming>Flow_ToRouter</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Explore</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Consistent</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Reflect</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Image</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Think</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Default</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_Explore" sourceRef="Gateway_Command" '
                 'targetRef="Call_TreeOfThoughts">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=command = '
                 '"/explore"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Consistent" sourceRef="Gateway_Command" '
                 'targetRef="Call_SelfConsistency">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=command = '
                 '"/consistent"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Reflect" sourceRef="Gateway_Command" '
                 'targetRef="Task_ReflexionWrite">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=command = '
                 '"/reflect"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Image" sourceRef="Gateway_Command" '
                 'targetRef="Task_DeferImage">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=command = '
                 '"/image"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Think" sourceRef="Gateway_Command" '
                 'targetRef="Task_DeferThink">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=command = '
                 '"/think"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Default" sourceRef="Gateway_Command" '
                 'targetRef="Call_AgentLoop"/>\n'
                 '\n'
                 '    <bpmn:callActivity id="Call_AgentLoop" name="agentLoop (LangGraph ReAct)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:calledElement processId="projector_agent_loop" '
                 'propagateAllChildVariables="true"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Default</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AgentToPersist</bpmn:outgoing>\n'
                 '    </bpmn:callActivity>\n'
                 '    <bpmn:sequenceFlow id="Flow_AgentToPersist" sourceRef="Call_AgentLoop" '
                 'targetRef="Task_PersistReply"/>\n'
                 '\n'
                 '    <bpmn:callActivity id="Call_TreeOfThoughts" name="exploreThoughts (LangGraph '
                 'ToT)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:calledElement processId="projector_tree_of_thoughts" '
                 'propagateAllChildVariables="true"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Explore</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_TotToPersist</bpmn:outgoing>\n'
                 '    </bpmn:callActivity>\n'
                 '    <bpmn:sequenceFlow id="Flow_TotToPersist" sourceRef="Call_TreeOfThoughts" '
                 'targetRef="Task_PersistReply"/>\n'
                 '\n'
                 '    <bpmn:callActivity id="Call_SelfConsistency" name="consistentAnswer '
                 '(LangGraph SC)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:calledElement processId="projector_self_consistency" '
                 'propagateAllChildVariables="true"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Consistent</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ScToPersist</bpmn:outgoing>\n'
                 '    </bpmn:callActivity>\n'
                 '    <bpmn:sequenceFlow id="Flow_ScToPersist" sourceRef="Call_SelfConsistency" '
                 'targetRef="Task_PersistReply"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ReflexionWrite" name="reflexion write (episodic '
                 'memory)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="projector.reflexion.write"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=convoId" target="convoId"/>\n'
                 '          <zeebe:input source="=callerDid" target="callerDid"/>\n'
                 '          <zeebe:input source="=argText" target="lessonText"/>\n'
                 '          <zeebe:output source="=reply" target="reply"/>\n'
                 '          <zeebe:output source="=rkey" target="reflexionRkey"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Reflect</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ReflectToPersist</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ReflectToPersist" '
                 'sourceRef="Task_ReflexionWrite" targetRef="Task_PersistReply"/>\n'
                 '\n'
                 '    <!-- /image and /think are deferred to Phase 3; for now we route them\n'
                 '         back to the default agentLoop with a note in the reply. The CF\n'
                 '         Worker can keep handling these directly while BPMN matures. -->\n'
                 '    <bpmn:serviceTask id="Task_DeferImage" name="defer /image to CF direct">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="projector.command.deferred"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;/image&quot;" target="command"/>\n'
                 '          <zeebe:output source="=reply" target="reply"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Image</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_DeferToPersist1</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_DeferToPersist1" sourceRef="Task_DeferImage" '
                 'targetRef="Task_PersistReply"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_DeferThink" name="defer /think to CF direct">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="projector.command.deferred"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;/think&quot;" target="command"/>\n'
                 '          <zeebe:output source="=reply" target="reply"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Think</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_DeferToPersist2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_DeferToPersist2" sourceRef="Task_DeferThink" '
                 'targetRef="Task_PersistReply"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_PersistReply" name="persist reply + OCEL '
                 'flow.completed">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="projector.persist.message"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=convoId" target="convoId"/>\n'
                 '          <zeebe:input source="=callerDid" target="callerDid"/>\n'
                 '          <zeebe:input source="=reply" target="reply"/>\n'
                 '          <zeebe:input source="=command" target="command"/>\n'
                 '          <zeebe:output source="=rkey" target="replyRkey"/>\n'
                 '          <zeebe:output source="=uri" target="replyUri"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_AgentToPersist</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_TotToPersist</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_ScToPersist</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_ReflectToPersist</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_DeferToPersist1</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_DeferToPersist2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ToAudit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToAudit" sourceRef="Task_PersistReply" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit projector message audit">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;com.etzhayyim.apps.projector.sendProjectMessage.completed&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;convoId&quot;: convoId, '
                 '&quot;callerDid&quot;: callerDid, &quot;command&quot;: command, '
                 '&quot;replyUri&quot;: replyUri, &quot;replyRkey&quot;: replyRkey }" '
                 'target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ToAudit</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ToEnd</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToEnd" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="reply emitted">\n'
                 '      <bpmn:incoming>Flow_ToEnd</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '\n'
                 '  <bpmn:message id="Message_sendProjectMessage" '
                 'name="com.etzhayyim.apps.projector.sendProjectMessage">\n'
                 '    <bpmn:extensionElements>\n'
                 '      <zeebe:subscription correlationKey="=convoId"/>\n'
                 '    </bpmn:extensionElements>\n'
                 '  </bpmn:message>\n'
                 '</bpmn:definitions>\n',
                 10508,
                 '00-contracts/bpmn/com/etzhayyim/projector/sendProjectMessage.bpmn',
                 '2026-04-27T16:00:00Z',
                 'did:web:projector.etzhayyim.com',
                 'did:web:projector.etzhayyim.com',
                 'sys.bpmn.seed.projector',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-send-project-message-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id, owner_did, bpmn_process_id, version, xml, xml_byte_size,\n'
         '      source_path, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, 1,\n'
         "      $4, CAST($5 AS integer), $6, 'active',\n"
         '      $7, 1, $8, $9, $10\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $11\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-agent-loop-v1',
                 'did:web:projector.etzhayyim.com',
                 'projector_agent_loop',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  projector.agentLoop — Camunda 8.9 agentic pattern: AI Agent connector +\n'
                 '  ad-hoc sub-process. The single serviceTask `Task_AgentLoop` runs a\n'
                 '  LangGraph ReAct StateGraph internally; the BPMN layer treats it as the\n'
                 '  AI Agent container. Tools are loaded dynamically from project members\n'
                 '  (MCP discovery) inside the LangGraph node — they are NOT modeled as\n'
                 '  BPMN tasks because the tool set is per-project and changes at runtime.\n'
                 '\n'
                 '  CoT + Reflexion are folded into the agentLoop:\n'
                 '    - Reflexion: Task_ReflexionLoad reads past episodes from RisingWave\n'
                 '      and injects them into the system prompt (no LLM call here).\n'
                 '    - CoT: the system prompt instructs the LLM to emit '
                 '<reasoning>...</reasoning>;\n'
                 '      the loop captures it into vars.reasoning.\n'
                 '\n'
                 '  NSID:      com.etzhayyim.apps.projector.agentLoop\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-agent-loop-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_projector_agent_loop"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/projector"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="projector_agent_loop" name="projector agentLoop" '
                 'isExecutable="true">\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.projector.agentLoop", "version": 1, '
                 '"resultTimeoutMs": 60000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start" name="loop in">\n'
                 '      <bpmn:outgoing>Flow_ToReflexion</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToReflexion" sourceRef="Start" '
                 'targetRef="Task_ReflexionLoad"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ReflexionLoad" name="reflexion load (episodic '
                 'memory)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="projector.reflexion.load"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=convoId" target="convoId"/>\n'
                 '          <zeebe:input source="=callerDid" target="callerDid"/>\n'
                 '          <zeebe:output source="=memories" target="reflexionMemory"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ToReflexion</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ToHistory</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToHistory" sourceRef="Task_ReflexionLoad" '
                 'targetRef="Task_LoadHistory"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_LoadHistory" name="load chat history">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_repo_record&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=&quot;collection = %s AND repo = %s&quot;" '
                 'target="whereExpr"/>\n'
                 '          <zeebe:input source="=[&quot;com.etzhayyim.convo.message&quot;, callerDid]" '
                 'target="whereParams"/>\n'
                 '          <zeebe:input source="=&quot;value_json,created_at&quot;" '
                 'target="columns"/>\n'
                 '          <zeebe:input source="=&quot;ts_ms DESC&quot;" target="orderBy"/>\n'
                 '          <zeebe:input source="=20" target="limit"/>\n'
                 '          <zeebe:output source="=rows" target="historyRows"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ToHistory</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ToTools</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToTools" sourceRef="Task_LoadHistory" '
                 'targetRef="Task_DiscoverTools"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_DiscoverTools" name="discover member MCP tools">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="projector.tools.discover"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=convoId" target="convoId"/>\n'
                 '          <zeebe:output source="=tools" target="memberTools"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ToTools</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ToAgent</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToAgent" sourceRef="Task_DiscoverTools" '
                 'targetRef="Task_AgentLoop"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AgentLoop" name="LangGraph ReAct (CoT + tools)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="projector.agent.loop"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=convoId" target="convoId"/>\n'
                 '          <zeebe:input source="=callerDid" target="callerDid"/>\n'
                 '          <zeebe:input source="=text" target="userText"/>\n'
                 '          <zeebe:input source="=reflexionMemory" target="reflexionMemory"/>\n'
                 '          <zeebe:input source="=historyRows" target="historyRows"/>\n'
                 '          <zeebe:input source="=memberTools" target="memberTools"/>\n'
                 '          <zeebe:input source="=&quot;fast&quot;" target="tier"/>\n'
                 '          <zeebe:input source="=8" target="maxIterations"/>\n'
                 '          <zeebe:output source="=reply" target="reply"/>\n'
                 '          <zeebe:output source="=reasoning" target="reasoning"/>\n'
                 '          <zeebe:output source="=toolsCalled" target="toolsCalled"/>\n'
                 '          <zeebe:output source="=iterations" target="iterations"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ToAgent</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ToEnd</bpmn:outgoing>\n'
                 '      <!-- Camunda agentic pattern #4: guardrail interrupt. The LangGraph\n'
                 '           guardrail node returns {ok:false, reason} on policy violation\n'
                 '           and the primitive raises an error matching Error_GuardrailDenied\n'
                 '           below, which the boundary event catches. -->\n'
                 '    </bpmn:serviceTask>\n'
                 '\n'
                 '    <bpmn:boundaryEvent id="BE_GuardrailDenied" name="guardrail denied" '
                 'attachedToRef="Task_AgentLoop">\n'
                 '      <bpmn:outgoing>Flow_GuardrailToEnd</bpmn:outgoing>\n'
                 '      <bpmn:errorEventDefinition errorRef="Error_GuardrailDenied"/>\n'
                 '    </bpmn:boundaryEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_GuardrailToEnd" sourceRef="BE_GuardrailDenied" '
                 'targetRef="EndDenied"/>\n'
                 '    <bpmn:endEvent id="EndDenied" name="denied">\n'
                 '      <bpmn:incoming>Flow_GuardrailToEnd</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_ToEnd" sourceRef="Task_AgentLoop" '
                 'targetRef="End"/>\n'
                 '    <bpmn:endEvent id="End" name="reply ready">\n'
                 '      <bpmn:incoming>Flow_ToEnd</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '\n'
                 '  <bpmn:error id="Error_GuardrailDenied" name="agent.guardrail.denied" '
                 'errorCode="agent.guardrail.denied"/>\n'
                 '</bpmn:definitions>\n',
                 6344,
                 '00-contracts/bpmn/com/etzhayyim/projector/agentLoop.bpmn',
                 '2026-04-27T16:00:00Z',
                 'did:web:projector.etzhayyim.com',
                 'did:web:projector.etzhayyim.com',
                 'sys.bpmn.seed.projector',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-agent-loop-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id, owner_did, bpmn_process_id, version, xml, xml_byte_size,\n'
         '      source_path, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, 1,\n'
         "      $4, CAST($5 AS integer), $6, 'active',\n"
         '      $7, 1, $8, $9, $10\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $11\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-tree-of-thoughts-v1',
                 'did:web:projector.etzhayyim.com',
                 'projector_tree_of_thoughts',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  projector.treeOfThoughts (ToT, Yao et al. 2023) — explore N candidate\n'
                 '  thoughts, self-evaluate each, rank, and emit the best. Implemented as\n'
                 '  one LangGraph StateGraph in `projector.tot.expand`. The BPMN layer\n'
                 '  exists so the OCEL audit (`tot.thought.expanded` × N + '
                 '`tot.thought.evaluated`\n'
                 '  + `tot.thought.ranked`) sits at the same boundary as every other\n'
                 '  projector flow.\n'
                 '\n'
                 '  NSID:      com.etzhayyim.apps.projector.treeOfThoughts\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-tree-of-thoughts-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_projector_tree_of_thoughts"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/projector"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="projector_tree_of_thoughts" name="projector treeOfThoughts" '
                 'isExecutable="true">\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.projector.treeOfThoughts", "version": 1, '
                 '"resultTimeoutMs": 90000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start" name="explore">\n'
                 '      <bpmn:outgoing>Flow_ToExpand</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToExpand" sourceRef="Start" '
                 'targetRef="Task_TotExpand"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_TotExpand" name="LangGraph ToT (expand → evaluate '
                 '→ rank)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="projector.tot.expand"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=convoId" target="convoId"/>\n'
                 '          <zeebe:input source="=callerDid" target="callerDid"/>\n'
                 '          <zeebe:input source="=argText" target="question"/>\n'
                 '          <zeebe:input source="=4" target="branchCount"/>\n'
                 '          <zeebe:input source="=&quot;classifier&quot;" target="tier"/>\n'
                 '          <zeebe:output source="=reply" target="reply"/>\n'
                 '          <zeebe:output source="=approaches" target="approaches"/>\n'
                 '          <zeebe:output source="=scores" target="scores"/>\n'
                 '          <zeebe:output source="=bestIndex" target="bestIndex"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ToExpand</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ToEnd</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToEnd" sourceRef="Task_TotExpand" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="best path picked">\n'
                 '      <bpmn:incoming>Flow_ToEnd</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 2592,
                 '00-contracts/bpmn/com/etzhayyim/projector/treeOfThoughts.bpmn',
                 '2026-04-27T16:00:00Z',
                 'did:web:projector.etzhayyim.com',
                 'did:web:projector.etzhayyim.com',
                 'sys.bpmn.seed.projector',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-tree-of-thoughts-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id, owner_did, bpmn_process_id, version, xml, xml_byte_size,\n'
         '      source_path, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, 1,\n'
         "      $4, CAST($5 AS integer), $6, 'active',\n"
         '      $7, 1, $8, $9, $10\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $11\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-self-consistency-v1',
                 'did:web:projector.etzhayyim.com',
                 'projector_self_consistency',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  projector.selfConsistency (Wang et al. 2022) — sample N parallel CoT\n'
                 "  paths at temperature 0.7, extract each path's final answer, take the\n"
                 '  majority vote. Implemented inside `projector.sc.parallel` using\n'
                 '  LangGraph + asyncio.gather; BPMN keeps the OCEL boundary (one\n'
                 '  `sc.path.sampled` × N + one `sc.vote.tallied`).\n'
                 '\n'
                 '  NSID:      com.etzhayyim.apps.projector.selfConsistency\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-self-consistency-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_projector_self_consistency"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/projector"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="projector_self_consistency" name="projector selfConsistency" '
                 'isExecutable="true">\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.projector.selfConsistency", "version": 1, '
                 '"resultTimeoutMs": 90000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start" name="consistent">\n'
                 '      <bpmn:outgoing>Flow_ToSample</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToSample" sourceRef="Start" '
                 'targetRef="Task_ScParallel"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ScParallel" name="LangGraph SC (parallel sample → '
                 'vote)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="projector.sc.parallel"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=convoId" target="convoId"/>\n'
                 '          <zeebe:input source="=callerDid" target="callerDid"/>\n'
                 '          <zeebe:input source="=argText" target="question"/>\n'
                 '          <zeebe:input source="=5" target="pathCount"/>\n'
                 '          <zeebe:input source="=0.7" target="temperature"/>\n'
                 '          <zeebe:input source="=&quot;fast&quot;" target="tier"/>\n'
                 '          <zeebe:output source="=reply" target="reply"/>\n'
                 '          <zeebe:output source="=answer" target="answer"/>\n'
                 '          <zeebe:output source="=paths" target="paths"/>\n'
                 '          <zeebe:output source="=tally" target="tally"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ToSample</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ToEnd</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToEnd" sourceRef="Task_ScParallel" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="majority chosen">\n'
                 '      <bpmn:incoming>Flow_ToEnd</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 2573,
                 '00-contracts/bpmn/com/etzhayyim/projector/selfConsistency.bpmn',
                 '2026-04-27T16:00:00Z',
                 'did:web:projector.etzhayyim.com',
                 'did:web:projector.etzhayyim.com',
                 'sys.bpmn.seed.projector',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-self-consistency-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id, owner_did, nsid, bpmn_process_id, bpmn_version,\n'
         '      result_timeout_ms, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, $4, 1,\n'
         "      CAST($5 AS integer), 'active',\n"
         '      $6, 1, $7, $8, $9\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $10\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/projector-sendProjectMessage-v1',
                 'did:web:projector.etzhayyim.com',
                 'com.etzhayyim.apps.projector.sendProjectMessage',
                 'projector_send_project_message',
                 60000,
                 '2026-04-27T16:00:00Z',
                 'did:web:projector.etzhayyim.com',
                 'did:web:projector.etzhayyim.com',
                 'sys.bpmn.seed.projector',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/projector-sendProjectMessage-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id, owner_did, nsid, bpmn_process_id, bpmn_version,\n'
         '      result_timeout_ms, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, $4, 1,\n'
         "      CAST($5 AS integer), 'active',\n"
         '      $6, 1, $7, $8, $9\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $10\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/projector-agentLoop-v1',
                 'did:web:projector.etzhayyim.com',
                 'com.etzhayyim.apps.projector.agentLoop',
                 'projector_agent_loop',
                 60000,
                 '2026-04-27T16:00:00Z',
                 'did:web:projector.etzhayyim.com',
                 'did:web:projector.etzhayyim.com',
                 'sys.bpmn.seed.projector',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/projector-agentLoop-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id, owner_did, nsid, bpmn_process_id, bpmn_version,\n'
         '      result_timeout_ms, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, $4, 1,\n'
         "      CAST($5 AS integer), 'active',\n"
         '      $6, 1, $7, $8, $9\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $10\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/projector-treeOfThoughts-v1',
                 'did:web:projector.etzhayyim.com',
                 'com.etzhayyim.apps.projector.treeOfThoughts',
                 'projector_tree_of_thoughts',
                 90000,
                 '2026-04-27T16:00:00Z',
                 'did:web:projector.etzhayyim.com',
                 'did:web:projector.etzhayyim.com',
                 'sys.bpmn.seed.projector',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/projector-treeOfThoughts-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id, owner_did, nsid, bpmn_process_id, bpmn_version,\n'
         '      result_timeout_ms, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, $4, 1,\n'
         "      CAST($5 AS integer), 'active',\n"
         '      $6, 1, $7, $8, $9\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $10\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/projector-selfConsistency-v1',
                 'did:web:projector.etzhayyim.com',
                 'com.etzhayyim.apps.projector.selfConsistency',
                 'projector_self_consistency',
                 90000,
                 '2026-04-27T16:00:00Z',
                 'did:web:projector.etzhayyim.com',
                 'did:web:projector.etzhayyim.com',
                 'sys.bpmn.seed.projector',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/projector-selfConsistency-v1']}]

DOWN = [{'sql': 'DELETE FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/projector-sendProjectMessage-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/projector-agentLoop-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/projector-treeOfThoughts-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/projector-selfConsistency-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_process_def WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-send-project-message-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_process_def WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-agent-loop-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_process_def WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-tree-of-thoughts-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_process_def WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/projector-self-consistency-v1']}]


def upgrade() -> None:
    execute_bound_statements(op.get_bind(), UP)


def downgrade() -> None:
    execute_bound_statements(op.get_bind(), DOWN)
