"""Captured from Kysely migration 20260428280000_fix_maps_timer_bpmn_start_events."""

from __future__ import annotations

from alembic import op

from graph_schema.db import execute_bound_statements


revision = "r_20260428280000_fix_maps_timer_bpmn_start_events"
down_revision = 'r_20260428270000_fix_flight_offer_timer_bpmn_start_events'
branch_labels = None
depends_on = None

UP = [{'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — advances the maps coverage frontier every 2 minutes.\n'
                 '\n'
                 '  Pipeline (ADR-0056 generic primitives, no custom task type):\n'
                 '\n'
                 '    1. generic.db.select     — top gap from view_maps_coverage_gap_ranked\n'
                 '    2. generic.http.fetch    — POST to '
                 'dispatcher.etzhayyim.com/xrpc/app.etzhayyim.apps.maps.advanceCoverage\n'
                 '                                (the XRPC handler runs createCollectionJob + '
                 'bumps last_fetched_at)\n'
                 '    3. generic.audit.emit    — OCEL 2.0 event for coverage.advance\n'
                 '\n'
                 '  Why timer-start (not subscribeRepos): coverage frontier advance is a '
                 'scheduled\n'
                 '  sweep, not a reaction to incoming AT commits. Keeping it in BPMN rather than\n'
                 '  a heartbeat cron retires the cron alarm per ADR-0056 §"Timer-start BPMN".\n'
                 '\n'
                 '  NSID derivation (sync-bpmn-actors.py convention):\n'
                 '    path = 00-contracts/bpmn/ai/gftd/maps/advanceCoverage.bpmn\n'
                 '    NSID = app.etzhayyim.apps.maps.advanceCoverage\n'
                 '    vertex_id = '
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-advance-coverage-v1\n'
                 '\n'
                 "  Timer-start processes get no lexicon binding row — they fire on Zeebe's\n"
                 '  schedule, not XRPC. The XRPC NSID `app.etzhayyim.apps.maps.advanceCoverage`\n'
                 '  above is served by maps-ui Worker directly (see collection-commands.ts).\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_maps_advance_coverage"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/maps"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="maps_advance_coverage" name="maps coverage advance" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "app.etzhayyim.apps.maps.advanceCoverage", "version": 1, '
                 '"resultTimeoutMs": 30000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 2 minutes">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT2M">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/PT1M</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer" sourceRef="Start_Timer" '
                 'targetRef="Task_PickGap"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_PickGap"/>\n'
                 '\n'
                 '    <!-- Step 1 — pick top-1 gap via ranked view (UDF-backed) -->\n'
                 '    <bpmn:serviceTask id="Task_PickGap" name="pick top coverage gap">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;mv_maps_coverage_gap_ranked&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=&quot;vertex_id, source_did, label, '
                 'collected_count, world_total, gap_score, hours_since_fetch&quot;" '
                 'target="columns"/>\n'
                 '          <zeebe:input source="=1"                                         '
                 'target="limit"/>\n'
                 '          <zeebe:input source="=&quot;gap_score DESC&quot;"                '
                 'target="orderBy"/>\n'
                 '          <zeebe:input source="=&quot;gap_score &gt; 0.0&quot;"            '
                 'target="where"/>\n'
                 '          <zeebe:output source="=rows"     target="gapRows"/>\n'
                 '          <zeebe:output source="=rowCount" target="gapCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_PickGap" '
                 'targetRef="Gateway_HasGap"/>\n'
                 '\n'
                 '    <!-- Bail early if nothing to do -->\n'
                 '    <bpmn:exclusiveGateway id="Gateway_HasGap" name="gap found?">\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_HasGap</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_NoGap</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_HasGap" sourceRef="Gateway_HasGap" '
                 'targetRef="Task_Advance">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression"\n'
                 '                                '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">=gapCount &gt; '
                 '0</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_NoGap" sourceRef="Gateway_HasGap" '
                 'targetRef="End">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression"\n'
                 '                                '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">=gapCount &lt;= '
                 '0</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '\n'
                 '    <!-- Step 2 — call the maps Worker XRPC to actually advance -->\n'
                 '    <bpmn:serviceTask id="Task_Advance" name="advanceCoverage XRPC">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.http.fetch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;https://maps.etzhayyim.com/xrpc/app.etzhayyim.apps.maps.advanceCoverage&quot;" '
                 'target="url"/>\n'
                 '          <zeebe:input source="=&quot;POST&quot;"                           '
                 'target="method"/>\n'
                 '          <zeebe:input source="=&quot;application/json&quot;"               '
                 'target="contentType"/>\n'
                 '          <zeebe:input source="={ &quot;limit&quot;: 1, &quot;sourceDid&quot;: '
                 'gapRows[0].source_did, &quot;label&quot;: gapRows[0].label }" target="body"/>\n'
                 '          <zeebe:input source="=15000"                                     '
                 'target="timeoutMs"/>\n'
                 '          <zeebe:output source="=status"   target="advanceStatus"/>\n'
                 '          <zeebe:output source="=bodyJson" target="advanceResult"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_HasGap</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_Advance" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <!-- Step 3 — OCEL audit emit -->\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit coverage.advance OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;app.etzhayyim.apps.maps.coverage.advance&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;sourceDid&quot;: gapRows[0].source_did, '
                 '&quot;label&quot;: gapRows[0].label, &quot;gapScore&quot;: gapRows[0].gap_score, '
                 '&quot;collected&quot;: gapRows[0].collected_count, &quot;worldTotal&quot;: '
                 'gapRows[0].world_total, &quot;status&quot;: advanceStatus }" '
                 'target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_4</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_4" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_4</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_NoGap</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 6886,
                 '00-contracts/bpmn/ai/gftd/maps/advanceCoverage.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-advance-coverage-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — triggers maps-bulk-ingest-ferry-routes K8s pod every 7d.\n'
                 '  Resident dumper queries OSM Overpass for relation[route=ferry] across 7\n'
                 '  continent bboxes + ferry_terminal / harbour nodes, writes parquet shards\n'
                 '  to B2, and INSERTs into RisingWave vertex_spatial as SeaRoute / Port.\n'
                 '  ODbL license.\n'
                 '\n'
                 '  NSID: app.etzhayyim.apps.maps.bulkRefreshFerryRoutes\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-ferry-routes-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_maps_bulk_refresh_ferry_routes"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/maps"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="maps_bulk_refresh_ferry_routes" name="maps bulk refresh '
                 'ferry routes" isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "app.etzhayyim.apps.maps.bulkRefreshFerryRoutes", "version": 1, '
                 '"resultTimeoutMs": 600000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 7 days">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_P7D">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/P7D</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer" sourceRef="Start_Timer" '
                 'targetRef="Task_Trigger"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Trigger"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Trigger" name="POST /trigger to ferry-routes '
                 'dumper pod">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.http.fetch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;http://bulk-ingest-ferry-routes.maps-bulk-ingest.svc.cluster.local:8080/trigger&quot;" '
                 'target="url"/>\n'
                 '          <zeebe:input source="=&quot;POST&quot;"                '
                 'target="method"/>\n'
                 '          <zeebe:input source="=&quot;application/json&quot;"    '
                 'target="contentType"/>\n'
                 '          <zeebe:input source="={}"                              '
                 'target="body"/>\n'
                 '          <zeebe:input source="=30000"                           '
                 'target="timeoutMs"/>\n'
                 '          <zeebe:output source="=status"   target="triggerStatus"/>\n'
                 '          <zeebe:output source="=bodyJson" target="triggerResult"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Trigger" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit bulk.refresh OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;app.etzhayyim.apps.maps.bulk.refresh.triggered&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;source&quot;: &quot;ferry-routes&quot;, '
                 '&quot;status&quot;: triggerStatus, &quot;startedAt&quot;: '
                 'triggerResult.started_at }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 3765,
                 '00-contracts/bpmn/ai/gftd/maps/bulkRefreshFerryRoutes.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-ferry-routes-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — triggers maps-bulk-ingest-geonames K8s pod every 24h.\n'
                 '  Resident dumper downloads geonames.org/export/dump/{DATASET}.zip,\n'
                 '  parses TSV, writes parquet shards to B2, INSERTs into RisingWave\n'
                 '  vertex_spatial.\n'
                 '\n'
                 '  NSID: app.etzhayyim.apps.maps.bulkRefreshGeonames\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-geonames-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_maps_bulk_refresh_geonames"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/maps"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="maps_bulk_refresh_geonames" name="maps bulk refresh '
                 'geonames" isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "app.etzhayyim.apps.maps.bulkRefreshGeonames", "version": 1, '
                 '"resultTimeoutMs": 600000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 24 hours">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT24H">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/PT24H</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer" sourceRef="Start_Timer" '
                 'targetRef="Task_Trigger"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Trigger"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Trigger" name="POST /trigger to dumper pod">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.http.fetch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;http://bulk-ingest-geonames.maps-bulk-ingest.svc.cluster.local:8080/trigger&quot;" '
                 'target="url"/>\n'
                 '          <zeebe:input source="=&quot;POST&quot;"                '
                 'target="method"/>\n'
                 '          <zeebe:input source="=&quot;application/json&quot;"    '
                 'target="contentType"/>\n'
                 '          <zeebe:input source="={}"                              '
                 'target="body"/>\n'
                 '          <zeebe:input source="=30000"                           '
                 'target="timeoutMs"/>\n'
                 '          <zeebe:output source="=status"   target="triggerStatus"/>\n'
                 '          <zeebe:output source="=bodyJson" target="triggerResult"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Trigger" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit bulk.refresh OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;app.etzhayyim.apps.maps.bulk.refresh.triggered&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;source&quot;: &quot;geonames&quot;, '
                 '&quot;status&quot;: triggerStatus, &quot;startedAt&quot;: '
                 'triggerResult.started_at }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 3641,
                 '00-contracts/bpmn/ai/gftd/maps/bulkRefreshGeonames.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-geonames-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — triggers maps-bulk-ingest-gtfs-jp K8s pod every 24h.\n'
                 '  Resident dumper downloads each GTFS-JP feed (zip) listed in its feed\n'
                 '  index, parses routes/stops/trips/stop_times/calendar, writes parquet\n'
                 '  shards to B2, INSERTs into RisingWave vertex_spatial as\n'
                 '  Railway / BusRoute / Station / BusStop with timetable summary in props.\n'
                 '\n'
                 '  NSID: app.etzhayyim.apps.maps.bulkRefreshGtfsJp\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-gtfs-jp-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_maps_bulk_refresh_gtfs_jp"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/maps"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="maps_bulk_refresh_gtfs_jp" name="maps bulk refresh gtfs jp" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "app.etzhayyim.apps.maps.bulkRefreshGtfsJp", "version": 1, '
                 '"resultTimeoutMs": 600000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 24 hours">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT24H">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/PT24H</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer" sourceRef="Start_Timer" '
                 'targetRef="Task_Trigger"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Trigger"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Trigger" name="POST /trigger to gtfs-jp dumper '
                 'pod">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.http.fetch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;http://bulk-ingest-gtfs-jp.maps-bulk-ingest.svc.cluster.local:8080/trigger&quot;" '
                 'target="url"/>\n'
                 '          <zeebe:input source="=&quot;POST&quot;"                '
                 'target="method"/>\n'
                 '          <zeebe:input source="=&quot;application/json&quot;"    '
                 'target="contentType"/>\n'
                 '          <zeebe:input source="={}"                              '
                 'target="body"/>\n'
                 '          <zeebe:input source="=30000"                           '
                 'target="timeoutMs"/>\n'
                 '          <zeebe:output source="=status"   target="triggerStatus"/>\n'
                 '          <zeebe:output source="=bodyJson" target="triggerResult"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Trigger" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit bulk.refresh OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;app.etzhayyim.apps.maps.bulk.refresh.triggered&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;source&quot;: &quot;gtfs-jp&quot;, '
                 '&quot;status&quot;: triggerStatus, &quot;startedAt&quot;: '
                 'triggerResult.started_at }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 3759,
                 '00-contracts/bpmn/ai/gftd/maps/bulkRefreshGtfsJp.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-gtfs-jp-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — triggers maps-bulk-ingest-openflights K8s pod every 7d.\n'
                 '  Resident dumper downloads OpenFlights airports.dat / routes.dat /\n'
                 '  airlines.dat (ODbL) and INSERTs ~7K Airports + ~67K AirRoutes into\n'
                 '  RisingWave vertex_spatial. Route midpoint is the lat/lng anchor;\n'
                 '  src/dst metadata lives in props JSON.\n'
                 '\n'
                 '  NSID: app.etzhayyim.apps.maps.bulkRefreshOpenflights\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-openflights-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_maps_bulk_refresh_openflights"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/maps"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="maps_bulk_refresh_openflights" name="maps bulk refresh '
                 'openflights" isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "app.etzhayyim.apps.maps.bulkRefreshOpenflights", "version": 1, '
                 '"resultTimeoutMs": 600000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 7 days">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_P7D">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/P7D</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer" sourceRef="Start_Timer" '
                 'targetRef="Task_Trigger"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Trigger"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Trigger" name="POST /trigger to openflights '
                 'dumper pod">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.http.fetch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;http://bulk-ingest-openflights.maps-bulk-ingest.svc.cluster.local:8080/trigger&quot;" '
                 'target="url"/>\n'
                 '          <zeebe:input source="=&quot;POST&quot;"                '
                 'target="method"/>\n'
                 '          <zeebe:input source="=&quot;application/json&quot;"    '
                 'target="contentType"/>\n'
                 '          <zeebe:input source="={}"                              '
                 'target="body"/>\n'
                 '          <zeebe:input source="=30000"                           '
                 'target="timeoutMs"/>\n'
                 '          <zeebe:output source="=status"   target="triggerStatus"/>\n'
                 '          <zeebe:output source="=bodyJson" target="triggerResult"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Trigger" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit bulk.refresh OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;app.etzhayyim.apps.maps.bulk.refresh.triggered&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;source&quot;: &quot;openflights&quot;, '
                 '&quot;status&quot;: triggerStatus, &quot;startedAt&quot;: '
                 'triggerResult.started_at }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 3764,
                 '00-contracts/bpmn/ai/gftd/maps/bulkRefreshOpenflights.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-openflights-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — triggers maps-bulk-ingest-osm-planet K8s pod weekly.\n'
                 '  Resident dumper iterates 8 Geofabrik regional PBF extracts (~50GB total),\n'
                 '  filters via osmium-tool to named POIs (place/amenity/shop/tourism/building),\n'
                 '  exports to GeoJSON-Seq, writes Parquet to B2, COPY-loads into RW.\n'
                 '\n'
                 '  Cadence: R/PT7D (weekly) instead of PT24H — Geofabrik dumps refresh once\n'
                 "  per week, and the data is heavier (~50M rows / pass) so we don't re-ingest\n"
                 '  it every day.\n'
                 '\n'
                 '  NSID: app.etzhayyim.apps.maps.bulkRefreshOsmPlanet\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-osm-planet-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_maps_bulk_refresh_osm_planet"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/maps"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="maps_bulk_refresh_osm_planet" name="maps bulk refresh osm '
                 'planet" isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "app.etzhayyim.apps.maps.bulkRefreshOsmPlanet", "version": 1, '
                 '"resultTimeoutMs": 600000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 7 days">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT7D">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/P7D</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer" sourceRef="Start_Timer" '
                 'targetRef="Task_Trigger"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Trigger"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Trigger" name="POST /trigger to dumper pod">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.http.fetch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;http://bulk-ingest-osm-planet.maps-bulk-ingest.svc.cluster.local:8080/trigger&quot;" '
                 'target="url"/>\n'
                 '          <zeebe:input source="=&quot;POST&quot;"                '
                 'target="method"/>\n'
                 '          <zeebe:input source="=&quot;application/json&quot;"    '
                 'target="contentType"/>\n'
                 '          <zeebe:input source="={}"                              '
                 'target="body"/>\n'
                 '          <zeebe:input source="=30000"                           '
                 'target="timeoutMs"/>\n'
                 '          <zeebe:output source="=status"   target="triggerStatus"/>\n'
                 '          <zeebe:output source="=bodyJson" target="triggerResult"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Trigger" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit bulk.refresh OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;app.etzhayyim.apps.maps.bulk.refresh.triggered&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;source&quot;: &quot;osm_planet&quot;, '
                 '&quot;status&quot;: triggerStatus, &quot;startedAt&quot;: '
                 'triggerResult.started_at }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 3890,
                 '00-contracts/bpmn/ai/gftd/maps/bulkRefreshOsmPlanet.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-osm-planet-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — triggers the maps-bulk-ingest-wikidata K8s pod\n'
                 '  every 24 hours. Resident dumper pod streams Wikidata `latest-all.json.gz`,\n'
                 '  filters to P625-bearing entities, writes Parquet shards to B2, then\n'
                 '  COPY-loads into RisingWave vertex_spatial.\n'
                 '\n'
                 '  Pairs with the existing CF Worker dispatch (advanceCoverage / '
                 'runCoverageJob):\n'
                 '\n'
                 '    advanceCoverage    (PT1M)  → CF Worker incremental crawl (50 rows/tick)\n'
                 '    bulkRefreshWikidata (PT24H) → K8s pod full dump (~5M rows / pass)\n'
                 '\n'
                 '  The dumper is idempotent — collisions are silently dropped via PRIMARY KEY\n'
                 '  first-write-wins, so the two pipelines coexist cleanly.\n'
                 '\n'
                 '  Trigger endpoint is the K8s ClusterIP service; resolution from the Zeebe\n'
                 '  worker pod (mitama-udf namespace) goes through the kube DNS:\n'
                 '    bulk-ingest-wikidata.maps-bulk-ingest.svc.cluster.local:8080\n'
                 '\n'
                 '  NSID: app.etzhayyim.apps.maps.bulkRefreshWikidata\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-wikidata-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_maps_bulk_refresh_wikidata"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/maps"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="maps_bulk_refresh_wikidata" name="maps bulk refresh '
                 'wikidata" isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "app.etzhayyim.apps.maps.bulkRefreshWikidata", "version": 1, '
                 '"resultTimeoutMs": 600000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 24 hours">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT24H">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/PT24H</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer" sourceRef="Start_Timer" '
                 'targetRef="Task_Trigger"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Trigger"/>\n'
                 '\n'
                 '    <!-- POST /trigger to the resident dumper pod. Returns 202 immediately;\n'
                 '         the pod runs the 8-12h dump asynchronously and exposes /status. -->\n'
                 '    <bpmn:serviceTask id="Task_Trigger" name="POST /trigger to dumper pod">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.http.fetch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;http://bulk-ingest-wikidata.maps-bulk-ingest.svc.cluster.local:8080/trigger&quot;" '
                 'target="url"/>\n'
                 '          <zeebe:input source="=&quot;POST&quot;"                '
                 'target="method"/>\n'
                 '          <zeebe:input source="=&quot;application/json&quot;"    '
                 'target="contentType"/>\n'
                 '          <zeebe:input source="={}"                              '
                 'target="body"/>\n'
                 '          <zeebe:input source="=30000"                           '
                 'target="timeoutMs"/>\n'
                 '          <zeebe:output source="=status"   target="triggerStatus"/>\n'
                 '          <zeebe:output source="=bodyJson" target="triggerResult"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Trigger" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit bulk.refresh OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;app.etzhayyim.apps.maps.bulk.refresh.triggered&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;source&quot;: &quot;wikidata&quot;, '
                 '&quot;status&quot;: triggerStatus, &quot;startedAt&quot;: '
                 'triggerResult.started_at }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 4401,
                 '00-contracts/bpmn/ai/gftd/maps/bulkRefreshWikidata.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-wikidata-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — triggers maps-bulk-ingest-wikipedia K8s pod every 24h.\n'
                 '  Resident dumper iterates 107+ Wikipedia langs, downloading geo_tags.sql.gz\n'
                 '  + page.sql.gz, joining to (lat, lon, title), writing Parquet to B2,\n'
                 '  COPY-loading into RisingWave vertex_spatial.\n'
                 '\n'
                 '  NSID: app.etzhayyim.apps.maps.bulkRefreshWikipedia\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-wikipedia-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_maps_bulk_refresh_wikipedia"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/maps"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="maps_bulk_refresh_wikipedia" name="maps bulk refresh '
                 'wikipedia" isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "app.etzhayyim.apps.maps.bulkRefreshWikipedia", "version": 1, '
                 '"resultTimeoutMs": 600000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 24 hours">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT24H">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/PT24H</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer" sourceRef="Start_Timer" '
                 'targetRef="Task_Trigger"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Trigger"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Trigger" name="POST /trigger to dumper pod">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.http.fetch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;http://bulk-ingest-wikipedia.maps-bulk-ingest.svc.cluster.local:8080/trigger&quot;" '
                 'target="url"/>\n'
                 '          <zeebe:input source="=&quot;POST&quot;"                '
                 'target="method"/>\n'
                 '          <zeebe:input source="=&quot;application/json&quot;"    '
                 'target="contentType"/>\n'
                 '          <zeebe:input source="={}"                              '
                 'target="body"/>\n'
                 '          <zeebe:input source="=30000"                           '
                 'target="timeoutMs"/>\n'
                 '          <zeebe:output source="=status"   target="triggerStatus"/>\n'
                 '          <zeebe:output source="=bodyJson" target="triggerResult"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Trigger" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit bulk.refresh OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;app.etzhayyim.apps.maps.bulk.refresh.triggered&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;source&quot;: &quot;wikipedia&quot;, '
                 '&quot;status&quot;: triggerStatus, &quot;startedAt&quot;: '
                 'triggerResult.started_at }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 3691,
                 '00-contracts/bpmn/ai/gftd/maps/bulkRefreshWikipedia.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-wikipedia-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — refreshes maps coverage statistics every 15 minutes.\n'
                 '\n'
                 '  Pairs with advanceCoverage.bpmn (PT2M frontier advance):\n'
                 '\n'
                 '    advanceCoverage    (PT2M)  → creates MapsJob for top gap, bumps '
                 'last_fetched_at\n'
                 '    refreshCoverageStats (PT15M) → re-counts vertex_spatial → UPDATE '
                 'collected_count\n'
                 '\n'
                 '  Without this loop, `vertex_maps_coverage_target.collected_count` would\n'
                 '  stay at the seed value forever and `advanceCoverage` would keep picking\n'
                 '  the same top gap in a spin. 15-minute cadence is ~7× slower than the\n'
                 '  advance cadence, so real ingest progress is reflected within 1-2 cycles\n'
                 '  of the next advance without trashing hot-path latency.\n'
                 '\n'
                 '  NSID: app.etzhayyim.apps.maps.refreshCoverageStats\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-refresh-coverage-stats-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_maps_refresh_coverage_stats"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/maps"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="maps_refresh_coverage_stats" name="maps refresh coverage '
                 'stats" isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "app.etzhayyim.apps.maps.refreshCoverageStats", "version": 1, '
                 '"resultTimeoutMs": 60000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 15 minutes">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT15M">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/PT5M</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer" sourceRef="Start_Timer" '
                 'targetRef="Task_Refresh"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Refresh"/>\n'
                 '\n'
                 '    <!-- Single-call XRPC; all aggregation happens server-side via the MV. -->\n'
                 '    <bpmn:serviceTask id="Task_Refresh" name="refreshCoverageStats XRPC">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.http.fetch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;https://maps.etzhayyim.com/xrpc/app.etzhayyim.apps.maps.refreshCoverageStats&quot;" '
                 'target="url"/>\n'
                 '          <zeebe:input source="=&quot;POST&quot;"                '
                 'target="method"/>\n'
                 '          <zeebe:input source="=&quot;application/json&quot;"    '
                 'target="contentType"/>\n'
                 '          <zeebe:input source="={}"                              '
                 'target="body"/>\n'
                 '          <zeebe:input source="=45000"                           '
                 'target="timeoutMs"/>\n'
                 '          <zeebe:output source="=status"   target="refreshStatus"/>\n'
                 '          <zeebe:output source="=bodyJson" target="refreshResult"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Refresh" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit coverage.stats OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;app.etzhayyim.apps.maps.coverage.stats&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;status&quot;: refreshStatus, '
                 '&quot;scanned&quot;: refreshResult.scanned, &quot;updated&quot;: '
                 'refreshResult.updated, &quot;totalCollected&quot;: '
                 'refreshResult.totalCollectedAcrossTargets }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 4208,
                 '00-contracts/bpmn/ai/gftd/maps/refreshCoverageStats.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-refresh-coverage-stats-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — drives pending MapsJob rows to completion.\n'
                 '\n'
                 '  Pipeline (multi-instance parallel over at most 5 pending jobs per tick):\n'
                 '\n'
                 '    1. generic.db.select    — pending, dispatchable jobs (UDF filters out '
                 "'unsupported')\n"
                 '    2. multi-instance loop  — one instance per row, parallel, capped at 5\n'
                 '         generic.http.fetch — POST /xrpc/app.etzhayyim.apps.maps.runCoverageJob '
                 '{jobId}\n'
                 '                               (Worker fetches from external source, writes '
                 'vertex_spatial,\n'
                 '                                advances the job)\n'
                 '    3. generic.audit.emit   — OCEL event with aggregate stats\n'
                 '\n'
                 '  Cadence (PT3M):\n'
                 '    advanceCoverage       PT2M  →   (creates up to 1 new pending job per tick)\n'
                 '    runPendingCoverageJobs PT3M →   (drains up to 5 pending jobs per tick)\n'
                 '    refreshCoverageStats  PT15M →   (re-counts collected_count back into '
                 'targets)\n'
                 '\n'
                 '  Max steady-state throughput ≈ 5 jobs/3 min = 100 jobs/hour per BPMN\n'
                 '  instance. Overpass / GLEIF / Wikidata each have their own rate limits,\n'
                 "  enforced by the Worker handler's internal retry-on-429 logic.\n"
                 '\n'
                 '  NSID: app.etzhayyim.apps.maps.runPendingCoverageJobs\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-run-pending-coverage-jobs-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    id="Definitions_maps_run_pending_coverage_jobs"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/maps"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="maps_run_pending_coverage_jobs" name="maps run pending '
                 'coverage jobs" isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "app.etzhayyim.apps.maps.runPendingCoverageJobs", "version": 1, '
                 '"resultTimeoutMs": 180000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 3 minutes">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT3M">\n'
                 '        <bpmn:timeCycle xsi:type="bpmn:tFormalExpression"\n'
                 '                        '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">R/PT3M</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer" sourceRef="Start_Timer" '
                 'targetRef="Task_Select"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Select"/>\n'
                 '\n'
                 '    <!-- Step 1 — pick pending jobs whose source has a wired dispatch kind.\n'
                 '         UDF keeps the WHERE clause declarative; BPMN stays source-agnostic. '
                 '-->\n'
                 '    <bpmn:serviceTask id="Task_Select" name="select dispatchable pending jobs">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_maps_job&quot;"             '
                 'target="table"/>\n'
                 '          <zeebe:input source="=&quot;job_id, source_id, label, '
                 'pipeline_type&quot;" target="columns"/>\n'
                 '          <zeebe:input source="=5"                                       '
                 'target="limit"/>\n'
                 '          <zeebe:input source="=&quot;created_at ASC&quot;"               '
                 'target="orderBy"/>\n'
                 '          <zeebe:input source="=&quot;status = \'pending\' AND '
                 "maps_source_dispatch_kind(source_id, COALESCE(label, '')) IN ('overpass', "
                 "'gleif', 'wikidata', 'stac', 'seismic', 'wikipedia', 'commons', 'inaturalist', "
                 '\'gbif\', \'wikivoyage\', \'eonet\', \'opensky\')&quot;" target="where"/>\n'
                 '          <zeebe:output source="=rows"     target="jobRows"/>\n'
                 '          <zeebe:output source="=rowCount" target="jobCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Select" '
                 'targetRef="Gateway_HasWork"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gateway_HasWork" name="pending?">\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Work</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_NoWork</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_Work" sourceRef="Gateway_HasWork" '
                 'targetRef="Task_Run">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression"\n'
                 '                                '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">=jobCount &gt; '
                 '0</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_NoWork" sourceRef="Gateway_HasWork" '
                 'targetRef="End">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression"\n'
                 '                                '
                 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">=jobCount &lt;= '
                 '0</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '\n'
                 '    <!-- Step 2 — multi-instance parallel: one runCoverageJob XRPC call per '
                 'pending row. -->\n'
                 '    <bpmn:serviceTask id="Task_Run" name="runCoverageJob (parallel fan-out)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.http.fetch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;https://maps.etzhayyim.com/xrpc/app.etzhayyim.apps.maps.runCoverageJob&quot;" '
                 'target="url"/>\n'
                 '          <zeebe:input source="=&quot;POST&quot;"             target="method"/>\n'
                 '          <zeebe:input source="=&quot;application/json&quot;" '
                 'target="contentType"/>\n'
                 '          <zeebe:input source="={ &quot;jobId&quot;: job.job_id, '
                 '&quot;maxRecords&quot;: 100 }" target="body"/>\n'
                 '          <zeebe:input source="=90000"                        '
                 'target="timeoutMs"/>\n'
                 '          <zeebe:output source="=bodyJson" target="runResult"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Work</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '      <bpmn:multiInstanceLoopCharacteristics isSequential="false">\n'
                 '        <bpmn:extensionElements>\n'
                 '          <zeebe:loopCharacteristics\n'
                 '            inputCollection="=jobRows"\n'
                 '            inputElement="job"/>\n'
                 '        </bpmn:extensionElements>\n'
                 '      </bpmn:multiInstanceLoopCharacteristics>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_Run" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit coverage.runBatch OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;app.etzhayyim.apps.maps.coverage.runBatch&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;jobsPicked&quot;: jobCount }" '
                 'target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_4</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_4" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_4</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_NoWork</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 7024,
                 '00-contracts/bpmn/ai/gftd/maps/runPendingCoverageJobs.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-run-pending-coverage-jobs-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "xml" = $1,\n'
         '          "xml_byte_size" = CAST($2 AS integer),\n'
         '          "version" = 2,\n'
         '          "source_path" = $3,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $4\n'
         '    ',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — Sentinel STAC ingest (Sentinel-1 GRD + Sentinel-2 L2A).\n'
                 '\n'
                 '  Pipeline (Phase 2):\n'
                 '\n'
                 '    1. maps.sentinel.stac.search    — LangChain wrapper around STAC\n'
                 '                                       POST /search. Writes each scene\n'
                 '                                       directly to vertex_satellite_scene\n'
                 '                                       (WHERE NOT EXISTS idempotent).\n'
                 '                                       Returns scenesFound/scenesIngested\n'
                 '                                       + runId + byPlatform.\n'
                 '    2. exclusive gateway            — short-circuit when 0 scenes found.\n'
                 '    3. generic.audit.emit           — OCEL event with aggregate stats.\n'
                 '\n'
                 '  Note: Task_PersistScenes removed in Phase 2. The STAC search primitive\n'
                 '  writes to vertex_satellite_scene internally. The fan-out generic.db.insert\n'
                 '  step was Phase 1 and is no longer needed.\n'
                 '\n'
                 '  Cadence: R/PT24H. AOI list comes from env SENTINEL_AOIS_JSON (falls back\n'
                 '  to 12 KAMI layer coordinator centroids). One BPMN instance per day.\n'
                 '\n'
                 '  ADR-2604271800. NSID: app.etzhayyim.apps.maps.sentinelIngest.\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-sentinel-ingest-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_maps_sentinel_ingest"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/maps"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="2.0">\n'
                 '  <bpmn:process id="maps_sentinel_ingest" name="maps sentinel ingest" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "app.etzhayyim.apps.maps.sentinelIngest", "version": 2, '
                 '"resultTimeoutMs": 600000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 24 hours">\n'
                 '      <bpmn:outgoing>Flow_ToSearch</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT24H">\n'
                 '        <bpmn:timeCycle '
                 'xsi:type="bpmn:tFormalExpression">R/PT24H</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_ToSearch_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToSearch" sourceRef="Start_Timer" '
                 'targetRef="Task_StacSearch"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToSearch_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_StacSearch"/>\n'
                 '\n'
                 '    <!-- Step 1: STAC search + direct write to vertex_satellite_scene.\n'
                 '         Phase 2: primitive handles DB writes internally via sync_cursor.\n'
                 '         Returns scenesFound / scenesIngested counts for audit. -->\n'
                 '    <bpmn:serviceTask id="Task_StacSearch" name="STAC search + persist (S-1 GRD '
                 '+ S-2 L2A)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="maps.sentinel.stac.search"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=null"  target="aois"/>\n'
                 '          <zeebe:input source="=1"     target="time_range_days"/>\n'
                 '          <zeebe:input source="=10"    target="max_scenes_per_aoi"/>\n'
                 '          <zeebe:input source="=null"  target="platforms"/>\n'
                 '          <zeebe:input source="=30"    target="max_cloud_cover"/>\n'
                 '          <zeebe:output source="=runId"           target="runId"/>\n'
                 '          <zeebe:output source="=rows"            target="sceneRows"/>\n'
                 '          <zeebe:output source="=scenesFound"     target="scenesFound"/>\n'
                 '          <zeebe:output source="=scenesIngested"  target="scenesIngested"/>\n'
                 '          <zeebe:output source="=byPlatform"      target="byPlatform"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ToSearch</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_ToSearch_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ToGate</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToGate" sourceRef="Task_StacSearch" '
                 'targetRef="Gateway_HasScenes"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gateway_HasScenes" name="any scenes?">\n'
                 '      <bpmn:incoming>Flow_ToGate</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_HasScenes</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_NoScenes</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_HasScenes" sourceRef="Gateway_HasScenes" '
                 'targetRef="Task_Audit">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=scenesFound '
                 '&gt; 0</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_NoScenes" sourceRef="Gateway_HasScenes" '
                 'targetRef="Task_Audit">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=scenesFound '
                 '&lt;= 0</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit sentinel.ingest OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;app.etzhayyim.apps.maps.sentinel.ingest&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;runId&quot;: runId, '
                 '&quot;scenesFound&quot;: scenesFound, &quot;scenesIngested&quot;: '
                 'scenesIngested, &quot;byPlatform&quot;: byPlatform }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_HasScenes</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_NoScenes</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ToEnd</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ToEnd" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_ToEnd</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 5557,
                 '00-contracts/bpmn/ai/gftd/maps/sentinelIngest.bpmn',
                 'at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-sentinel-ingest-v1']}]

DOWN = [{'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "version" = 1,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-advance-coverage-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "version" = 1,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-ferry-routes-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "version" = 1,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-geonames-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "version" = 1,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-gtfs-jp-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "version" = 1,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-openflights-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "version" = 1,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-osm-planet-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "version" = 1,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-wikidata-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "version" = 1,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-bulk-refresh-wikipedia-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "version" = 1,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-refresh-coverage-stats-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "version" = 1,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-run-pending-coverage-jobs-v1']},
 {'sql': '\n'
         '      UPDATE vertex_bpmn_process_def\n'
         '      SET "version" = 1,\n'
         '          "deployed_at" = NULL,\n'
         '          "deployed_zeebe_key" = NULL\n'
         '      WHERE "vertex_id" = $1\n'
         '    ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/app.etzhayyim.apps.bpmn.processDef/maps-sentinel-ingest-v1']}]


def upgrade() -> None:
    execute_bound_statements(op.get_bind(), UP)


def downgrade() -> None:
    execute_bound_statements(op.get_bind(), DOWN)
