"""Captured from Kysely migration 20260427040000_seed_fund_ma_bpmn_actors."""

from __future__ import annotations

from alembic import op

from graph_schema.db import execute_bound_statements


revision = "r_20260427040000_seed_fund_ma_bpmn_actors"
down_revision = 'r_20260427033000_open_jpn_mynumber_application_medical'
branch_labels = None
depends_on = None

UP = [{'sql': '\n'
         '    CREATE TABLE IF NOT EXISTS vertex_ma_deal (\n'
         '      vertex_id            VARCHAR PRIMARY KEY,\n'
         '      _seq                 BIGINT,\n'
         '      created_date         TIMESTAMP,\n'
         '      sensitivity_ord      BIGINT,\n'
         '      owner_did            VARCHAR,\n'
         '      rkey                 VARCHAR,\n'
         '      repo                 VARCHAR,\n'
         '      did                  VARCHAR,\n'
         '      deal_id              VARCHAR,\n'
         '      side                 VARCHAR,\n'
         '      client_name          VARCHAR,\n'
         '      target_name          VARCHAR,\n'
         '      sector               VARCHAR,\n'
         '      jurisdiction         VARCHAR,\n'
         '      expected_value_usd   DOUBLE PRECISION,\n'
         '      status               VARCHAR,\n'
         '      stage                VARCHAR,\n'
         '      operator_did         VARCHAR,\n'
         '      source_url           VARCHAR,\n'
         '      confidence           DOUBLE PRECISION,\n'
         '      notes                VARCHAR\n'
         '    )\n'
         '  ',
  'parameters': []},
 {'sql': '\n'
         '    CREATE TABLE IF NOT EXISTS vertex_ma_candidate (\n'
         '      vertex_id            VARCHAR PRIMARY KEY,\n'
         '      _seq                 BIGINT,\n'
         '      created_date         TIMESTAMP,\n'
         '      sensitivity_ord      BIGINT,\n'
         '      owner_did            VARCHAR,\n'
         '      rkey                 VARCHAR,\n'
         '      repo                 VARCHAR,\n'
         '      did                  VARCHAR,\n'
         '      candidate_id         VARCHAR,\n'
         '      candidate_name       VARCHAR,\n'
         '      candidate_kind       VARCHAR,\n'
         '      sector               VARCHAR,\n'
         '      jurisdiction         VARCHAR,\n'
         '      legal_entity_did     VARCHAR,\n'
         '      screening_score      DOUBLE PRECISION,\n'
         '      source_url           VARCHAR,\n'
         '      confidence           DOUBLE PRECISION,\n'
         '      notes                VARCHAR\n'
         '    )\n'
         '  ',
  'parameters': []},
 {'sql': '\n'
         '    CREATE TABLE IF NOT EXISTS vertex_ma_valuation (\n'
         '      vertex_id              VARCHAR PRIMARY KEY,\n'
         '      _seq                   BIGINT,\n'
         '      created_date           TIMESTAMP,\n'
         '      sensitivity_ord        BIGINT,\n'
         '      owner_did              VARCHAR,\n'
         '      rkey                   VARCHAR,\n'
         '      repo                   VARCHAR,\n'
         '      did                    VARCHAR,\n'
         '      valuation_id           VARCHAR,\n'
         '      deal_id                VARCHAR,\n'
         '      method                 VARCHAR,\n'
         '      low_usd                DOUBLE PRECISION,\n'
         '      high_usd               DOUBLE PRECISION,\n'
         '      midpoint_usd           DOUBLE PRECISION,\n'
         '      currency               VARCHAR,\n'
         '      as_of_date             VARCHAR,\n'
         '      source_url             VARCHAR,\n'
         '      confidence             DOUBLE PRECISION,\n'
         '      notes                  VARCHAR\n'
         '    )\n'
         '  ',
  'parameters': []},
 {'sql': '\n'
         '    CREATE TABLE IF NOT EXISTS vertex_ma_match (\n'
         '      vertex_id              VARCHAR PRIMARY KEY,\n'
         '      _seq                   BIGINT,\n'
         '      created_date           TIMESTAMP,\n'
         '      sensitivity_ord        BIGINT,\n'
         '      owner_did              VARCHAR,\n'
         '      rkey                   VARCHAR,\n'
         '      repo                   VARCHAR,\n'
         '      did                    VARCHAR,\n'
         '      match_id               VARCHAR,\n'
         '      deal_id                VARCHAR,\n'
         '      buyer_candidate_id     VARCHAR,\n'
         '      rank                   INTEGER,\n'
         '      fit_score              DOUBLE PRECISION,\n'
         '      status                 VARCHAR,\n'
         '      source_url             VARCHAR,\n'
         '      confidence             DOUBLE PRECISION,\n'
         '      notes                  VARCHAR\n'
         '    )\n'
         '  ',
  'parameters': []},
 {'sql': '\n'
         '    CREATE TABLE IF NOT EXISTS edge_ma_deal_candidate (\n'
         '      edge_id              VARCHAR PRIMARY KEY,\n'
         '      src_vid              VARCHAR NOT NULL,\n'
         '      dst_vid              VARCHAR NOT NULL,\n'
         '      relationship         VARCHAR,\n'
         '      role                 VARCHAR,\n'
         '      score                DOUBLE PRECISION,\n'
         '      created_at           VARCHAR\n'
         '    )\n'
         '  ',
  'parameters': []},
 {'sql': '\n'
         '    CREATE TABLE IF NOT EXISTS edge_ma_deal_buyer (\n'
         '      edge_id              VARCHAR PRIMARY KEY,\n'
         '      src_vid              VARCHAR NOT NULL,\n'
         '      dst_vid              VARCHAR NOT NULL,\n'
         '      relationship         VARCHAR,\n'
         '      rank                 INTEGER,\n'
         '      fit_score            DOUBLE PRECISION,\n'
         '      status               VARCHAR,\n'
         '      created_at           VARCHAR\n'
         '    )\n'
         '  ',
  'parameters': []},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id, owner_did, bpmn_process_id, version, xml, xml_byte_size,\n'
         '      source_path, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, 1,\n'
         "      $4, CAST($5 AS integer), $6, 'active',\n"
         '      $7, CAST($8 AS integer), $9,\n'
         '      $10, $11\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $12\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/fund-managerDiscovery-v1',
                 'did:web:fund.etzhayyim.com',
                 'fund_manager_discovery',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Fund manager discovery pilot.\n'
                 '\n'
                 '  NSID:       com.etzhayyim.apps.fund.managerDiscovery\n'
                 '  Owner DID:  did:web:fund.etzhayyim.com\n'
                 '  Process ID: fund_manager_discovery\n'
                 '\n'
                 '  The Zeebe task types follow ADR-2604261200. Raw artifacts are persisted\n'
                 '  before graph writes, and cursor advancement is gated by visibility checks.\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_fund_manager_discovery"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/fund"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="fund_manager_discovery" name="fund manager discovery" '
                 'isExecutable="true">\n'
                 '    <bpmn:startEvent id="Start" name="discovery requested">\n'
                 '      <bpmn:outgoing>Flow_PlanSources</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_PlanSources" sourceRef="Start" '
                 'targetRef="Task_PlanSources"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_PlanSources" name="plan fund sources">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="fund.planSources" retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_PlanSources</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_FetchRaw</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_FetchRaw" sourceRef="Task_PlanSources" '
                 'targetRef="Task_FetchRaw"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_FetchRaw" name="fetch source artifacts">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="fund.fetchRaw" retries="3"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_FetchRaw</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_PersistArtifact</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_PersistArtifact" sourceRef="Task_FetchRaw" '
                 'targetRef="Task_PersistArtifact"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_PersistArtifact" name="persist raw artifact">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="fund.persistArtifact" retries="3"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_PersistArtifact</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_NormalizeManager</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_NormalizeManager" '
                 'sourceRef="Task_PersistArtifact" targetRef="Task_NormalizeManager"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_NormalizeManager" name="normalize manager">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="fund.normalizeManager" retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_NormalizeManager</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_NormalizeFund</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_NormalizeFund" sourceRef="Task_NormalizeManager" '
                 'targetRef="Task_NormalizeFund"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_NormalizeFund" name="normalize funds">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="fund.normalizeFund" retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_NormalizeFund</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_EnrichEntity</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_EnrichEntity" sourceRef="Task_NormalizeFund" '
                 'targetRef="Task_EnrichEntity"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_EnrichEntity" name="enrich legal entities">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="fund.enrichEntity" retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_EnrichEntity</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Health</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Health" sourceRef="Task_EnrichEntity" '
                 'targetRef="Task_Health"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Health" name="rw health gate">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="rw.health.probe" retries="1"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:output source="=healthy" target="rwHealthy"/>\n'
                 '          <zeebe:output source="=reason" target="rwHealthReason"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Health</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_HealthGate</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_HealthGate" sourceRef="Task_Health" '
                 'targetRef="Gateway_RwHealthy"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gateway_RwHealthy" name="RisingWave healthy?" '
                 'default="Flow_RwDegraded">\n'
                 '      <bpmn:incoming>Flow_HealthGate</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_WriteGraph</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_RwDegraded</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_WriteGraph" sourceRef="Gateway_RwHealthy" '
                 'targetRef="Task_WriteGraph">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=rwHealthy = '
                 'true</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_RwDegraded" sourceRef="Gateway_RwHealthy" '
                 'targetRef="Task_AuditRwDegraded"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_WriteGraph" name="write fund graph">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="fund.writeGraph" retries="3"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_WriteGraph</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_VerifyCoverage</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_VerifyCoverage" sourceRef="Task_WriteGraph" '
                 'targetRef="Task_VerifyCoverage"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_VerifyCoverage" name="verify fund coverage">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="fund.verifyCoverage" retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_VerifyCoverage</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Audit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Audit" sourceRef="Task_VerifyCoverage" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditRwDegraded" name="audit rw degraded">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit" retries="2"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:fund.etzhayyim.com&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;fund.managerDiscovery.rwDegraded&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={sourceId: sourceId, runId: runId, rwHealthy: '
                 'rwHealthy, rwHealthReason: rwHealthReason, status: &quot;rw-degraded&quot;}" '
                 'target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_RwDegraded</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_DegradedEnd</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_DegradedEnd" sourceRef="Task_AuditRwDegraded" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="audit fund discovery">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit" retries="2"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:fund.etzhayyim.com&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;fund.managerDiscovery.completed&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={sourceId: sourceId, runId: runId, '
                 'managersWritten: managersWritten, fundsWritten: fundsWritten, artifactsWritten: '
                 'artifactsWritten}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Audit</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="discovery completed">\n'
                 '      <bpmn:incoming>Flow_End</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_DegradedEnd</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 7702,
                 '00-contracts/bpmn/com/etzhayyim/fund/managerDiscovery.bpmn',
                 '2026-04-27T04:00:00Z',
                 2,
                 'did:web:fund.etzhayyim.com',
                 'did:web:fund.etzhayyim.com',
                 'sys.bpmn.seed.fund',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/fund-managerDiscovery-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id, owner_did, bpmn_process_id, version, xml, xml_byte_size,\n'
         '      source_path, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, 1,\n'
         "      $4, CAST($5 AS integer), $6, 'active',\n"
         '      $7, CAST($8 AS integer), $9,\n'
         '      $10, $11\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $12\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/ma-startDealWorkflow-v1',
                 'did:web:ma.etzhayyim.com',
                 'ma_start_deal_workflow',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Global M&A brokerage workflow.\n'
                 '\n'
                 '  NSID:       com.etzhayyim.apps.ma.startDealWorkflow\n'
                 '  Owner DID:  did:web:ma.etzhayyim.com\n'
                 '  Process ID: ma_start_deal_workflow\n'
                 '\n'
                 '  This is the first executable shell for etzhayyim-project-ma. It wires MA Core,\n'
                 '  APQC, ISCO, and ISIC actors through stable Zeebe task types and emits a final\n'
                 '  audit event for process-mining visibility.\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_ma_start_deal_workflow"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/ma"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="ma_start_deal_workflow" name="M&amp;A deal workflow" '
                 'isExecutable="true">\n'
                 '    <bpmn:startEvent id="Start" name="deal intake">\n'
                 '      <bpmn:outgoing>Flow_Intake</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Intake" sourceRef="Start" '
                 'targetRef="Task_Intake"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Intake" name="sales origination intake">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ma.salesOrigination.intake" retries="2"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=side" target="side"/>\n'
                 '          <zeebe:input source="=clientName" target="clientName"/>\n'
                 '          <zeebe:input source="=sector" target="sector"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Intake</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Screen</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Screen" sourceRef="Task_Intake" '
                 'targetRef="Task_Screen"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Screen" name="target screening">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ma.targetScreening.score" retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Screen</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Valuation</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Valuation" sourceRef="Task_Screen" '
                 'targetRef="Task_Valuation"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Valuation" name="valuation and structure">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ma.investmentAdviser.valuation" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Valuation</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Match</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Match" sourceRef="Task_Valuation" '
                 'targetRef="Task_Match"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Match" name="buyer matching">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ma.buyerMatching.rank" retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Match</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Negotiate</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Negotiate" sourceRef="Task_Match" '
                 'targetRef="Task_Negotiate"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Negotiate" name="broker negotiation">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ma.tradeBroker.negotiate" retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Negotiate</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Outreach</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Outreach" sourceRef="Task_Negotiate" '
                 'targetRef="Task_Outreach"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Outreach" name="compose outreach draft">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ma.outreach.composeDraft" retries="2"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;ma&quot;" target="mailboxLocal"/>\n'
                 '          <zeebe:input source="=&quot;draft_only&quot;" target="outreachMode"/>\n'
                 '          <zeebe:input source="=true" target="approvalRequired"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Outreach</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ApproveOutreach</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ApproveOutreach" sourceRef="Task_Outreach" '
                 'targetRef="Task_ApproveOutreach"/>\n'
                 '\n'
                 '    <bpmn:userTask id="Task_ApproveOutreach" name="approve outreach draft">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:formDefinition '
                 'formKey="camunda-forms:bpmn:ma-outreach-approval-v1"/>\n'
                 '        <zeebe:assignmentDefinition candidateGroups="ma-operators"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ApproveOutreach</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_PrepareMailerSend</bpmn:outgoing>\n'
                 '    </bpmn:userTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_PrepareMailerSend" '
                 'sourceRef="Task_ApproveOutreach" targetRef="Task_PrepareMailerSend"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_PrepareMailerSend" name="prepare mailer send '
                 'payload">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ma.outreach.prepareMailerSend" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_PrepareMailerSend</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_SendApproved</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_SendApproved" sourceRef="Task_PrepareMailerSend" '
                 'targetRef="Task_SendApproved"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_SendApproved" name="stage approved mailer send">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ma.outreach.sendApproved" retries="2"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=true" target="dryRun"/>\n'
                 '          <zeebe:input source="=false" target="sendEnabled"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_SendApproved</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Close</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Close" sourceRef="Task_SendApproved" '
                 'targetRef="Task_Close"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Close" name="closing and PMI handoff">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ma.integration.closeAndHandoff" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Close</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Health</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Health" sourceRef="Task_Close" '
                 'targetRef="Task_Health"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Health" name="rw health gate">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="rw.health.probe" retries="1"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:output source="=healthy" target="rwHealthy"/>\n'
                 '          <zeebe:output source="=reason" target="rwHealthReason"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Health</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_HealthGate</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_HealthGate" sourceRef="Task_Health" '
                 'targetRef="Gateway_RwHealthy"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gateway_RwHealthy" name="RisingWave healthy?" '
                 'default="Flow_RwDegraded">\n'
                 '      <bpmn:incoming>Flow_HealthGate</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_WriteGraph</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_RwDegraded</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_WriteGraph" sourceRef="Gateway_RwHealthy" '
                 'targetRef="Task_WriteGraph">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=rwHealthy = '
                 'true</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_RwDegraded" sourceRef="Gateway_RwHealthy" '
                 'targetRef="Task_AuditRwDegraded"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_WriteGraph" name="write MA graph">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="ma.writeGraph" retries="2"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=false" target="dryRun"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_WriteGraph</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Audit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Audit" sourceRef="Task_WriteGraph" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditRwDegraded" name="audit rw degraded">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit" retries="2"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:ma.etzhayyim.com&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;ma.startDealWorkflow.rwDegraded&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={dealId: dealId, side: side, sector: sector, '
                 'rwHealthy: rwHealthy, rwHealthReason: rwHealthReason, status: '
                 '&quot;rw-degraded&quot;}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_RwDegraded</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_DegradedEnd</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_DegradedEnd" sourceRef="Task_AuditRwDegraded" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="audit MA workflow">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit" retries="2"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:ma.etzhayyim.com&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;ma.startDealWorkflow.completed&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={dealId: dealId, side: side, sector: sector, '
                 'status: status, matchedBuyerCount: matchedBuyerCount, closingStage: '
                 'closingStage}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Audit</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="workflow completed">\n'
                 '      <bpmn:incoming>Flow_End</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_DegradedEnd</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 9840,
                 '00-contracts/bpmn/com/etzhayyim/ma/startDealWorkflow.bpmn',
                 '2026-04-27T04:00:00Z',
                 3,
                 'did:web:ma.etzhayyim.com',
                 'did:web:ma.etzhayyim.com',
                 'sys.bpmn.seed.ma',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/ma-startDealWorkflow-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id, owner_did, nsid, bpmn_process_id, bpmn_version,\n'
         '      result_timeout_ms, status, created_at, sensitivity_ord, org_id, user_id,\n'
         '      actor_id, write_table_allowlist\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, $4, 1,\n'
         "      CAST($5 AS integer), 'active', $6,\n"
         '      CAST($7 AS integer), $8, $9,\n'
         '      $10, $11\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $12\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/fund-managerDiscovery-v1',
                 'did:web:fund.etzhayyim.com',
                 'com.etzhayyim.apps.fund.managerDiscovery',
                 'fund_manager_discovery',
                 600000,
                 '2026-04-27T04:00:00Z',
                 2,
                 'did:web:fund.etzhayyim.com',
                 'did:web:fund.etzhayyim.com',
                 'sys.bpmn.seed.fund',
                 'vertex_fund,vertex_fund_manager,vertex_fund_investor,vertex_fund_investee,edge_fund_managed_by,edge_fund_backed_by,edge_fund_invests_in,edge_fund_sponsored_by',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/fund-managerDiscovery-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id, owner_did, nsid, bpmn_process_id, bpmn_version,\n'
         '      result_timeout_ms, status, created_at, sensitivity_ord, org_id, user_id,\n'
         '      actor_id, write_table_allowlist\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, $4, 1,\n'
         "      CAST($5 AS integer), 'active', $6,\n"
         '      CAST($7 AS integer), $8, $9,\n'
         '      $10, $11\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $12\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/ma-startDealWorkflow-v1',
                 'did:web:ma.etzhayyim.com',
                 'com.etzhayyim.apps.ma.startDealWorkflow',
                 'ma_start_deal_workflow',
                 900000,
                 '2026-04-27T04:00:00Z',
                 3,
                 'did:web:ma.etzhayyim.com',
                 'did:web:ma.etzhayyim.com',
                 'sys.bpmn.seed.ma',
                 'vertex_ma_deal,vertex_ma_candidate,vertex_ma_valuation,vertex_ma_match,edge_ma_deal_candidate,edge_ma_deal_buyer',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/ma-startDealWorkflow-v1']}]

DOWN = [{'sql': 'DELETE FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/fund-managerDiscovery-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/ma-startDealWorkflow-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_process_def WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/fund-managerDiscovery-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_process_def WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/ma-startDealWorkflow-v1']},
 {'sql': 'DROP TABLE IF EXISTS edge_ma_deal_buyer', 'parameters': []},
 {'sql': 'DROP TABLE IF EXISTS edge_ma_deal_candidate', 'parameters': []},
 {'sql': 'DROP TABLE IF EXISTS vertex_ma_match', 'parameters': []},
 {'sql': 'DROP TABLE IF EXISTS vertex_ma_valuation', 'parameters': []},
 {'sql': 'DROP TABLE IF EXISTS vertex_ma_candidate', 'parameters': []},
 {'sql': 'DROP TABLE IF EXISTS vertex_ma_deal', 'parameters': []}]


def upgrade() -> None:
    execute_bound_statements(op.get_bind(), UP)


def downgrade() -> None:
    execute_bound_statements(op.get_bind(), DOWN)
