"""Captured from Kysely migration 20260426010000_maps3d_photogrammetry."""

from __future__ import annotations

from alembic import op

from graph_schema.db import execute_bound_statements


revision = "r_20260426010000_maps3d_photogrammetry"
down_revision = 'r_20260425223000_open_lei_robotics_ems_bridge'
branch_labels = None
depends_on = None

UP = [{'sql': '\n'
         '    CREATE TABLE IF NOT EXISTS vertex_maps3d_tile (\n'
         '      vertex_id VARCHAR PRIMARY KEY,\n'
         '      _seq BIGINT,\n'
         '      created_date DATE,\n'
         '      sensitivity_ord BIGINT,\n'
         '      owner_did VARCHAR,\n'
         '      tile_h3 VARCHAR NOT NULL,\n'
         '      h3_resolution BIGINT,\n'
         '      centroid_lat DOUBLE PRECISION,\n'
         '      centroid_lng DOUBLE PRECISION,\n'
         '      priority BIGINT,\n'
         '      status VARCHAR NOT NULL,\n'
         '      mesh_uri VARCHAR,\n'
         '      image_count BIGINT,\n'
         '      triangle_count BIGINT,\n'
         '      reconstruction_ms BIGINT,\n'
         '      last_attempt_at VARCHAR,\n'
         '      attempt_count BIGINT,\n'
         '      error_code VARCHAR,\n'
         '      error_message VARCHAR,\n'
         '      created_at VARCHAR,\n'
         '      org_id VARCHAR,\n'
         '      user_id VARCHAR,\n'
         '      actor_id VARCHAR\n'
         '    )\n'
         '  ',
  'parameters': []},
 {'sql': '\n'
         '    CREATE INDEX IF NOT EXISTS idx_maps3d_tile_status ON vertex_maps3d_tile (status)\n'
         '  ',
  'parameters': []},
 {'sql': '\n'
         '    CREATE INDEX IF NOT EXISTS idx_maps3d_tile_priority ON vertex_maps3d_tile (priority, '
         'status)\n'
         '  ',
  'parameters': []},
 {'sql': '\n    CREATE INDEX IF NOT EXISTS idx_maps3d_tile_h3 ON vertex_maps3d_tile (tile_h3)\n  ',
  'parameters': []},
 {'sql': '\n'
         '    CREATE TABLE IF NOT EXISTS vertex_langgraph_state (\n'
         '      vertex_id VARCHAR PRIMARY KEY,\n'
         '      _seq BIGINT,\n'
         '      created_date DATE,\n'
         '      sensitivity_ord BIGINT,\n'
         '      owner_did VARCHAR,\n'
         '      run_id VARCHAR NOT NULL,\n'
         '      parent_run_id VARCHAR,\n'
         '      graph_name VARCHAR NOT NULL,\n'
         '      tile_h3 VARCHAR,\n'
         '      node_name VARCHAR NOT NULL,\n'
         '      checkpoint_seq BIGINT,\n'
         '      state_json VARCHAR,\n'
         '      audit_json VARCHAR,\n'
         '      latency_ms BIGINT,\n'
         '      status VARCHAR,\n'
         '      created_at VARCHAR,\n'
         '      org_id VARCHAR,\n'
         '      user_id VARCHAR,\n'
         '      actor_id VARCHAR\n'
         '    )\n'
         '  ',
  'parameters': []},
 {'sql': '\n'
         '    CREATE INDEX IF NOT EXISTS idx_langgraph_run ON vertex_langgraph_state (run_id, '
         'checkpoint_seq)\n'
         '  ',
  'parameters': []},
 {'sql': '\n'
         '    CREATE INDEX IF NOT EXISTS idx_langgraph_tile ON vertex_langgraph_state (tile_h3)\n'
         '  ',
  'parameters': []},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (vertex_id, owner_did, bpmn_process_id, version, '
         'xml, xml_byte_size, source_path, status, created_at, sensitivity_ord, org_id, user_id, '
         'actor_id)\n'
         "    SELECT $1, $2, $3, 1, $4, CAST($5 AS integer), $6, 'active', $7, 1, $8, $9, $10\n"
         '    WHERE NOT EXISTS (SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $11)\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/maps3d-process-tile-v1',
                 'did:web:bpmn.etzhayyim.com',
                 'maps3d_process_tile',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  maps3d.processTile — single-tile photogrammetry pipeline.\n'
                 '\n'
                 '  Cadence: timer-start R/PT15M draws one pending tile per tick; manual\n'
                 '  invocation via `POST '
                 'http://dispatcher.etzhayyim.com:8080/xrpc/com.etzhayyim.apps.maps3d.processTile`\n'
                 '  with { tileH3 } skips the picker.\n'
                 '\n'
                 '  Pipeline (sequential within one tile, time-budgeted):\n'
                 '    1. generic.db.select   — one pending row from vertex_maps3d_tile (priority '
                 'DESC)\n'
                 '    2. exclusive gateway   — bail out cleanly if no work\n'
                 '    3. maps3d.fetchMapillary  — Mapillary v4 candidate set\n'
                 '    4. maps3d.curateImages    — LangGraph 30-image down-select\n'
                 '    5. maps3d.colmapTile      — COLMAP CPU dense reconstruction (boundary timer '
                 '60min)\n'
                 '    6. exclusive gateway      — success?\n'
                 '        no  → maps3d.replanReconstruction → End (mark tile failed)\n'
                 '        yes → continue\n'
                 '    7. maps3d.simplifyAndExport — Open3D quadric decimate + saturated GLB\n'
                 '    8. maps3d.visionAnnotate    — Murakumo Vision over the curated images\n'
                 '    9. maps3d.linkActor         — LangGraph entity → registry DID '
                 'disambiguation\n'
                 '   10. generic.db.insert        — vertex_spatial Building rows + edges + '
                 'vertex_maps3d_tile.status=done\n'
                 '   11. generic.audit.emit       — OCEL maps3d.tile.processed\n'
                 '   12. End\n'
                 '\n'
                 '  Steady-state throughput: 1 tile / ~45 min on a 2-core colmap-worker pod.\n'
                 '  Tokyo landmark backfill (~2,000 tiles) ≈ 60 days end-to-end with one pod.\n'
                 '\n'
                 '  NSID: com.etzhayyim.apps.maps3d.processTile\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/maps3d-process-tile-v1\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_maps3d_process_tile"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/maps3d"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="maps3d_process_tile" name="maps3d processTile" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.maps3d.processTile", "version": 1, '
                 '"resultTimeoutMs": 5400000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <!-- ============================== Start ============================== '
                 '-->\n'
                 '    <bpmn:startEvent id="Start" name="every 15 minutes">\n'
                 '      <bpmn:outgoing>Flow_Start</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT15M">\n'
                 '        <bpmn:timeCycle '
                 'xsi:type="bpmn:tFormalExpression">R/PT15M</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Start" sourceRef="Start" '
                 'targetRef="Task_SelectTile"/>\n'
                 '\n'
                 '    <!-- 1. Pick one pending tile from the registry. attempt_count is\n'
                 '         pulled so the replanner can apply its bounded-retry policy. -->\n'
                 '    <bpmn:serviceTask id="Task_SelectTile" name="select pending tile">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_maps3d_tile&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=&quot;tile_h3, priority, image_count, status, '
                 'attempt_count&quot;" target="columns"/>\n'
                 '          <zeebe:input source="=1" target="limit"/>\n'
                 '          <zeebe:input source="=&quot;priority ASC, last_attempt_at NULLS FIRST, '
                 'tile_h3 ASC&quot;" target="orderBy"/>\n'
                 '          <zeebe:input source="=&quot;status IN (\'pending\',\'stale\')&quot;" '
                 'target="where"/>\n'
                 '          <zeebe:output source="=rows" target="tileRows"/>\n'
                 '          <zeebe:output source="=rowCount" target="tileCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Start</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterSelect</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterSelect" sourceRef="Task_SelectTile" '
                 'targetRef="Gateway_HasTile"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gateway_HasTile" name="tile?">\n'
                 '      <bpmn:incoming>Flow_AfterSelect</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Yes_HasTile</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_No_HasTile</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_No_HasTile" sourceRef="Gateway_HasTile" '
                 'targetRef="End">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=tileCount '
                 '&lt;= 0</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Yes_HasTile" sourceRef="Gateway_HasTile" '
                 'targetRef="Task_FetchMapillary">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=tileCount '
                 '&gt; 0</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '\n'
                 '    <!-- 3. Mapillary candidate set. -->\n'
                 '    <bpmn:serviceTask id="Task_FetchMapillary" name="fetch Mapillary '
                 'candidates">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="maps3d.fetchMapillary"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=tileRows[1].tile_h3" target="tileH3"/>\n'
                 '          <zeebe:input source="=200" target="maxImages"/>\n'
                 '          <zeebe:input source="=0.5" target="minQuality"/>\n'
                 '          <zeebe:output source="=candidates" target="mapillaryCandidates"/>\n'
                 '          <zeebe:output source="=totalAvailable" target="mapillaryTotal"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Yes_HasTile</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterFetch</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterFetch" sourceRef="Task_FetchMapillary" '
                 'targetRef="Task_CurateImages"/>\n'
                 '\n'
                 '    <!-- 4. LangGraph image curation. -->\n'
                 '    <bpmn:serviceTask id="Task_CurateImages" name="curate images (LangGraph)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="maps3d.curateImages"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=tileRows[1].tile_h3" target="tileH3"/>\n'
                 '          <zeebe:input source="=mapillaryCandidates" target="candidates"/>\n'
                 '          <zeebe:input source="=30" target="targetCount"/>\n'
                 '          <zeebe:input source="=8" target="minCount"/>\n'
                 '          <zeebe:output source="=selectedIds" target="selectedIds"/>\n'
                 '          <zeebe:output source="=abort" target="curateAbort"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_AfterFetch</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterCurate</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterCurate" sourceRef="Task_CurateImages" '
                 'targetRef="Gateway_CurateOK"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gateway_CurateOK" name="enough images?">\n'
                 '      <bpmn:incoming>Flow_AfterCurate</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Curate_Yes</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Curate_No</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_Curate_No" sourceRef="Gateway_CurateOK" '
                 'targetRef="Task_FailedAudit">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=curateAbort = '
                 'true</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Curate_Yes" sourceRef="Gateway_CurateOK" '
                 'targetRef="Task_Colmap">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=curateAbort = '
                 'false</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '\n'
                 '    <!-- 5. COLMAP CPU dense reconstruction with 60-min hard timeout. -->\n'
                 '    <bpmn:serviceTask id="Task_Colmap" name="COLMAP dense (CPU, 60min budget)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="maps3d.colmapTile"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=tileRows[1].tile_h3" target="tileH3"/>\n'
                 '          <zeebe:input source="=selectedIds" target="selectedIds"/>\n'
                 '          <zeebe:input source="=mapillaryCandidates" target="imageUrls"/>\n'
                 '          <zeebe:input source="=true" target="denseEnabled"/>\n'
                 '          <zeebe:input source="=&quot;exhaustive&quot;" target="matcher"/>\n'
                 '          <zeebe:output source="=ok" target="colmapOk"/>\n'
                 '          <zeebe:output source="=rawMeshUri" target="rawMeshUri"/>\n'
                 '          <zeebe:output source="=imageCount" target="registeredImages"/>\n'
                 '          <zeebe:output source="=errorCode" target="colmapErrorCode"/>\n'
                 '          <zeebe:output source="=errorMessage" target="colmapErrorMessage"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Curate_Yes</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterColmap</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:boundaryEvent id="Boundary_ColmapTimeout" attachedToRef="Task_Colmap" '
                 'name="60 min">\n'
                 '      <bpmn:outgoing>Flow_ColmapTimeout</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_Colmap_60min">\n'
                 '        <bpmn:timeDuration '
                 'xsi:type="bpmn:tFormalExpression">PT60M</bpmn:timeDuration>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:boundaryEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_ColmapTimeout" '
                 'sourceRef="Boundary_ColmapTimeout" targetRef="Task_Replan"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterColmap" sourceRef="Task_Colmap" '
                 'targetRef="Gateway_ColmapOK"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gateway_ColmapOK" name="reconstruct ok?">\n'
                 '      <bpmn:incoming>Flow_AfterColmap</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Colmap_Yes</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Colmap_No</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_Colmap_No" sourceRef="Gateway_ColmapOK" '
                 'targetRef="Task_Replan">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=colmapOk = '
                 'false</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Colmap_Yes" sourceRef="Gateway_ColmapOK" '
                 'targetRef="Task_Simplify">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=colmapOk = '
                 'true</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '\n'
                 '    <!-- 6. Failure replanner (LangGraph) — bounded retry policy.\n'
                 '         attempt = (current attempt_count from row) + 1. The worker\n'
                 '         caps retries at 2 attempts and falls back to downgradeOsm so\n'
                 '         transient failures never permanently brick a tile. -->\n'
                 '    <bpmn:serviceTask id="Task_Replan" name="replan reconstruction '
                 '(LangGraph)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="maps3d.replanReconstruction"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=tileRows[1].tile_h3" target="tileH3"/>\n'
                 '          <zeebe:input source="=if colmapErrorCode = null then '
                 '&quot;TIMEOUT&quot; else colmapErrorCode" target="errorCode"/>\n'
                 '          <zeebe:input source="=if colmapErrorMessage = null then &quot;boundary '
                 'timer fired&quot; else colmapErrorMessage" target="errorMessage"/>\n'
                 '          <zeebe:input source="=if registeredImages = null then 0 else '
                 'registeredImages" target="imageCount"/>\n'
                 '          <zeebe:input source="=(if tileRows[1].attempt_count = null then 0 else '
                 'tileRows[1].attempt_count) + 1" target="attempt"/>\n'
                 '          <zeebe:output source="=action" target="replanAction"/>\n'
                 '          <zeebe:output source="=rationale" target="replanRationale"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Colmap_No</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_ColmapTimeout</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterReplan</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterReplan" sourceRef="Task_Replan" '
                 'targetRef="Gateway_ReplanAction"/>\n'
                 '\n'
                 "    <!-- 6b. Branch on the replanner's chosen action. retry/requestMore\n"
                 '         loop the tile back into the queue (next R/PT15M tick re-picks\n'
                 '         it with attempt_count incremented). downgradeOsm marks the\n'
                 '         tile so the maps-3d UI keeps showing it via the OSM extrude\n'
                 '         (Phase-1) path. abort is reserved for unrecoverable failures\n'
                 '         and parks the tile until manual review. -->\n'
                 '    <bpmn:exclusiveGateway id="Gateway_ReplanAction" name="replan action?">\n'
                 '      <bpmn:incoming>Flow_AfterReplan</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Replan_Retry</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Replan_RequestMore</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Replan_DowngradeOsm</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Replan_Abort</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_Replan_Retry" sourceRef="Gateway_ReplanAction" '
                 'targetRef="Task_IncAttempt">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=replanAction '
                 '= "retry"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Replan_RequestMore" '
                 'sourceRef="Gateway_ReplanAction" targetRef="Task_IncAttempt">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=replanAction '
                 '= "requestMore"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Replan_DowngradeOsm" '
                 'sourceRef="Gateway_ReplanAction" targetRef="Task_MarkOsmOnly">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=replanAction '
                 '= "downgradeOsm"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Replan_Abort" sourceRef="Gateway_ReplanAction" '
                 'targetRef="Task_FailedAudit">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=replanAction '
                 '= "abort"</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '\n'
                 '    <!-- 6c. retry/requestMore — bump attempt_count, reset to pending.\n'
                 '         The R/PT15M timer-start picker will re-select this tile on\n'
                 '         the next tick. error_code + error_message are preserved on\n'
                 '         the row for observability. -->\n'
                 '    <bpmn:serviceTask id="Task_IncAttempt" name="bump attempt + requeue">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_maps3d_tile&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="={ &quot;tile_h3&quot;: tileRows[1].tile_h3, '
                 '&quot;status&quot;: &quot;pending&quot;, &quot;attempt_count&quot;: (if '
                 'tileRows[1].attempt_count = null then 0 else tileRows[1].attempt_count) + 1, '
                 '&quot;last_attempt_at&quot;: &quot;now&quot;, &quot;error_code&quot;: '
                 'colmapErrorCode, &quot;error_message&quot;: colmapErrorMessage }" '
                 'target="row"/>\n'
                 '          <zeebe:input source="=&quot;tile_h3&quot;" target="conflictKey"/>\n'
                 '          <zeebe:input '
                 'source="=&quot;status,attempt_count,last_attempt_at,error_code,error_message&quot;" '
                 'target="updateColumns"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Replan_Retry</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Replan_RequestMore</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterIncAttempt</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterIncAttempt" sourceRef="Task_IncAttempt" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <!-- 6d. downgradeOsm — terminal state for tiles where photogrammetry\n'
                 "         can't recover. The maps-3d UI still renders them via the\n"
                 '         Phase-1 OSM extrude path (BuildingExtrudeAdapter), so the user\n'
                 "         doesn't see a hole in the world; they just don't get the\n"
                 '         photoreal mesh skin. -->\n'
                 '    <bpmn:serviceTask id="Task_MarkOsmOnly" name="mark tile osm-only">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_maps3d_tile&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="={ &quot;tile_h3&quot;: tileRows[1].tile_h3, '
                 '&quot;status&quot;: &quot;osm-only&quot;, &quot;attempt_count&quot;: (if '
                 'tileRows[1].attempt_count = null then 0 else tileRows[1].attempt_count) + 1, '
                 '&quot;last_attempt_at&quot;: &quot;now&quot;, &quot;error_code&quot;: '
                 'colmapErrorCode, &quot;error_message&quot;: colmapErrorMessage }" '
                 'target="row"/>\n'
                 '          <zeebe:input source="=&quot;tile_h3&quot;" target="conflictKey"/>\n'
                 '          <zeebe:input '
                 'source="=&quot;status,attempt_count,last_attempt_at,error_code,error_message&quot;" '
                 'target="updateColumns"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Replan_DowngradeOsm</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterMarkOsmOnly</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterMarkOsmOnly" sourceRef="Task_MarkOsmOnly" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <!-- 7. Open3D simplify + saturated GLB export. -->\n'
                 '    <bpmn:serviceTask id="Task_Simplify" name="simplify + export GLB">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="maps3d.simplifyAndExport"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=tileRows[1].tile_h3" target="tileH3"/>\n'
                 '          <zeebe:input source="=rawMeshUri" target="rawMeshUri"/>\n'
                 '          <zeebe:input source="=5000" target="targetTriangles"/>\n'
                 '          <zeebe:input source="=1.3" target="saturate"/>\n'
                 '          <zeebe:input source="=false" target="segmentByFootprint"/>\n'
                 '          <zeebe:output source="=tileMeshUri" target="tileMeshUri"/>\n'
                 '          <zeebe:output source="=triangleCount" target="finalTriangles"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Colmap_Yes</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterSimplify</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterSimplify" sourceRef="Task_Simplify" '
                 'targetRef="Task_Vision"/>\n'
                 '\n'
                 '    <!-- 8. Murakumo Vision annotation across the curated images. -->\n'
                 '    <bpmn:serviceTask id="Task_Vision" name="vision annotate">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="maps3d.visionAnnotate"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=tileRows[1].tile_h3" target="tileH3"/>\n'
                 '          <zeebe:input source="=selectedIds" target="imageRefs"/>\n'
                 '          <zeebe:input source="=0.55" target="minConfidence"/>\n'
                 '          <zeebe:output source="=detections" target="visionDetections"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_AfterSimplify</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterVision</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterVision" sourceRef="Task_Vision" '
                 'targetRef="Task_LinkActor"/>\n'
                 '\n'
                 '    <!-- 9. LangGraph actor disambiguation. -->\n'
                 '    <bpmn:serviceTask id="Task_LinkActor" name="link actors (LangGraph)">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="maps3d.linkActor"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=tileRows[1].tile_h3" target="tileH3"/>\n'
                 '          <zeebe:input source="=visionDetections" target="detections"/>\n'
                 '          <zeebe:input source="=0.7" target="minConfidence"/>\n'
                 '          <zeebe:output source="=links" target="actorLinks"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_AfterVision</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterLink</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterLink" sourceRef="Task_LinkActor" '
                 'targetRef="Task_MarkDone"/>\n'
                 '\n'
                 '    <!-- 10. Mark tile done. The worker tasks have already INSERT-ed into\n'
                 '         vertex_spatial / vertex_vision_result / edge_* via Hyperdrive. -->\n'
                 '    <bpmn:serviceTask id="Task_MarkDone" name="mark tile done">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_maps3d_tile&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="={ &quot;tile_h3&quot;: tileRows[1].tile_h3, '
                 '&quot;status&quot;: &quot;done&quot;, &quot;mesh_uri&quot;: tileMeshUri, '
                 '&quot;image_count&quot;: registeredImages, &quot;triangle_count&quot;: '
                 'finalTriangles, &quot;last_attempt_at&quot;: &quot;now&quot; }" target="row"/>\n'
                 '          <zeebe:input source="=&quot;tile_h3&quot;" target="conflictKey"/>\n'
                 '          <zeebe:input '
                 'source="=&quot;status,mesh_uri,image_count,triangle_count,last_attempt_at&quot;" '
                 'target="updateColumns"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_AfterLink</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterMark</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterMark" sourceRef="Task_MarkDone" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <!-- 11. OCEL audit. -->\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit maps3d.tile.processed OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;com.etzhayyim.apps.maps3d.tile.processed&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;tileH3&quot;: tileRows[1].tile_h3, '
                 '&quot;triangles&quot;: finalTriangles, &quot;cameras&quot;: registeredImages, '
                 '&quot;detections&quot;: count(visionDetections), &quot;links&quot;: '
                 'count(actorLinks) }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_AfterMark</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterAudit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterAudit" sourceRef="Task_Audit" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <!-- Failure-path audit. Reached only on (a) curator abort (too few\n'
                 '         curated images) or (b) explicit abort from the replanner.\n'
                 "         Marks the row 'failed' so the picker won't immediately re-pick\n"
                 '         it; manual SQL reset is required to retry. -->\n'
                 '    <bpmn:serviceTask id="Task_FailedAudit" name="mark tile failed">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_maps3d_tile&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="={ &quot;tile_h3&quot;: tileRows[1].tile_h3, '
                 '&quot;status&quot;: &quot;failed&quot;, &quot;last_attempt_at&quot;: '
                 '&quot;now&quot; }" target="row"/>\n'
                 '          <zeebe:input source="=&quot;tile_h3&quot;" target="conflictKey"/>\n'
                 '          <zeebe:input source="=&quot;status,last_attempt_at&quot;" '
                 'target="updateColumns"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Curate_No</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Replan_Abort</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AfterFailedAudit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AfterFailedAudit" sourceRef="Task_FailedAudit" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_AfterAudit</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_AfterFailedAudit</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_AfterIncAttempt</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_AfterMarkOsmOnly</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_No_HasTile</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 22100,
                 '00-contracts/bpmn/com/etzhayyim/maps3d/processTile.bpmn',
                 '2026-04-26T01:00:00+09:00',
                 'did:web:bpmn.etzhayyim.com',
                 'did:web:bpmn.etzhayyim.com',
                 'sys.bpmn.seed.maps3d',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/maps3d-process-tile-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (vertex_id, owner_did, nsid, '
         'bpmn_process_id, bpmn_version, result_timeout_ms, status, created_at, sensitivity_ord, '
         'org_id, user_id, actor_id)\n'
         "    SELECT $1, $2, $3, $4, 1, CAST($5 AS integer), 'active', $6, 1, $7, $8, $9\n"
         '    WHERE NOT EXISTS (SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $10)\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.lexiconBinding/maps3d-process-tile-v1',
                 'did:web:bpmn.etzhayyim.com',
                 'com.etzhayyim.apps.maps3d.processTile',
                 'maps3d_process_tile',
                 5400000,
                 '2026-04-26T01:00:00+09:00',
                 'did:web:bpmn.etzhayyim.com',
                 'did:web:bpmn.etzhayyim.com',
                 'sys.bpmn.seed.maps3d',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.lexiconBinding/maps3d-process-tile-v1']}]

DOWN = [{'sql': 'DELETE FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.lexiconBinding/maps3d-process-tile-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_process_def WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/maps3d-process-tile-v1']},
 {'sql': 'DROP TABLE IF EXISTS vertex_langgraph_state', 'parameters': []},
 {'sql': 'DROP TABLE IF EXISTS vertex_maps3d_tile', 'parameters': []}]


def upgrade() -> None:
    execute_bound_statements(op.get_bind(), UP)


def downgrade() -> None:
    execute_bound_statements(op.get_bind(), DOWN)
