"""Captured from Kysely migration 20260430600300_update_copyright_bpmn_generic."""

from __future__ import annotations

from alembic import op

from graph_schema.db import execute_bound_statements


revision = "r_20260430600300_update_copyright_bpmn_generic"
down_revision = 'r_20260430600200_seed_copyright_mcp_tools'
branch_labels = None
depends_on = None

UP = [{'sql': 'UPDATE vertex_bpmn_process_def\n'
         '              SET "xml" = $1, xml_byte_size = $2::integer, "version" = 2\n'
         '              WHERE vertex_id = $3',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — ingests Crossref REST API works into vertex_work daily.\n'
                 '  Generic primitives only: generic.http.fetch + generic.db.bulkInsert + '
                 'generic.audit.emit\n'
                 '  No custom Python handler required (v2 rewrite, 2026-04-30).\n'
                 '  Single-page fetch: 100 most-recent works sorted by indexed desc.\n'
                 '  vertex_id dedup: RisingWave PK overwrite — safe to re-ingest same DOI.\n'
                 '  NSID: com.etzhayyim.apps.copyright.ingestCrossref\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/copyright-crossref-ingest-v2\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_copyright_crossref_ingest"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/copyright"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="2.0">\n'
                 '  <bpmn:process id="copyright_crossref_ingest" name="copyright crossref ingest" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.copyright.ingestCrossref", "version": 2, '
                 '"resultTimeoutMs": 120000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 1 day">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_P1D">\n'
                 '        <bpmn:timeCycle '
                 'xsi:type="bpmn:tFormalExpression">R/P1D</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer"  sourceRef="Start_Timer"  '
                 'targetRef="Task_Fetch"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Fetch"/>\n'
                 '\n'
                 '    <!-- Step 1: fetch 100 most-recent Crossref works (polite pool, mailto '
                 'param) -->\n'
                 '    <bpmn:serviceTask id="Task_Fetch" name="fetch Crossref works">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.http.fetch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;https://api.crossref.org/works?rows=100&amp;sort=indexed&amp;order=desc&amp;filter=from-pub-date%3A2020&amp;mailto=jun%40etzhayyim.com&quot;" '
                 'target="url"/>\n'
                 '          <zeebe:input source="=&quot;GET&quot;" target="method"/>\n'
                 '          <zeebe:input source="={ &quot;User-Agent&quot;: '
                 '&quot;etzhayyim-copyright/2.0 (mailto:jun@etzhayyim.com)&quot;, &quot;Accept&quot;: '
                 '&quot;application/json&quot; }" target="headers"/>\n'
                 '          <zeebe:input source="=60" target="timeoutSec"/>\n'
                 '          <zeebe:output source="=bodyJson" target="crossrefBody"/>\n'
                 '          <zeebe:output source="=status"   target="fetchStatus"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Fetch" '
                 'targetRef="Task_Insert"/>\n'
                 '\n'
                 '    <!-- Step 2: FEEL-transform items and bulk-insert into vertex_work -->\n'
                 '    <bpmn:serviceTask id="Task_Insert" name="bulk insert vertex_work">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.bulkInsert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_work&quot;" target="table"/>\n'
                 '          <zeebe:input source="= if crossrefBody != null and '
                 'crossrefBody.message != null and crossrefBody.message.items != null then for '
                 'item in crossrefBody.message.items[item.DOI != null] return { '
                 '&quot;vertex_id&quot;: '
                 '&quot;at://did:web:copyright.etzhayyim.com:crossref/com.etzhayyim.apps.copyright.work/doi-&quot; '
                 '+ replace(item.DOI, &quot;/&quot;, &quot;-&quot;), &quot;owner_did&quot;: '
                 '&quot;did:web:copyright.etzhayyim.com:crossref&quot;, &quot;rkey&quot;: '
                 '&quot;doi-&quot; + replace(item.DOI, &quot;/&quot;, &quot;-&quot;), '
                 '&quot;repo&quot;: &quot;did:web:copyright.etzhayyim.com:crossref&quot;, '
                 '&quot;did&quot;: &quot;did:web:copyright.etzhayyim.com:crossref&quot;, '
                 '&quot;status&quot;: &quot;active&quot;, &quot;kind&quot;: if item.type = '
                 '&quot;dataset&quot; or item.type = &quot;component&quot; then '
                 '&quot;dataset&quot; else &quot;literary&quot;, &quot;title&quot;: if item.title '
                 '!= null and count(item.title) &gt; 0 then item.title[1] else &quot;(no '
                 'title)&quot;, &quot;doi&quot;: item.DOI, &quot;registry&quot;: '
                 '&quot;crossref&quot;, &quot;berne_automatic&quot;: true, &quot;source_url&quot;: '
                 '&quot;https://doi.org/&quot; + item.DOI, &quot;collected_at&quot;: '
                 'string(now()), &quot;sensitivity_ord&quot;: 100 } else []" target="rows"/>\n'
                 '          <zeebe:output source="=inserted" target="rowsInserted"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_Insert" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <!-- Step 3: OCEL audit event -->\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit crossref.ingest OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;com.etzhayyim.apps.copyright.crossref.ingest.completed&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;registry&quot;: &quot;crossref&quot;, '
                 '&quot;rowsInserted&quot;: rowsInserted, &quot;fetchStatus&quot;: fetchStatus }" '
                 'target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_4</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_4" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_4</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 5782,
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/copyright-crossref-ingest-v1']},
 {'sql': 'UPDATE vertex_bpmn_process_def\n'
         '              SET "xml" = $1, xml_byte_size = $2::integer, "version" = 2\n'
         '              WHERE vertex_id = $3',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — ingests DataCite REST API DOIs into vertex_work daily.\n'
                 '  Generic primitives only: generic.http.fetch + generic.db.bulkInsert + '
                 'generic.audit.emit\n'
                 '  No custom Python handler required (v2 rewrite, 2026-04-30).\n'
                 '  Single-page fetch: 100 most-recent DOIs sorted by created desc.\n'
                 '  vertex_id dedup: RisingWave PK overwrite — safe to re-ingest same DOI.\n'
                 '  NSID: com.etzhayyim.apps.copyright.ingestDatacite\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/copyright-datacite-ingest-v2\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_copyright_datacite_ingest"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/copyright"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="2.0">\n'
                 '  <bpmn:process id="copyright_datacite_ingest" name="copyright datacite ingest" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.copyright.ingestDatacite", "version": 2, '
                 '"resultTimeoutMs": 120000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 1 day">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_P1D">\n'
                 '        <bpmn:timeCycle '
                 'xsi:type="bpmn:tFormalExpression">R/P1D</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer"  sourceRef="Start_Timer"  '
                 'targetRef="Task_Fetch"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_Fetch"/>\n'
                 '\n'
                 '    <!-- Step 1: fetch 100 most-recent DataCite DOIs -->\n'
                 '    <bpmn:serviceTask id="Task_Fetch" name="fetch DataCite DOIs">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.http.fetch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;https://api.datacite.org/dois?page%5Bsize%5D=100&amp;sort=created&amp;direction=desc&quot;" '
                 'target="url"/>\n'
                 '          <zeebe:input source="=&quot;GET&quot;" target="method"/>\n'
                 '          <zeebe:input source="={ &quot;Accept&quot;: '
                 '&quot;application/json&quot; }" target="headers"/>\n'
                 '          <zeebe:input source="=60" target="timeoutSec"/>\n'
                 '          <zeebe:output source="=bodyJson" target="dataciteBody"/>\n'
                 '          <zeebe:output source="=status"   target="fetchStatus"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Fetch" '
                 'targetRef="Task_Insert"/>\n'
                 '\n'
                 '    <!-- Step 2: FEEL-transform items and bulk-insert into vertex_work -->\n'
                 '    <bpmn:serviceTask id="Task_Insert" name="bulk insert vertex_work">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.bulkInsert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_work&quot;" target="table"/>\n'
                 '          <zeebe:input source="= if dataciteBody != null and dataciteBody.data '
                 '!= null then for item in dataciteBody.data[item.attributes != null and '
                 'item.attributes.doi != null] return { &quot;vertex_id&quot;: '
                 '&quot;at://did:web:copyright.etzhayyim.com:datacite/com.etzhayyim.apps.copyright.work/doi-&quot; '
                 '+ replace(item.attributes.doi, &quot;/&quot;, &quot;-&quot;), '
                 '&quot;owner_did&quot;: &quot;did:web:copyright.etzhayyim.com:datacite&quot;, '
                 '&quot;rkey&quot;: &quot;doi-&quot; + replace(item.attributes.doi, &quot;/&quot;, '
                 '&quot;-&quot;), &quot;repo&quot;: '
                 '&quot;did:web:copyright.etzhayyim.com:datacite&quot;, &quot;did&quot;: '
                 '&quot;did:web:copyright.etzhayyim.com:datacite&quot;, &quot;status&quot;: '
                 '&quot;active&quot;, &quot;kind&quot;: if item.attributes.types != null and '
                 '(item.attributes.types.resourceTypeGeneral = &quot;Dataset&quot; or '
                 'item.attributes.types.resourceTypeGeneral = &quot;Model&quot;) then '
                 '&quot;dataset&quot; else if item.attributes.types != null and '
                 '(item.attributes.types.resourceTypeGeneral = &quot;Software&quot; or '
                 'item.attributes.types.resourceTypeGeneral = &quot;InteractiveResource&quot; or '
                 'item.attributes.types.resourceTypeGeneral = &quot;Workflow&quot; or '
                 'item.attributes.types.resourceTypeGeneral = &quot;Service&quot;) then '
                 '&quot;software&quot; else if item.attributes.types != null and '
                 'item.attributes.types.resourceTypeGeneral = &quot;Audiovisual&quot; then '
                 '&quot;audiovisual&quot; else if item.attributes.types != null and '
                 'item.attributes.types.resourceTypeGeneral = &quot;Image&quot; then '
                 '&quot;visual&quot; else if item.attributes.types != null and '
                 'item.attributes.types.resourceTypeGeneral = &quot;Sound&quot; then '
                 '&quot;musical&quot; else &quot;literary&quot;, &quot;title&quot;: if '
                 'item.attributes.titles != null and count(item.attributes.titles) &gt; 0 then '
                 'item.attributes.titles[1].title else &quot;(no title)&quot;, &quot;doi&quot;: '
                 'item.attributes.doi, &quot;registry&quot;: &quot;datacite&quot;, '
                 '&quot;berne_automatic&quot;: true, &quot;source_url&quot;: '
                 '&quot;https://doi.org/&quot; + item.attributes.doi, &quot;collected_at&quot;: '
                 'string(now()), &quot;sensitivity_ord&quot;: 100 } else []" target="rows"/>\n'
                 '          <zeebe:output source="=inserted" target="rowsInserted"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_Insert" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <!-- Step 3: OCEL audit event -->\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit datacite.ingest OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;com.etzhayyim.apps.copyright.datacite.ingest.completed&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;registry&quot;: &quot;datacite&quot;, '
                 '&quot;rowsInserted&quot;: rowsInserted, &quot;fetchStatus&quot;: fetchStatus }" '
                 'target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_4</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_4" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_4</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 6538,
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/copyright-datacite-ingest-v1']},
 {'sql': 'UPDATE vertex_bpmn_process_def\n'
         '              SET "xml" = $1, xml_byte_size = $2::integer, "version" = 2\n'
         '              WHERE vertex_id = $3',
  'parameters': ['<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Timer-start BPMN — delta-aware copyright coverage social post every 6 hours.\n'
                 '  Generic primitives only: generic.db.select + generic.llm.chat + '
                 'generic.pds.dispatch + generic.db.insert\n'
                 '  No custom Python handler required (v2 rewrite, 2026-04-30).\n'
                 '  Skips post if total vertex_work count delta < minDelta since last post.\n'
                 '  NSID: com.etzhayyim.apps.copyright.socialCoverageReport\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/copyright-coverage-report-v2\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_copyright_coverage_report"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/copyright"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="2.0">\n'
                 '  <bpmn:process id="copyright_coverage_report" name="copyright coverage report" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.copyright.socialCoverageReport", "version": 2, '
                 '"resultTimeoutMs": 120000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 6 hours">\n'
                 '      <bpmn:outgoing>Flow_Timer</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_PT6H">\n'
                 '        <bpmn:timeCycle '
                 'xsi:type="bpmn:tFormalExpression">R/PT6H</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual / on-demand">\n'
                 '      <bpmn:outgoing>Flow_Manual</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_Timer"  sourceRef="Start_Timer"  '
                 'targetRef="Task_GetTotal"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_Manual" sourceRef="Start_Manual" '
                 'targetRef="Task_GetTotal"/>\n'
                 '\n'
                 '    <!-- Step 1: count total vertex_work rows -->\n'
                 '    <bpmn:serviceTask id="Task_GetTotal" name="count vertex_work">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;SELECT count(*) AS total_works FROM '
                 'vertex_work&quot;" target="sql"/>\n'
                 '          <zeebe:output source="= if rows != null and count(rows) &gt; 0 then '
                 'rows[1].total_works else 0" target="totalWorks"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Timer</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_Manual</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_GetTotal" '
                 'targetRef="Task_GetLastCount"/>\n'
                 '\n'
                 '    <!-- Step 2: read last-post count from ingest state -->\n'
                 '    <bpmn:serviceTask id="Task_GetLastCount" name="read last post count">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;SELECT COALESCE(last_post_count, 0) AS '
                 "last_count FROM vertex_copyright_ingest_state WHERE registry = 'coverage-report' "
                 'LIMIT 1&quot;" target="sql"/>\n'
                 '          <zeebe:output source="= if rows != null and count(rows) &gt; 0 then '
                 'rows[1].last_count else 0" target="lastCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_GetLastCount" '
                 'targetRef="GW_ShouldPost"/>\n'
                 '\n'
                 '    <!-- Gateway: post only if enough new works (or force) -->\n'
                 '    <bpmn:exclusiveGateway id="GW_ShouldPost" name="enough new works?">\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Post</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_Skip</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_Post" name="yes" sourceRef="GW_ShouldPost" '
                 'targetRef="Task_LLM">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression"><![CDATA[= '
                 '(totalWorks - lastCount) >= (if minDelta != null then minDelta else 10) or '
                 'forcePost = true]]></bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_Skip" name="no" sourceRef="GW_ShouldPost" '
                 'targetRef="Task_SkipAudit">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression"><![CDATA[= '
                 'not((totalWorks - lastCount) >= (if minDelta != null then minDelta else 10) or '
                 'forcePost = true)]]></bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '\n'
                 '    <!-- Post path: generate text via LLM -->\n'
                 '    <bpmn:serviceTask id="Task_LLM" name="generate coverage post text">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.llm.chat"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;fast&quot;" target="tier"/>\n'
                 '          <zeebe:input source="=&quot;You are the Copyright Registry agent '
                 '(copyright.etzhayyim.com). Write concise, factual social posts about global copyright '
                 'data coverage. Max 250 characters. Be engaging, mention numbers, use #copyright '
                 '#openaccess.&quot;" target="system"/>\n'
                 '          <zeebe:input source="= &quot;Coverage update: &quot; + '
                 'string(totalWorks) + &quot; works indexed. +&quot; + string(totalWorks - '
                 'lastCount) + &quot; new since last report. Registries: Crossref and DataCite. '
                 'Write a 1-2 sentence social post about this copyright coverage milestone.&quot;" '
                 'target="user"/>\n'
                 '          <zeebe:input source="=300" target="maxTokens"/>\n'
                 '          <zeebe:output source="=content" target="postText"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Post</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_5</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_5" sourceRef="Task_LLM" targetRef="Task_Post"/>\n'
                 '\n'
                 '    <!-- Post path: dispatch social post to Bluesky via C-path -->\n'
                 '    <bpmn:serviceTask id="Task_Post" name="post to copyright.etzhayyim.com">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.pds.dispatch"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;app.bsky.feed.post&quot;" target="type"/>\n'
                 '          <zeebe:input source="={ &quot;repo&quot;: '
                 '&quot;did:web:copyright.etzhayyim.com&quot;, &quot;text&quot;: postText, '
                 '&quot;langs&quot;: [&quot;en&quot;] }" target="payload"/>\n'
                 '          <zeebe:output source="=uri" target="postUri"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_5</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_6</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_6" sourceRef="Task_Post" '
                 'targetRef="Task_UpdateState"/>\n'
                 '\n'
                 '    <!-- Post path: persist new total as last-post count -->\n'
                 '    <bpmn:serviceTask id="Task_UpdateState" name="update coverage state">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;INSERT INTO vertex_copyright_ingest_state '
                 '(registry, cursor, last_ingested_at, total_ingested, last_post_count, '
                 "last_posted_at, owner_did, created_at, updated_at) VALUES ('coverage-report', "
                 '\'\', NOW(), $1, $1, NOW(), \'did:web:copyright.etzhayyim.com\', NOW(), NOW())&quot;" '
                 'target="sql"/>\n'
                 '          <zeebe:input source="=[totalWorks]" target="params"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_6</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_7</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_7" sourceRef="Task_UpdateState" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <!-- Post path audit -->\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit coverage.report OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;com.etzhayyim.apps.copyright.coverage.report.fired&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;posted&quot;: true, '
                 '&quot;totalWorks&quot;: totalWorks, &quot;delta&quot;: totalWorks - lastCount, '
                 '&quot;postUri&quot;: postUri }" target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_7</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_End_Post</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End_Post" sourceRef="Task_Audit" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <!-- Skip path audit -->\n'
                 '    <bpmn:serviceTask id="Task_SkipAudit" name="emit coverage.skipped OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input '
                 'source="=&quot;com.etzhayyim.apps.copyright.coverage.report.skipped&quot;" '
                 'target="eventType"/>\n'
                 '          <zeebe:input source="={ &quot;posted&quot;: false, '
                 '&quot;totalWorks&quot;: totalWorks, &quot;delta&quot;: totalWorks - lastCount }" '
                 'target="attributes"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Skip</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_End_Skip</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End_Skip" sourceRef="Task_SkipAudit" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="done">\n'
                 '      <bpmn:incoming>Flow_End_Post</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_End_Skip</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 9049,
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/copyright-coverage-report-v1']}]

DOWN = []


def upgrade() -> None:
    execute_bound_statements(op.get_bind(), UP)


def downgrade() -> None:
    execute_bound_statements(op.get_bind(), DOWN)
