"""Captured from Kysely migration 20260429091300_seed_coverage_lda_core_bpmn_actors."""

from __future__ import annotations

from alembic import op

from graph_schema.db import execute_bound_statements


revision = "r_20260429091300_seed_coverage_lda_core_bpmn_actors"
down_revision = 'r_20260429091200_seed_coverage_lda_fission_incremental_bpmn_acto'
branch_labels = None
depends_on = None

UP = [{'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id, owner_did, bpmn_process_id, version, xml, xml_byte_size,\n'
         '      source_path, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, 1,\n'
         "      $4, CAST($5 AS integer), $6, 'active',\n"
         '      $7, 1, $8, $9, $10\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $11\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/coverage-inferLdaSignals-v1',
                 'did:web:coverage.etzhayyim.com',
                 'coverage_infer_lda_signals',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  coverage.inferLdaSignals — Phase A of LDA latent entity inference (ADR-0096).\n'
                 '\n'
                 '  Extracts observable signal tokens from RisingWave vertex tables and\n'
                 '  refreshes vertex_lda_signal doc_frequency counts. Runs daily to keep\n'
                 '  signal vocabulary up-to-date as new observable records arrive.\n'
                 '\n'
                 '  Pipeline:\n'
                 '    1. generic.db.select  — read active viewpoints from vertex_lda_viewpoint\n'
                 '    2. generic.db.select  — count observable records per source collection '
                 '(corpus size)\n'
                 '    3. generic.db.select  — read signals needing doc_frequency refresh\n'
                 '    4. generic.db.select  — aggregate doc_frequency from each source collection\n'
                 '    5. generic.db.bulkInsert — upsert refreshed doc_frequency + idf_score into '
                 'vertex_lda_signal\n'
                 '    6. generic.audit.emit — OCEL summary\n'
                 '\n'
                 '  Trigger:\n'
                 '    timer-start R/P1D (daily) AND XRPC '
                 '(`com.etzhayyim.apps.coverage.inferLdaSignals`).\n'
                 '\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/coverage-infer-lda-signals-v1\n'
                 '  NSID:      com.etzhayyim.apps.coverage.inferLdaSignals\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_coverage_infer_lda_signals"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/coverage"\n'
                 '    exporter="hand-written" exporterVersion="2.0">\n'
                 '  <bpmn:process id="coverage_infer_lda_signals" name="coverage infer LDA '
                 'signals" isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.coverage.inferLdaSignals", "version": 1, '
                 '"resultTimeoutMs": 120000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 1 day">\n'
                 '      <bpmn:outgoing>Flow_1</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_P1D">\n'
                 '        <bpmn:timeCycle '
                 'xsi:type="bpmn:tFormalExpression">R/P1D</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual trigger">\n'
                 '      <bpmn:outgoing>Flow_0</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_0" sourceRef="Start_Manual" '
                 'targetRef="Task_ReadViewpoints"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_1" sourceRef="Start_Timer"  '
                 'targetRef="Task_ReadViewpoints"/>\n'
                 '\n'
                 '    <!-- Step 1: Read active viewpoints -->\n'
                 '    <bpmn:serviceTask id="Task_ReadViewpoints" name="read active viewpoints">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_lda_viewpoint&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=&quot;vertex_id, viewpoint_kind, '
                 'signal_vocab_size&quot;" target="columns"/>\n'
                 '          <zeebe:input source="=&quot;active = true&quot;" target="where"/>\n'
                 '          <zeebe:input source="=10" target="limit"/>\n'
                 '          <zeebe:output source="=rows"     target="viewpoints"/>\n'
                 '          <zeebe:output source="=rowCount" target="viewpointCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_0</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_1</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_ReadViewpoints" '
                 'targetRef="Task_ReadCorpusSize"/>\n'
                 '\n'
                 '    <!-- Step 2: Count corpus size for IDF computation -->\n'
                 '    <bpmn:serviceTask id="Task_ReadCorpusSize" name="count observable corpus '
                 'size">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_repo_record&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=&quot;COUNT(*) AS corpus_size&quot;" '
                 'target="columns"/>\n'
                 '          <zeebe:input source="=1" target="limit"/>\n'
                 '          <zeebe:output source="=rows[1].corpus_size" target="corpusSize"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_ReadCorpusSize" '
                 'targetRef="Task_ReadSignals"/>\n'
                 '\n'
                 '    <!-- Step 3: Read signals needing refresh (all, batch 500) -->\n'
                 '    <bpmn:serviceTask id="Task_ReadSignals" name="read signals to refresh">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_lda_signal&quot;" target="table"/>\n'
                 '          <zeebe:input source="=&quot;vertex_id, viewpoint_vid, signal_token, '
                 'signal_kind, source_collection, extraction_expr, doc_frequency&quot;" '
                 'target="columns"/>\n'
                 '          <zeebe:input source="=if (batchSize = null) then 500 else batchSize" '
                 'target="limit"/>\n'
                 '          <zeebe:input source="=&quot;vertex_id ASC&quot;" target="orderBy"/>\n'
                 '          <zeebe:output source="=rows"     target="signals"/>\n'
                 '          <zeebe:output source="=rowCount" target="signalCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_4</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_4" sourceRef="Task_ReadSignals" '
                 'targetRef="Gateway_HasSignals"/>\n'
                 '    <bpmn:exclusiveGateway id="Gateway_HasSignals" name="has signals?" '
                 'default="Flow_NoSignals">\n'
                 '      <bpmn:incoming>Flow_4</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_4a</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_NoSignals</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_4a" sourceRef="Gateway_HasSignals" '
                 'targetRef="Task_ReadCollectionCounts">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=signalCount '
                 '&gt; 0</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '\n'
                 '    <!-- Step 4: Count records per collection for freq estimation -->\n'
                 '    <bpmn:serviceTask id="Task_ReadCollectionCounts" name="count records per '
                 'source collection">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_repo_record&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=&quot;collection AS source_collection, COUNT(*) '
                 'AS cnt&quot;" target="columns"/>\n'
                 '          <zeebe:input source="=&quot;collection IS NOT NULL&quot;" '
                 'target="where"/>\n'
                 '          <zeebe:input source="=100" target="limit"/>\n'
                 '          <zeebe:input source="=&quot;source_collection&quot;" '
                 'target="groupBy"/>\n'
                 '          <zeebe:output source="=rows"     target="collectionCounts"/>\n'
                 '          <zeebe:output source="=rowCount" target="collectionCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_4a</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_5</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_5" sourceRef="Task_ReadCollectionCounts" '
                 'targetRef="Task_UpsertSignals"/>\n'
                 '\n'
                 '    <!-- Step 5: Bulk-upsert signals with refreshed IDF scores -->\n'
                 '    <bpmn:serviceTask id="Task_UpsertSignals" name="upsert signal doc_frequency '
                 'and idf">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.bulkInsert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_lda_signal&quot;" target="table"/>\n'
                 '          <zeebe:input source="=for s in signals return {\n'
                 '    &quot;vertex_id&quot;:         s.vertex_id,\n'
                 '    &quot;_seq&quot;:              1,\n'
                 '    &quot;sensitivity_ord&quot;:   0,\n'
                 '    &quot;owner_did&quot;:         &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;viewpoint_vid&quot;:     s.viewpoint_vid,\n'
                 '    &quot;signal_token&quot;:      s.signal_token,\n'
                 '    &quot;signal_kind&quot;:       s.signal_kind,\n'
                 '    &quot;source_collection&quot;: s.source_collection,\n'
                 '    &quot;extraction_expr&quot;:   s.extraction_expr,\n'
                 '    &quot;doc_frequency&quot;:     if (count(collectionCounts[source_collection '
                 '= s.source_collection]) > 0) then collectionCounts[source_collection = '
                 's.source_collection][1].cnt else s.doc_frequency,\n'
                 '    &quot;idf_score&quot;:         if (corpusSize > 0 and (if '
                 '(count(collectionCounts[source_collection = s.source_collection]) > 0) then '
                 'collectionCounts[source_collection = s.source_collection][1].cnt else '
                 's.doc_frequency) > 0) then corpusSize / (if '
                 '(count(collectionCounts[source_collection = s.source_collection]) > 0) then '
                 'collectionCounts[source_collection = s.source_collection][1].cnt else '
                 's.doc_frequency) else 1.0,\n'
                 '    &quot;actor_did&quot;:         &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;org_did&quot;:           &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;created_at&quot;:        now()\n'
                 '  }" target="rows"/>\n'
                 '          <zeebe:output source="=inserted" target="upsertedCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_5</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_6</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_6" sourceRef="Task_UpsertSignals" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <!-- Step 6: OCEL audit -->\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit LDA signals OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:coverage.etzhayyim.com&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;coverage.inferLdaSignals.refresh&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={\n'
                 '            &quot;viewpoint_count&quot;:    viewpointCount,\n'
                 '            &quot;signal_count&quot;:       signalCount,\n'
                 '            &quot;signals_upserted&quot;:   upsertedCount,\n'
                 '            &quot;corpus_size&quot;:        corpusSize,\n'
                 '            &quot;collection_count&quot;:   collectionCount\n'
                 '          }" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_6</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_7</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_7" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditNoSignals" name="audit no LDA signals">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:coverage.etzhayyim.com&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;coverage.inferLdaSignals.abort&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={&quot;reason&quot;: '
                 '&quot;no_signals_to_refresh&quot;, &quot;viewpoint_count&quot;: viewpointCount, '
                 '&quot;signal_count&quot;: signalCount, &quot;corpus_size&quot;: corpusSize}" '
                 'target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_NoSignals</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_NoSignalsEnd</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_NoSignals" sourceRef="Gateway_HasSignals" '
                 'targetRef="Task_AuditNoSignals"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_NoSignalsEnd" sourceRef="Task_AuditNoSignals" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End">\n'
                 '      <bpmn:incoming>Flow_7</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_NoSignalsEnd</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 11028,
                 '00-contracts/bpmn/com/etzhayyim/coverage/inferLdaSignals.bpmn',
                 '2026-04-29T09:13:00Z',
                 'did:web:coverage.etzhayyim.com',
                 'did:web:coverage.etzhayyim.com',
                 'sys.bpmn.seed.coverage',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/coverage-inferLdaSignals-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id, owner_did, nsid, bpmn_process_id, bpmn_version,\n'
         '      result_timeout_ms, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, $4, 1,\n'
         "      CAST($5 AS integer), 'active',\n"
         '      $6, 1, $7, $8, $9\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $10\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/coverage-inferLdaSignals-v1',
                 'did:web:coverage.etzhayyim.com',
                 'com.etzhayyim.apps.coverage.inferLdaSignals',
                 'coverage_infer_lda_signals',
                 120000,
                 '2026-04-29T09:13:00Z',
                 'did:web:coverage.etzhayyim.com',
                 'did:web:coverage.etzhayyim.com',
                 'sys.bpmn.seed.coverage',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/coverage-inferLdaSignals-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id, owner_did, bpmn_process_id, version, xml, xml_byte_size,\n'
         '      source_path, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, 1,\n'
         "      $4, CAST($5 AS integer), $6, 'active',\n"
         '      $7, 1, $8, $9, $10\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $11\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/coverage-inferLdaTopics-v1',
                 'did:web:coverage.etzhayyim.com',
                 'coverage_infer_lda_topics',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  coverage.inferLdaTopics — Phase B of LDA latent entity inference (ADR-0096).\n'
                 '\n'
                 '  Reads the current signal vocabulary and observable record corpus, runs\n'
                 '  Gibbs sampling (via Murakumo Python External UDF, io_threads=100) to\n'
                 '  converge K latent topics, then writes vertex_lda_topic and\n'
                 '  edge_topic_signal_weight (φ distribution) to RisingWave.\n'
                 '\n'
                 '  Per ADR-0044: Gibbs sampling is heavy Python (numpy/scipy) → Python\n'
                 '  External UDF with io_threads=100. Called via generic.llm.json which\n'
                 '  bridges to the pymagatama LDA module.\n'
                 '\n'
                 '  Pipeline:\n'
                 '    1. generic.db.select  — read converged model watermark (latest model_slug)\n'
                 '    2. generic.db.select  — read signal vocabulary per viewpoint (< 500 '
                 'signals)\n'
                 '    3. generic.db.select  — read observable record sample (up to 10K records)\n'
                 '    4. generic.llm.json   — Gibbs sampling → K topic↔signal weight matrices\n'
                 '    5. generic.db.insert  — write vertex_lda_model metadata\n'
                 '    6. generic.db.bulkInsert — write vertex_lda_topic (K rows)\n'
                 '    7. generic.db.bulkInsert — write edge_topic_signal_weight (K × vocab rows)\n'
                 '    8. generic.audit.emit — OCEL summary\n'
                 '\n'
                 '  Trigger:\n'
                 '    timer-start R/P7D (weekly) AND XRPC '
                 '(`com.etzhayyim.apps.coverage.inferLdaTopics`).\n'
                 '\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/coverage-infer-lda-topics-v1\n'
                 '  NSID:      com.etzhayyim.apps.coverage.inferLdaTopics\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_coverage_infer_lda_topics"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/coverage"\n'
                 '    exporter="hand-written" exporterVersion="2.0">\n'
                 '  <bpmn:process id="coverage_infer_lda_topics" name="coverage infer LDA topics" '
                 'isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.coverage.inferLdaTopics", "version": 1, '
                 '"resultTimeoutMs": 600000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 7 days">\n'
                 '      <bpmn:outgoing>Flow_1</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_P7D">\n'
                 '        <bpmn:timeCycle '
                 'xsi:type="bpmn:tFormalExpression">R/P7D</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual trigger">\n'
                 '      <bpmn:outgoing>Flow_0</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_0" sourceRef="Start_Manual" '
                 'targetRef="Task_ReadModelWatermark"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_1" sourceRef="Start_Timer"  '
                 'targetRef="Task_ReadModelWatermark"/>\n'
                 '\n'
                 '    <!-- Step 1: Read latest converged model watermark -->\n'
                 '    <bpmn:serviceTask id="Task_ReadModelWatermark" name="read latest model '
                 'watermark">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;mv_lda_model_latest&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=&quot;training_corpus, model_vid, k_topics, '
                 'perplexity, trained_at&quot;" target="columns"/>\n'
                 '          <zeebe:input source="=5" target="limit"/>\n'
                 '          <zeebe:output source="=rows"     target="latestModels"/>\n'
                 '          <zeebe:output source="=rowCount" target="modelCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_0</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_1</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_ReadModelWatermark" '
                 'targetRef="Task_ReadSignalVocab"/>\n'
                 '\n'
                 '    <!-- Step 2: Read signal vocabulary (bounded: < 500 signals per ADR-0096) '
                 '-->\n'
                 '    <bpmn:serviceTask id="Task_ReadSignalVocab" name="read signal vocabulary">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_lda_signal&quot;" target="table"/>\n'
                 '          <zeebe:input source="=&quot;vertex_id, viewpoint_vid, signal_token, '
                 'signal_kind, doc_frequency, idf_score&quot;" target="columns"/>\n'
                 '          <zeebe:input source="=&quot;doc_frequency > 0&quot;" target="where"/>\n'
                 '          <zeebe:input source="=500" target="limit"/>\n'
                 '          <zeebe:input source="=&quot;idf_score DESC&quot;" target="orderBy"/>\n'
                 '          <zeebe:output source="=rows"     target="signalVocab"/>\n'
                 '          <zeebe:output source="=rowCount" target="vocabSize"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_ReadSignalVocab" '
                 'targetRef="Task_ReadRecordSample"/>\n'
                 '\n'
                 '    <!-- Step 3: Read record sample for training corpus -->\n'
                 '    <bpmn:serviceTask id="Task_ReadRecordSample" name="read observable record '
                 'sample">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_repo_record&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=&quot;vertex_id, collection, owner_did&quot;" '
                 'target="columns"/>\n'
                 '          <zeebe:input source="=if (sampleSize = null) then 10000 else '
                 'sampleSize" target="limit"/>\n'
                 '          <zeebe:input source="=&quot;_seq DESC&quot;" target="orderBy"/>\n'
                 '          <zeebe:output source="=rows"     target="recordSample"/>\n'
                 '          <zeebe:output source="=rowCount" target="sampleCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_4</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_4" sourceRef="Task_ReadRecordSample" '
                 'targetRef="Gateway_HasCorpus"/>\n'
                 '    <bpmn:exclusiveGateway id="Gateway_HasCorpus" name="training corpus '
                 'available?" default="Flow_NoCorpus">\n'
                 '      <bpmn:incoming>Flow_4</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_RunGibbs</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_NoCorpus</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_RunGibbs" sourceRef="Gateway_HasCorpus" '
                 'targetRef="Task_RunGibbs">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=vocabSize '
                 '&gt; 0 and sampleCount &gt; 0</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_NoCorpus" sourceRef="Gateway_HasCorpus" '
                 'targetRef="Task_AuditNoInput"/>\n'
                 '\n'
                 '    <!-- Step 4: Run LDA Gibbs sampling via Murakumo Python UDF (io_threads=100) '
                 '-->\n'
                 '    <bpmn:serviceTask id="Task_RunGibbs" name="run Gibbs sampling for K '
                 'topics">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.llm.json"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="={\n'
                 '            &quot;task&quot;:        &quot;lda_gibbs&quot;,\n'
                 '            &quot;k_topics&quot;:    if (kTopics = null) then 50 else kTopics,\n'
                 '            &quot;alpha&quot;:       if (alpha = null) then 1.0 else alpha,\n'
                 '            &quot;beta&quot;:        if (beta  = null) then 0.1 else beta,\n'
                 '            &quot;iterations&quot;: if (iters  = null) then 200 else iters,\n'
                 '            &quot;vocab&quot;:       for s in signalVocab return { '
                 '&quot;id&quot;: s.vertex_id, &quot;token&quot;: s.signal_token, '
                 '&quot;kind&quot;: s.signal_kind, &quot;idf&quot;: s.idf_score },\n'
                 '            &quot;corpus&quot;:      for r in recordSample return { '
                 '&quot;id&quot;: r.vertex_id, &quot;collection&quot;: r.collection }\n'
                 '          }" target="prompt"/>\n'
                 '          <zeebe:output source="=result.topics"       target="topicResults"/>\n'
                 '          <zeebe:output source="=result.perplexity"   target="perplexity"/>\n'
                 '          <zeebe:output source="=result.log_likelihood" '
                 'target="logLikelihood"/>\n'
                 '          <zeebe:output source="=result.convergence_iter" '
                 'target="convergenceIter"/>\n'
                 '          <zeebe:output source="=result.model_slug"   target="modelSlug"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_RunGibbs</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_5</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_5" sourceRef="Task_RunGibbs" '
                 'targetRef="Task_WriteModel"/>\n'
                 '\n'
                 '    <!-- Step 5: Write vertex_lda_model metadata -->\n'
                 '    <bpmn:serviceTask id="Task_WriteModel" name="write lda model metadata">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.insert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_lda_model&quot;" target="table"/>\n'
                 '          <zeebe:input source="={\n'
                 '            &quot;vertex_id&quot;:             '
                 '&quot;at://did:web:coverage.etzhayyim.com/com.etzhayyim.apps.coverage.ldaModel/&quot; + '
                 'modelSlug,\n'
                 '            &quot;_seq&quot;:                   1,\n'
                 '            &quot;sensitivity_ord&quot;:        0,\n'
                 '            &quot;owner_did&quot;:              '
                 '&quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '            &quot;model_slug&quot;:             modelSlug,\n'
                 '            &quot;model_version&quot;:          &quot;1.0.0&quot;,\n'
                 '            &quot;k_topics&quot;:              count(topicResults),\n'
                 '            &quot;alpha_prior&quot;:            if (alpha = null) then 1.0 else '
                 'alpha,\n'
                 '            &quot;beta_prior&quot;:             if (beta  = null) then 0.1 else '
                 'beta,\n'
                 '            &quot;training_corpus&quot;:        &quot;vertex_repo_record&quot;,\n'
                 '            &quot;training_record_count&quot;: sampleCount,\n'
                 '            &quot;viewpoints_used&quot;:        '
                 '&quot;lexical,behavioral,network,signal,semantic,temporal,geographic,economic&quot;,\n'
                 '            &quot;perplexity&quot;:             perplexity,\n'
                 '            &quot;log_likelihood&quot;:         logLikelihood,\n'
                 '            &quot;convergence_iter&quot;:       convergenceIter,\n'
                 '            &quot;status&quot;:                 &quot;converged&quot;,\n'
                 '            &quot;trained_at&quot;:             now(),\n'
                 '            &quot;actor_did&quot;:              '
                 '&quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '            &quot;org_did&quot;:               '
                 '&quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '            &quot;created_at&quot;:             now()\n'
                 '          }" target="row"/>\n'
                 '          <zeebe:output source="=inserted" target="modelInserted"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_5</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_6</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_6" sourceRef="Task_WriteModel" '
                 'targetRef="Task_WriteTopics"/>\n'
                 '\n'
                 '    <!-- Step 6: Bulk-write vertex_lda_topic (K rows) -->\n'
                 '    <bpmn:serviceTask id="Task_WriteTopics" name="write lda topics">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.bulkInsert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_lda_topic&quot;" target="table"/>\n'
                 '          <zeebe:input source="=for t in topicResults return {\n'
                 '            &quot;vertex_id&quot;:             '
                 '&quot;at://did:web:coverage.etzhayyim.com/com.etzhayyim.apps.coverage.ldaTopic/&quot; + '
                 'modelSlug + &quot;-&quot; + string(t.index),\n'
                 '            &quot;_seq&quot;:                   t.index + 1,\n'
                 '            &quot;sensitivity_ord&quot;:        0,\n'
                 '            &quot;owner_did&quot;:              '
                 '&quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '            &quot;model_vid&quot;:              '
                 '&quot;at://did:web:coverage.etzhayyim.com/com.etzhayyim.apps.coverage.ldaModel/&quot; + '
                 'modelSlug,\n'
                 '            &quot;topic_index&quot;:            t.index,\n'
                 '            &quot;primary_viewpoint_vid&quot;:  if (t.primary_viewpoint != null) '
                 'then '
                 '&quot;at://did:web:coverage.etzhayyim.com/com.etzhayyim.apps.coverage.ldaViewpoint/&quot; + '
                 't.primary_viewpoint else '
                 '&quot;at://did:web:coverage.etzhayyim.com/com.etzhayyim.apps.coverage.ldaViewpoint/lexical&quot;,\n'
                 '            &quot;topic_label&quot;:            if (t.label != null) then '
                 't.label else &quot;topic-&quot; + string(t.index),\n'
                 '            &quot;coherence_score&quot;:        if (t.coherence != null) then '
                 't.coherence else 0.0,\n'
                 '            &quot;top_signal_count&quot;:       if (t.top_signals != null) then '
                 'count(t.top_signals) else 0,\n'
                 '            &quot;entity_kind_hint&quot;:       if (t.entity_kind != null) then '
                 't.entity_kind else &quot;unknown&quot;,\n'
                 '            &quot;actor_did&quot;:              '
                 '&quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '            &quot;org_did&quot;:               '
                 '&quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '            &quot;created_at&quot;:             now()\n'
                 '          }" target="rows"/>\n'
                 '          <zeebe:output source="=inserted" target="topicsWritten"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_6</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_7</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_7" sourceRef="Task_WriteTopics" '
                 'targetRef="Task_WritePhiEdges"/>\n'
                 '\n'
                 '    <!-- Step 7: Bulk-write edge_topic_signal_weight (φ distribution) -->\n'
                 '    <bpmn:serviceTask id="Task_WritePhiEdges" name="write topic-signal weight '
                 'edges">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.bulkInsert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;edge_topic_signal_weight&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=for t in topicResults, sw in (if '
                 '(t.signal_weights != null) then t.signal_weights else [])[weight > 0.01] return '
                 '{\n'
                 '    &quot;edge_id&quot;:         &quot;lda-phi-&quot; + modelSlug + '
                 '&quot;-&quot; + string(t.index) + &quot;-&quot; + substring(sw.signal_id, 60),\n'
                 '    &quot;src_vid&quot;:         '
                 '&quot;at://did:web:coverage.etzhayyim.com/com.etzhayyim.apps.coverage.ldaTopic/&quot; + '
                 'modelSlug + &quot;-&quot; + string(t.index),\n'
                 '    &quot;dst_vid&quot;:         sw.signal_id,\n'
                 '    &quot;_seq&quot;:            1,\n'
                 '    &quot;sensitivity_ord&quot;: 0,\n'
                 '    &quot;owner_did&quot;:       &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;weight&quot;:          sw.weight,\n'
                 '    &quot;actor_did&quot;:       &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;org_did&quot;:         &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;created_at&quot;:      now()\n'
                 '  }" target="rows"/>\n'
                 '          <zeebe:output source="=inserted" target="phiEdgesWritten"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_7</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_8</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_8" sourceRef="Task_WritePhiEdges" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <!-- Step 8: OCEL audit -->\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit LDA topics OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:coverage.etzhayyim.com&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;coverage.inferLdaTopics.train&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={\n'
                 '            &quot;model_slug&quot;:      modelSlug,\n'
                 '            &quot;k_topics&quot;:       count(topicResults),\n'
                 '            &quot;vocab_size&quot;:      vocabSize,\n'
                 '            &quot;sample_count&quot;:    sampleCount,\n'
                 '            &quot;topics_written&quot;:  topicsWritten,\n'
                 '            &quot;phi_edges&quot;:       phiEdgesWritten,\n'
                 '            &quot;perplexity&quot;:      perplexity,\n'
                 '            &quot;log_likelihood&quot;:  logLikelihood,\n'
                 '            &quot;iters&quot;:           convergenceIter\n'
                 '          }" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_8</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_9</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_9" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditNoInput" name="emit LDA topics no-input '
                 'audit">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:coverage.etzhayyim.com&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;coverage.inferLdaTopics.noInput&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={ &quot;vocab_size&quot;: vocabSize, '
                 '&quot;sample_count&quot;: sampleCount, &quot;status&quot;: &quot;no-corpus&quot; '
                 '}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_NoCorpus</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_NoInputEnd</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_NoInputEnd" sourceRef="Task_AuditNoInput" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End">\n'
                 '      <bpmn:incoming>Flow_9</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_NoInputEnd</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 16379,
                 '00-contracts/bpmn/com/etzhayyim/coverage/inferLdaTopics.bpmn',
                 '2026-04-29T09:13:00Z',
                 'did:web:coverage.etzhayyim.com',
                 'did:web:coverage.etzhayyim.com',
                 'sys.bpmn.seed.coverage',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/coverage-inferLdaTopics-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id, owner_did, nsid, bpmn_process_id, bpmn_version,\n'
         '      result_timeout_ms, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, $4, 1,\n'
         "      CAST($5 AS integer), 'active',\n"
         '      $6, 1, $7, $8, $9\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $10\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/coverage-inferLdaTopics-v1',
                 'did:web:coverage.etzhayyim.com',
                 'com.etzhayyim.apps.coverage.inferLdaTopics',
                 'coverage_infer_lda_topics',
                 600000,
                 '2026-04-29T09:13:00Z',
                 'did:web:coverage.etzhayyim.com',
                 'did:web:coverage.etzhayyim.com',
                 'sys.bpmn.seed.coverage',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/coverage-inferLdaTopics-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id, owner_did, bpmn_process_id, version, xml, xml_byte_size,\n'
         '      source_path, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, 1,\n'
         "      $4, CAST($5 AS integer), $6, 'active',\n"
         '      $7, 1, $8, $9, $10\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $11\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/coverage-inferLdaEntities-v1',
                 'did:web:coverage.etzhayyim.com',
                 'coverage_infer_lda_entities',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  coverage.inferLdaEntities — Phase C of LDA latent entity inference '
                 '(ADR-0096).\n'
                 '\n'
                 '  Reads the converged topic model (from inferLdaTopics) and identifies\n'
                 '  stable topic clusters that represent latent (unobservable) entities.\n'
                 '  Creates vertex_latent_entity rows, edge_topic_entity_binding,\n'
                 '  edge_entity_evidence, and edge_entity_cohort_link (ADR-0026 bridge).\n'
                 '\n'
                 '  An entity emerges when ≥2 viewpoints independently assign high weight\n'
                 '  to the same topic cluster AND evidence_count ≥ 20 records.\n'
                 '\n'
                 '  Pipeline:\n'
                 '    1. generic.db.select  — read latest converged model + topics\n'
                 '    2. generic.db.select  — read top-N record→topic assignments (θ, high-weight '
                 'only)\n'
                 '    3. generic.db.select  — read mv_lda_topic_top_signals (consensus check)\n'
                 '    4. generic.db.bulkInsert — create vertex_latent_entity (consensus ≥ 2 '
                 'viewpoints)\n'
                 '    5. generic.db.bulkInsert — create edge_topic_entity_binding (topic→entity)\n'
                 '    6. generic.db.bulkInsert — create edge_entity_evidence (record→entity)\n'
                 '    7. generic.db.bulkInsert — create edge_entity_cohort_link (entity→ADR-0026 '
                 'cohort)\n'
                 '    8. generic.audit.emit — OCEL summary\n'
                 '\n'
                 '  Trigger:\n'
                 '    timer-start R/P7D (weekly, after inferLdaTopics) AND XRPC '
                 '(`com.etzhayyim.apps.coverage.inferLdaEntities`).\n'
                 '\n'
                 '  vertex_id: '
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/coverage-infer-lda-entities-v1\n'
                 '  NSID:      com.etzhayyim.apps.coverage.inferLdaEntities\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_coverage_infer_lda_entities"\n'
                 '    targetNamespace="https://etzhayyim.com/bpmn/coverage"\n'
                 '    exporter="hand-written" exporterVersion="2.0">\n'
                 '  <bpmn:process id="coverage_infer_lda_entities" name="coverage infer LDA '
                 'entities" isExecutable="true">\n'
                 '\n'
                 '    <bpmn:documentation>\n'
                 '      { "nsid": "com.etzhayyim.apps.coverage.inferLdaEntities", "version": 1, '
                 '"resultTimeoutMs": 300000 }\n'
                 '    </bpmn:documentation>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Timer" name="every 7 days">\n'
                 '      <bpmn:outgoing>Flow_1</bpmn:outgoing>\n'
                 '      <bpmn:timerEventDefinition id="Timer_P7D">\n'
                 '        <bpmn:timeCycle '
                 'xsi:type="bpmn:tFormalExpression">R/P7D</bpmn:timeCycle>\n'
                 '      </bpmn:timerEventDefinition>\n'
                 '    </bpmn:startEvent>\n'
                 '\n'
                 '    <bpmn:startEvent id="Start_Manual" name="manual trigger">\n'
                 '      <bpmn:outgoing>Flow_0</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '\n'
                 '    <bpmn:sequenceFlow id="Flow_0" sourceRef="Start_Manual" '
                 'targetRef="Task_ReadTopics"/>\n'
                 '    <bpmn:sequenceFlow id="Flow_1" sourceRef="Start_Timer"  '
                 'targetRef="Task_ReadTopics"/>\n'
                 '\n'
                 '    <!-- Step 1: Read latest converged topics -->\n'
                 '    <bpmn:serviceTask id="Task_ReadTopics" name="read converged topics">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_lda_topic&quot;" target="table"/>\n'
                 '          <zeebe:input source="=&quot;vertex_id, model_vid, topic_index, '
                 'primary_viewpoint_vid, topic_label, coherence_score, top_signal_count, '
                 'entity_kind_hint&quot;" target="columns"/>\n'
                 '          <zeebe:input source="=&quot;coherence_score > 0.1&quot;" '
                 'target="where"/>\n'
                 '          <zeebe:input source="=100" target="limit"/>\n'
                 '          <zeebe:input source="=&quot;coherence_score DESC&quot;" '
                 'target="orderBy"/>\n'
                 '          <zeebe:output source="=rows"     target="topics"/>\n'
                 '          <zeebe:output source="=rowCount" target="topicCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_0</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_1</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_2</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_ReadTopics" '
                 'targetRef="Gateway_HasTopics"/>\n'
                 '    <bpmn:exclusiveGateway id="Gateway_HasTopics" name="topics available?" '
                 'default="Flow_NoTopics">\n'
                 '      <bpmn:incoming>Flow_2</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ReadThetaEdges</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_NoTopics</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_ReadThetaEdges" sourceRef="Gateway_HasTopics" '
                 'targetRef="Task_ReadThetaEdges">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=topicCount '
                 '&gt; 0</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_NoTopics" sourceRef="Gateway_HasTopics" '
                 'targetRef="Task_AuditNoInput"/>\n'
                 '\n'
                 '    <!-- Step 2: Read high-weight record→topic assignments (θ, weight > 0.3) '
                 '-->\n'
                 '    <bpmn:serviceTask id="Task_ReadThetaEdges" name="read record-topic '
                 'assignments">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;edge_record_topic_weight&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=&quot;src_vid, dst_vid, weight, '
                 'source_collection&quot;" target="columns"/>\n'
                 '          <zeebe:input source="=&quot;weight > 0.3&quot;" target="where"/>\n'
                 '          <zeebe:input source="=if (thetaLimit = null) then 5000 else '
                 'thetaLimit" target="limit"/>\n'
                 '          <zeebe:input source="=&quot;weight DESC&quot;" target="orderBy"/>\n'
                 '          <zeebe:output source="=rows"     target="thetaEdges"/>\n'
                 '          <zeebe:output source="=rowCount" target="thetaCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ReadThetaEdges</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_3</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_ReadThetaEdges" '
                 'targetRef="Task_ReadTopicSignals"/>\n'
                 '\n'
                 '    <!-- Step 3: Read topic signal summary for viewpoint consensus check -->\n'
                 '    <bpmn:serviceTask id="Task_ReadTopicSignals" name="read topic signal '
                 'summary">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.select"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;mv_lda_topic_top_signals&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=&quot;topic_vid, entity_kind_hint, '
                 'coherence_score, signal_count, total_weight&quot;" target="columns"/>\n'
                 '          <zeebe:input source="=100" target="limit"/>\n'
                 '          <zeebe:output source="=rows"     target="topicSignals"/>\n'
                 '          <zeebe:output source="=rowCount" target="topicSignalCount"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_3</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_4</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_4" sourceRef="Task_ReadTopicSignals" '
                 'targetRef="Task_CreateEntities"/>\n'
                 '\n'
                 '    <!-- Step 4: Create vertex_latent_entity for topics with enough evidence '
                 '-->\n'
                 '    <bpmn:serviceTask id="Task_CreateEntities" name="create latent entities">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.bulkInsert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;vertex_latent_entity&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=for t in topics[count(thetaEdges[dst_vid = '
                 'vertex_id]) >= 5] return {\n'
                 '    &quot;vertex_id&quot;:             '
                 '&quot;at://did:web:coverage.etzhayyim.com/com.etzhayyim.apps.coverage.latentEntity/lda-&quot; '
                 '+ substring(t.vertex_id, 80),\n'
                 '    &quot;_seq&quot;:                   t.topic_index + 1,\n'
                 '    &quot;sensitivity_ord&quot;:        if (t.entity_kind_hint = '
                 '&quot;person&quot;) then 300 else 0,\n'
                 '    &quot;owner_did&quot;:              &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;entity_kind&quot;:            if (t.entity_kind_hint != null) then '
                 't.entity_kind_hint else &quot;unknown&quot;,\n'
                 '    &quot;canonical_label&quot;:        t.topic_label,\n'
                 '    &quot;existence_probability&quot;:  if (sum(for e in thetaEdges[dst_vid = '
                 't.vertex_id] return e.weight) > 0) then 1 - exp(-(sum(for e in '
                 'thetaEdges[dst_vid = t.vertex_id] return e.weight)) / 10) else 0.0,\n'
                 '    &quot;existence_mass&quot;:         sum(for e in thetaEdges[dst_vid = '
                 't.vertex_id] return e.weight),\n'
                 '    &quot;primary_viewpoint_vid&quot;:  t.primary_viewpoint_vid,\n'
                 '    &quot;primary_topic_vid&quot;:      t.vertex_id,\n'
                 '    &quot;k_evidence_count&quot;:       count(thetaEdges[dst_vid = '
                 't.vertex_id]),\n'
                 '    &quot;viewpoint_consensus&quot;:    1,\n'
                 '    &quot;fission_eligible&quot;:       (if (sum(for e in thetaEdges[dst_vid = '
                 't.vertex_id] return e.weight) > 0) then 1 - exp(-(sum(for e in '
                 'thetaEdges[dst_vid = t.vertex_id] return e.weight)) / 10) else 0.0) > 0.85 and '
                 'count(thetaEdges[dst_vid = t.vertex_id]) >= 20,\n'
                 '    &quot;status&quot;:                 if ((if (sum(for e in thetaEdges[dst_vid '
                 '= t.vertex_id] return e.weight) > 0) then 1 - exp(-(sum(for e in '
                 'thetaEdges[dst_vid = t.vertex_id] return e.weight)) / 10) else 0.0) > 0.5) then '
                 '&quot;emerging&quot; else &quot;latent&quot;,\n'
                 '    &quot;actor_did&quot;:              &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;org_did&quot;:               &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;created_at&quot;:             now()\n'
                 '  }" target="rows"/>\n'
                 '          <zeebe:output source="=inserted" target="entitiesCreated"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_4</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_5</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_5" sourceRef="Task_CreateEntities" '
                 'targetRef="Task_BindTopics"/>\n'
                 '\n'
                 '    <!-- Step 5: Create edge_topic_entity_binding (topic → entity) -->\n'
                 '    <bpmn:serviceTask id="Task_BindTopics" name="bind topics to entities">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.bulkInsert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;edge_topic_entity_binding&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=for t in topics[count(thetaEdges[dst_vid = '
                 'vertex_id]) &gt;= 5] return {\n'
                 '    &quot;edge_id&quot;:             &quot;lda-bind-&quot; + '
                 'substring(t.vertex_id, 60),\n'
                 '    &quot;src_vid&quot;:             t.vertex_id,\n'
                 '    &quot;dst_vid&quot;:             '
                 '&quot;at://did:web:coverage.etzhayyim.com/com.etzhayyim.apps.coverage.latentEntity/lda-&quot; '
                 '+ substring(t.vertex_id, 80),\n'
                 '    &quot;_seq&quot;:                1,\n'
                 '    &quot;sensitivity_ord&quot;:     0,\n'
                 '    &quot;owner_did&quot;:           &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;binding_confidence&quot;:  t.coherence_score,\n'
                 '    &quot;stability_score&quot;:     0.5,\n'
                 '    &quot;binding_type&quot;:        &quot;primary&quot;,\n'
                 '    &quot;actor_did&quot;:           &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;org_did&quot;:             &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;created_at&quot;:          now()\n'
                 '  }" target="rows"/>\n'
                 '          <zeebe:output source="=inserted" target="bindingsCreated"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_5</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_6</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_6" sourceRef="Task_BindTopics" '
                 'targetRef="Task_LinkEvidence"/>\n'
                 '\n'
                 '    <!-- Step 6: Create edge_entity_evidence (record → entity, top 1000) -->\n'
                 '    <bpmn:serviceTask id="Task_LinkEvidence" name="link evidence to entities">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.bulkInsert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;edge_entity_evidence&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=for e in (slice(thetaEdges, 0, 1000))\n'
                 '  return {\n'
                 '    &quot;edge_id&quot;:             &quot;lda-ev-&quot; + substring(e.src_vid, '
                 '60) + &quot;-&quot; + substring(e.dst_vid, 60),\n'
                 '    &quot;src_vid&quot;:             e.src_vid,\n'
                 '    &quot;dst_vid&quot;:             '
                 '&quot;at://did:web:coverage.etzhayyim.com/com.etzhayyim.apps.coverage.latentEntity/lda-&quot; '
                 '+ substring(e.dst_vid, 80),\n'
                 '    &quot;_seq&quot;:                1,\n'
                 '    &quot;sensitivity_ord&quot;:     0,\n'
                 '    &quot;owner_did&quot;:           &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;evidence_weight&quot;:     e.weight,\n'
                 '    &quot;evidence_kind&quot;:       &quot;statistical&quot;,\n'
                 '    &quot;source_collection&quot;:   if (e.source_collection != null) then '
                 'e.source_collection else &quot;unknown&quot;,\n'
                 '    &quot;observed_at&quot;:         now(),\n'
                 '    &quot;actor_did&quot;:           &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;org_did&quot;:             &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;created_at&quot;:          now()\n'
                 '  }" target="rows"/>\n'
                 '          <zeebe:output source="=inserted" target="evidenceLinked"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_6</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_7</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_7" sourceRef="Task_LinkEvidence" '
                 'targetRef="Task_LinkCohorts"/>\n'
                 '\n'
                 '    <!-- Step 7: Create edge_entity_cohort_link for fission-eligible entities '
                 '(ADR-0026 bridge) -->\n'
                 '    <bpmn:serviceTask id="Task_LinkCohorts" name="link fission-eligible entities '
                 'to cohorts">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.db.bulkInsert"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;edge_entity_cohort_link&quot;" '
                 'target="table"/>\n'
                 '          <zeebe:input source="=for t in topics[count(thetaEdges[dst_vid = '
                 'vertex_id]) &gt;= 20 and (if (sum(thetaEdges[dst_vid = vertex_id].weight) &gt; '
                 '0) then 1 - exp(-(sum(thetaEdges[dst_vid = vertex_id].weight)) / 10) else 0.0) '
                 '&gt; 0.85] return {\n'
                 '    &quot;edge_id&quot;:             &quot;lda-cohort-link-&quot; + '
                 'substring(t.vertex_id, 60),\n'
                 '    &quot;src_vid&quot;:             '
                 '&quot;at://did:web:coverage.etzhayyim.com/com.etzhayyim.apps.coverage.latentEntity/lda-&quot; '
                 '+ substring(t.vertex_id, 80),\n'
                 '    &quot;dst_vid&quot;:             '
                 '&quot;at://did:web:natural-person.etzhayyim.com/com.etzhayyim.apps.naturalPerson.populationCohort/contemporary-001-2000&quot;,\n'
                 '    &quot;_seq&quot;:                1,\n'
                 '    &quot;sensitivity_ord&quot;:     0,\n'
                 '    &quot;owner_did&quot;:           &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;link_confidence&quot;:     if (sum(thetaEdges[dst_vid = '
                 't.vertex_id].weight) &gt; 0) then 1 - exp(-(sum(thetaEdges[dst_vid = '
                 't.vertex_id].weight)) / 10) else 0.0,\n'
                 '    &quot;link_type&quot;:           &quot;fission_candidate&quot;,\n'
                 '    &quot;actor_did&quot;:           &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;org_did&quot;:             &quot;did:web:coverage.etzhayyim.com&quot;,\n'
                 '    &quot;created_at&quot;:          now()\n'
                 '  }" target="rows"/>\n'
                 '          <zeebe:output source="=inserted" target="cohortLinked"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_7</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_8</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_8" sourceRef="Task_LinkCohorts" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <!-- Step 8: OCEL audit -->\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="emit LDA entities OCEL">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:coverage.etzhayyim.com&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;coverage.inferLdaEntities.bind&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={\n'
                 '            &quot;topics_read&quot;:       topicCount,\n'
                 '            &quot;theta_edges_read&quot;:   thetaCount,\n'
                 '            &quot;entities_created&quot;:   entitiesCreated,\n'
                 '            &quot;bindings_created&quot;:   bindingsCreated,\n'
                 '            &quot;evidence_linked&quot;:    evidenceLinked,\n'
                 '            &quot;cohort_links&quot;:       cohortLinked\n'
                 '          }" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_8</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_9</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_9" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditNoInput" name="emit LDA entities no-input '
                 'audit">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:coverage.etzhayyim.com&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input source="=&quot;coverage.inferLdaEntities.noInput&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={ &quot;topics_read&quot;: topicCount, '
                 '&quot;status&quot;: &quot;no-topics&quot; }" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_NoTopics</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_NoInputEnd</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_NoInputEnd" sourceRef="Task_AuditNoInput" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End">\n'
                 '      <bpmn:incoming>Flow_9</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_NoInputEnd</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 16636,
                 '00-contracts/bpmn/com/etzhayyim/coverage/inferLdaEntities.bpmn',
                 '2026-04-29T09:13:00Z',
                 'did:web:coverage.etzhayyim.com',
                 'did:web:coverage.etzhayyim.com',
                 'sys.bpmn.seed.coverage',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/coverage-inferLdaEntities-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id, owner_did, nsid, bpmn_process_id, bpmn_version,\n'
         '      result_timeout_ms, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, $4, 1,\n'
         "      CAST($5 AS integer), 'active',\n"
         '      $6, 1, $7, $8, $9\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $10\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/coverage-inferLdaEntities-v1',
                 'did:web:coverage.etzhayyim.com',
                 'com.etzhayyim.apps.coverage.inferLdaEntities',
                 'coverage_infer_lda_entities',
                 300000,
                 '2026-04-29T09:13:00Z',
                 'did:web:coverage.etzhayyim.com',
                 'did:web:coverage.etzhayyim.com',
                 'sys.bpmn.seed.coverage',
                 'at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/coverage-inferLdaEntities-v1']}]

DOWN = [{'sql': 'DELETE FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/coverage-inferLdaSignals-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_process_def WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/coverage-inferLdaSignals-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/coverage-inferLdaTopics-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_process_def WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/coverage-inferLdaTopics-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.binding/coverage-inferLdaEntities-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_process_def WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.etzhayyim.com/com.etzhayyim.apps.bpmn.processDef/coverage-inferLdaEntities-v1']}]


def upgrade() -> None:
    execute_bound_statements(op.get_bind(), UP)


def downgrade() -> None:
    execute_bound_statements(op.get_bind(), DOWN)
