"""Captured from Kysely migration 20260427120000_seed_business_person_bpmn_actor."""

from __future__ import annotations

from alembic import op

from graph_schema.db import execute_bound_statements


revision = "r_20260427120000_seed_business_person_bpmn_actor"
down_revision = 'r_20260427114000_seed_gov_ago_official_source_coverage'
branch_labels = None
depends_on = None

UP = [{'sql': '\n'
         '    INSERT INTO vertex_bpmn_process_def (\n'
         '      vertex_id, owner_did, bpmn_process_id, version, xml, xml_byte_size,\n'
         '      source_path, status, created_at, sensitivity_ord, org_id, user_id, actor_id\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, 1,\n'
         "      $4, CAST($5 AS integer), $6, 'active',\n"
         '      $7, 2, $8, $9, $10\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_process_def WHERE vertex_id = $11\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/business-person-collectPublicRoles-v1',
                 'did:web:business-person.gftd.ai',
                 'business_person_collect_public_roles',
                 '<?xml version="1.0" encoding="UTF-8"?>\n'
                 '<!--\n'
                 '  Business person public-role ingest wrapper.\n'
                 '\n'
                 '  NSID:       ai.gftd.apps.businessPerson.collectPublicRoles\n'
                 '  Owner DID:  did:web:business-person.gftd.ai\n'
                 '  Process ID: business_person_collect_public_roles\n'
                 '\n'
                 '  This process starts public-only collection jobs through the business-person\n'
                 '  PDS app and gates graph consumption on RisingWave health/visibility.\n'
                 '-->\n'
                 '<bpmn:definitions\n'
                 '    xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"\n'
                 '    xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"\n'
                 '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
                 '    id="Definitions_business_person_collect_public_roles"\n'
                 '    targetNamespace="https://gftd.ai/bpmn/business-person"\n'
                 '    exporter="hand-written"\n'
                 '    exporterVersion="1.0">\n'
                 '  <bpmn:process id="business_person_collect_public_roles" name="business person '
                 'collect public roles" isExecutable="true">\n'
                 '    <bpmn:startEvent id="Start" name="collection requested">\n'
                 '      <bpmn:outgoing>Flow_PlanSources</bpmn:outgoing>\n'
                 '    </bpmn:startEvent>\n'
                 '    <bpmn:sequenceFlow id="Flow_PlanSources" sourceRef="Start" '
                 'targetRef="Task_PlanSources"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_PlanSources" name="plan public role sources">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="businessPerson.planPublicRoleSources" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_PlanSources</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_DispatchCollectionJobs</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_DispatchCollectionJobs" '
                 'sourceRef="Task_PlanSources" targetRef="Task_DispatchCollectionJobs"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_DispatchCollectionJobs" name="dispatch public '
                 'collection jobs">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.pds.dispatch" retries="3"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;com.atproto.repo.createRecord&quot;" '
                 'target="type"/>\n'
                 '          <zeebe:input source="={repo: '
                 '&quot;did:web:business-person.gftd.ai&quot;, collection: '
                 '&quot;ai.gftd.apps.businessPerson.collectionJob&quot;, record: {sourceId: '
                 'sourceId, sourceUrl: sourceUrl, jurisdiction: jurisdiction, format: format, '
                 'limit: limit, publicOnly: true, requestedBy: operatorDid}}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_DispatchCollectionJobs</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_PrepareSourceRequest</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_PrepareSourceRequest" '
                 'sourceRef="Task_DispatchCollectionJobs" targetRef="Task_PrepareSourceRequest"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_PrepareSourceRequest" name="prepare source '
                 'request">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="businessPerson.prepareSourceRequest" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_PrepareSourceRequest</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_FetchPublicSource</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_FetchPublicSource" '
                 'sourceRef="Task_PrepareSourceRequest" targetRef="Task_FetchPublicSource"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_FetchPublicSource" name="fetch public source '
                 'payload">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="businessPerson.fetchPublicSource" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_FetchPublicSource</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_AdvanceSourceCursor</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_AdvanceSourceCursor" '
                 'sourceRef="Task_FetchPublicSource" targetRef="Task_AdvanceSourceCursor"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AdvanceSourceCursor" name="advance source '
                 'cursor">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="businessPerson.advanceSourceCursor" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_AdvanceSourceCursor</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ScheduleNextPage</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ScheduleNextPage" '
                 'sourceRef="Task_AdvanceSourceCursor" targetRef="Task_ScheduleNextPage"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ScheduleNextPage" name="schedule next source '
                 'page">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="businessPerson.scheduleNextPage" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ScheduleNextPage</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ExtractCorporateHpRoles</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ExtractCorporateHpRoles" '
                 'sourceRef="Task_ScheduleNextPage" targetRef="Task_ExtractCorporateHpRoles"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ExtractCorporateHpRoles" name="extract corporate '
                 'HP public roles">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="businessPerson.extractCorporateHpRoles" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ExtractCorporateHpRoles</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ExtractCompaniesHouseOfficers</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ExtractCompaniesHouseOfficers" '
                 'sourceRef="Task_ExtractCorporateHpRoles" '
                 'targetRef="Task_ExtractCompaniesHouseOfficers"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ExtractCompaniesHouseOfficers" name="extract '
                 'Companies House officers">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition '
                 'type="businessPerson.extractCompaniesHouseOfficers" retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ExtractCompaniesHouseOfficers</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ExtractGbizinfoRepresentatives</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ExtractGbizinfoRepresentatives" '
                 'sourceRef="Task_ExtractCompaniesHouseOfficers" '
                 'targetRef="Task_ExtractGbizinfoRepresentatives"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ExtractGbizinfoRepresentatives" name="extract '
                 'gBizINFO representatives">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition '
                 'type="businessPerson.extractGbizinfoRepresentatives" retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ExtractGbizinfoRepresentatives</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ExtractEdinetOfficers</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ExtractEdinetOfficers" '
                 'sourceRef="Task_ExtractGbizinfoRepresentatives" '
                 'targetRef="Task_ExtractEdinetOfficers"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ExtractEdinetOfficers" name="extract EDINET '
                 'officers">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="businessPerson.extractEdinetOfficers" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ExtractEdinetOfficers</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ExtractSecEdgarOfficers</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ExtractSecEdgarOfficers" '
                 'sourceRef="Task_ExtractEdinetOfficers" '
                 'targetRef="Task_ExtractSecEdgarOfficers"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ExtractSecEdgarOfficers" name="extract SEC EDGAR '
                 'officers">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="businessPerson.extractSecEdgarOfficers" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ExtractSecEdgarOfficers</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_ExtractHandelsregisterOfficers</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_ExtractHandelsregisterOfficers" '
                 'sourceRef="Task_ExtractSecEdgarOfficers" '
                 'targetRef="Task_ExtractHandelsregisterOfficers"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_ExtractHandelsregisterOfficers" name="extract '
                 'Handelsregister officers">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition '
                 'type="businessPerson.extractHandelsregisterOfficers" retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_ExtractHandelsregisterOfficers</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_NormalizePublicRoles</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_NormalizePublicRoles" '
                 'sourceRef="Task_ExtractHandelsregisterOfficers" '
                 'targetRef="Task_NormalizePublicRoles"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_NormalizePublicRoles" name="normalize public '
                 'roles">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="businessPerson.normalizePublicRoles" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_NormalizePublicRoles</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Health</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Health" sourceRef="Task_NormalizePublicRoles" '
                 'targetRef="Task_Health"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Health" name="rw health gate">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="rw.health.probe" retries="1"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:output source="=healthy" target="rwHealthy"/>\n'
                 '          <zeebe:output source="=reason" target="rwHealthReason"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Health</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_HealthGate</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_HealthGate" sourceRef="Task_Health" '
                 'targetRef="Gateway_RwHealthy"/>\n'
                 '\n'
                 '    <bpmn:exclusiveGateway id="Gateway_RwHealthy" name="RisingWave healthy?" '
                 'default="Flow_RwDegraded">\n'
                 '      <bpmn:incoming>Flow_HealthGate</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_WriteGraph</bpmn:outgoing>\n'
                 '      <bpmn:outgoing>Flow_RwDegraded</bpmn:outgoing>\n'
                 '    </bpmn:exclusiveGateway>\n'
                 '    <bpmn:sequenceFlow id="Flow_WriteGraph" sourceRef="Gateway_RwHealthy" '
                 'targetRef="Task_WriteGraph">\n'
                 '      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=rwHealthy = '
                 'true</bpmn:conditionExpression>\n'
                 '    </bpmn:sequenceFlow>\n'
                 '    <bpmn:sequenceFlow id="Flow_RwDegraded" sourceRef="Gateway_RwHealthy" '
                 'targetRef="Task_AuditRwDegraded"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_WriteGraph" name="write public-role graph">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="businessPerson.writeGraph" retries="3"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=false" target="dryRun"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_WriteGraph</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_VerifyCoverage</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_VerifyCoverage" sourceRef="Task_WriteGraph" '
                 'targetRef="Task_VerifyCoverage"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_VerifyCoverage" name="verify public-role '
                 'coverage">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="businessPerson.verifyCoverage" '
                 'retries="2"/>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_VerifyCoverage</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_Audit</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_Audit" sourceRef="Task_VerifyCoverage" '
                 'targetRef="Task_Audit"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_AuditRwDegraded" name="audit rw degraded">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit" retries="2"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:business-person.gftd.ai&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input '
                 'source="=&quot;businessPerson.collectPublicRoles.rwDegraded&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={sourceId: sourceId, jurisdiction: jurisdiction, '
                 'sourceUrl: sourceUrl, publicOnly: true, rwHealthy: rwHealthy, rwHealthReason: '
                 'rwHealthReason}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_RwDegraded</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_DegradedEnd</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_DegradedEnd" sourceRef="Task_AuditRwDegraded" '
                 'targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:serviceTask id="Task_Audit" name="audit public-role collection">\n'
                 '      <bpmn:extensionElements>\n'
                 '        <zeebe:taskDefinition type="generic.audit.emit" retries="2"/>\n'
                 '        <zeebe:ioMapping>\n'
                 '          <zeebe:input source="=&quot;did:web:business-person.gftd.ai&quot;" '
                 'target="actor"/>\n'
                 '          <zeebe:input '
                 'source="=&quot;businessPerson.collectPublicRoles.completed&quot;" '
                 'target="action"/>\n'
                 '          <zeebe:input source="={sourceId: sourceId, jurisdiction: jurisdiction, '
                 'sourceUrl: sourceUrl, publicOnly: true}" target="payload"/>\n'
                 '        </zeebe:ioMapping>\n'
                 '      </bpmn:extensionElements>\n'
                 '      <bpmn:incoming>Flow_Audit</bpmn:incoming>\n'
                 '      <bpmn:outgoing>Flow_End</bpmn:outgoing>\n'
                 '    </bpmn:serviceTask>\n'
                 '    <bpmn:sequenceFlow id="Flow_End" sourceRef="Task_Audit" targetRef="End"/>\n'
                 '\n'
                 '    <bpmn:endEvent id="End" name="collection queued">\n'
                 '      <bpmn:incoming>Flow_End</bpmn:incoming>\n'
                 '      <bpmn:incoming>Flow_DegradedEnd</bpmn:incoming>\n'
                 '    </bpmn:endEvent>\n'
                 '  </bpmn:process>\n'
                 '</bpmn:definitions>\n',
                 12665,
                 '00-contracts/bpmn/ai/gftd/business-person/collectPublicRoles.bpmn',
                 '2026-04-27T12:00:00Z',
                 'did:web:business-person.gftd.ai',
                 'did:web:business-person.gftd.ai',
                 'sys.bpmn.seed.business-person',
                 'at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/business-person-collectPublicRoles-v1']},
 {'sql': '\n'
         '    INSERT INTO vertex_bpmn_lexicon_binding (\n'
         '      vertex_id, owner_did, nsid, bpmn_process_id, bpmn_version,\n'
         '      result_timeout_ms, status, created_at, sensitivity_ord, org_id, user_id,\n'
         '      actor_id, write_table_allowlist\n'
         '    )\n'
         '    SELECT\n'
         '      $1, $2, $3, $4, 1,\n'
         "      300000, 'active', $5, 2, $6, $7,\n"
         '      $8, $9\n'
         '    WHERE NOT EXISTS (\n'
         '      SELECT 1 FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $10\n'
         '    )\n'
         '  ',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.binding/businessPerson-collectPublicRoles-v1',
                 'did:web:business-person.gftd.ai',
                 'ai.gftd.apps.businessPerson.collectPublicRoles',
                 'business_person_collect_public_roles',
                 '2026-04-27T12:00:00Z',
                 'did:web:business-person.gftd.ai',
                 'did:web:business-person.gftd.ai',
                 'sys.bpmn.seed.business-person',
                 'vertex_business_person',
                 'at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.binding/businessPerson-collectPublicRoles-v1']}]

DOWN = [{'sql': 'DELETE FROM vertex_bpmn_lexicon_binding WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.binding/businessPerson-collectPublicRoles-v1']},
 {'sql': 'DELETE FROM vertex_bpmn_process_def WHERE vertex_id = $1',
  'parameters': ['at://did:web:bpmn.gftd.ai/ai.gftd.apps.bpmn.processDef/business-person-collectPublicRoles-v1']}]


def upgrade() -> None:
    execute_bound_statements(op.get_bind(), UP)


def downgrade() -> None:
    execute_bound_statements(op.get_bind(), DOWN)
