"""
Py Kotodama WASM entrypoint for the Sketch clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/sketch.kotoba")
db = DatomicClient.connect()
app = Runtime("sketch-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"sketch.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"sketch.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/projects", methods=["POST"])
def create_project(request):
    """Create a Project."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'ownerId', 'teamId'])
    if err:
        return err, 400
    err = _require(data, ['name'])
    if err:
        return err, 400
    rec = {"id": new_id("sketch_pro")}
    rec["name"] = data.get('name')
    rec["ownerId"] = data.get('ownerId')
    rec["teamId"] = data.get('teamId')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Project", rec)
    return rec, 201

@app.route("/v1/projects", methods=["GET"])
def list_projects(request):
    """List Projects with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Project")
    rows = _apply_filters(rows, params, ['name', 'ownerId', 'teamId'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/projects/<eid>", methods=["GET"])
def get_project(request, eid):
    """Retrieve a Project by id (supports ?expand=)."""
    rows = _query("Project", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/projects/<eid>", methods=["POST", "PATCH"])
def update_project(request, eid):
    """Update a Project."""
    rows = _query("Project", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'ownerId', 'teamId'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Project", rec)
    return rec, 200

@app.route("/v1/projects/<eid>", methods=["DELETE"])
def delete_project(request, eid):
    """Delete a Project."""
    rows = _query("Project", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"sketch.Project", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/files", methods=["POST"])
def create_file(request):
    """Create a File."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['projectId', 'name', 'contentRef', 'version'])
    if err:
        return err, 400
    err = _require(data, ['name', 'version'])
    if err:
        return err, 400
    rec = {"id": new_id("sketch_fil")}
    rec["projectId"] = data.get('projectId')
    rec["name"] = data.get('name')
    rec["contentRef"] = data.get('contentRef')
    rec["version"] = _as_int(data.get('version'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("File", rec)
    return rec, 201

@app.route("/v1/files", methods=["GET"])
def list_files(request):
    """List Files with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("File")
    rows = _apply_filters(rows, params, ['projectId', 'name', 'contentRef', 'version'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/files/<eid>", methods=["GET"])
def get_file(request, eid):
    """Retrieve a File by id (supports ?expand=)."""
    rows = _query("File", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'projectId': 'Project'})
    return rec, 200

@app.route("/v1/files/<eid>", methods=["POST", "PATCH"])
def update_file(request, eid):
    """Update a File."""
    rows = _query("File", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['projectId', 'name', 'contentRef', 'version'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("File", rec)
    return rec, 200

@app.route("/v1/files/<eid>", methods=["DELETE"])
def delete_file(request, eid):
    """Delete a File."""
    rows = _query("File", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"sketch.File", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/frames", methods=["POST"])
def create_frame(request):
    """Create a Frame."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['fileId', 'name', 'width', 'height'])
    if err:
        return err, 400
    err = _require(data, ['name', 'width'])
    if err:
        return err, 400
    rec = {"id": new_id("sketch_fra")}
    rec["fileId"] = data.get('fileId')
    rec["name"] = data.get('name')
    rec["width"] = _as_float(data.get('width'))
    rec["height"] = _as_float(data.get('height'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Frame", rec)
    return rec, 201

@app.route("/v1/frames", methods=["GET"])
def list_frames(request):
    """List Frames with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Frame")
    rows = _apply_filters(rows, params, ['fileId', 'name', 'width', 'height'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/frames/<eid>", methods=["GET"])
def get_frame(request, eid):
    """Retrieve a Frame by id (supports ?expand=)."""
    rows = _query("Frame", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'fileId': 'File'})
    return rec, 200

@app.route("/v1/frames/<eid>", methods=["POST", "PATCH"])
def update_frame(request, eid):
    """Update a Frame."""
    rows = _query("Frame", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['fileId', 'name', 'width', 'height'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Frame", rec)
    return rec, 200

@app.route("/v1/frames/<eid>", methods=["DELETE"])
def delete_frame(request, eid):
    """Delete a Frame."""
    rows = _query("Frame", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"sketch.Frame", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/components", methods=["POST"])
def create_component(request):
    """Create a Component."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['fileId', 'name', 'description'])
    if err:
        return err, 400
    err = _require(data, ['name', 'description'])
    if err:
        return err, 400
    rec = {"id": new_id("sketch_com")}
    rec["fileId"] = data.get('fileId')
    rec["name"] = data.get('name')
    rec["description"] = data.get('description')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Component", rec)
    return rec, 201

@app.route("/v1/components", methods=["GET"])
def list_components(request):
    """List Components with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Component")
    rows = _apply_filters(rows, params, ['fileId', 'name', 'description'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/components/<eid>", methods=["GET"])
def get_component(request, eid):
    """Retrieve a Component by id (supports ?expand=)."""
    rows = _query("Component", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'fileId': 'File'})
    return rec, 200

@app.route("/v1/components/<eid>", methods=["POST", "PATCH"])
def update_component(request, eid):
    """Update a Component."""
    rows = _query("Component", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['fileId', 'name', 'description'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Component", rec)
    return rec, 200

@app.route("/v1/components/<eid>", methods=["DELETE"])
def delete_component(request, eid):
    """Delete a Component."""
    rows = _query("Component", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"sketch.Component", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/comments", methods=["POST"])
def create_comment(request):
    """Create a Comment."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['fileId', 'authorId', 'body', 'resolved'])
    if err:
        return err, 400
    err = _require(data, ['body', 'resolved'])
    if err:
        return err, 400
    rec = {"id": new_id("sketch_com")}
    rec["fileId"] = data.get('fileId')
    rec["authorId"] = data.get('authorId')
    rec["body"] = data.get('body')
    rec["resolved"] = _as_bool(data.get('resolved'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Comment", rec)
    return rec, 201

@app.route("/v1/comments", methods=["GET"])
def list_comments(request):
    """List Comments with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Comment")
    rows = _apply_filters(rows, params, ['fileId', 'authorId', 'body', 'resolved'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/comments/<eid>", methods=["GET"])
def get_comment(request, eid):
    """Retrieve a Comment by id (supports ?expand=)."""
    rows = _query("Comment", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'fileId': 'File'})
    return rec, 200

@app.route("/v1/comments/<eid>", methods=["POST", "PATCH"])
def update_comment(request, eid):
    """Update a Comment."""
    rows = _query("Comment", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['fileId', 'authorId', 'body', 'resolved'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Comment", rec)
    return rec, 200

@app.route("/v1/comments/<eid>", methods=["DELETE"])
def delete_comment(request, eid):
    """Delete a Comment."""
    rows = _query("Comment", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"sketch.Comment", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/exports", methods=["POST"])
def create_export(request):
    """Create a Export."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['fileId', 'format', 'scale', 'contentRef'])
    if err:
        return err, 400
    err = _require(data, ['format', 'scale'])
    if err:
        return err, 400
    rec = {"id": new_id("sketch_exp")}
    rec["fileId"] = data.get('fileId')
    rec["format"] = data.get('format')
    rec["scale"] = _as_float(data.get('scale'))
    rec["contentRef"] = data.get('contentRef')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Export", rec)
    return rec, 201

@app.route("/v1/exports", methods=["GET"])
def list_exports(request):
    """List Exports with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Export")
    rows = _apply_filters(rows, params, ['fileId', 'format', 'scale', 'contentRef'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/exports/<eid>", methods=["GET"])
def get_export(request, eid):
    """Retrieve a Export by id (supports ?expand=)."""
    rows = _query("Export", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'fileId': 'File'})
    return rec, 200

@app.route("/v1/exports/<eid>", methods=["POST", "PATCH"])
def update_export(request, eid):
    """Update a Export."""
    rows = _query("Export", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['fileId', 'format', 'scale', 'contentRef'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Export", rec)
    return rec, 200

@app.route("/v1/exports/<eid>", methods=["DELETE"])
def delete_export(request, eid):
    """Delete a Export."""
    rows = _query("Export", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"sketch.Export", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "sketch-compat", "tier": "L4",
            "entities": ['Project', 'File', 'Frame', 'Component', 'Comment', 'Export']}, 200


if __name__ == "__main__":
    app.start()
