name = "WellBecoming"
version = "0.1.0"
defaultTargets = ["WellBecoming", "Karma"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.14.0"

[[lean_lib]]
name = "WellBecoming"

[[lean_lib]]
name = "Karma"
