"""
Py Kotodama WASM entrypoint for the Patreon clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/patreon.kotoba")
db = DatomicClient.connect()
app = Runtime("patreon-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"patreon.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"patreon.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/users", methods=["POST"])
def create_user(request):
    """Create a User."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'about', 'fullName', 'firstName', 'lastName', 'email', 'isCreator', 'isEmailVerified', 'likeCount', 'created'])
    if err:
        return err, 400
    err = _require(data, ['id', 'about'])
    if err:
        return err, 400
    rec = {"id": new_id("patreon_use")}
    rec["id"] = data.get('id')
    rec["about"] = data.get('about')
    rec["fullName"] = data.get('fullName')
    rec["firstName"] = data.get('firstName')
    rec["lastName"] = data.get('lastName')
    rec["email"] = data.get('email')
    rec["isCreator"] = _as_bool(data.get('isCreator'))
    rec["isEmailVerified"] = _as_bool(data.get('isEmailVerified'))
    rec["likeCount"] = _as_int(data.get('likeCount'))
    rec["created"] = data.get('created')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("User", rec)
    return rec, 201

@app.route("/v1/users", methods=["GET"])
def list_users(request):
    """List Users with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("User")
    rows = _apply_filters(rows, params, ['id', 'about', 'fullName', 'firstName', 'lastName', 'email', 'isCreator', 'isEmailVerified', 'likeCount', 'created'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/users/<eid>", methods=["GET"])
def get_user(request, eid):
    """Retrieve a User by id (supports ?expand=)."""
    rows = _query("User", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/users/<eid>", methods=["POST", "PATCH"])
def update_user(request, eid):
    """Update a User."""
    rows = _query("User", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'about', 'fullName', 'firstName', 'lastName', 'email', 'isCreator', 'isEmailVerified', 'likeCount', 'created'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("User", rec)
    return rec, 200

@app.route("/v1/users/<eid>", methods=["DELETE"])
def delete_user(request, eid):
    """Delete a User."""
    rows = _query("User", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"patreon.User", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/members", methods=["POST"])
def create_member(request):
    """Create a Member."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'patronStatus', 'lastChargeStatus', 'fullName', 'email', 'currentlyEntitledAmountCents', 'campaignLifetimeSupportCents', 'willPayAmountCents', 'isFollower', 'isFreeTrial', 'lastChargeDate', 'nextChargeDate', 'pledgeRelationshipStart'])
    if err:
        return err, 400
    err = _require(data, ['id', 'patronStatus'])
    if err:
        return err, 400
    if data.get('patronStatus') and data['patronStatus'] not in ['active_patron', 'declined_patron', 'former_patron']:
        return {"error": {"message": "invalid patronStatus; allowed: " + ", ".join(['active_patron', 'declined_patron', 'former_patron']), "type": "invalid_request_error"}}, 400
    if data.get('lastChargeStatus') and data['lastChargeStatus'] not in ['Paid', 'Declined', 'Deleted', 'Pending', 'Refunded', 'Fraud', 'Refunded by Patreon', 'Other', 'Partially Refunded', 'Free Trial', 'Refund Pending', 'Refund Declined']:
        return {"error": {"message": "invalid lastChargeStatus; allowed: " + ", ".join(['Paid', 'Declined', 'Deleted', 'Pending', 'Refunded', 'Fraud', 'Refunded by Patreon', 'Other', 'Partially Refunded', 'Free Trial', 'Refund Pending', 'Refund Declined']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("patreon_mem")}
    rec["id"] = data.get('id')
    rec["patronStatus"] = data.get('patronStatus')
    rec["lastChargeStatus"] = data.get('lastChargeStatus')
    rec["fullName"] = data.get('fullName')
    rec["email"] = data.get('email')
    rec["currentlyEntitledAmountCents"] = _as_int(data.get('currentlyEntitledAmountCents'))
    rec["campaignLifetimeSupportCents"] = _as_int(data.get('campaignLifetimeSupportCents'))
    rec["willPayAmountCents"] = _as_int(data.get('willPayAmountCents'))
    rec["isFollower"] = _as_bool(data.get('isFollower'))
    rec["isFreeTrial"] = _as_bool(data.get('isFreeTrial'))
    rec["lastChargeDate"] = data.get('lastChargeDate')
    rec["nextChargeDate"] = data.get('nextChargeDate')
    rec["pledgeRelationshipStart"] = data.get('pledgeRelationshipStart')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Member", rec)
    return rec, 201

@app.route("/v1/members", methods=["GET"])
def list_members(request):
    """List Members with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Member")
    rows = _apply_filters(rows, params, ['id', 'patronStatus', 'lastChargeStatus', 'fullName', 'email', 'currentlyEntitledAmountCents', 'campaignLifetimeSupportCents', 'willPayAmountCents', 'isFollower', 'isFreeTrial', 'lastChargeDate', 'nextChargeDate', 'pledgeRelationshipStart'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/members/<eid>", methods=["GET"])
def get_member(request, eid):
    """Retrieve a Member by id (supports ?expand=)."""
    rows = _query("Member", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/members/<eid>", methods=["POST", "PATCH"])
def update_member(request, eid):
    """Update a Member."""
    rows = _query("Member", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'patronStatus', 'lastChargeStatus', 'fullName', 'email', 'currentlyEntitledAmountCents', 'campaignLifetimeSupportCents', 'willPayAmountCents', 'isFollower', 'isFreeTrial', 'lastChargeDate', 'nextChargeDate', 'pledgeRelationshipStart'])
    if err:
        return err, 400
    if data.get('patronStatus') and data['patronStatus'] not in ['active_patron', 'declined_patron', 'former_patron']:
        return {"error": {"message": "invalid patronStatus; allowed: " + ", ".join(['active_patron', 'declined_patron', 'former_patron']), "type": "invalid_request_error"}}, 400
    if data.get('lastChargeStatus') and data['lastChargeStatus'] not in ['Paid', 'Declined', 'Deleted', 'Pending', 'Refunded', 'Fraud', 'Refunded by Patreon', 'Other', 'Partially Refunded', 'Free Trial', 'Refund Pending', 'Refund Declined']:
        return {"error": {"message": "invalid lastChargeStatus; allowed: " + ", ".join(['Paid', 'Declined', 'Deleted', 'Pending', 'Refunded', 'Fraud', 'Refunded by Patreon', 'Other', 'Partially Refunded', 'Free Trial', 'Refund Pending', 'Refund Declined']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Member", rec)
    return rec, 200

@app.route("/v1/members/<eid>", methods=["DELETE"])
def delete_member(request, eid):
    """Delete a Member."""
    rows = _query("Member", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"patreon.Member", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/campaigns", methods=["POST"])
def create_campaign(request):
    """Create a Campaign."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'creationName', 'currency', 'name', 'patronCount', 'payPerName', 'isMonthly', 'isNsfw', 'createdAt', 'publishedAt'])
    if err:
        return err, 400
    err = _require(data, ['id', 'creationName'])
    if err:
        return err, 400
    rec = {"id": new_id("patreon_cam")}
    rec["id"] = data.get('id')
    rec["creationName"] = data.get('creationName')
    rec["currency"] = data.get('currency')
    rec["name"] = data.get('name')
    rec["patronCount"] = _as_int(data.get('patronCount'))
    rec["payPerName"] = data.get('payPerName')
    rec["isMonthly"] = _as_bool(data.get('isMonthly'))
    rec["isNsfw"] = _as_bool(data.get('isNsfw'))
    rec["createdAt"] = data.get('createdAt')
    rec["publishedAt"] = data.get('publishedAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Campaign", rec)
    return rec, 201

@app.route("/v1/campaigns", methods=["GET"])
def list_campaigns(request):
    """List Campaigns with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Campaign")
    rows = _apply_filters(rows, params, ['id', 'creationName', 'currency', 'name', 'patronCount', 'payPerName', 'isMonthly', 'isNsfw', 'createdAt', 'publishedAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/campaigns/<eid>", methods=["GET"])
def get_campaign(request, eid):
    """Retrieve a Campaign by id (supports ?expand=)."""
    rows = _query("Campaign", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/campaigns/<eid>", methods=["POST", "PATCH"])
def update_campaign(request, eid):
    """Update a Campaign."""
    rows = _query("Campaign", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'creationName', 'currency', 'name', 'patronCount', 'payPerName', 'isMonthly', 'isNsfw', 'createdAt', 'publishedAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Campaign", rec)
    return rec, 200

@app.route("/v1/campaigns/<eid>", methods=["DELETE"])
def delete_campaign(request, eid):
    """Delete a Campaign."""
    rows = _query("Campaign", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"patreon.Campaign", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/tiers", methods=["POST"])
def create_tier(request):
    """Create a Tier."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'amountCents', 'description', 'patronCount', 'published', 'requiresShipping', 'title', 'createdAt'])
    if err:
        return err, 400
    err = _require(data, ['id', 'amountCents'])
    if err:
        return err, 400
    rec = {"id": new_id("patreon_tie")}
    rec["id"] = data.get('id')
    rec["amountCents"] = _as_int(data.get('amountCents'))
    rec["description"] = data.get('description')
    rec["patronCount"] = _as_int(data.get('patronCount'))
    rec["published"] = _as_bool(data.get('published'))
    rec["requiresShipping"] = _as_bool(data.get('requiresShipping'))
    rec["title"] = data.get('title')
    rec["createdAt"] = data.get('createdAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Tier", rec)
    return rec, 201

@app.route("/v1/tiers", methods=["GET"])
def list_tiers(request):
    """List Tiers with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Tier")
    rows = _apply_filters(rows, params, ['id', 'amountCents', 'description', 'patronCount', 'published', 'requiresShipping', 'title', 'createdAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/tiers/<eid>", methods=["GET"])
def get_tier(request, eid):
    """Retrieve a Tier by id (supports ?expand=)."""
    rows = _query("Tier", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/tiers/<eid>", methods=["POST", "PATCH"])
def update_tier(request, eid):
    """Update a Tier."""
    rows = _query("Tier", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'amountCents', 'description', 'patronCount', 'published', 'requiresShipping', 'title', 'createdAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Tier", rec)
    return rec, 200

@app.route("/v1/tiers/<eid>", methods=["DELETE"])
def delete_tier(request, eid):
    """Delete a Tier."""
    rows = _query("Tier", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"patreon.Tier", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/benefits", methods=["POST"])
def create_benefit(request):
    """Create a Benefit."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'benefitType', 'description', 'isDeleted', 'isPublished', 'title', 'tiersCount', 'createdAt'])
    if err:
        return err, 400
    err = _require(data, ['id', 'benefitType'])
    if err:
        return err, 400
    rec = {"id": new_id("patreon_ben")}
    rec["id"] = data.get('id')
    rec["benefitType"] = data.get('benefitType')
    rec["description"] = data.get('description')
    rec["isDeleted"] = _as_bool(data.get('isDeleted'))
    rec["isPublished"] = _as_bool(data.get('isPublished'))
    rec["title"] = data.get('title')
    rec["tiersCount"] = _as_int(data.get('tiersCount'))
    rec["createdAt"] = data.get('createdAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Benefit", rec)
    return rec, 201

@app.route("/v1/benefits", methods=["GET"])
def list_benefits(request):
    """List Benefits with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Benefit")
    rows = _apply_filters(rows, params, ['id', 'benefitType', 'description', 'isDeleted', 'isPublished', 'title', 'tiersCount', 'createdAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/benefits/<eid>", methods=["GET"])
def get_benefit(request, eid):
    """Retrieve a Benefit by id (supports ?expand=)."""
    rows = _query("Benefit", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/benefits/<eid>", methods=["POST", "PATCH"])
def update_benefit(request, eid):
    """Update a Benefit."""
    rows = _query("Benefit", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['id', 'benefitType', 'description', 'isDeleted', 'isPublished', 'title', 'tiersCount', 'createdAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Benefit", rec)
    return rec, 200

@app.route("/v1/benefits/<eid>", methods=["DELETE"])
def delete_benefit(request, eid):
    """Delete a Benefit."""
    rows = _query("Benefit", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"patreon.Benefit", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "patreon-compat", "tier": "L4",
            "entities": ['User', 'Member', 'Campaign', 'Tier', 'Benefit']}, 200


if __name__ == "__main__":
    app.start()
