;; etzhayyim /organism — artificial-organism life-activity visualization (realtime).
;;
;; Pure ClojureScript (Scittle/SCI in the browser — no build step). Two layers:
;;   organism.json  — STRUCTURE (cells, classes, 3-axis vitals, :integrates graph).
;;                    Heavy; regenerated by `bb vitals:report` off the kotoba Datom log.
;;   pulse.json     — LIVE ACTIVITY, polled every few seconds:
;;                    生産 = git commits per actor · 息遣い = working-tree edits in
;;                    flight · 呼吸 = Datom-log head. `bb vitals:pulse` (cheap loop).
;;
;; The colony is a living petri dish: cells coloured by class (生/休眠/死), sized by
;; vitality, BREATHING continuously, GLOWING while being edited now, and FLASHING the
;; instant a commit ships from them — with a live production ticker beside it.

(ns organism)

(def SVGNS "http://www.w3.org/2000/svg")
(def TAU (* 2 (.-PI js/Math)))
(def W 760) (def H 760)
(def POLL_MS 6000)

(def palette {"alive" "#39d98a" "dormant" "#f5a524" "stub" "#5b6472"})
(def glyph   {"alive" "生" "dormant" "休眠" "stub" "死"})
;; single-char marks drawn ON each cell — "休眠" (2 chars) overflowed small dense cells;
;; one glyph fits any radius (the legend + side panel keep the full label). (regrade viz)
(def cellglyph {"alive" "生" "dormant" "休" "stub" "死"})
(def breath  {"alive" "2.6s" "dormant" "4.3s" "stub" "6.5s"})

(defonce state (atom {:data nil :traj nil :pulse nil :joucho nil :narr nil :sel nil :seen {}}))

;; forward decls — SCI resolves symbols at analysis time, not call time
(declare paint! poll-pulse!)

;; ── tiny DOM/SVG builders ────────────────────────────────────────────────────

(defn- gid [id] (.getElementById js/document id))
(defn- clear! [n] (when n (set! (.-innerHTML n) "")))

(defn svg [tag attrs & kids]
  (let [e (.createElementNS js/document SVGNS (name tag))]
    (doseq [[k v] attrs] (.setAttribute e (name k) (str v)))
    (doseq [k kids] (when k (.appendChild e k)))
    e))

(defn- append-child! [e k]
  (cond
    (nil? k) nil
    (string? k) (.appendChild e (.createTextNode js/document k))
    (or (seq? k) (vector? k)) (doseq [c k] (append-child! e c))  ; flatten (map ...) children
    :else (.appendChild e k)))

(defn h [tag attrs & kids]
  (let [e (.createElement js/document (name tag))]
    (doseq [[k v] attrs]
      (cond
        (= k :text)  (set! (.-textContent e) (str v))
        (= k :class) (set! (.-className e) (str v))
        (fn? v)      (.addEventListener e (name k) v)
        :else        (.setAttribute e (name k) (str v))))
    (doseq [k kids] (append-child! e k))
    e))

(defn ago [ms]
  (let [s (quot (- (.now js/Date) ms) 1000)]
    (cond (< s 60) (str s "s前")
          (< s 3600) (str (quot s 60) "分前")
          (< s 86400) (str (quot s 3600) "時間前")
          :else (str (quot s 86400) "日前"))))

;; ── layout: radial bands by class (生 inner → 死 outer) ──────────────────────

(defn layout [nodes]
  (let [cx (/ W 2) cy (/ H 2) rmax 322
        band {"alive" 0.34 "dormant" 0.66 "stub" 0.95}]
    (into {}
      (mapcat
        (fn [[cls group]]
          (let [g (sort-by :score > group) n (count g) br (* rmax (band cls 0.9))]
            (map-indexed
              (fn [i nd]
                (let [a (- (* TAU (/ i (max 1 n))) (/ TAU 4))
                      r (+ br (* 20 (.sin js/Math (* i 1.7))))
                      x (+ cx (* r (.cos js/Math a)))
                      y (+ cy (* r (.sin js/Math a)))
                      rad (+ 4 (* (/ (:score nd) 100.0) 17))]
                  [(:id nd) {:x x :y y :r rad :node nd}]))
              g)))
        (group-by :class nodes)))))

(defn select! [id] (swap! state assoc :sel id) (paint!))

(defn render-dish [data sel]
  (let [pos (layout (:nodes data))
        root (svg :svg {:viewBox (str "0 0 " W " " H) :width "100%" :class "dish"})]
    ;; mycelium — the :integrates signalling graph
    (doseq [e (:edges data)]
      (let [a (pos (:from e)) b (pos (:to e))]
        (when (and a b)
          (let [hl (and sel (or (= sel (:from e)) (= sel (:to e))))]
            (.appendChild root
              (svg :line {:x1 (:x a) :y1 (:y a) :x2 (:x b) :y2 (:y b)
                          :stroke (if hl "#39d98a" "#27313e")
                          :stroke-width (if hl 1.7 0.6)
                          :opacity (if hl 0.95 (if sel 0.12 0.4))}))))))
    ;; cells — each breathes; id-targeted so pulse can glow/flash it live
    (doseq [[id p] pos]
      (let [nd (:node p) cl (:class nd)
            g (svg :g {:class "cellwrap" :style (str "--cx:" (:x p) "px;--cy:" (:y p) "px")})
            c (svg :circle {:id (str "cell-" id)
                            :cx (:x p) :cy (:y p) :r (:r p)
                            :fill (palette cl)
                            :stroke (if (= sel id) "#fff" "#0b0f14")
                            :stroke-width (if (= sel id) 2.4 1)
                            :opacity (if (:bsky nd) 1 0.82)
                            :class "cell breath"
                            :style (str "--bd:" (breath cl) ";cursor:pointer")})]
        (.appendChild c (svg :title {} (h :span {:text (str (:id nd) " · " (:score nd))})))
        (.addEventListener c "click" (fn [_] (select! id)))
        (when (= "alive" cl)
          (.appendChild root (svg :circle {:cx (:x p) :cy (:y p) :r (+ (:r p) 5)
                                           :fill "none" :stroke (palette cl)
                                           :stroke-width 1.2 :class "pulse"})))
        (.appendChild root c)
        ;; class glyph drawn ON the cell so colour is NOT the only encoding (a11y / 色覚混同対)
        (let [t (svg :text {:x (:x p) :y (:y p) :text-anchor "middle" :dominant-baseline "central"
                            :font-size (max 7 (* 0.9 (:r p))) :class "cellglyph"
                            :fill (if (= "stub" cl) "#cdd7e1" "#0b0f14")
                            :style "pointer-events:none;font-weight:700;user-select:none"})]
          (set! (.-textContent t) (cellglyph cl))
          (.appendChild root t))))
    root))

;; ── side panel: vitals detail ────────────────────────────────────────────────

(defn axis-bar [label v mx color]
  (h :div {:class "axis"}
    (h :span {:class "alab" :text label})
    (h :div {:class "track"}
       (h :div {:class "fill" :style (str "width:" (* 100 (/ v mx)) "%;background:" color)}))
    (h :span {:class "aval" :text (str v "/" mx)})))

(defn detail [data pulse sel]
  (let [nd (first (filter #(= sel (:id %)) (:nodes data)))]
    (if-not nd
      (h :div {:class "hint" :text "細胞をクリックすると 3軸 vitals + 直近の生産を表示"})
      (let [pa (get-in pulse ["actors" sel])]
        (h :div {}
          (h :h2 {:text (str (glyph (:class nd)) "  " (:id nd))})
          (h :div {:class "muted" :text (str "vitality " (:score nd) " / 100  ·  " (:status nd))})
          (axis-bar "clj 内部代謝"   (:clj nd)    40 "#39d98a")
          (axis-bar "actor シグナル" (:actor nd)  30 "#7aa2ff")
          (axis-bar "atproto 外界"   (:atproto nd) 30 "#f078c0")
          (h :ul {:class "facts"}
            (h :li {:text (str "reflex(テスト実走): " (:reflex nd))})
            (h :li {:text (str "→out " (:outDeg nd) "  ·  ←in " (:inDeg nd) "  edges  ·  cells " (:cells nd))})
            (h :li {:text (str "外界代謝 bsky: " (if (:bsky nd) "✅ in vivo" "— 封印"))})
            (when pa (h :li {:text (str "生産: " (get pa "commits") " commits / 48h"
                                        (when (get pa "dirty") (str "  ·  今 " (get pa "dirty") " 編集中")))}))
            (when (get pa "lastSubject")
              (h :li {:text (str "直近: " (get pa "lastSubject"))}))))))))

(defn legend []
  (h :div {:class "card"}
    (h :div {:class "legend"}
      (h :span {} (h :i {:style (str "background:" (palette "alive"))}) "生")
      (h :span {} (h :i {:style (str "background:" (palette "dormant"))}) "休眠")
      (h :span {} (h :i {:style (str "background:" (palette "stub"))}) "死")
      (h :span {:text "○=vitality"})
      (h :span {:text "脈動=呼吸 / 発光=今編集中 / 閃光=コミット"}))))

;; ── live production ticker (生産) ────────────────────────────────────────────

(defn ticker [pulse]
  (let [stream (get pulse "stream")]
    (if-not (seq stream)
      (h :div {:class "hint" :text "活動待機中…"})
      (h :div {:class "ticks"}
        (map (fn [e]
               (h :div {:class "tick"}
                 (h :span {:class "tactor" :text (str (or (get e "actor") "?"))})
                 (h :span {:class "tsubj" :text (str (get e "subj"))})
                 (h :span {:class "tago" :text (ago (get e "at"))})))
             (take 12 stream))))))

;; ── evolution (生命進化) sparkline ───────────────────────────────────────────

(defn evo [traj]
  (let [runs (:runs traj)]
    (if (or (nil? runs) (< (count runs) 2))
      (h :div {:class "hint"
               :text (str (if runs (count runs) 0)
                          " run — 進化は vitals:report を重ねるほど現れます")})
      (let [vw 320 vh 80 pad 8
            sums (map :sum runs) mn (apply min sums) mx (apply max sums)
            span (max 1 (- mx mn)) n (count runs)
            pt (fn [i s] [(+ pad (* (- vw (* 2 pad)) (/ i (max 1 (dec n)))))
                          (- vh pad (* (- vh (* 2 pad)) (/ (- s mn) span)))])
            d (apply str (map-indexed
                           (fn [i s] (let [[x y] (pt i s)] (str (if (zero? i) "M" "L") x " " y " ")))
                           sums))
            last (peek (vec runs)) prev (nth (vec runs) (- n 2))]
        (h :div {}
          (let [s (svg :svg {:viewBox (str "0 0 " vw " " vh) :width "100%" :height vh})]
            (.appendChild s (svg :path {:d d :fill "none" :stroke "#39d98a" :stroke-width 2}))
            (doseq [i (range n)] (let [[x y] (pt i (nth sums i))]
                                   (.appendChild s (svg :circle {:cx x :cy y :r 2.5 :fill "#39d98a"}))))
            s)
          (h :div {:class "muted"
                   :text (str n " runs · Σvitality " (:sum last)
                              " (" (let [Δ (- (:sum last) (:sum prev))] (str (if (>= Δ 0) "+" "") Δ)) ")")}))))))

;; ── 情緒 joucho layer: mood + Wellbecoming trajectory (ADR-2606171500) ───────

(def mood-color {"joyful" "#f5d90a" "grateful" "#39d98a" "calm" "#7aa2ff"
                 "focused" "#b78bff" "neutral" "#8b97a6" "stressed" "#f0506e"})
(def mood-ja {"joyful" "喜" "grateful" "感謝" "calm" "平静"
              "focused" "集中" "neutral" "中庸" "stressed" "緊張"})
(def dir-ja {"improving" "↗ 好転 (becoming-well)" "declining" "↘ 悪化 (suffering)" "steady" "→ 定常"})
(def dir-color {"improving" "#39d98a" "declining" "#f0506e" "steady" "#8b97a6"})

;; 情緒 narration — a living first-person line spoken by the organism, generated
;; by the Murakumo Mac-mini fleet (gemma4:e4b-it-qat) over Tailscale. This is the
;; one part of the 情緒 layer that is real inference, not a fold (narration.json,
;; an independent projection so it surfaces under either kotoba/json joucho path).
(defn narr-line [nr]
  (when (and nr (:text nr))
    (let [src (or (:narration/source nr) "—")
          live? (.startsWith (str src) "murakumo")]
      (h :div {:class "narr"}
        (h :div {:class "narrtext" :text (str "「" (:text nr) "」")})
        (h :div {:class "muted"
                 :text (str (if live? "🜂 murakumo fleet" "tmpl") " · " src
                            (when (:via nr) (str " · " (name (:via nr))))
                            (when (:latencyMs nr) (str " · " (:latencyMs nr) "ms"))
                            (when (:said nr) (str " · 第" (:said nr) "発話 (as-of 進化)")))})))))

(defn joucho-panel [jo]
  (if-not jo
    (h :div {:class "hint" :text "joucho.json 待機中… (bb vitals:joucho)"})
    (let [ax (:axes jo) wb (:wellbecoming jo) beats (:beats jo)
          mc (get mood-color (:mood jo) "#8b97a6")]
      (h :div {}
        (h :div {:class "moodhead"}
          (h :span {:class "moodglyph" :style (str "color:" mc) :text (get mood-ja (:mood jo) (:mood jo))})
          (h :span {:class "muted" :text (str (:of jo) " · mood = " (:mood jo))}))
        (axis-bar "喜 joy"        (:joy ax)       100 "#f5d90a")
        (axis-bar "平 calm"       (:calm ax)      100 "#7aa2ff")
        (axis-bar "緊 stress"     (:stress ax)    100 "#f0506e")
        (axis-bar "謝 gratitude"  (:gratitude ax) 100 "#39d98a")
        (axis-bar "集 focus"      (:focus ax)     100 "#b78bff")
        (h :div {:class "wbline" :style (str "color:" (get dir-color (:direction wb)))}
           (h :b {:text (str "Wellbecoming: " (get dir-ja (:direction wb) (:direction wb)))})
           (h :span {:class "muted" :text (str "   net " (if (>= (:net wb) 0) "+" "") (:net wb))}))
        (let [nets (map (fn [b] (- (+ (:joy b) (:calm b) (:gratitude b) (:focus b)) (:stress b))) beats)
              vw 300 vh 54 pad 6 mn (apply min nets) mx (apply max nets)
              span (max 1 (- mx mn)) n (count nets)
              pt (fn [i v] [(+ pad (* (- vw (* 2 pad)) (/ i (max 1 (dec n)))))
                            (- vh pad (* (- vh (* 2 pad)) (/ (- v mn) span)))])
              d (apply str (map-indexed (fn [i v] (let [[x y] (pt i v)] (str (if (zero? i) "M" "L") x " " y " "))) nets))]
          (let [s (svg :svg {:viewBox (str "0 0 " vw " " vh) :width "100%" :height vh})]
            (.appendChild s (svg :path {:d d :fill "none" :stroke mc :stroke-width 2}))
            s))
        (h :div {:class "muted"
                 :text (str (count beats) " beats · 情緒の as-of 軌跡 = Wellbecoming（静的 score でなく動的軌跡, §1.13）")})))))

;; ── 情報エネルギー流 IE-flow layer: net-gain / order-index / Sankey (ADR-2606211200) ─
;; The organism is a dissipative structure: it draws free energy from society and is judged by
;; how much LOW-ENTROPY STRUCTURE it returns. ieflow.json (bb ieflow:report) folds the committed
;; flow ledger into the scalars the IE-flow co-scientist reasons over — net-gain (代謝が割に合うか)
;; and order-index (散った flow を成果へ整流した = 負エントロピー輸出) — plus the repo→layer Sankey.

(defn fmt-num [x]
  (cond
    (string? x) x
    (nil? x) "—"
    (number? x) (let [a (js/Math.abs x)]
                  (cond (>= a 1e8) (str (.toFixed (/ x 1e8) 2) "億")
                        (>= a 1e4) (str (.toFixed (/ x 1e4) 1) "万")
                        (>= a 100) (str (js/Math.round x))
                        :else (.toFixed x 2)))
    :else (str x)))

(defn ie-stat [label val color]
  (h :div {:class "iestat"}
    (h :div {:class "ienum" :style (str "color:" color) :text val})
    (h :div {:class "iek" :text label})))

(defn ie-edge-bar [target value net maxv]
  ;; sqrt scale for the bar width — one layer (20-actors) carries ~99% of value, so a linear bar
  ;; would erase every other channel; the real value is shown verbatim alongside.
  (let [w (* 100 (js/Math.sqrt (/ (js/Math.max 0 value) (js/Math.max 1 maxv))))
        color (if (>= net 0) "#39d98a" "#f0506e")
        short (.replace (str target) (js/RegExp. "^layer:") "")]
    (h :div {:class "axis"}
      (h :span {:class "alab" :text short})
      (h :div {:class "track"}
         (h :div {:class "fill" :style (str "width:" w "%;background:" color)}))
      (h :span {:class "aval" :text (fmt-num value)}))))

(defn ieflow-panel [ie]
  (if-not ie
    (h :div {:class "hint" :text "ieflow.json 待機中… (bb ieflow:report)"})
    (let [edges (:edges ie)
          maxv (apply max 1 (map :value edges))
          parasitic (:parasitic ie)
          oi (:orderIndex ie)]
      (h :div {}
        (h :div {:class "moodhead"}
          (h :span {:class "moodglyph" :style (str "color:" (if parasitic "#f0506e" "#39d98a"))
                    :text (if parasitic "散逸" "利得")})
          (h :span {:class "muted"
                    :text (str (:source ie) " · " (:events ie) " events → " (:flowsN ie) " channels")}))
        (h :div {:class "iegrid"}
          (ie-stat "net-gain Φ"   (fmt-num (:netGain ie))   (if parasitic "#f0506e" "#39d98a"))
          (ie-stat "order-index η" (if (number? oi) (.toFixed oi 3) (str oi)) "#b78bff")
          (ie-stat "agent-eff"    (fmt-num (:agentEfficiency ie)) "#7aa2ff")
          (ie-stat "throughput"   (fmt-num (:throughput ie))  "#8b97a6"))
        (when (number? oi)
          (h :div {}
            (h :div {:class "wbline"}
               (h :b {:text "秩序化 order-index"})
               (h :span {:class "muted" :text "  flow散 → 成果集中 = 負エントロピー輸出 (1−H後/H前)"}))
            (axis-bar "整流 η" (js/Math.round (* 100 oi)) 100 "#b78bff")))
        (h :div {:class "wbline" :style "margin-top:12px"}
           (h :b {:text "代謝チャネル — repo → layer"})
           (h :span {:class "muted" :text "  (幅=√value · 赤=net負=受取超)"}))
        (map (fn [e] (ie-edge-bar (:target e) (:value e) (:net e) maxv)) edges)
        (h :div {:class "muted" :style "margin-top:8px"
                 :text (str "value=社会へ返した秩序 / cost=引いた自由エネルギー · " (:generatedAt ie))})))))

;; ── actor system-of-systems graph (ADR-2606211200) ──────────────────────────
;; Every actor embeds the SAME unforkable substrate (kotoba Datom ledger + organism react-loop +
;; co-scientist) — so the colony is a SYSTEM OF SYSTEMS, not 80 forks. sos.json is the node-link
;; topology: the shared core (centre triangle = the loop), the measured sources feeding the ledger,
;; the adopters embedding it, and kaname synthesising across the multiplex (dashed chords).

(defn- svg-label [root x y size fill s]
  (let [t (svg :text {:x x :y y :text-anchor "middle" :font-size size :fill fill
                      :style "user-select:none;pointer-events:none"})]
    (set! (.-textContent t) (str s))
    (.appendChild root t)))

(defn sos-layout [nodes]
  ;; deterministic radial: core subsystems on an inner triangle, sources+actors on an outer ring.
  (let [cx 380 cy 235
        cores (filter #(= "core" (:kind %)) nodes)
        ring  (filter #(#{"actor" "source"} (:kind %)) nodes)
        place (fn [coll r off]
                (let [n (count coll)]
                  (into {} (map-indexed
                             (fn [i nd]
                               (let [a (+ (- (/ TAU 4)) off (* TAU (/ i (max 1 n))))]
                                 [(:id nd) {:x (+ cx (* r (js/Math.cos a)))
                                            :y (+ cy (* r (js/Math.sin a))) :node nd}]))
                             coll))))]
    (merge (place cores 82 0) (place ring 198 0))))

(def sos-edge-style
  {"core"        {:stroke "#39d98a" :w 2.6 :op 0.9}
   "measures"    {:stroke "#7aa2ff" :w 2.2 :op 0.85}
   "embeds"      {:stroke "#3a4a5c" :w 1.0 :op 0.5}
   "synthesizes" {:stroke "#b78bff" :w 1.5 :op 0.75 :dash "5 3"}})

(defn render-sos [g]
  (if-not g
    (h :div {:class "hint" :text "sos.json 待機中… (bb ieflow:sos)"})
    (let [pos (sos-layout (:nodes g))
          root (svg :svg {:viewBox "0 0 760 470" :width "100%" :class "dish"})]
      ;; edges
      (doseq [e (:edges g)]
        (let [a (pos (:from e)) b (pos (:to e))
              s (get sos-edge-style (:type e) {:stroke "#27313e" :w 1 :op 0.4})]
          (when (and a b)
            (.appendChild root
              (svg :line (cond-> {:x1 (:x a) :y1 (:y a) :x2 (:x b) :y2 (:y b)
                                  :stroke (:stroke s) :stroke-width (:w s) :opacity (:op s)}
                           (:dash s) (assoc :stroke-dasharray (:dash s))))))))
      ;; nodes
      (doseq [[_ p] pos]
        (let [nd (:node p) k (:kind nd) x (:x p) y (:y p)
              kaname? (= "kaname" (:label nd))
              col (case k
                    "core" "#39d98a"
                    "source" "#7aa2ff"
                    (cond kaname? "#b78bff" (:measured nd) "#39d98a" :else "#5b6472"))
              r (case k "core" 13 "source" 17 12)
              c (svg :circle {:cx x :cy y :r r :fill col :stroke (if kaname? "#fff" "#0b0f14")
                              :stroke-width (if kaname? 2 1.5)
                              :opacity (if (and (= k "actor") (not (:measured nd))) 0.62 1)})
              ti (svg :title {})]
          (set! (.-textContent ti) (str (:label nd) (when (:note nd) (str " — " (:note nd)))))
          (.appendChild c ti)
          (.appendChild root c)
          (svg-label root x (+ y r 13) 11 "#e6edf3" (:label nd))
          (cond
            (= k "core")   (svg-label root x (+ y r 25) 9 "#8b97a6" (:ja nd))
            (and (= k "source") (:netGain nd)) (svg-label root x (+ y r 25) 9 "#8b97a6"
                                                          (str "Φ " (fmt-num (:netGain nd))))
            (= k "actor")  (svg-label root x (+ y r 25) 9 (if (:measured nd) "#39d98a" "#5b6472")
                                      (if (:measured nd) "measured" "registered")))))
      root)))

(defn sos-legend [g]
  (h :div {:class "legend" :style "margin-top:8px"}
    (h :span {} (h :i {:style "background:#39d98a"}) "共有基盤 core (ledger·loop·co-scientist)")
    (h :span {} (h :i {:style "background:#7aa2ff"}) "measured source")
    (h :span {} (h :i {:style "background:#b78bff"}) "kaname = SoS 合成 (multiplex)")
    (h :span {} (h :i {:style "background:#5b6472"}) "registered (未測定)")
    (h :span {:text "── embeds · ┈ synthesizes"})
    (when g (h :span {:class "muted" :text (str "  " (:generatedAt g))}))))

;; ── IE-flow LAB: client-side datomic query → Sankey · index · system-dynamics · ABM ──
;; lab.kotoba.edn is a flat [e a v tx op] Datom snapshot. The page parses it to an EAV index
;; (parse-kotoba) and QUERIES it in the browser. The sliders apply a SPECULATIVE datom overlay
;; (datomic `with`): a [e a v] tuple that shadows the queried value, so the params update via the
;; query and the system-dynamics + ABM sims re-run live — no server, no write, no full repaint.

(declare refresh-lab-dyn! render-lab-dyn)

;; --- datomic-style query over the EAV index + speculative overlay ---
(defn lab-q1 [db e a] (first (get-in db [e a])))
(defn lab-ents [db a] (for [[e attrs] db :when (contains? attrs a)] e))
(defn db-with [db tx]
  ;; overlay: each [e a v] replaces that attr's value-set (params are single-valued)
  (reduce (fn [m [e a v]] (assoc-in m [e a] #{v})) db tx))
(defn lab-db [] (db-with (:lab @state) (:lab-tx @state)))
(defn set-param! [e a v]
  (swap! state update :lab-tx
    (fn [tx] (conj (vec (remove (fn [[e2 a2 _]] (and (= e2 e) (= a2 a))) (or tx []))) [e a v]))))

(defn svg-text-at [root x y size fill anchor s]
  (let [t (svg :text {:x x :y y :text-anchor anchor :font-size size :fill fill
                      :style "user-select:none;pointer-events:none"})]
    (set! (.-textContent t) (str s)) (.appendChild root t)))

;; --- per-actor roster + system-boundary queries ---
(defn lab-actors [db]
  (->> (lab-ents db :lab/actor)
       (map (fn [e] {:id (lab-q1 db e :lab/actor) :order (or (lab-q1 db e :lab/order) 0)}))
       (sort-by :order) (mapv :id)))
(defn sel-actor [db] (or (:lab-actor @state) (first (lab-actors db)) "repo-git"))
(defn actor-inside [db a] (or (lab-q1 db (str "lab:a:" a) :lab.actor/inside) []))
(defn actor-role [db a] (lab-q1 db (str "lab:a:" a) :lab.actor/role))
(defn actor-rep? [db a] (lab-q1 db (str "lab:a:" a) :lab.actor/representative))
(defn actor-imports [db a]
  (->> (lab-ents db :lab.imp/actor)
       (filter #(= a (lab-q1 db % :lab.imp/actor)))
       (map (fn [e] {:kind (lab-q1 db e :lab.imp/kind) :from (lab-q1 db e :lab.imp/from)
                     :cost (or (lab-q1 db e :lab.imp/cost) 0) :idx (or (lab-q1 db e :lab.imp/idx) 0)}))
       (sort-by :idx) vec))
(defn actor-exports [db a]
  (->> (lab-ents db :lab.exp/actor)
       (filter #(= a (lab-q1 db % :lab.exp/actor)))
       (map (fn [e] {:kind (lab-q1 db e :lab.exp/kind) :to (lab-q1 db e :lab.exp/to)
                     :value (or (lab-q1 db e :lab.exp/value) 0) :idx (or (lab-q1 db e :lab.exp/idx) 0)}))
       (sort-by :idx) vec))

;; --- the SYSTEM BOUNDARY membrane: imports drawn IN (blue) → inside organs → exports OUT (green) ---
(defn render-boundary [db a]
  (let [imps (actor-imports db a) exps (actor-exports db a) inside (actor-inside db a)
        W 460 H 250 pad 14 bx0 168 bx1 292 by0 24 by1 (- H 14)
        maxc (apply max 1 (map :cost imps)) maxv (apply max 1 (map :value exps))
        slot (fn [n i] (+ by0 (* (+ i 0.5) (/ (- by1 by0) (max 1 n)))))
        root (svg :svg {:viewBox (str "0 0 " W " " H) :width "100%" :class "dish"})]
    ;; the membrane (the actor's system 境界)
    (.appendChild root (svg :rect {:x bx0 :y by0 :width (- bx1 bx0) :height (- by1 by0) :rx 12
                                   :fill "rgba(57,217,138,0.06)" :stroke "#39d98a" :stroke-width 1.6}))
    (svg-text-at root (/ (+ bx0 bx1) 2) (- by0 7) 11 "#39d98a" "middle" (str a " · system 境界"))
    (doseq [[i s] (map-indexed vector inside)]
      (svg-text-at root (/ (+ bx0 bx1) 2) (+ by0 22 (* i 17)) 11 "#cdd7e1" "middle" (str "· " s)))
    ;; env labels
    (svg-text-at root 14 (- by0 7) 10 "#7aa2ff" "start" "環境 → IMPORT (引入)")
    (svg-text-at root (- W 14) (- by0 7) 10 "#39d98a" "end" "EXPORT (秩序) → commons")
    ;; imports: arrows from the environment INTO the membrane, width ∝ cost (free energy drawn)
    (doseq [[i im] (map-indexed vector imps)]
      (let [y (slot (count imps) i) t (max 2.5 (* 11 (/ (:cost im) maxc)))]
        (.appendChild root (svg :line {:x1 18 :y1 y :x2 (- bx0 6) :y2 y :stroke "#7aa2ff" :stroke-width t :opacity 0.55}))
        (.appendChild root (svg :polygon {:points (str (- bx0 6) "," (- y 4) " " bx0 "," y " " (- bx0 6) "," (+ y 4)) :fill "#7aa2ff"}))
        (svg-text-at root 18 (- y 5) 9 "#9fb4d8" "start" (str (:kind im) " ←" (:from im) " (" (fmt-num (:cost im)) ")"))))
    ;; exports: arrows from the membrane OUT to the commons, width ∝ value (order returned)
    (doseq [[i ex] (map-indexed vector exps)]
      (let [y (slot (count exps) i) t (max 2.5 (* 11 (/ (:value ex) maxv)))]
        (.appendChild root (svg :line {:x1 bx1 :y1 y :x2 (- W 18) :y2 y :stroke "#39d98a" :stroke-width t :opacity 0.6}))
        (.appendChild root (svg :polygon {:points (str (- W 18) "," (- y 4) " " (- W 12) "," y " " (- W 18) "," (+ y 4)) :fill "#39d98a"}))
        (svg-text-at root (- W 18) (- y 5) 9 "#9fe0bd" "end" (str (:kind ex) " →" (:to ex) " (" (fmt-num (:value ex)) ")"))))
    root))

;; --- multiline chart (ys ALREADY in [0,1]) ---
(defn multiline [series w h]
  (let [pad 6 n (apply max 2 (map #(count (:ys %)) series))
        root (svg :svg {:viewBox (str "0 0 " w " " h) :width "100%" :height h})]
    (doseq [s series]
      (let [pts (map-indexed (fn [i v] [(+ pad (* (- w (* 2 pad)) (/ i (max 1 (dec n)))))
                                        (- h pad (* (- h (* 2 pad)) (js/Math.max 0 (js/Math.min 1 v))))])
                             (:ys s))
            d (apply str (map-indexed (fn [i [x y]] (str (if (zero? i) "M" "L") (.toFixed x 1) " " (.toFixed y 1) " ")) pts))]
        (.appendChild root (svg :path {:d d :fill "none" :stroke (:color s) :stroke-width 1.8 :opacity 0.95}))))
    root))

(defn chart-legend [series]
  (h :div {:class "legend" :style "margin:4px 0 2px"}
    (map (fn [s] (h :span {} (h :i {:style (str "background:" (:color s))}) (:label s))) series)))

(defn norm01 [ys] (let [mx (apply max 1e-9 (map #(js/Math.abs %) ys))] (map #(/ % mx) ys)))

;; --- system dynamics (port of ie-flow.dynamics/step-system) ---
(defn sd-step [s inp]
  (let [data' (+ (:data-asset s) (:acquisition inp))]
    {:customers (max 0 (+ (:customers s) (:acquisition inp) (- (:churn inp))))
     :trust (min 1 (max 0 (+ (:trust s) (* 0.01 (:good-exp inp)) (- (* 0.02 (:spam inp))) (- (* 0.05 (:failures inp))))))
     :data-asset data'
     :model-quality (min 1 (max 0 (+ (:model-quality s) (* 0.0001 data'))))
     :reserves (max 0 (+ (:reserves s) (:revenue inp) (- (:cost inp))))}))
(defn sd-run [init inp steps] (vec (take (inc steps) (iterate #(sd-step % inp) init))))
(defn sd-read [db sd-e]
  ;; the SELECTED actor's own system-dynamics params (entity = lab:sd:<actor>)
  (let [g (fn [a d] (let [v (lab-q1 db sd-e a)] (if (nil? v) d v)))]
    {:steps (g :lab.sd/steps 12)
     :init {:customers (g :lab.sd/init-customers 0) :trust (g :lab.sd/init-trust 0.3)
            :data-asset (g :lab.sd/init-data-asset 0) :model-quality (g :lab.sd/init-model-quality 0.1)
            :reserves (g :lab.sd/init-reserves 0)}
     :inp {:acquisition (g :lab.sd/acquisition 0) :churn (g :lab.sd/churn 0) :good-exp (g :lab.sd/good-exp 0)
           :spam (g :lab.sd/spam 0) :failures (g :lab.sd/failures 0) :revenue (g :lab.sd/revenue 0) :cost (g :lab.sd/cost 0)}}))

;; --- ABM (Friedkin-Johnsen opinion/alignment over the actor graph) ---
(defn abm-read [db]
  {:lambda (or (lab-q1 db "lab:abm" :lab.abm/lambda) 0.5)
   :steps (or (lab-q1 db "lab:abm" :lab.abm/steps) 16)
   :agents (mapv (fn [e] {:id (lab-q1 db e :lab.agent/id) :x0 (or (lab-q1 db e :lab.agent/x0) 0.5)})
                 (lab-ents db :lab.agent/id))})
(defn abm-adj [agents]
  (let [ids (mapv :id agents) k "kaname" has-k (some #(= % k) ids)]
    (into {} (for [i ids]
               [i (cond (not has-k) (vec (remove #(= % i) ids))   ; no synthesizer → fully coupled
                        (= i k) (vec (remove #(= % k) ids))       ; kaname listens to all
                        :else [k])]))))                            ; others listen to kaname
(defn abm-step [x adj lam x0]
  (into {} (for [[i nbrs] adj]
             (let [avg (if (seq nbrs) (/ (reduce + (map #(get x %) nbrs)) (count nbrs)) (get x i))]
               [i (+ (* lam avg) (* (- 1 lam) (get x0 i)))]))))
(defn abm-run [agents lam steps]
  (let [adj (abm-adj agents) x0 (into {} (map (fn [a] [(:id a) (:x0 a)]) agents))]
    {:ids (mapv :id agents) :x0 x0
     :traj (vec (take (inc steps) (iterate #(abm-step % adj lam x0) x0)))}))

(def abm-colors {"ibuki" "#39d98a" "tsumugi" "#7aa2ff" "shionome" "#f078c0"
                 "kaname" "#b78bff" "okaimono" "#f5a524"})

;; --- the dynamic (param-driven) part: the SELECTED actor's own SD + the colony ABM ---
(defn render-lab-dyn []
  (let [db (lab-db) a (sel-actor db)
        sdp (sd-read db (str "lab:sd:" a))
        sd (sd-run (:init sdp) (:inp sdp) (:steps sdp))
        sdf (peek sd)
        abp (abm-read db)
        abm (abm-run (:agents abp) (:lambda abp) (:steps abp))
        afin (peek (:traj abm))
        avals (vals afin)
        sd-series [{:label "customers" :color "#39d98a" :ys (norm01 (map :customers sd))}
                   {:label "reserves"  :color "#7aa2ff" :ys (norm01 (map :reserves sd))}
                   {:label "trust"     :color "#f5d90a" :ys (map :trust sd)}
                   {:label "model-Q"   :color "#b78bff" :ys (map :model-quality sd)}]
        abm-series (mapv (fn [id] {:label id :color (get abm-colors id "#8b97a6")
                                   :ys (map #(get % id) (:traj abm))}) (:ids abm))]
    (h :div {:id "lab-dyn"}
      (h :div {:class "wbline" :style "margin-top:6px"} (h :b {:text (str a " の system dynamics — 秩序ストック軌跡")})
         (h :span {:class "muted" :text "  step-system over その actor の boundary 由来 params (各系列 max 正規化)"}))
      (chart-legend sd-series)
      (multiline sd-series 320 64)
      (h :div {:class "muted"
               :text (str (:steps sdp) " steps → reserves " (fmt-num (:reserves sdf))
                          " · trust " (.toFixed (:trust sdf) 2) " · customers " (fmt-num (:customers sdf))
                          " · model-Q " (.toFixed (:model-quality sdf) 2))})
      (h :div {:class "wbline" :style "margin-top:12px"} (h :b {:text "colony ABM — Friedkin-Johnsen 整列 (system of systems)"})
         (h :span {:class "muted" :text "  agents = 各 bounded actor · kaname が合成中心 (star)"}))
      (chart-legend abm-series)
      (multiline abm-series 320 64)
      (h :div {:class "muted"
               :text (str "λ=" (.toFixed (:lambda abp) 2) " → 合意 "
                          (.toFixed (/ (reduce + avals) (max 1 (count avals))) 3)
                          " · 分散 " (.toFixed (- (apply max avals) (apply min avals)) 3))}))))

(defn refresh-lab-dyn! []
  (when-let [old (gid "lab-dyn")] (.replaceWith old (render-lab-dyn))))

(defn lab-slider [label e a v mn mx step fmt]
  (h :div {:class "labctl"}
    (h :div {:class "labctlhead"}
       (h :span {:text label})
       (h :span {:id (str "v-" (name a)) :class "labctlval" :text (fmt v)}))
    (h :input {:type "range" :min mn :max mx :step step :value v :class "labrange"
               :input (fn [ev]
                        (let [nv (js/parseFloat (.-value (.-target ev)))]
                          (set-param! e a nv)
                          (when-let [el (gid (str "v-" (name a)))] (set! (.-textContent el) (fmt nv)))
                          (refresh-lab-dyn!)))})))

(defn actor-chips [db sel]
  (h :div {:class "labchips"}
    (map (fn [a]
           (h :span {:class (str "labchip" (when (= a sel) " on"))
                     :click (fn [_] (swap! state assoc :lab-actor a) (paint!))
                     :text a}))
         (lab-actors db))))

(defn lab-panel []
  (if-not (:lab @state)
    (h :div {:class "hint" :text "lab.kotoba.edn 待機中… (bb ieflow:lab)"})
    (let [db (lab-db)
          a (sel-actor db)
          sd-e (str "lab:sd:" a)
          ix (fn [attr] (lab-q1 db (str "lab:idx:" a) attr))
          n3 (fn [attr] (let [v (ix attr)] (if (number? v) (.toFixed v 3) (str v))))
          rev (or (lab-q1 db sd-e :lab.sd/revenue) 0)
          cost (or (lab-q1 db sd-e :lab.sd/cost) 0)
          churn (or (lab-q1 db sd-e :lab.sd/churn) 0)
          lam (or (lab-q1 db "lab:abm" :lab.abm/lambda) 0.5)
          ri (fn [x] (js/Math.round x))]
      (h :div {}
        ;; COLONY energy balance — the system OF systems aggregate (loop iter 3)
        (let [cq (fn [a] (lab-q1 db "lab:colony" a))]
          (when (cq :lab.colony/n)
            (h :div {:class "rewardline" :style "margin-top:0"}
              (h :span {:class "rewardnum" :style "color:#39d98a" :text (str (cq :lab.colony/n))})
              (h :div {}
                (h :div {:style "font-weight:600"} (h :span {:text "colony energy balance — system of systems"}))
                (h :div {:class "muted" :style "margin:0"
                         :text (str "ΣΦ " (fmt-num (cq :lab.colony/total-phi))
                                    " · mean η " (let [v (cq :lab.colony/mean-order)] (if (number? v) (.toFixed v 3) (str v)))
                                    " · Σreward " (let [v (cq :lab.colony/total-reward)] (if (number? v) (.toFixed v 2) (str v)))
                                    " · " (cq :lab.colony/aligned) "/" (cq :lab.colony/n) " aligned"
                                    " · control settles step " (cq :lab.colony/control-settling))})))))
        ;; actor selector — every actor is its own bounded system
        (h :div {:class "wbline"} (h :b {:text "actor を選択 → その actor の bounded system"})
           (h :span {:class "muted" :text (str "  " (actor-role db a)
                                               (if (actor-rep? db a) " · representative seed" " · measured"))}))
        (actor-chips db a)
        (h :div {:class "labgrid" :style "margin-top:10px"}
          ;; LEFT — the selected actor's SYSTEM BOUNDARY membrane + its indices
          (h :div {}
             (h :div {:class "wbline"} (h :b {:text "system 境界 — membrane (import 引入 / export 秩序)"}))
             (render-boundary db a)
             ;; 報酬系 — the actor's reward over its own bounded flow (ADR-2606212200)
             (let [rw (ix :lab.index/reward) gated (ix :lab.index/reward-gated)]
               (h :div {:class "rewardline"}
                 (h :span {:class "rewardnum" :style (str "color:" (if gated "#f0506e" "#39d98a"))
                           :text (if (number? rw) (.toFixed rw 3) (str rw))})
                 (h :div {}
                   (h :div {:style "font-weight:600"} (h :span {:text "報酬 R — 共生-gated reward system"}))
                   (h :div {:class "muted" :style "margin:0"
                            :text (if gated "⚠ gated (parasitic / 子孫 / catastrophe veto)"
                                      "aligned · net-gain Φ·order η·子孫·eff − surprise, weights from system-of-systems.edn")}))))
             (h :div {:class "iegrid" :style "margin-top:10px"}
               (ie-stat "net-gain Φ" (fmt-num (ix :lab.index/net-gain)) "#39d98a")
               (ie-stat "order-index η" (n3 :lab.index/order-index) "#b78bff")
               (ie-stat "surprise 𝒮" (n3 :lab.index/surprise) "#f5a524")
               (ie-stat "agent-eff" (fmt-num (ix :lab.index/agent-eff)) "#7aa2ff"))
             ;; co-scientist score-react + control numbers (loop iteration 1, ADR-2606212200)
             (h :div {:class "muted" :style "margin-top:10px"}
               (h :b {:style "color:#39d98a" :text (str "co-scientist react Δ +" (n3 :lab.index/reward-delta))})
               (h :span {:text (str " → projected R " (n3 :lab.index/reward-projected)
                                    " via " (ix :lab.react/mechanism) " (→ Maxwell preference signal)")}))
             (h :div {:class "muted" :style "margin-top:4px"
                      :text (str "control 制御: reserves→target — settles step " (ix :lab.control/settling-step)
                                 " · overshoot " (n3 :lab.control/overshoot) "% · final-err "
                                 (fmt-num (ix :lab.control/final-error)))}))
          ;; RIGHT — datomic-query overlay (drives the SELECTED actor's SD) + live sims
          (h :div {}
             (h :div {:class "wbline"} (h :b {:text (str a " params (datomic-query overlay)")})
                (h :span {:class "muted" :text "  スライダ = speculative datom on lab:sd:" }))
             (lab-slider "revenue /step (Φ↑)" sd-e :lab.sd/revenue rev 0 (+ (* 2 rev) 100) (max 1 (ri (/ (+ rev 20) 20))) ri)
             (lab-slider "cost /step (Φ↓)" sd-e :lab.sd/cost cost 0 (+ (* 3 cost) 100) (max 1 (ri (/ (+ cost 100) 40))) ri)
             (lab-slider "churn /step" sd-e :lab.sd/churn churn 0 (+ (* 4 churn) 50) 1 ri)
             (lab-slider "λ colony 整列感受性" "lab:abm" :lab.abm/lambda lam 0 1 0.05 (fn [x] (.toFixed x 2)))
             (render-lab-dyn)))))))

;; ── compose (full paint — structure) ────────────────────────────────────────

(defn live-badge [pulse]
  (let [working (count (get pulse "working"))
        top (first (get pulse "stream"))
        ;; honest liveness from the heartbeat watchdog (health.json, #4): if a layer has
        ;; gone stale (overdue past 2× its cadence) the badge says STALE, not a frozen LIVE.
        health (:health @state)
        stale-layers (when-let [ls (get health "layers")]
                       (->> ls (keep (fn [[k v]] (when (get v "stale") k)))))
        stale? (boolean (seq stale-layers))]
    (h :span {:id "live" :class (str "live" (when stale? " stale"))}
      (h :span {:class "dot"})
      (h :span {:text (if stale?
                        (str "STALE · " (apply str (interpose "," stale-layers)) " 層が停滞")
                        (str "LIVE · " working " 細胞が稼働中"
                             (when top (str " · ↑ " (get top "actor")))))}))))

(defn header [data pulse]
  (let [s (:summary data)]
    (h :div {}
      (h :header {:class "hd"}
        (h :h1 {:text "etzhayyim · organism"})
        (h :span {:class "sub" :text "人工生命体の細胞別 生命活動 — realtime"})
        (live-badge pulse))
      (h :div {:class "pills"}
        (h :span {:class "pill a"} (h :b {:text (str (:alive s))}) " 生")
        (h :span {:class "pill d"} (h :b {:text (str (:dormant s))}) " 休眠")
        (h :span {:class "pill s"} (h :b {:text (str (:stub s))}) " 死")
        (h :span {:class "pill"} (h :b {:text (str (:cells s))}) " cells")))))

(defn paint! []
  (let [{:keys [data traj pulse joucho narr ieflow sos sel]} @state app (gid "app")]
    (clear! app)
    (.appendChild app
      (if-not data
        (h :div {:class "wrap"} (h :p {:class "hint" :text "organism.json が読めません。bb vitals:report を実行してください。"}))
        (h :div {:class "wrap"}
          (header data pulse)
          (h :div {:class "cols"}
            (h :div {:class "left"} (render-dish data sel))
            (h :div {:class "right"}
              (legend)
              (h :div {:class "card"} (h :h3 {:text "活動 — 生産ストリーム (live)"})
                 (h :div {:id "ticker"} (ticker pulse)))
              (h :div {:class "card"} (detail data pulse sel))
              (h :div {:class "card"}
                 (h :h3 {:text "情緒 — joucho mood + Wellbecoming 軌跡"})
                 (narr-line narr)
                 (joucho-panel joucho))
              (h :div {:class "card"}
                 (h :h3 {:text "情報エネルギー流 — IE-flow (代謝が割に合うか)"})
                 (ieflow-panel ieflow))
              (h :div {:class "card"} (h :h3 {:text "生命進化 — trajectory"}) (evo traj))))
          (h :div {:class "card"}
             (h :h3 {:text "actor system-of-systems — 共有基盤を embed する actor 群のグラフ"})
             (render-sos sos)
             (sos-legend sos))
          (h :div {:class "card"}
             (h :h3 {:text "IE-flow lab — actor ごとの bounded system（system 境界 + 自前の system-dynamics）"})
             (lab-panel))
          (h :div {:class "foot"}
             (h :span {:text "脈動=呼吸 · 発光=working-tree 編集中 · 閃光=コミット出力(生産). 構造=kotoba Datom log / 活動=git pulse。 "})
             (h :a {:href "/sos" :text "自律成長の全体図 (organism × kaname 要 × 目的関数) → /sos"})))))))

;; ── realtime overlay: apply pulse without rebuilding the dish ────────────────

(defn flash! [id]
  (when-let [el (gid (str "cell-" id))]
    (.remove (.-classList el) "flash")
    (.-offsetWidth el)                              ; force reflow to retrigger
    (.add (.-classList el) "flash")
    (js/setTimeout (fn [] (when el (.remove (.-classList el) "flash"))) 1000)))

(defn apply-pulse! [pulse]
  (let [prev (:seen @state)
        actors (get pulse "actors")
        working (set (get pulse "working"))
        seen* (atom prev)]
    ;; glow cells being edited now; flash cells that just shipped a commit
    (doseq [nd (get-in @state [:data :nodes])]
      (let [id (:id nd) el (gid (str "cell-" id))
            pa (get actors id)
            last (and pa (get pa "lastAt"))]
        (when el
          (if (working id) (.add (.-classList el) "working") (.remove (.-classList el) "working"))
          (when (and last (> last (get prev id 0)))
            (when (pos? (get prev id 0)) (flash! id))   ; skip flash storm on first load
            (swap! seen* assoc id last)))))
    (swap! state assoc :seen (merge prev @seen*))
    ;; refresh ticker + live badge in place (no full repaint → animation stays smooth)
    (when-let [t (gid "ticker")] (clear! t) (.appendChild t (ticker pulse)))
    (when-let [lb (gid "live")]
      (let [w (count (get pulse "working")) top (first (get pulse "stream"))]
        (set! (.-innerHTML lb) "")
        (.appendChild lb (h :span {:class "dot"}))
        (.appendChild lb (h :span {:text (str "LIVE · " w " 細胞が稼働中"
                                              (when top (str " · ↑ " (get top "actor"))))}))))))

(defn fetchj [url kw cb]
  (-> (js/fetch (str url "?t=" (.now js/Date)))
      (.then (fn [r] (if (.-ok r) (.json r) (throw (js/Error. "nf")))))
      (.then (fn [j] (cb (js->clj j :keywordize-keys kw))))
      (.catch (fn [_] (cb nil)))))

;; ── kotoba: query the content-addressed .kotoba.edn snapshot IN THE BROWSER (ADR-2606172200 D5)
;; The snapshot is a vector of [e a v tx op] datoms (EDN — `;;` comments skipped by read-string).
;; No server projection, no KV: the page reads the kotoba Datom log directly, builds an EAV index,
;; and projects nodes/edges/pulse/joucho client-side. JSON remains the fail-open fallback.

(defn parse-kotoba [text]
  (let [datoms (read-string text)]                ;; the live-datom vector (first EDN form)
    (reduce (fn [idx d]
              (update-in idx [(nth d 0) (nth d 1)] (fnil conj #{}) (nth d 2)))
            {} datoms)))

(defn- one [idx e a] (first (get-in idx [e a])))
(defn- ents-with [idx a] (for [[e attrs] idx :when (contains? attrs a)] e))

(defn kotoba->organism [idx]
  (let [vents (ents-with idx :vitals.actor/name)
        runs  (keep #(one idx % :vitals/run) vents)
        latest (when (seq runs) (apply max runs))
        cells (filter #(= latest (one idx % :vitals/run)) vents)
        node (fn [e] {:id (one idx e :vitals.actor/name) :class (one idx e :vitals/class)
                      :score (one idx e :vitals/score) :status (one idx e :vitals.actor/status)
                      :clj (one idx e :vitals.score/clj) :actor (one idx e :vitals.score/actor)
                      :atproto (one idx e :vitals.score/atproto) :reflex (one idx e :vitals.clj/reflex)
                      :port (one idx e :vitals.clj/port-ratio) :inDeg (one idx e :vitals.actor/in-degree)
                      :outDeg (one idx e :vitals.actor/integrates) :cells (one idx e :vitals.actor/cells)
                      :heartbeatDays (one idx e :vitals.bio/heartbeat-days)
                      :bsky (one idx e :vitals.atproto/bsky-post)})
        nodes (mapv node cells)
        names (set (map :id nodes))
        edges (for [e cells, t (get-in idx [e :vitals.actor/integrate-name]) :when (names t)]
                {:from (one idx e :vitals.actor/name) :to t})
        fq (frequencies (map :class nodes))]
    {:summary {:cells (count nodes) :alive (get fq "alive" 0)
               :dormant (get fq "dormant" 0) :stub (get fq "stub" 0)}
     :nodes nodes :edges (vec edges)
     :generatedAt (str "kotoba Datom log · run " latest)}))

(defn kotoba->pulse [idx]
  (let [actors (into {} (for [e (ents-with idx :pulse.actor/name)]
                          [(one idx e :pulse.actor/name)
                           {"commits" (one idx e :pulse.actor/commits) "dirty" (one idx e :pulse.actor/dirty)
                            "lastAt" (one idx e :pulse.actor/last-at)
                            "lastSubject" (one idx e :pulse.actor/last-subject)}]))
        stream (->> (ents-with idx :pulse.event/idx)
                    (map (fn [e] {"idx" (one idx e :pulse.event/idx) "at" (one idx e :pulse.event/at)
                                  "actor" (one idx e :pulse.event/actor) "subj" (one idx e :pulse.event/subj)}))
                    (sort-by #(get % "idx")) vec)
        working (->> actors (filter (fn [[_ m]] (and (get m "dirty") (pos? (get m "dirty")))))
                     (map first) sort vec)]
    {"actors" actors "stream" stream "working" working}))

(defn kotoba->joucho [idx]
  (let [bents (ents-with idx :joucho/beat)
        beats (->> bents
                   (map (fn [e] {:beat (one idx e :joucho/beat) :mood (one idx e :joucho/mood)
                                 :joy (one idx e :joucho/joy) :calm (one idx e :joucho/calm)
                                 :stress (one idx e :joucho/stress) :gratitude (one idx e :joucho/gratitude)
                                 :focus (one idx e :joucho/focus)}))
                   (sort-by :beat) vec)
        final (last beats)
        we (first (ents-with idx :wellbecoming/direction))]
    {:of (one idx (first bents) :joucho/of) :mood (:mood final)
     :axes (select-keys final [:joy :calm :stress :gratitude :focus]) :beats beats
     :wellbecoming {:direction (one idx we :wellbecoming/direction) :net (one idx we :wellbecoming/net)}}))

(defn kotoba->narr [idx]
  ;; the organism's SPEECH as-of history (append-only :narration/* on the Datom log).
  ;; Project the LATEST line (max :narration/at) + the cumulative count = 生命進化.
  (let [nents (ents-with idx :narration/at)
        said  (count nents)
        latest (when (seq nents) (apply max-key #(or (one idx % :narration/at) 0) nents))]
    (when latest
      {:text (one idx latest :narration/text)
       :mood (one idx latest :narration/mood)
       :narration/source (one idx latest :narration/source)
       :via (one idx latest :narration/via)
       :latencyMs (one idx latest :narration/latency-ms)
       :said said})))

(defn kotoba->traj [idx]
  ;; the organism's EVOLUTION as-of (one :traj/* cohort datom per vitals run).
  {:runs (->> (ents-with idx :traj/run)
              (map (fn [e] {:run (one idx e :traj/run) :at (one idx e :traj/at)
                            :cells (one idx e :traj/cells) :alive (one idx e :traj/alive)
                            :dormant (one idx e :traj/dormant) :stub (one idx e :traj/stub)
                            :sum (one idx e :traj/sum)}))
              (sort-by :run) vec)})

(defn fetch-kotoba
  "Fetch a .kotoba.edn snapshot, project via `proj`; on any failure call `(fallback)`."
  [url proj cb fallback]
  (-> (js/fetch (str url "?t=" (.now js/Date)))
      (.then (fn [r] (if (.-ok r) (.text r) (throw (js/Error. "nf")))))
      (.then (fn [t] (cb (proj (parse-kotoba t)))))
      (.catch (fn [_] (fallback)))))

(defn poll-pulse! []
  (fetch-kotoba "narration.kotoba.edn" kotoba->narr
    (fn [nr] (when nr (swap! state assoc :narr nr) (paint!)))
    (fn [] (fetchj "narration.json" true (fn [nr] (when nr (swap! state assoc :narr nr) (paint!))))))
  (fetch-kotoba "pulse.kotoba.edn" kotoba->pulse
    (fn [p] (when p (swap! state assoc :pulse p) (apply-pulse! p)))
    (fn [] (fetchj "pulse.json" false
             (fn [p] (when p (swap! state assoc :pulse p) (apply-pulse! p))))))
  (fetchj "health.json" false (fn [hh] (when hh (swap! state assoc :health hh) (paint!))))
  (fetchj "ieflow.json" true (fn [ie] (when ie (swap! state assoc :ieflow ie) (paint!))))
  (fetchj "sos.json" true (fn [g] (when g (swap! state assoc :sos g) (paint!)))))

;; ── boot — read the kotoba Datom log (snapshot) in the browser; JSON is fail-open ──────────────

(defn boot-pulse [p]
  (swap! state assoc :pulse p)
  (when p (swap! state assoc :seen
                 (into {} (map (fn [[k v]] [k (get v "lastAt" 0)]) (get p "actors")))))
  (paint!)
  (when p (apply-pulse! p))
  (js/setInterval poll-pulse! POLL_MS))

(defn boot []
  (fetch-kotoba "vitals.kotoba.edn" kotoba->organism
    (fn [d] (swap! state assoc :data d)
      (fetch-kotoba "pulse.kotoba.edn" kotoba->pulse boot-pulse
        (fn [] (fetchj "pulse.json" false boot-pulse)))
      (fetchj "health.json" false (fn [hh] (when hh (swap! state assoc :health hh) (paint!))))
      (fetch-kotoba "trajectory.kotoba.edn" kotoba->traj
        (fn [t] (swap! state assoc :traj t) (paint!))
        (fn [] (fetchj "trajectory.json" true (fn [t] (swap! state assoc :traj t) (paint!)))))
      (fetch-kotoba "narration.kotoba.edn" kotoba->narr
        (fn [nr] (when nr (swap! state assoc :narr nr) (paint!)))
        (fn [] (fetchj "narration.json" true (fn [nr] (when nr (swap! state assoc :narr nr) (paint!))))))
      (fetch-kotoba "joucho.kotoba.edn" kotoba->joucho
        (fn [jo] (swap! state assoc :joucho jo) (paint!))
        (fn [] (fetchj "joucho.json" true (fn [jo] (swap! state assoc :joucho jo) (paint!)))))
      (fetchj "ieflow.json" true (fn [ie] (when ie (swap! state assoc :ieflow ie) (paint!))))
      (fetchj "sos.json" true (fn [g] (when g (swap! state assoc :sos g) (paint!))))
      ;; IE-flow lab: parse the flat Datom snapshot to an EAV index queried client-side
      (fetch-kotoba "lab.kotoba.edn" identity
        (fn [db] (swap! state assoc :lab db :lab-tx []) (paint!))
        (fn [] nil)))
    ;; fail-open: no vitals snapshot yet → JSON projection
    (fn [] (fetchj "organism.json" true
             (fn [d] (swap! state assoc :data d)
               (fetchj "pulse.json" false boot-pulse)
               (fetchj "trajectory.json" true (fn [t] (swap! state assoc :traj t) (paint!)))
               (fetchj "joucho.json" true (fn [jo] (swap! state assoc :joucho jo) (paint!))))))))

(boot)
