"""
Py Kotodama WASM entrypoint for the Twitch clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/twitch.kotoba")
db = DatomicClient.connect()
app = Runtime("twitch-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"twitch.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"twitch.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/users", methods=["POST"])
def create_user(request):
    """Create a User."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['userLogin', 'userName', 'broadcasterType'])
    if err:
        return err, 400
    err = _require(data, ['userLogin', 'userName'])
    if err:
        return err, 400
    if data.get('broadcasterType') and data['broadcasterType'] not in ['partner', 'affiliate', '']:
        return {"error": {"message": "invalid broadcasterType; allowed: " + ", ".join(['partner', 'affiliate', '']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("twitch_use")}
    rec["userLogin"] = data.get('userLogin')
    rec["userName"] = data.get('userName')
    rec["broadcasterType"] = data.get('broadcasterType')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("User", rec)
    return rec, 201

@app.route("/v1/users", methods=["GET"])
def list_users(request):
    """List Users with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("User")
    rows = _apply_filters(rows, params, ['userLogin', 'userName', 'broadcasterType'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/users/<eid>", methods=["GET"])
def get_user(request, eid):
    """Retrieve a User by id (supports ?expand=)."""
    rows = _query("User", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/users/<eid>", methods=["POST", "PATCH"])
def update_user(request, eid):
    """Update a User."""
    rows = _query("User", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['userLogin', 'userName', 'broadcasterType'])
    if err:
        return err, 400
    if data.get('broadcasterType') and data['broadcasterType'] not in ['partner', 'affiliate', '']:
        return {"error": {"message": "invalid broadcasterType; allowed: " + ", ".join(['partner', 'affiliate', '']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("User", rec)
    return rec, 200

@app.route("/v1/users/<eid>", methods=["DELETE"])
def delete_user(request, eid):
    """Delete a User."""
    rows = _query("User", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"twitch.User", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/channels", methods=["POST"])
def create_channel(request):
    """Create a Channel."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['broadcasterLogin', 'broadcasterName', 'broadcasterLanguage', 'gameId', 'gameName', 'title', 'delay'])
    if err:
        return err, 400
    err = _require(data, ['broadcasterLogin', 'broadcasterName'])
    if err:
        return err, 400
    rec = {"id": new_id("twitch_cha")}
    rec["broadcasterLogin"] = data.get('broadcasterLogin')
    rec["broadcasterName"] = data.get('broadcasterName')
    rec["broadcasterLanguage"] = data.get('broadcasterLanguage')
    rec["gameId"] = data.get('gameId')
    rec["gameName"] = data.get('gameName')
    rec["title"] = data.get('title')
    rec["delay"] = _as_int(data.get('delay'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Channel", rec)
    return rec, 201

@app.route("/v1/channels", methods=["GET"])
def list_channels(request):
    """List Channels with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Channel")
    rows = _apply_filters(rows, params, ['broadcasterLogin', 'broadcasterName', 'broadcasterLanguage', 'gameId', 'gameName', 'title', 'delay'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/channels/<eid>", methods=["GET"])
def get_channel(request, eid):
    """Retrieve a Channel by id (supports ?expand=)."""
    rows = _query("Channel", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'gameId': 'Game'})
    return rec, 200

@app.route("/v1/channels/<eid>", methods=["POST", "PATCH"])
def update_channel(request, eid):
    """Update a Channel."""
    rows = _query("Channel", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['broadcasterLogin', 'broadcasterName', 'broadcasterLanguage', 'gameId', 'gameName', 'title', 'delay'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Channel", rec)
    return rec, 200

@app.route("/v1/channels/<eid>", methods=["DELETE"])
def delete_channel(request, eid):
    """Delete a Channel."""
    rows = _query("Channel", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"twitch.Channel", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/streams", methods=["POST"])
def create_stream(request):
    """Create a Stream."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['userId', 'userName', 'gameId', 'gameName', 'type', 'viewerCount', 'title', 'language'])
    if err:
        return err, 400
    err = _require(data, ['userName', 'gameName'])
    if err:
        return err, 400
    rec = {"id": new_id("twitch_str")}
    rec["userId"] = data.get('userId')
    rec["userName"] = data.get('userName')
    rec["gameId"] = data.get('gameId')
    rec["gameName"] = data.get('gameName')
    rec["type"] = data.get('type')
    rec["viewerCount"] = _as_int(data.get('viewerCount'))
    rec["title"] = data.get('title')
    rec["language"] = data.get('language')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Stream", rec)
    return rec, 201

@app.route("/v1/streams", methods=["GET"])
def list_streams(request):
    """List Streams with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Stream")
    rows = _apply_filters(rows, params, ['userId', 'userName', 'gameId', 'gameName', 'type', 'viewerCount', 'title', 'language'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/streams/<eid>", methods=["GET"])
def get_stream(request, eid):
    """Retrieve a Stream by id (supports ?expand=)."""
    rows = _query("Stream", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'userId': 'User', 'gameId': 'Game'})
    return rec, 200

@app.route("/v1/streams/<eid>", methods=["POST", "PATCH"])
def update_stream(request, eid):
    """Update a Stream."""
    rows = _query("Stream", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['userId', 'userName', 'gameId', 'gameName', 'type', 'viewerCount', 'title', 'language'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Stream", rec)
    return rec, 200

@app.route("/v1/streams/<eid>", methods=["DELETE"])
def delete_stream(request, eid):
    """Delete a Stream."""
    rows = _query("Stream", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"twitch.Stream", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/videos", methods=["POST"])
def create_video(request):
    """Create a Video."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['userId', 'title', 'description', 'type', 'viewable', 'viewCount', 'duration'])
    if err:
        return err, 400
    err = _require(data, ['title', 'description'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['archive', 'highlight', 'upload']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['archive', 'highlight', 'upload']), "type": "invalid_request_error"}}, 400
    if data.get('viewable') and data['viewable'] not in ['public', 'private', 'unlisted']:
        return {"error": {"message": "invalid viewable; allowed: " + ", ".join(['public', 'private', 'unlisted']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("twitch_vid")}
    rec["userId"] = data.get('userId')
    rec["title"] = data.get('title')
    rec["description"] = data.get('description')
    rec["type"] = data.get('type')
    rec["viewable"] = data.get('viewable')
    rec["viewCount"] = _as_int(data.get('viewCount'))
    rec["duration"] = _as_int(data.get('duration'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Video", rec)
    return rec, 201

@app.route("/v1/videos", methods=["GET"])
def list_videos(request):
    """List Videos with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Video")
    rows = _apply_filters(rows, params, ['userId', 'title', 'description', 'type', 'viewable', 'viewCount', 'duration'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/videos/<eid>", methods=["GET"])
def get_video(request, eid):
    """Retrieve a Video by id (supports ?expand=)."""
    rows = _query("Video", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'userId': 'User'})
    return rec, 200

@app.route("/v1/videos/<eid>", methods=["POST", "PATCH"])
def update_video(request, eid):
    """Update a Video."""
    rows = _query("Video", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['userId', 'title', 'description', 'type', 'viewable', 'viewCount', 'duration'])
    if err:
        return err, 400
    if data.get('type') and data['type'] not in ['archive', 'highlight', 'upload']:
        return {"error": {"message": "invalid type; allowed: " + ", ".join(['archive', 'highlight', 'upload']), "type": "invalid_request_error"}}, 400
    if data.get('viewable') and data['viewable'] not in ['public', 'private', 'unlisted']:
        return {"error": {"message": "invalid viewable; allowed: " + ", ".join(['public', 'private', 'unlisted']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Video", rec)
    return rec, 200

@app.route("/v1/videos/<eid>", methods=["DELETE"])
def delete_video(request, eid):
    """Delete a Video."""
    rows = _query("Video", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"twitch.Video", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/clips", methods=["POST"])
def create_clip(request):
    """Create a Clip."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['broadcasterId', 'creatorId', 'gameId', 'title', 'viewCount', 'duration', 'isFeatured'])
    if err:
        return err, 400
    err = _require(data, ['title', 'viewCount'])
    if err:
        return err, 400
    rec = {"id": new_id("twitch_cli")}
    rec["broadcasterId"] = data.get('broadcasterId')
    rec["creatorId"] = data.get('creatorId')
    rec["gameId"] = data.get('gameId')
    rec["title"] = data.get('title')
    rec["viewCount"] = _as_int(data.get('viewCount'))
    rec["duration"] = _as_float(data.get('duration'))
    rec["isFeatured"] = _as_bool(data.get('isFeatured'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Clip", rec)
    return rec, 201

@app.route("/v1/clips", methods=["GET"])
def list_clips(request):
    """List Clips with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Clip")
    rows = _apply_filters(rows, params, ['broadcasterId', 'creatorId', 'gameId', 'title', 'viewCount', 'duration', 'isFeatured'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/clips/<eid>", methods=["GET"])
def get_clip(request, eid):
    """Retrieve a Clip by id (supports ?expand=)."""
    rows = _query("Clip", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'gameId': 'Game'})
    return rec, 200

@app.route("/v1/clips/<eid>", methods=["POST", "PATCH"])
def update_clip(request, eid):
    """Update a Clip."""
    rows = _query("Clip", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['broadcasterId', 'creatorId', 'gameId', 'title', 'viewCount', 'duration', 'isFeatured'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Clip", rec)
    return rec, 200

@app.route("/v1/clips/<eid>", methods=["DELETE"])
def delete_clip(request, eid):
    """Delete a Clip."""
    rows = _query("Clip", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"twitch.Clip", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/games", methods=["POST"])
def create_game(request):
    """Create a Game."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'boxArtUrl'])
    if err:
        return err, 400
    err = _require(data, ['name', 'boxArtUrl'])
    if err:
        return err, 400
    rec = {"id": new_id("twitch_gam")}
    rec["name"] = data.get('name')
    rec["boxArtUrl"] = data.get('boxArtUrl')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Game", rec)
    return rec, 201

@app.route("/v1/games", methods=["GET"])
def list_games(request):
    """List Games with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Game")
    rows = _apply_filters(rows, params, ['name', 'boxArtUrl'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/games/<eid>", methods=["GET"])
def get_game(request, eid):
    """Retrieve a Game by id (supports ?expand=)."""
    rows = _query("Game", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/games/<eid>", methods=["POST", "PATCH"])
def update_game(request, eid):
    """Update a Game."""
    rows = _query("Game", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'boxArtUrl'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Game", rec)
    return rec, 200

@app.route("/v1/games/<eid>", methods=["DELETE"])
def delete_game(request, eid):
    """Delete a Game."""
    rows = _query("Game", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"twitch.Game", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "twitch-compat", "tier": "L4",
            "entities": ['User', 'Channel', 'Stream', 'Video', 'Clip', 'Game']}, 200


if __name__ == "__main__":
    app.start()
