"""
Py Kotodama WASM entrypoint for the D_wave clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/d_wave.kotoba")
db = DatomicClient.connect()
app = Runtime("d_wave-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"d_wave.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"d_wave.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/problemmetadatas", methods=["POST"])
def create_problem_metadata(request):
    """Create a ProblemMetadata."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type', 'label', 'status', 'submittedBy', 'submittedOn', 'solvedOn'])
    if err:
        return err, 400
    err = _require(data, ['type', 'label'])
    if err:
        return err, 400
    if data.get('status') and data['status'] not in ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED']:
        return {"error": {"message": "invalid status; allowed: " + ", ".join(['PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED']), "type": "invalid_request_error"}}, 400
    rec = {"id": new_id("dwave_pro")}
    rec["type"] = data.get('type')
    rec["label"] = data.get('label')
    rec["status"] = data.get('status')
    rec["submittedBy"] = data.get('submittedBy')
    rec["submittedOn"] = data.get('submittedOn')
    rec["solvedOn"] = data.get('solvedOn')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("ProblemMetadata", rec)
    return rec, 201

@app.route("/v1/problemmetadatas", methods=["GET"])
def list_problem_metadatas(request):
    """List ProblemMetadatas with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("ProblemMetadata")
    rows = _apply_filters(rows, params, ['type', 'label', 'status', 'submittedBy', 'submittedOn', 'solvedOn'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/problemmetadatas/<eid>", methods=["GET"])
def get_problem_metadata(request, eid):
    """Retrieve a ProblemMetadata by id (supports ?expand=)."""
    rows = _query("ProblemMetadata", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/problemmetadatas/<eid>", methods=["POST", "PATCH"])
def update_problem_metadata(request, eid):
    """Update a ProblemMetadata."""
    rows = _query("ProblemMetadata", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['type', 'label', 'status', 'submittedBy', 'submittedOn', 'solvedOn'])
    if err:
        return err, 400
    if data.get('status') and data['status'] not in ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED']:
        return {"error": {"message": "invalid status; allowed: " + ", ".join(['PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED']), "type": "invalid_request_error"}}, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("ProblemMetadata", rec)
    return rec, 200

@app.route("/v1/problemmetadatas/<eid>", methods=["DELETE"])
def delete_problem_metadata(request, eid):
    """Delete a ProblemMetadata."""
    rows = _query("ProblemMetadata", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"d_wave.ProblemMetadata", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/solverconfigurations", methods=["POST"])
def create_solver_configuration(request):
    """Create a SolverConfiguration."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['status', 'description', 'avgLoad'])
    if err:
        return err, 400
    err = _require(data, ['status', 'description'])
    if err:
        return err, 400
    rec = {"id": new_id("dwave_sol")}
    rec["status"] = data.get('status')
    rec["description"] = data.get('description')
    rec["avgLoad"] = _as_float(data.get('avgLoad'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("SolverConfiguration", rec)
    return rec, 201

@app.route("/v1/solverconfigurations", methods=["GET"])
def list_solver_configurations(request):
    """List SolverConfigurations with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("SolverConfiguration")
    rows = _apply_filters(rows, params, ['status', 'description', 'avgLoad'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/solverconfigurations/<eid>", methods=["GET"])
def get_solver_configuration(request, eid):
    """Retrieve a SolverConfiguration by id (supports ?expand=)."""
    rows = _query("SolverConfiguration", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/solverconfigurations/<eid>", methods=["POST", "PATCH"])
def update_solver_configuration(request, eid):
    """Update a SolverConfiguration."""
    rows = _query("SolverConfiguration", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['status', 'description', 'avgLoad'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("SolverConfiguration", rec)
    return rec, 200

@app.route("/v1/solverconfigurations/<eid>", methods=["DELETE"])
def delete_solver_configuration(request, eid):
    """Delete a SolverConfiguration."""
    rows = _query("SolverConfiguration", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"d_wave.SolverConfiguration", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/structuredproblemdatas", methods=["POST"])
def create_structured_problem_data(request):
    """Create a StructuredProblemData."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['format', 'lin', 'quad', 'offset'])
    if err:
        return err, 400
    err = _require(data, ['format', 'lin'])
    if err:
        return err, 400
    rec = {"id": new_id("dwave_str")}
    rec["format"] = data.get('format')
    rec["lin"] = data.get('lin')
    rec["quad"] = data.get('quad')
    rec["offset"] = _as_float(data.get('offset'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("StructuredProblemData", rec)
    return rec, 201

@app.route("/v1/structuredproblemdatas", methods=["GET"])
def list_structured_problem_datas(request):
    """List StructuredProblemDatas with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("StructuredProblemData")
    rows = _apply_filters(rows, params, ['format', 'lin', 'quad', 'offset'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/structuredproblemdatas/<eid>", methods=["GET"])
def get_structured_problem_data(request, eid):
    """Retrieve a StructuredProblemData by id (supports ?expand=)."""
    rows = _query("StructuredProblemData", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/structuredproblemdatas/<eid>", methods=["POST", "PATCH"])
def update_structured_problem_data(request, eid):
    """Update a StructuredProblemData."""
    rows = _query("StructuredProblemData", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['format', 'lin', 'quad', 'offset'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("StructuredProblemData", rec)
    return rec, 200

@app.route("/v1/structuredproblemdatas/<eid>", methods=["DELETE"])
def delete_structured_problem_data(request, eid):
    """Delete a StructuredProblemData."""
    rows = _query("StructuredProblemData", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"d_wave.StructuredProblemData", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/structuredproblemanswers", methods=["POST"])
def create_structured_problem_answer(request):
    """Create a StructuredProblemAnswer."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['format', 'activeVariables', 'energies', 'solutions', 'numOccurrences', 'numVariables', 'timing'])
    if err:
        return err, 400
    err = _require(data, ['format', 'activeVariables'])
    if err:
        return err, 400
    rec = {"id": new_id("dwave_str")}
    rec["format"] = data.get('format')
    rec["activeVariables"] = data.get('activeVariables')
    rec["energies"] = data.get('energies')
    rec["solutions"] = data.get('solutions')
    rec["numOccurrences"] = data.get('numOccurrences')
    rec["numVariables"] = _as_int(data.get('numVariables'))
    rec["timing"] = data.get('timing')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("StructuredProblemAnswer", rec)
    return rec, 201

@app.route("/v1/structuredproblemanswers", methods=["GET"])
def list_structured_problem_answers(request):
    """List StructuredProblemAnswers with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("StructuredProblemAnswer")
    rows = _apply_filters(rows, params, ['format', 'activeVariables', 'energies', 'solutions', 'numOccurrences', 'numVariables', 'timing'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/structuredproblemanswers/<eid>", methods=["GET"])
def get_structured_problem_answer(request, eid):
    """Retrieve a StructuredProblemAnswer by id (supports ?expand=)."""
    rows = _query("StructuredProblemAnswer", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/structuredproblemanswers/<eid>", methods=["POST", "PATCH"])
def update_structured_problem_answer(request, eid):
    """Update a StructuredProblemAnswer."""
    rows = _query("StructuredProblemAnswer", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['format', 'activeVariables', 'energies', 'solutions', 'numOccurrences', 'numVariables', 'timing'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("StructuredProblemAnswer", rec)
    return rec, 200

@app.route("/v1/structuredproblemanswers/<eid>", methods=["DELETE"])
def delete_structured_problem_answer(request, eid):
    """Delete a StructuredProblemAnswer."""
    rows = _query("StructuredProblemAnswer", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"d_wave.StructuredProblemAnswer", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/regions", methods=["POST"])
def create_region(request):
    """Create a Region."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['code', 'name', 'endpoint'])
    if err:
        return err, 400
    err = _require(data, ['code', 'name'])
    if err:
        return err, 400
    rec = {"id": new_id("dwave_reg")}
    rec["code"] = data.get('code')
    rec["name"] = data.get('name')
    rec["endpoint"] = data.get('endpoint')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Region", rec)
    return rec, 201

@app.route("/v1/regions", methods=["GET"])
def list_regions(request):
    """List Regions with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Region")
    rows = _apply_filters(rows, params, ['code', 'name', 'endpoint'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/regions/<eid>", methods=["GET"])
def get_region(request, eid):
    """Retrieve a Region by id (supports ?expand=)."""
    rows = _query("Region", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/regions/<eid>", methods=["POST", "PATCH"])
def update_region(request, eid):
    """Update a Region."""
    rows = _query("Region", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['code', 'name', 'endpoint'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Region", rec)
    return rec, 200

@app.route("/v1/regions/<eid>", methods=["DELETE"])
def delete_region(request, eid):
    """Delete a Region."""
    rows = _query("Region", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"d_wave.Region", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "d_wave-compat", "tier": "L4",
            "entities": ['ProblemMetadata', 'SolverConfiguration', 'StructuredProblemData', 'StructuredProblemAnswer', 'Region']}, 200


if __name__ == "__main__":
    app.start()
