"""
Py Kotodama WASM entrypoint for the Lime_scooters clean-room actor.

Clean-room, API-shaped CRUD over a Datomic-backed Kotoba schema.
Generated by 70-tools/deepen_actors.py (ADR 260607 deepening phase).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/lime_scooters.kotoba")
db = DatomicClient.connect()
app = Runtime("lime_scooters-compat")


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"lime_scooters.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    """Read records of an entity from Datomic (optionally by id)."""
    pattern = {"entity": f"lime_scooters.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing)}}
    return None


@app.route("/v1/drivers", methods=["POST"])
def create_driver(request):
    """Create a Driver."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'licensePlate'])
    if err:
        return err, 400
    rec = {"id": new_id("limescoo_dri")}
    rec["name"] = data.get('name')
    rec["licensePlate"] = data.get('licensePlate')
    rec["rating"] = float(data.get('rating') or 0)
    rec["online"] = bool(data.get('online'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Driver", rec)
    return rec, 201

@app.route("/v1/drivers", methods=["GET"])
def list_drivers(request):
    """List Drivers."""
    items = _query("Driver")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/drivers/<eid>", methods=["GET"])
def get_driver(request, eid):
    """Retrieve a Driver by id."""
    rows = _query("Driver", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/drivers/<eid>", methods=["POST", "PATCH"])
def update_driver(request, eid):
    """Update a Driver."""
    rows = _query("Driver", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Driver", rec)
    return rec, 200

@app.route("/v1/drivers/<eid>", methods=["DELETE"])
def delete_driver(request, eid):
    """Delete a Driver."""
    rows = _query("Driver", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"lime_scooters.Driver", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/riders", methods=["POST"])
def create_rider(request):
    """Create a Rider."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'phone'])
    if err:
        return err, 400
    rec = {"id": new_id("limescoo_rid")}
    rec["name"] = data.get('name')
    rec["phone"] = data.get('phone')
    rec["rating"] = float(data.get('rating') or 0)
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Rider", rec)
    return rec, 201

@app.route("/v1/riders", methods=["GET"])
def list_riders(request):
    """List Riders."""
    items = _query("Rider")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/riders/<eid>", methods=["GET"])
def get_rider(request, eid):
    """Retrieve a Rider by id."""
    rows = _query("Rider", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/riders/<eid>", methods=["POST", "PATCH"])
def update_rider(request, eid):
    """Update a Rider."""
    rows = _query("Rider", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Rider", rec)
    return rec, 200

@app.route("/v1/riders/<eid>", methods=["DELETE"])
def delete_rider(request, eid):
    """Delete a Rider."""
    rows = _query("Rider", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"lime_scooters.Rider", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/trips", methods=["POST"])
def create_trip(request):
    """Create a Trip."""
    data = request.json or request.form or {}
    err = _require(data, ['origin', 'destination'])
    if err:
        return err, 400
    rec = {"id": new_id("limescoo_tri")}
    rec["riderId"] = data.get('riderId')
    rec["driverId"] = data.get('driverId')
    rec["origin"] = data.get('origin')
    rec["destination"] = data.get('destination')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Trip", rec)
    return rec, 201

@app.route("/v1/trips", methods=["GET"])
def list_trips(request):
    """List Trips."""
    items = _query("Trip")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/trips/<eid>", methods=["GET"])
def get_trip(request, eid):
    """Retrieve a Trip by id."""
    rows = _query("Trip", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/trips/<eid>", methods=["POST", "PATCH"])
def update_trip(request, eid):
    """Update a Trip."""
    rows = _query("Trip", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Trip", rec)
    return rec, 200

@app.route("/v1/trips/<eid>", methods=["DELETE"])
def delete_trip(request, eid):
    """Delete a Trip."""
    rows = _query("Trip", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"lime_scooters.Trip", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/vehicles", methods=["POST"])
def create_vehicle(request):
    """Create a Vehicle."""
    data = request.json or request.form or {}
    err = _require(data, ['make', 'model'])
    if err:
        return err, 400
    rec = {"id": new_id("limescoo_veh")}
    rec["driverId"] = data.get('driverId')
    rec["make"] = data.get('make')
    rec["model"] = data.get('model')
    rec["plate"] = data.get('plate')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Vehicle", rec)
    return rec, 201

@app.route("/v1/vehicles", methods=["GET"])
def list_vehicles(request):
    """List Vehicles."""
    items = _query("Vehicle")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/vehicles/<eid>", methods=["GET"])
def get_vehicle(request, eid):
    """Retrieve a Vehicle by id."""
    rows = _query("Vehicle", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/vehicles/<eid>", methods=["POST", "PATCH"])
def update_vehicle(request, eid):
    """Update a Vehicle."""
    rows = _query("Vehicle", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Vehicle", rec)
    return rec, 200

@app.route("/v1/vehicles/<eid>", methods=["DELETE"])
def delete_vehicle(request, eid):
    """Delete a Vehicle."""
    rows = _query("Vehicle", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"lime_scooters.Vehicle", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/fares", methods=["POST"])
def create_fare(request):
    """Create a Fare."""
    data = request.json or request.form or {}
    err = _require(data, ['base', 'distanceKm'])
    if err:
        return err, 400
    rec = {"id": new_id("limescoo_far")}
    rec["tripId"] = data.get('tripId')
    rec["base"] = float(data.get('base') or 0)
    rec["distanceKm"] = float(data.get('distanceKm') or 0)
    rec["total"] = float(data.get('total') or 0)
    rec["currency"] = data.get('currency')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Fare", rec)
    return rec, 201

@app.route("/v1/fares", methods=["GET"])
def list_fares(request):
    """List Fares."""
    items = _query("Fare")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/fares/<eid>", methods=["GET"])
def get_fare(request, eid):
    """Retrieve a Fare by id."""
    rows = _query("Fare", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/fares/<eid>", methods=["POST", "PATCH"])
def update_fare(request, eid):
    """Update a Fare."""
    rows = _query("Fare", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Fare", rec)
    return rec, 200

@app.route("/v1/fares/<eid>", methods=["DELETE"])
def delete_fare(request, eid):
    """Delete a Fare."""
    rows = _query("Fare", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"lime_scooters.Fare", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/ratings", methods=["POST"])
def create_rating(request):
    """Create a Rating."""
    data = request.json or request.form or {}
    err = _require(data, ['byRole', 'score'])
    if err:
        return err, 400
    rec = {"id": new_id("limescoo_rat")}
    rec["tripId"] = data.get('tripId')
    rec["byRole"] = data.get('byRole')
    rec["score"] = int(data.get('score') or 0)
    rec["comment"] = data.get('comment')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Rating", rec)
    return rec, 201

@app.route("/v1/ratings", methods=["GET"])
def list_ratings(request):
    """List Ratings."""
    items = _query("Rating")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/ratings/<eid>", methods=["GET"])
def get_rating(request, eid):
    """Retrieve a Rating by id."""
    rows = _query("Rating", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/ratings/<eid>", methods=["POST", "PATCH"])
def update_rating(request, eid):
    """Update a Rating."""
    rows = _query("Rating", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Rating", rec)
    return rec, 200

@app.route("/v1/ratings/<eid>", methods=["DELETE"])
def delete_rating(request, eid):
    """Delete a Rating."""
    rows = _query("Rating", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"lime_scooters.Rating", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "lime_scooters-compat", "entities": ['Driver', 'Rider', 'Trip', 'Vehicle', 'Fare', 'Rating']}, 200


if __name__ == "__main__":
    app.start()
