"""
Py Kotodama WASM entrypoint for the Bigcommerce clean-room actor.

Clean-room, API-shaped CRUD over a Datomic-backed Kotoba schema.
Generated by 70-tools/deepen_actors.py (ADR 260607 deepening phase).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/bigcommerce.kotoba")
db = DatomicClient.connect()
app = Runtime("bigcommerce-compat")


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"bigcommerce.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    """Read records of an entity from Datomic (optionally by id)."""
    pattern = {"entity": f"bigcommerce.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing)}}
    return None


@app.route("/v1/products", methods=["POST"])
def create_product(request):
    """Create a Product."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'type'])
    if err:
        return err, 400
    rec = {"id": new_id("bigcomme_pro")}
    rec["name"] = data.get('name')
    rec["type"] = data.get('type')
    rec["sku"] = data.get('sku')
    rec["description"] = data.get('description')
    rec["weight"] = float(data.get('weight') or 0)
    rec["price"] = float(data.get('price') or 0)
    rec["costPrice"] = float(data.get('costPrice') or 0)
    rec["retailPrice"] = float(data.get('retailPrice') or 0)
    rec["salePrice"] = float(data.get('salePrice') or 0)
    rec["brandId"] = int(data.get('brandId') or 0)
    rec["inventoryLevel"] = int(data.get('inventoryLevel') or 0)
    rec["inventoryTracking"] = data.get('inventoryTracking')
    rec["isFreeShipping"] = bool(data.get('isFreeShipping'))
    rec["isVisible"] = bool(data.get('isVisible'))
    rec["isFeatured"] = bool(data.get('isFeatured'))
    rec["availability"] = data.get('availability')
    rec["condition"] = data.get('condition')
    rec["upc"] = data.get('upc')
    rec["gtin"] = data.get('gtin')
    rec["mpn"] = data.get('mpn')
    rec["totalSold"] = int(data.get('totalSold') or 0)
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Product", rec)
    return rec, 201

@app.route("/v1/products", methods=["GET"])
def list_products(request):
    """List Products."""
    items = _query("Product")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/products/<eid>", methods=["GET"])
def get_product(request, eid):
    """Retrieve a Product by id."""
    rows = _query("Product", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/products/<eid>", methods=["POST", "PATCH"])
def update_product(request, eid):
    """Update a Product."""
    rows = _query("Product", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Product", rec)
    return rec, 200

@app.route("/v1/products/<eid>", methods=["DELETE"])
def delete_product(request, eid):
    """Delete a Product."""
    rows = _query("Product", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"bigcommerce.Product", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/variants", methods=["POST"])
def create_variant(request):
    """Create a Variant."""
    data = request.json or request.form or {}
    err = _require(data, ['sku', 'price'])
    if err:
        return err, 400
    rec = {"id": new_id("bigcomme_var")}
    rec["productId"] = int(data.get('productId') or 0)
    rec["sku"] = data.get('sku')
    rec["price"] = float(data.get('price') or 0)
    rec["costPrice"] = float(data.get('costPrice') or 0)
    rec["salePrice"] = float(data.get('salePrice') or 0)
    rec["weight"] = float(data.get('weight') or 0)
    rec["upc"] = data.get('upc')
    rec["gtin"] = data.get('gtin')
    rec["mpn"] = data.get('mpn')
    rec["inventoryLevel"] = int(data.get('inventoryLevel') or 0)
    rec["purchasingDisabled"] = bool(data.get('purchasingDisabled'))
    rec["calculatedPrice"] = float(data.get('calculatedPrice') or 0)
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Variant", rec)
    return rec, 201

@app.route("/v1/variants", methods=["GET"])
def list_variants(request):
    """List Variants."""
    items = _query("Variant")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/variants/<eid>", methods=["GET"])
def get_variant(request, eid):
    """Retrieve a Variant by id."""
    rows = _query("Variant", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/variants/<eid>", methods=["POST", "PATCH"])
def update_variant(request, eid):
    """Update a Variant."""
    rows = _query("Variant", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Variant", rec)
    return rec, 200

@app.route("/v1/variants/<eid>", methods=["DELETE"])
def delete_variant(request, eid):
    """Delete a Variant."""
    rows = _query("Variant", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"bigcommerce.Variant", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/categories", methods=["POST"])
def create_category(request):
    """Create a Category."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'description'])
    if err:
        return err, 400
    rec = {"id": new_id("bigcomme_cat")}
    rec["parentId"] = int(data.get('parentId') or 0)
    rec["name"] = data.get('name')
    rec["description"] = data.get('description')
    rec["views"] = int(data.get('views') or 0)
    rec["sortOrder"] = int(data.get('sortOrder') or 0)
    rec["pageTitle"] = data.get('pageTitle')
    rec["isVisible"] = bool(data.get('isVisible'))
    rec["defaultProductSort"] = data.get('defaultProductSort')
    rec["imageUrl"] = data.get('imageUrl')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Category", rec)
    return rec, 201

@app.route("/v1/categories", methods=["GET"])
def list_categories(request):
    """List Categories."""
    items = _query("Category")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/categories/<eid>", methods=["GET"])
def get_category(request, eid):
    """Retrieve a Category by id."""
    rows = _query("Category", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/categories/<eid>", methods=["POST", "PATCH"])
def update_category(request, eid):
    """Update a Category."""
    rows = _query("Category", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Category", rec)
    return rec, 200

@app.route("/v1/categories/<eid>", methods=["DELETE"])
def delete_category(request, eid):
    """Delete a Category."""
    rows = _query("Category", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"bigcommerce.Category", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/brands", methods=["POST"])
def create_brand(request):
    """Create a Brand."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'pageTitle'])
    if err:
        return err, 400
    rec = {"id": new_id("bigcomme_bra")}
    rec["name"] = data.get('name')
    rec["pageTitle"] = data.get('pageTitle')
    rec["metaDescription"] = data.get('metaDescription')
    rec["searchKeywords"] = data.get('searchKeywords')
    rec["imageUrl"] = data.get('imageUrl')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Brand", rec)
    return rec, 201

@app.route("/v1/brands", methods=["GET"])
def list_brands(request):
    """List Brands."""
    items = _query("Brand")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/brands/<eid>", methods=["GET"])
def get_brand(request, eid):
    """Retrieve a Brand by id."""
    rows = _query("Brand", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/brands/<eid>", methods=["POST", "PATCH"])
def update_brand(request, eid):
    """Update a Brand."""
    rows = _query("Brand", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Brand", rec)
    return rec, 200

@app.route("/v1/brands/<eid>", methods=["DELETE"])
def delete_brand(request, eid):
    """Delete a Brand."""
    rows = _query("Brand", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"bigcommerce.Brand", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/customers", methods=["POST"])
def create_customer(request):
    """Create a Customer."""
    data = request.json or request.form or {}
    err = _require(data, ['email', 'firstName'])
    if err:
        return err, 400
    rec = {"id": new_id("bigcomme_cus")}
    rec["email"] = data.get('email')
    rec["firstName"] = data.get('firstName')
    rec["lastName"] = data.get('lastName')
    rec["company"] = data.get('company')
    rec["phone"] = data.get('phone')
    rec["notes"] = data.get('notes')
    rec["taxExemptCategory"] = data.get('taxExemptCategory')
    rec["customerGroupId"] = int(data.get('customerGroupId') or 0)
    rec["addressCount"] = int(data.get('addressCount') or 0)
    rec["originChannelId"] = int(data.get('originChannelId') or 0)
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Customer", rec)
    return rec, 201

@app.route("/v1/customers", methods=["GET"])
def list_customers(request):
    """List Customers."""
    items = _query("Customer")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/customers/<eid>", methods=["GET"])
def get_customer(request, eid):
    """Retrieve a Customer by id."""
    rows = _query("Customer", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/customers/<eid>", methods=["POST", "PATCH"])
def update_customer(request, eid):
    """Update a Customer."""
    rows = _query("Customer", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Customer", rec)
    return rec, 200

@app.route("/v1/customers/<eid>", methods=["DELETE"])
def delete_customer(request, eid):
    """Delete a Customer."""
    rows = _query("Customer", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"bigcommerce.Customer", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/orders", methods=["POST"])
def create_order(request):
    """Create a Order."""
    data = request.json or request.form or {}
    err = _require(data, ['status', 'paymentStatus'])
    if err:
        return err, 400
    rec = {"id": new_id("bigcomme_ord")}
    rec["status"] = data.get('status')
    rec["statusId"] = int(data.get('statusId') or 0)
    rec["paymentStatus"] = data.get('paymentStatus')
    rec["paymentMethod"] = data.get('paymentMethod')
    rec["currencyCode"] = data.get('currencyCode')
    rec["totalIncTax"] = data.get('totalIncTax')
    rec["subtotalIncTax"] = data.get('subtotalIncTax')
    rec["customerId"] = int(data.get('customerId') or 0)
    rec["customerMessage"] = data.get('customerMessage')
    rec["orderSource"] = data.get('orderSource')
    rec["ipAddress"] = data.get('ipAddress')
    rec["isDeleted"] = bool(data.get('isDeleted'))
    rec["geoipCountry"] = data.get('geoipCountry')
    rec["taxProviderId"] = data.get('taxProviderId')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Order", rec)
    return rec, 201

@app.route("/v1/orders", methods=["GET"])
def list_orders(request):
    """List Orders."""
    items = _query("Order")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/orders/<eid>", methods=["GET"])
def get_order(request, eid):
    """Retrieve a Order by id."""
    rows = _query("Order", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/orders/<eid>", methods=["POST", "PATCH"])
def update_order(request, eid):
    """Update a Order."""
    rows = _query("Order", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Order", rec)
    return rec, 200

@app.route("/v1/orders/<eid>", methods=["DELETE"])
def delete_order(request, eid):
    """Delete a Order."""
    rows = _query("Order", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"bigcommerce.Order", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "bigcommerce-compat", "entities": ['Product', 'Variant', 'Category', 'Brand', 'Customer', 'Order']}, 200


if __name__ == "__main__":
    app.start()
