apiVersion: etzhayyim.io/v1alpha1
kind: AppDiscovery
metadata:
  name: etzhayyim-performer-org-etzhayyim-sys-app-hrse-pba7d22f
  namespace: etzhayyim-apps-prod
spec:
  actorName: hrse-app
  framework: nextjs
  capabilities:
    - EmailAnalysisCapability
    - RecordRoutingCapability
    - LLMIntegrationCapability
    - ResendWebhookCapability
    - AuthenticationCapability
    - ClerkSubscriptionCapability
    - MasterDataManagementCapability
    - AgencyProfileCapability
    - RecruiterAgentCapability
    - SESEmailAutomationCapability
