"""
Py Kotodama WASM entrypoint for the Digitalocean clean-room actor.

Clean-room, API-shaped CRUD over a Datomic-backed Kotoba schema.
Generated by 70-tools/deepen_actors.py (ADR 260607 deepening phase).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/digitalocean.kotoba")
db = DatomicClient.connect()
app = Runtime("digitalocean-compat")


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"digitalocean.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    """Read records of an entity from Datomic (optionally by id)."""
    pattern = {"entity": f"digitalocean.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing)}}
    return None


@app.route("/v1/droplets", methods=["POST"])
def create_droplet(request):
    """Create a Droplet."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'memory'])
    if err:
        return err, 400
    rec = {"id": new_id("digitalo_dro")}
    rec["name"] = data.get('name')
    rec["memory"] = int(data.get('memory') or 0)
    rec["vcpus"] = int(data.get('vcpus') or 0)
    rec["disk"] = int(data.get('disk') or 0)
    rec["locked"] = bool(data.get('locked'))
    rec["status"] = data.get('status')
    rec["sizeSlug"] = data.get('sizeSlug')
    rec["vpcUuid"] = data.get('vpcUuid')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Droplet", rec)
    return rec, 201

@app.route("/v1/droplets", methods=["GET"])
def list_droplets(request):
    """List Droplets."""
    items = _query("Droplet")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/droplets/<eid>", methods=["GET"])
def get_droplet(request, eid):
    """Retrieve a Droplet by id."""
    rows = _query("Droplet", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/droplets/<eid>", methods=["POST", "PATCH"])
def update_droplet(request, eid):
    """Update a Droplet."""
    rows = _query("Droplet", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Droplet", rec)
    return rec, 200

@app.route("/v1/droplets/<eid>", methods=["DELETE"])
def delete_droplet(request, eid):
    """Delete a Droplet."""
    rows = _query("Droplet", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"digitalocean.Droplet", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/volumes", methods=["POST"])
def create_volume(request):
    """Create a Volume."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'description'])
    if err:
        return err, 400
    rec = {"id": new_id("digitalo_vol")}
    rec["name"] = data.get('name')
    rec["description"] = data.get('description')
    rec["sizeGigabytes"] = int(data.get('sizeGigabytes') or 0)
    rec["filesystemType"] = data.get('filesystemType')
    rec["filesystemLabel"] = data.get('filesystemLabel')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Volume", rec)
    return rec, 201

@app.route("/v1/volumes", methods=["GET"])
def list_volumes(request):
    """List Volumes."""
    items = _query("Volume")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/volumes/<eid>", methods=["GET"])
def get_volume(request, eid):
    """Retrieve a Volume by id."""
    rows = _query("Volume", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/volumes/<eid>", methods=["POST", "PATCH"])
def update_volume(request, eid):
    """Update a Volume."""
    rows = _query("Volume", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Volume", rec)
    return rec, 200

@app.route("/v1/volumes/<eid>", methods=["DELETE"])
def delete_volume(request, eid):
    """Delete a Volume."""
    rows = _query("Volume", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"digitalocean.Volume", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/images", methods=["POST"])
def create_image(request):
    """Create a Image."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'type'])
    if err:
        return err, 400
    rec = {"id": new_id("digitalo_ima")}
    rec["name"] = data.get('name')
    rec["type"] = data.get('type')
    rec["distribution"] = data.get('distribution')
    rec["slug"] = data.get('slug')
    rec["public"] = bool(data.get('public'))
    rec["minDiskSize"] = int(data.get('minDiskSize') or 0)
    rec["sizeGigabytes"] = float(data.get('sizeGigabytes') or 0)
    rec["description"] = data.get('description')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Image", rec)
    return rec, 201

@app.route("/v1/images", methods=["GET"])
def list_images(request):
    """List Images."""
    items = _query("Image")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/images/<eid>", methods=["GET"])
def get_image(request, eid):
    """Retrieve a Image by id."""
    rows = _query("Image", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/images/<eid>", methods=["POST", "PATCH"])
def update_image(request, eid):
    """Update a Image."""
    rows = _query("Image", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Image", rec)
    return rec, 200

@app.route("/v1/images/<eid>", methods=["DELETE"])
def delete_image(request, eid):
    """Delete a Image."""
    rows = _query("Image", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"digitalocean.Image", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/projects", methods=["POST"])
def create_project(request):
    """Create a Project."""
    data = request.json or request.form or {}
    err = _require(data, ['ownerUuid', 'name'])
    if err:
        return err, 400
    rec = {"id": new_id("digitalo_pro")}
    rec["ownerUuid"] = data.get('ownerUuid')
    rec["ownerId"] = int(data.get('ownerId') or 0)
    rec["name"] = data.get('name')
    rec["description"] = data.get('description')
    rec["purpose"] = data.get('purpose')
    rec["environment"] = data.get('environment')
    rec["isDefault"] = bool(data.get('isDefault'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Project", rec)
    return rec, 201

@app.route("/v1/projects", methods=["GET"])
def list_projects(request):
    """List Projects."""
    items = _query("Project")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/projects/<eid>", methods=["GET"])
def get_project(request, eid):
    """Retrieve a Project by id."""
    rows = _query("Project", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/projects/<eid>", methods=["POST", "PATCH"])
def update_project(request, eid):
    """Update a Project."""
    rows = _query("Project", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Project", rec)
    return rec, 200

@app.route("/v1/projects/<eid>", methods=["DELETE"])
def delete_project(request, eid):
    """Delete a Project."""
    rows = _query("Project", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"digitalocean.Project", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/regions", methods=["POST"])
def create_region(request):
    """Create a Region."""
    data = request.json or request.form or {}
    err = _require(data, ['slug', 'name'])
    if err:
        return err, 400
    rec = {"id": new_id("digitalo_reg")}
    rec["slug"] = data.get('slug')
    rec["name"] = data.get('name')
    rec["available"] = bool(data.get('available'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Region", rec)
    return rec, 201

@app.route("/v1/regions", methods=["GET"])
def list_regions(request):
    """List Regions."""
    items = _query("Region")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/regions/<eid>", methods=["GET"])
def get_region(request, eid):
    """Retrieve a Region by id."""
    rows = _query("Region", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/regions/<eid>", methods=["POST", "PATCH"])
def update_region(request, eid):
    """Update a Region."""
    rows = _query("Region", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Region", rec)
    return rec, 200

@app.route("/v1/regions/<eid>", methods=["DELETE"])
def delete_region(request, eid):
    """Delete a Region."""
    rows = _query("Region", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"digitalocean.Region", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/databases", methods=["POST"])
def create_database(request):
    """Create a Database."""
    data = request.json or request.form or {}
    err = _require(data, ['name', 'engine'])
    if err:
        return err, 400
    rec = {"id": new_id("digitalo_dat")}
    rec["name"] = data.get('name')
    rec["engine"] = data.get('engine')
    rec["version"] = data.get('version')
    rec["semanticVersion"] = data.get('semanticVersion')
    rec["status"] = data.get('status')
    rec["region"] = data.get('region')
    rec["size"] = data.get('size')
    rec["numNodes"] = int(data.get('numNodes') or 0)
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Database", rec)
    return rec, 201

@app.route("/v1/databases", methods=["GET"])
def list_databases(request):
    """List Databases."""
    items = _query("Database")
    return {"object": "list", "data": items, "count": len(items)}, 200

@app.route("/v1/databases/<eid>", methods=["GET"])
def get_database(request, eid):
    """Retrieve a Database by id."""
    rows = _query("Database", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    return rows[0], 200

@app.route("/v1/databases/<eid>", methods=["POST", "PATCH"])
def update_database(request, eid):
    """Update a Database."""
    rows = _query("Database", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    data = request.json or request.form or {}
    rec = rows[0]
    for k, v in data.items():
        if k in rec and k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Database", rec)
    return rec, 200

@app.route("/v1/databases/<eid>", methods=["DELETE"])
def delete_database(request, eid):
    """Delete a Database."""
    rows = _query("Database", eid)
    if not rows:
        return {"error": {"message": "Not found"}}, 404
    db.retract({"entity": f"digitalocean.Database", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "digitalocean-compat", "entities": ['Droplet', 'Volume', 'Image', 'Project', 'Region', 'Database']}, 200


if __name__ == "__main__":
    app.start()
