app_identifier "com.etzhayyim.yoro"
app 6760579144

# name set in ASC as "YORO Messenger" (en-GB)

subtitle({
  "en-GB" => "Encrypted AT Protocol Chat"
})

privacy_url({
  "en-GB" => "https://yoro.etzhayyim.com/privacy"
})
support_url({
  "en-GB" => "https://yoro.etzhayyim.com/support"
})
marketing_url({
  "en-GB" => "https://yoro.etzhayyim.com"
})

copyright "2026 GIFTED AGENT LLC"

primary_category "SOCIAL_NETWORKING"
secondary_category "UTILITIES"

app_rating_config_path "./fastlane/rating_config.json"
